project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "courses/*.qmd"
    - "msa/*.qmd"
    - "!ignored.qmd"
    - "!courses/old/"
resources:
  - CNAME
  - ./chess/*
  - ./wed/**
  - ./html/**




execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Vadim Sokolov"
  search: false
  navbar:
    title: false
    left:
      - href: index.qmd
        text: home
      - href: cv.qmd
        text: cv
      - href: research.qmd
        text: research
      - text: "teaching"
        menu:
          - href: courses/468.qmd
            text: Predictive Analytics (UG)
          - href: courses/568.qmd
            text: Predictive Analytics (MS)
          - href: courses/664.qmd
            text: Bayes (MS)
          - href: courses/610.qmd
            text: Deep Learning (MS)
          - href: courses/750.qmd
            text: Bayesian Learning (PhD)
          - href: courses/41000/41000.qmd
            text: Statistics (MBA)

format:
  html:
    theme: cosmo
    fontsize: 1.2em
    css: styles.css
    toc: false



