[Full CV](doc/cv.pdf)

## Education

- Ph.D., 2008, Computational Mathematics, Northern Illinois University
- Diploma (summa cum laude), 2004, Applied Mathematics, Rostov State University
- Graduate Studies in Statistics, 2013-2014, University of Chicago

## Positions
- Associate Professor, Systems Engineering and Operations Research, George Mason University, 2023-present
- Asistant Professor, Systems Engineering and Operations Research, George Mason University, 2016-2023
- Visiting Assistant Professor, Statistics,The University of Chicago Booth School of Business, 2019-2023
- Assistant Professor, Systems Engineering and Operations Research, George Mason University, 2016-2023
- Lecturer, Master of Science in Analytics, University of Chicago, 2015-2016
- Fellow, Computation Institute, University of Chicago, 2014-2016
- Principal Computational Scientist, Transportation Research and Analysis Computing Center, Argonne National Laboratory, 2013-2016
- Computational Scientist, Transportation Research and Analysis Computing Center, Argonne National Laboratory, 2008-2013
