---
bibliography: doc/citations.bib
csl: doc/american-statistical-association.csl
---

[Google Scholar](https://scholar.google.com/citations?user=A5HXf0IAAAAJ&hl=en)\
[Polaris Project](http://polaris.es.anl.gov/)\
[Geneology](image/tree.png)\


## papers
---
nocite: '@*'
---
<div id="refs"></div>

## software
- [POLARIS](https://github.com/anl-polaris/polaris): Designer. Developer. Transportation systems simulations framework (C\+\+)
- [GREET](https://greet.es.anl.gov/greet/): Designer. Lead Developer. An implementation of The Greenhouse Gases, Regulated Emissions, and Energy Use in Transportation (GREET) Model. (C\#, .NET, SQLite). more then 800 unique users within first year of release, 2013
- [MATCOM](http://www.siam.org/books/ot116/): Contributor. Distributed on CD with Numerical Linear Algebra and Applications, Second Edition book By Biswa Nath Datta, SIAM. (MATLAB)
- [TRANSIMS](https://sourceforge.net/projects/transims/): Contributor. An agent-based forecast software for modeling regional transport systems. (C\+\+); 22,295 total downloads since 2006
- [Advanced Numerical Methods II](http://library.wolfram.com/infocenter/Conferences/5787/): Sole Developer. Package for solving large scale control problems. (Mathematica); an experimental library that was not published

## research coverage
- Demystifying the future of connected and autonomous vehicles ([Newswise](https://www.newswise.com/doescience/demystifying-the-future-of-connected-and-autonomous-vehicles/?article_id=695538)
- Argonne wins grant to help transit agencies cope with emergencies ([Chicago Tribune](http://www.chicagotribune.com/ct-argonne-evacuation-plan-met-20150213-story.html ))
- Argonne will research how transportation systems should respond to natural hazards ([WBEZ](https://www.wbez.org/stories/argonne-will-research-how-transportation-systems-should-respond-to-natural-hazards/5f1cc196-7675-428c-8994-283bbe135afd))
- What Happens When Developers, Scientists and Super-Computers Connect on Urban Design ([Next City](https://nextcity.org/daily/entry/chicago-lakesim-scientists-developers-urban-design))
- UM wins $2.7M grant to study driverless cars ([The Detroit News](http://www.detroitnews.com/story/business/autos/2015/11/18/um-gets-doe-grant/76005542/))
- UM teams with Argonne, Idaho national labs to study potential energy savings of connected vehicles ([Michigan News](http://ns.umich.edu/new/releases/23308-u-m-teams-with-argonne-idaho-national-labs-to-study-potential-energy-savings-of-connected-vehicles))
- Argonne to study emergency response of Chicago transit ([Chicago Sun Times](http://chicago.suntimes.com/news/argonne-to-study-emergency-response-of-chicago-transit/))
- Designing future cities ([phys.org](http://phys.org/news/2014-10-future-cities.html))
- Using a Real Life SimCity to Design a Massive Development ([Curbed Chicago](http://chicago.curbed.com/2015/1/16/10001642/reallife-simcity-being-used-to-design-a-massive-development))