

## SYST 468. Applied Predictive Analytics
 
**Department of Systems Engineering and Operations Research**\
**George Mason University**\
**Spring 2018**\

**For Syllabus click [here](syllabus.html)**\

SYST 468 is an undergraduate course focused on applying statistical and machine learning methodologies to develop predictive models. We will learn both classical methods for regression and classification, such as linear regression and logistic regression as well as new methods such as deep learning. We will consider applications in engineering, finance and artificial intelligence. There will be an emphasis on assumptions and interpretation. Although basics of probability and statistics will be revisited, it is targeted towards students who have completed (and remember the concepts from) a course in introductory statistics. We will make extensive use of computational tools, such as the R language for statistical computing, both for illustration in class and in homework problems. 

#### Announcements
- 04\/17\/2018: Final project is posted. Due May 9 at midnight.
- 04\/04\/2018: HW4 is posted. Due April 11.
- 02\/28\/2018: Midterm review is posted, see hw folder on Dropbox. Will go over it toady. 
- 02\/25\/2018: HW3 is posted, due March 7 at the beginning of the class. 
- 02\/22\/2018: Midterm is on March 7. 
- 02\/12\/2018: HW 2: Problems 8,9,16-19 from probability notes. Due Feb 21 at beginning of the class. Upload to bb.
- 01\/30\/2018: HW 1: Problems 1,2,5,7,14 from notes. Due Feb 7 at beginning of the class.
- 01\/30\/2018: Notes for week 1 and 2 are posted.
- 01\/11\/2018: Payed summer internship in analytics @ GMU: [details](files/reu_flyer_v2.pdf). Apply by Feb 15!
- 12\/17\/2017: Check back regularly for announcements



#### Course staff
**Lecture Notes**:	Will be made available one-day in advance on [Bb](https://mymasonportal.gmu.edu/) \
**Instructor**: [Vadim Sokolov](../../index.qmd) \
**Office**: [Building](https://goo.gl/maps/iLp2PzxkSxF2 Engineering), Room 2242 \
vsokolov(at)gmu.edu \
**Tel**: 703-993-4533 \
**TA**: Jungho Park (jpark98@gmu.edu)\


#### Offie hours
Vadim Sokolov: Wed 2:30-4:30pm (at Engineering 2242)\
Jungho Park: Mon 1-3pm (at Egnineering 2216)\


#### Lectures
**Location**: [Hall](https://goo.gl/maps/8MaM7ezdvaw Planetary) 127\
**Times**: 4:30-7:10pm on Wednesday

#### Grades
**Grade composition**: Grade based on participation in class, in-class midterm, homework assignments, and final project.


#### Textbooks
- Diez, Barr and Cetinkaya-Rundel [Statistics](https://www.openintro.org/stat/textbook.php?stat_book##os OpenIntro), OpenIntro, 2015
- James, Witten, Hastie and Tibshirani, [R](http://www-bcf.usc.edu/~gareth/ISL/index.html An Introduction to Statistical Learning with Applications in), Springer, 2009.
- Hyndman and Athanasopoulos, [Practice](https://www.otexts.org/fpp Forecasting: Principles and), OTexts, 2013.
- Additional reading: [List](https://chrisalbon.com/blog/data_science_reading_list.html Data Science Reading)

#### Links
- [Interpretability](http://nautil.us/issue/40/learning/is-artificial-intelligence-permanently-inscrutable Model)
- [Survey](https://www.dropbox.com/s/dtpabgu0o9z5t8z/2015-data-science-salary-survey.pdf?dl##1 Data Sceince)
- [Note](https://www.dropbox.com/s/b34zjdupyc247v5/keynes.pdf?dl##1 J. M. Keynes's Investment Performance: A)
- [Search](https://www.youtube.com/watch?v##WH-HWWkCMeU Bayes)
- [Times)](http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html How Y'all (NY)
- [Hall](https://www.youtube.com/watch?v##Zr_xWfThjJ0&app##desktop  Monte)
- [EPL](http://faculty.chicagobooth.edu/nicholas.polson/teaching/41000/speigelhalter-EPL.pdf) 
- [Cleaning](https://whatsthebigdata.com/2016/05/01/data-scientists-spend-most-of-their-time-cleaning-data/ Data)
- [Forest](http://nerds.airbnb.com/unboxing-the-random-forest-classifier Airbnb) (Random)
- [regrsssion](https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ Facebook) (Decision trees and logistic)
- [learning](https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html Youtube) (deep)
- [series](https://eng.uber.com/telematics/ Uber) (time)
- [Analysis](http://www.itl.nist.gov/div898/handbook/eda/eda.htm Exploratory Data)
- [Overfitting](http://memosisland.blogspot.de/2017/08/understanding-overfitting-inaccurate.html)
- [2016](https://arxiv.org/abs/1704.01171 Election)


#### Deep Learning
 - [learning](http://course.fast.ai/ Course by Jeremy Howard on coding aspects of deep)
  - [learning](https://youtu.be/vq2nnJ4g6N0 Short introduction into deep)
  - [Architectures](http://www.asimovinstitute.org/neural-network-zoo/)
  - [Keras](https://keras.io/)
  - [ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)
 - [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html Opt)
 - [Momentum](http://distill.pub/2017/momentum/)
 - [Backprop](http://cs231n.stanford.edu/slides/2016/winter1516_lecture4.pdf)
