

## SYST/OR 568. Applied Predictive Analytics - Mason Analytics MS
 
 Instructor: [Vadim Sokolov](../../index.qmd)\
vsokolov@gmu.edu \
Skype: vsokolov83\\
TA: SeyedOmid HashemiAmiri \
ohashem@masonlive.gmu.edu

\\

**[Materials](https://www.dropbox.com/sh/41vlmd82fk0z7yj/AABK7uUgEvcRbVmEHIAYIzP3a?dl##0 Course)**\\

Starting this week (March 23) this class is moving online. We will use the following online resources:
. DataCamp. You need to sign up for it, using the [link](https://www.datacamp.com/groups/shared_links/5188e189b8369c5687fba1bb1c9792a5207eea8f3829bac8aeaebfbd9ee5345a invite). You will need to use your @masonlive.gmu.edu email to get free access. 
. Stanford's [Learning](https://online.stanford.edu/courses/sohs-ystatslearning-statistical-learning Statistical) class.
. [Book](http://faculty.marshall.usc.edu/gareth-james/ISL/ ISLR)
. [here](https://piazza.com/gmu/spring2020/568/home Piazza) for discussing HW\/project\/midterm. You can sign up [](https://piazza.com/gmu/spring2020/568)

{{<p>}}

For each week I provide direct links to DataCamp courses and Statistical Learning videos. 

######## Week of March 23
. Datacamp: [R](https://learn.datacamp.com/courses/working-with-dates-and-times-in-r Working with Dates and Times in)
. Resampling Methods (ISLR Chapter 5). Videos: 
[a](https://youtu.be/_2ij6eaaSl0),
[b](https://youtu.be/nZAM5OXrktY),
[c](https://youtu.be/S06JpVoNaA0),
[d](https://youtu.be/p4BYWX7PTBM),
[e](https://youtu.be/BzHz0J9a6k0),
[HandsOn](https://youtu.be/6dSXlqHAoMk)
######## Week of March 30
. [(c](https://www.dropbox.com/s/6ykq3r7f4u5vs30/midterm.pdf?dl##1 Midterm) due. Please submit 3 files to the BB. (a) First page with your signature acknowledging the honor code (b) PDF file with you solution (do not copy-paste large code chunks, just essential parts that you added on top of my scripts)) zip file with R scripts. 
######## Week of April 6 
. Linear Model Selection and Regularization (ISLR Chapter 6).  Videos:
[a](https://youtu.be/91si52nk3LA),
[b](https://youtu.be/nLpJd_iKmrE),
[c](https://youtu.be/NJhMSpI2Uj8),
[e](https://youtu.be/LkifE44myLc d and),
[f](https://youtu.be/3p9JNaJCOb4),
[g](https://youtu.be/cSKzqb0EKS0),
[h](https://youtu.be/A5I1G1MfUmA),
[i](https://youtu.be/xMKVUstjXBE),
[j](https://youtu.be/QlyROnAjnEk),
[k](https://youtu.be/eYxwWGJcOfw),
[HandsOn](https://youtu.be/3kwdDGnV8MM)
. Project proposals Due. Proposal is to be half-a-page and to contain: (a) description of the data to be analysed. (b) What is the goal of analysis, e.g. predict y from x or understand relations between y and x. (c) Why this is important? (d) What methods you think you will use? You can do it in bullet-points. 
######## Week of April 13
. [HW3](https://www.dropbox.com/s/6wcm4byztfwbgmq/3_hw_pa.pdf?dl##1) Due
. Tree-based Methods (ISLR Chapter 8).  Videos:
[a](https://youtu.be/6ENTbK3yQUQ),
[a2](https://youtu.be/GfPR7Xhdokc),
[b](https://youtu.be/hPEJoITBbQ4),
[c](https://youtu.be/lq_xzBRIWm4),
[d](https://youtu.be/U3MdBNysk9w),
[HandsOn](https://youtu.be/0wZUXtvAtDc)
. Datacamp: [R](https://learn.datacamp.com/courses/machine-learning-with-tree-based-models-in-r Machine Learning with Tree-Based Models in)
######## Week of April 20
. HW4 Due (ISLR: Ch 8, Ex. 4, 7, 8, 11)
. Unsupervised Learning (ISLR Chapter 10).  Videos:
Unsupervised Learning (Chapter 10)
[a](https://youtu.be/ipyxSYXgzjQ),
[b](https://youtu.be/dbuSGWCgdzw),
[c](https://youtu.be/aIybuNt9ps4),
[d](https://youtu.be/Tuuc9Y06tAc),
[e](https://youtu.be/yUJcTpWNY_o),
[HandsOn](https://youtu.be/lFHISDj_4EQ)
. Datacamp: [R](https://learn.datacamp.com/courses/unsupervised-learning-in-r Unsupervised Learning in)
######## Week of April 26
. Project intermediate reports are Due
. Life session discussing the projects
######## Week of April 27
. HW5 Due (ISLR: Ch 10, Ex. 3, 10)
. Optimization (I will post my videos on YouTube and will post links here when done)
. Datacamp: [website](https://learn.datacamp.com/courses/communicating-with-data-in-the-tidyverse Communicating with Data in the Tidyverse (Ch 3-4)). Plus you can use rmarkdown materials on the [](https://rmarkdown.rstudio.com official)
######## Week of May 4
. Final Project Presentations Due. Delivered as html file generated from R Markdown. Your HTML pages will be published on the course page and will be publicly available. 

{{<p>}}
\

Introduces predictive analytics with applications in engineering, business, finance,health care, and social economic areas. Topics include time series and cross-sectional data processing, data visualization, correlation, linear and multiple regressions, classification and clustering, time series decomposition, factor models and causal models, predictive modeling performance analysis, and case study. Provides a foundation of basic theory and methodology with applied examples to analyze large engineering, social, and econometric data for predictive decision making. Hands-on experiments with R will be emphasized.
\\
**[Syllabus](syllabus.html)**\\

#### Place and Time
- Fridays 4:30 pm - 7:10pm at Sandbridge Hall 107 (Jan 21, 2020 - May 13, 2020)

#### Grades
**Grade composition**: Grade based entirely on participation in class, homework assignments, in-class midterm and final project.


#### Textbooks
- Diez, Barr and Cetinkaya-Rundel [Statistics](https://www.openintro.org/stat/textbook.php?stat_book##os OpenIntro), OpenIntro, 2015
- James, Witten, Hastie and Tibshirani, [R](http://www-bcf.usc.edu/~gareth/ISL/index.html An Introduction to Statistical Learning with Applications in), Springer, 2009.
- Kuhn and Johnson, [Modeling](http://appliedpredictivemodeling.com/ Applied Predictive), Springer, 2013.
- Hyndman and Athanasopoulos, [Practice](https://www.otexts.org/fpp Forecasting: Principles and), OTexts, 2013.

#### Links
- [Learning](https://www.kaggle.com/surveys/2017 The State of Data Science and Machine)
- [Interpretability](http://nautil.us/issue/40/learning/is-artificial-intelligence-permanently-inscrutable Model)
- [Survey](https://www.dropbox.com/s/3pbrsozriu7luhg/2015-data-science-salary-survey.pdf?dl##1 Data Sceince)
- [Note](https://www.dropbox.com/s/fbxis2l6dbdvegb/keynes.pdf?dl##1 J. M. Keynes's Investment Performance: A)
- [Search](https://www.youtube.com/watch?v##WH-HWWkCMeU Bayes)
- [Times)](http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html How Y'all (NY)
- [Hall](https://www.youtube.com/watch?v##Zr_xWfThjJ0&app##desktop  Monte)
- [EPL](http://faculty.chicagobooth.edu/nicholas.polson/teaching/41000/speigelhalter-EPL.pdf) 
- [Cleaning](https://whatsthebigdata.com/2016/05/01/data-scientists-spend-most-of-their-time-cleaning-data/ Data)
- [Forest](http://nerds.airbnb.com/unboxing-the-random-forest-classifier Airbnb) (Random)
- [regrsssion](https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ Facebook) (Decision trees and logistic)
- [learning](https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html Youtube) (deep)
- [series](https://eng.uber.com/telematics/ Uber) (time)
- [Analysis](http://www.itl.nist.gov/div898/handbook/eda/eda.htm Exploratory Data)
- [Overfitting](http://memosisland.blogspot.de/2017/08/understanding-overfitting-inaccurate.html)
- [2016](https://arxiv.org/abs/1704.01171 Election)

#### Deep Learning
 - [learning](http://course.fast.ai/ Course by Jeremy Howard on coding aspects of deep)
  - [learning](https://youtu.be/vq2nnJ4g6N0 Short introduction into deep)
  - [Architectures](http://www.asimovinstitute.org/neural-network-zoo/)
  - [Keras](https://keras.io/)
  - [ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)
 - [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html Opt)
 - [Momentum](http://distill.pub/2017/momentum/)
 - [Backprop](http://cs231n.stanford.edu/slides/2016/winter1516_lecture4.pdf)


#### Final Project Data
- Debby Kermer (data services): [info](http://dataservices.gmu.edu/consulting/staff/dkermer contact)
- [Shopping](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2 Grocery)
- [Walmart](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting/data)
- [Yelp](https://www.yelp.com/dataset_challenge)
- [Airbnb](http://databits.io/challenges/airbnb-user-pathways-challenge)
- [Zillow](http://www.zillow.com/research/data/)
- [Uber](https://github.com/fivethirtyeight/uber-tlc-foil-response)
- [FiveThirtyErigh](https://github.com/fivethirtyeight/data)
- [each](https://archive.ics.uci.edu/ml/datasets.html   UCE ML Repo) (Lots of datasets along with descriptions of)
- [mining](http://www.kdnuggets.com  Knuggets) (Lot of links to datasets relevant for data)
- [datasets](http://www.pewresearch.org/data/download-datasets   Pew Research Center Survey)
- [data](http://econdata.net  ExonData) (The site has links to plenty of regional, state, and local economic)
- [data](http://3stages.org/idata   3stages) (Searchable listing 363 Internet sites of Social Science)
- [statistics](http://www.bls.gov/data   Bureau of labor)
- [government](http://explore.data.gov   data.gov) (A repository for information collected by the federal)
- [datasets](https://data.medicare.gov  Medicare)
- [Statistics](http://transtats.bts.gov/homepage.asp   Bureau of Transportation)
- [Nations](http://data.un.org  United)
- [Analytics](https://data.cityofchicago.org Chicago) (Urban)
- [Trips](http://www.andresmh.com/nyctaxitrips/ NYC Taxi)
- [Virginia](https://data.virginia.gov)

#### Very biased and noisy course recommendations
Here are the courses that cover different aspects of data science
- Statistical modeling (STAT250, SYST664, OR719, STAT 554)
- Data management (AIT614)
- Optimization (OR604)

#### Notebooks (ISLR labs)
- [Introduction](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/2_introduction.ipynb)
- [Regression](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/3_regression.ipynb)
- [Classification](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/4_classification.ipynb)
- [CV](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/5_cv.ipynb)
- [Selection](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/6_selection.ipynb Model)
- [Models](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/7_nonlinear.ipynb Nonlinear)
- [Trees](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/8_trees.ipynb)
- [SVM](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/9_svm.ipynb)
- [PCA](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/10_pca.ipynb)
- [All](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/tree/master/)

#### Previous instances
- [2016](./fall2016/index.html Fall)
- [2017](./spring2017/index.html Spring)
