

## SYST/OR 568. Applied Predictive Analytics
 
#https://patriotweb.gmu.edu/pls/prod/bwckctlg.p_disp_listcrse?term_in##201670&subj_in##SYST&crse_in##568&schd_in##LEC 
#https://patriotweb.gmu.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in##201670&crn_in##75285
#https://patriotweb.gmu.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in##201670&crn_in##75284
**Department of Systems Engineering and Operations Research**\
**George Mason University**\
**Spring 2017**\

**For Syllabus click [here](syllabus.html)**\


Introduces predictive analytics with applications in engineering, business, finance, health care, and social economic areas. Topics include time series and cross-sectional data processing, data visualization, correlation, linear and multiple regressions, classification and clustering, time series decomposition, factor models and causal models, predictive modeling performance analysis, and case study. Provides a foundation of basic theory and methodology with applied examples to analyze large engineering, social, and econometric data for predictive decision making. Hands-on experiments with R will be emphasized.

#### Announcements
- 5\/4\/2014: We will have lecture on March 9, midterms due March 30.
- 2\/15\/2017: Final projects are due on Monday of the finals week, May 15 at 9am. 
- 2\/15\/2017: Final projects presentations scheduled on May 4
- 2\/15\/2017: Take home midterm is during the week of March 6th (before the Spring break) and due March 23
- 2\/13\/2017: HW2 is due this Friday, Feb 17
- 12\/30\/2016: Check back regularly for announcements



#### Course staff
**Lecture Notes**:	Will be made available one-day in advance on [Bb](https://mymasonportal.gmu.edu/) \
**Instructor**: [[Vadim Sokolov](../../index.qmd)  \
**Office**: [Building](https://goo.gl/maps/iLp2PzxkSxF2 Engineering), Room 2242 \
vsokolov(at)gmu.edu \
**Tel**: 703-993-4533 \
**TA**: Bahman Pedrood (bpedrood (at) gmu.edu)\

#### Other Notes
- [Bootstrap](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/ii12yeiy6748lcn/Bootstrap.ipynb)

#### Offie hours
Bahman Pedrood: Wednesday  5-7pm (at Engineering 2241)\
Vadim Sokolov: Thursday 5-7pm (at Engineering 2242)\

#PDF file can be downloaded from [here](https://www.dropbox.com/s/w1p99jcow9lm6td/syllabus.pdf?dl##1)


#### Lectures
**Location**: [Hall](https://goo.gl/maps/rab5xYwPuNP2 Innovation) 105\
**Times**: 7:20-10pm on Thursday
#### Grades
**Grade composition**: No in-class examination. Grade based entirely on participation in class, homework assigments, take-home midterm and final project.


#### Textbooks
- Diez, Barr and Cetinkaya-Rundel [Statistics](https://www.openintro.org/stat/textbook.php?stat_book##os OpenIntro), OpenIntro, 2015
- James, Witten, Hastie and Tibshirani, [R](http://www-bcf.usc.edu/~gareth/ISL/index.html An Introduction to Statistical Learning with Applications in), Springer, 2009.
- Kuhn and Johnson, [Modeling](http://appliedpredictivemodeling.com/ Applied Predictive), Springer, 2013.
- Hyndman and Athanasopoulos, [Practice](https://www.otexts.org/fpp Forecasting: Principles and), OTexts, 2013.

#### Links
- [Interpretability](http://nautil.us/issue/40/learning/is-artificial-intelligence-permanently-inscrutable Model)
- [Survey](https://www.dropbox.com/s/dtpabgu0o9z5t8z/2015-data-science-salary-survey.pdf?dl##1 Data Sceince)
- [Note](https://www.dropbox.com/s/b34zjdupyc247v5/keynes.pdf?dl##1 J. M. Keynes's Investment Performance: A)
- [Search](https://www.youtube.com/watch?v##WH-HWWkCMeU Bayes)
- [Times)](http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html How Y'all (NY)
- [Hall](https://www.youtube.com/watch?v##Zr_xWfThjJ0&app##desktop  Monte)
- [EPL](http://faculty.chicagobooth.edu/nicholas.polson/teaching/41000/speigelhalter-EPL.pdf) 
- [Cleaning](https://whatsthebigdata.com/2016/05/01/data-scientists-spend-most-of-their-time-cleaning-data/ Data)
- [Forest](http://nerds.airbnb.com/unboxing-the-random-forest-classifier Airbnb) (Random)
- [regrsssion](https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/ Facebook) (Decision trees and logistic)
- [learning](https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html Youtube) (deep)
- [series](https://eng.uber.com/telematics/ Uber) (time)
- [Analysis](http://www.itl.nist.gov/div898/handbook/eda/eda.htm Exploratory Data)
- [Overfitting](http://memosisland.blogspot.de/2017/08/understanding-overfitting-inaccurate.html)
- [2016](https://arxiv.org/abs/1704.01171 Election)

#### Deep Learning
 - [learning](http://course.fast.ai/ Course by Jeremy Howard on coding aspects of deep)
  - [learning](https://youtu.be/vq2nnJ4g6N0 Short introduction into deep)
  - [Architectures](http://www.asimovinstitute.org/neural-network-zoo/)
  - [Keras](https://keras.io/)
  - [ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)
 - [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html Opt)
 - [Momentum](http://distill.pub/2017/momentum/)
 - [Backprop](http://cs231n.stanford.edu/slides/2016/winter1516_lecture4.pdf)


#### Final Project Data
- Debby Kermer (data services): [info](http://dataservices.gmu.edu/consulting/staff/dkermer contact)
- [Shopping](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2 Grocery)
- [Walmart](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting/data)
- [Yelp](https://www.yelp.com/dataset_challenge)
- [Airbnb](http://databits.io/challenges/airbnb-user-pathways-challenge)
- [Zillow](http://www.zillow.com/research/data/)
- [Uber](https://github.com/fivethirtyeight/uber-tlc-foil-response)
- [FiveThirtyErigh](https://github.com/fivethirtyeight/data)
- [each](https://archive.ics.uci.edu/ml/datasets.html   UCE ML Repo) (Lots of datasets along with descriptions of)
- [mining](http://www.kdnuggets.com  Knuggets) (Lot of links to datasets relevant for data)
- [datasets](http://www.pewresearch.org/data/download-datasets   Pew Research Center Survey)
- [data](http://econdata.net  ExonData) (The site has links to plenty of regional, state, and local economic)
- [data](http://3stages.org/idata   3stages) (Searchable listing 363 Internet sites of Social Science)
- [statistics](http://www.bls.gov/data   Bureau of labor)
- [government](http://explore.data.gov   data.gov) (A repository for information collected by the federal)
- [datasets](https://data.medicare.gov  Medicare)
- [Statistics](http://transtats.bts.gov/homepage.asp   Bureau of Transportation)
- [Nations](http://data.un.org  United)
- [Analytics](https://data.cityofchicago.org Chicago) (Urban)
- [Trips](http://www.andresmh.com/nyctaxitrips/ NYC Taxi)
- [Virginia](https://data.virginia.gov)

#### Very biased and noisy course recommendations
Here are the courses that cover different aspects of data science
- Statistical modeling (STAT250, SYST664, OR719, STAT 554)
- Data management (AIT614)
- Optimization (OR604)

#### Notebooks (ISLR labs)
- [Introduction](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/2_introduction.ipynb)
- [Regression](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/3_regression.ipynb)
- [Clasification](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/4_classification.ipynb)
- [CV](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/5_cv.ipynb)
- [Selection](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/6_selection.ipynb Model)
- [Models](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/7_nonlinear.ipynb Nonlinear)
- [Trees](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/8_trees.ipynb)
- [SVM](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/9_svm.ipynb)
- [PCA](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/blob/master/10_pca.ipynb)
- [All](https://nbviewer.jupyter.org/github/VadimSokolov/ISLRNoteBook/tree/master/)

#### Previous instances
- [2016](./fall2016/index.html Fall)
