

## OR 750. Advanced Data Analytics
 
#https://patriotweb.gmu.edu/pls/prod/bwckctlg.p_disp_listcrse?term_in##201670&subj_in##SYST&crse_in##568&schd_in##LEC 
#https://patriotweb.gmu.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in##201670&crn_in##75285
#https://patriotweb.gmu.edu/pls/prod/bwckschd.p_disp_detail_sched?term_in##201670&crn_in##75284
**Department of Systems Engineering and Operations Research**\
**George Mason University**\
**Fall 2017**\

#**For Syllabus click [here](syllabus.html)**\


The class will consist of 7-8 lectures given by the instructor on several advanced topics in data analysis. The rest of the semester (another 6-7 lectures) students will present on the topic of their choice. 

**For Lecture notes and homework click [here](https://www.dropbox.com/sh/q2ywfjg4rj569c0/AAClairRwV4p6mINUiA1O_nSa?dl##0)**\

#### Course Presentations
- Bayesian Optimization for ML and Engineering. By Laura Schultz (11/1)
- Adversarial Auto-encoders. By Bill Jeffries on 11/8
- RNN for EDU: [(11/8](https://web.stanford.edu/~cpiech/bio/papers/deepKnowledgeTracing.pdf Deep Knowledge Tracing). By Qian Hu)
- RNN/LSTM. By Darron Fuller.
- Hierarchical Bayes and STAN. By Tuan Lee (11\/15)
- Convolutional Networks: Convolution/pooling layers, network design, theory. By Kathleen Perez-Lopez on 11\/15. Materials: [slides](https://www.youtube.com/watch?v##5shwqPBVpbc&index##4&list##PLkFD6_40KJIxopmdJF_CLNqG3QuDFHQUm Brief info), [](https://youtu.be/4TLYJ20kniA lecture video), [](https://bcourses.berkeley.edu/courses/1453965/files/69671012/download?verifier##XD3l2nlSb1lJ5CUTGcJA7YSU7Ttel1VtvyTzd28J)


- DL for Threat Detection. By James Lee. 11/29
- VAE: [VampPrior](https://arxiv.org/abs/1705.07120 VAE with a). By Hossein Fotouhi on 11/29.
- Language Modeling: [Documents](https://arxiv.org/pdf/1602.02410.pdf Exploring the Limits of Language Modeling), [](https://arxiv.org/pdf/1301.3781.pdf Efficient Estimation of Word Representations in Vector Space), [](https://arxiv.org/pdf/1405.4053.pdf Distributed Representations of Sentences and). By Anya Mityushina on 11/29
- Reinforcement learning. By Jeff Schneider


#### Announcements
- 10\/24: No lecture this Wednesday (10\/25)
- 10\/24: HW3 Posted
- 10\/03\/2017: Instructions on setting up Google Cloud Machines posted [here](gcloud.html)
- 9\/24\/2017: HW2 posted
- 9\/24\/2017: Solutions for HW1 posted
- 9\/7\/2017: HW1 posted
- 5\/3\/2017: First class is on Aug 30 at 4:30pm

#### List of topics
- Probabilistic models for Machine Learning
	-- Conjugate distributions, exponential family
	-- Model choice
	-- Hierarchical linear and generalize linear models (regression and classification)
	-- Models for missing data (EM-algorithm)
	-- LDA, Normal mixtures, Bayes PCA
	-- Bayes computations (MCMC, Variational Bayes)
	-- Graphical Models
	-- Probabilistic modeling with Stan
 - Deep learning
	 -- Optimization
	 -- Architectures (CNN, LSTM, MP, VAE)
	 -- Bayesian DL
	 -- Generative models (GANs)
	 -- Modeling with TensorFlow
- Filtering
	 -- Kalman Filter
	 -- Extended KF and ensemble KF
	 -- Particle filter
	 -- Modeling with DLM package in R
- Probability and Statistics methods for Decision Making
	-- Real-time hypothesis testing
	-- Brownian motion
	-- Bayesian methods for optimal stopping time detection
- Bayesian Optimization
	-- Tuning machine learning algorithms
	-- Engineering model calibration
	-- Modeling with spearmint

 
#### Course staff
#*Lecture Notes**:	Will be made available one-day in advance on [Bb](https://mymasonportal.gmu.edu/) \
**Instructor**: [Sokolov](http://vsokolov.org Vadim) \
**Office**: [Building](https://goo.gl/maps/iLp2PzxkSxF2 Engineering), Room 2242 \
vsokolov(at)gmu.edu \
**Tel**: 703-993-4533 \


#### Books
- The Probability and Statistics Cookbook ([page)](http://statistics.zone book)
- Pattern Recognition and Machine Learning
([page)](https://www.microsoft.com/en-us/research/people/cmbishop/?from##http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fpeople%2Fcmbishop%2Fprml%2F book)
- Lectures on "Probability in High Dimension" ([pdf)](https://www.princeton.edu/~rvan/ORF570.pdf)
- Book on "High-Dimensional Probability" ([pdf)](http://www-personal.umich.edu/~romanv/papers/HDP-book/HDP-book.pdf)
- Blog post on SGD ([link)](https://xianblog.wordpress.com/2017/05/10/the-invasion-of-the-stochastic-gradients/)
- Machine Learning: A Bayesian and Optimization Perspective([safari)](http://proquest.safaribooksonline.com.mutex.gmu.edu/book/programming/machine-learning/9780128015223/cover-image/cover_xhtml?uicode##gmu)
- A Bayesian Course with Examples in R and Stan ([page)](http://xcelab.net/rm/statistical-rethinking/ book)
- Doing Bayesian Data Analysis, Second Edition: A Tutorial with R, JAGS, and Stan  ([amazon)](http://a.co/g5zQvzw)


#### Office hours
Vadim Sokolov: By appointment (at Engineering 2242)\


#### Lectures
**Location**: [Building](https://goo.gl/maps/7rV5nAX5CDB2 Nguyen Engineering) 1109\
**Times**: 4:30-7:10pm on Wednesday

#### Grades
**Grade composition**: No in-class examination. Grade is based entirely on participation in class and homework assignments.



#### Deep Learning
##PAPERS##
- Normalization Propagation: A Parametric Technique for Removing Internal Covariate Shift in Deep Networks ([paper)](https://arxiv.org/pdf/1603.01431.pdf)
- Why does Monte Carlo Fail to Work Properly in High-Dimensional Optimization Problems? ([paper)](https://arxiv.org/pdf/1603.00311.pdf)
- Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift ([paper)](https://arxiv.org/pdf/1502.03167.pdf)
- Auto-Encoding Variational Bayes ([paper)](https://arxiv.org/pdf/1312.6114.pdf)
 - A Central Limit Theorem for Convex Sets ([slides)](https://arxiv.org/pdf/math/0605014.pdf paper), [](http://web.math.unifi.it/users/salani/cortona2007/talks/klartag.pdf)
- Learning Deep Architectures for AI ([monograph)](files/bengiofull2009.pdf)
- Representation Learning: A Review and New Perspectives ([paper)](http://www.iro.umontreal.ca/~lisa/pointeurs/TPAMISI-2012-04-0260-1.pdf)
- Sequence to Sequence Learning with Neural Networks ([paper)](https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf)
- Twin Networks: Using the Future as a Regularizer ([paper)](https://arxiv.org/pdf/1708.06742.pdf)
- Skip RNN ([paper)](http://www.gitxiv.com/posts/6ozns2NF7odKrHZ3r/skip-rnn blog and)
- VAE with a VampPrior ([paper)](https://arxiv.org/pdf/1705.07120.pdf)

##BLOGS##
- Bayesian DL ([blog)](http://www.datasciencecentral.com/profiles/blogs/a-curated-list-of-resources-dedicated-to-bayesian-deep-learning?utm_content##buffer3671b&utm_medium##social&utm_source##twitter.com&utm_campaign##buffer)
- Generative Adversarial Networks ([presentation)](https://channel9.msdn.com/Events/Neural-Information-Processing-Systems-Conference/Neural-Information-Processing-Systems-Conference-NIPS-2016/Generative-Adversarial-Networks)
- GANs at OpenAI ([blog)](https://blog.openai.com/generative-models/?utm_content##buffer50108&utm_medium##social&utm_source##twitter.com&utm_campaign##buffer)
- Revisiting the Unreasonable Effectiveness of Data
 ([blog)](https://research.googleblog.com/2017/07/revisiting-unreasonable-effectiveness.html)
- Learning the Enigma with Recurrent Neural Networks ([blog)](https://greydanus.github.io/2017/01/07/enigma-rnn/)
- Tuning CNN architecture ([blog)](https://bowenbaker.github.io/metaqnn/)
- Security ([blog)](http://www.cleverhans.io)
- Unsupervised learning ([blog)](https://medium.com/intuitionmachine/navigating-the-unsupervised-learning-landscape-951bd5842df9)
- DL Tuning ([blog)](http://theorangeduck.com/page/neural-network-not-working)
- Cybersecurity ([collection)](https://medium.com/@jason_trost/collection-of-deep-learning-cyber-security-research-papers-e1f856f71042 paper)
 - [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html Opt)
 - [Momentum](http://distill.pub/2017/momentum/)
 - LSTM [blog](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)
##VIDEOS##
- Deep Energy ([blog)](https://deepmind.com/blog/deepmind-ai-reduces-google-data-centre-cooling-bill-40/)
- DL Summer school 2015 ([videos)](http://videolectures.net/deeplearning2015_montreal/)
- DL Representations ([blog)](http://netdissect.csail.mit.edu)
- PyData 2017 ([videos)](https://www.analyticsvidhya.com/blog/2017/05/pydata-amsterdam-2017-machine-learning-deep-learning-data-science/)

#### Decision Making
- Multivariate Industrial Time Series with Cyber-Attack Simulation: Fault Detection Using an LSTM-based Predictive Data Model ([paper)](https://arxiv.org/pdf/1612.06676.pdf)
- Signal-based Bayesian Seismic Monitoring ([paper)](https://arxiv.org/abs/1703.00561)
- Introducing practical and robust anomaly detection in a time series ([blog)](https://blog.twitter.com/engineering/en_us/a/2015/introducing-practical-and-robust-anomaly-detection-in-a-time-series.html)
- Anomaly Detection with Twitter in R ([blog)](https://anomaly.io/anomaly-detection-twitter-r/)

#### Filtering
- Curse-of-dimensionality revisited: Collapse of the particle filter in very large scale systems ([paper)(](https://arxiv.org/abs/0805.3034)
- Can local particle filters beat the curse of dimensionality? ([paper)](https://arxiv.org/abs/1301.6585)

#### Bayes
- The Markov Chain Monte Carlo Revolution
 ([paper)](http://www.ams.org/journals/bull/2009-46-02/S0273-0979-08-01238-X/S0273-0979-08-01238-X.pdf)
- Graphical Models, Exponential Families, and Variational Inference ([monograph)](https://people.eecs.berkeley.edu/~wainwrig/Papers/WaiJor08_FTML.pdf)
- Variational Inference: A Review for Statisticians ([paper)](https://arxiv.org/pdf/1601.00670.pdf)
- Neural Block Sampling ([paper)](https://arxiv.org/pdf/1708.06040.pdf)
- Stochastic Variational Inference ([paper)](../../pdf/HoffmanBleiWangPaisley2013.pdf)
- A stochastic approximation method ([paper)](../../pdf/herbert51.pdf)
- A note on the evidence and Bayesian Occam’s razor ([paper)](http://mlg.eng.cam.ac.uk/zoubin/papers/05occam/occam.pdf)
- How to become a Bayesian in eight easy steps: An annotated reading list ([paper)](../pdf/becoming_bayes.pdf)
- Sparse Bayesian Learning and the Relevance Vector Machine ([)](http://www.jmlr.org/papers/volume1/tipping01a/tipping01a.pdf pdf)
- EM Algorithm ([blog)](https://cw.fel.cvut.cz/wiki/courses/ae4b33rpz/labs/12_em/start)


- Bayes DL ([blog)](https://medium.com/towards-data-science/building-a-bayesian-deep-learning-classifier-ece1845bc09)
- AB Testing ([blog)](https://www.r-bloggers.com/bayesian-ab-testing-made-easy/)


#### Calibration
- Learning Transferable Architectures for Scalable Image Recognition ([paper)](https://arxiv.org/abs/1707.07012)
- Hyperband ([demo)](https://people.eecs.berkeley.edu/~kjamieson/hyperband.html)
- Calibration at Google ([blog)](https://cloud.google.com/blog/big-data/2017/08/hyperparameter-tuning-in-cloud-machine-learning-engine-using-bayesian-optimization?utm_content##bufferdd61a&utm_medium##social&utm_source##twitter.com&utm_campaign##buffer)

#### Tools
- [Stan](http://mc-stan.org/documentation/)
- [TensorFlow](https://www.tensorflow.org)
- [(R)](https://cran.r-project.org/web/packages/dlm/dlm.pdf dlm)
- [Keras](https://keras.io)
- [(Google](http://playground.tensorflow.org TF Playground))
- [Sony](https://dl.sony.com DL) 
- [profiler](https://jiffyclub.github.io/snakeviz/ SnakeViz) (python)
- [PyTorch](http://pytorch.org)
- [projects](https://github.com/ritchieng/the-incredible-pytorch Pytorch resources) (a curated list of tutorials, papers,)
- [(Facebook](https://research.fb.com/prophet-forecasting-at-scale/ Prophet))
- [(Twitter](https://github.com/twitter/AnomalyDetection AnomalyDetection))
- [Examples](https://github.com/jeffalstott/pystan_time_series TS Stan)



#### Events
- Bayesian Chronological Modeling Workshop [site](https://www.eventbrite.co.uk/e/bayesian-chronological-modeling-workshop-tickets-36821622464)
#### Misc Links
 - [learning](http://www.cherwell.org/2017/05/01/independent-learning-more-beneficial-than-contact-hours-report-finds/?platform##hootsuite Independent)
