
# jemdoc: nodefaultcss, addcss{../../../jemdoc.css}

## OR 750. Deep Learning
**Department of Systems Engineering and Operations Research**\
**George Mason University**\
**Fall 2018**\

\\
This is a PhD course focused on developing deep learning predictive models. We will learn both practical and theoretical aspects of deep learning. We will consider applications in engineering, finance and artificial intelligence. It is targeted towards the students who have completed an introductory courses in statistics and optimization. We will make extensive use of computational tools, such as the Python language, both for illustration in class and in homework problems.  The class will consist of 12 lectures given by the instructor on several advanced topics in deep learning. At another 3 lectures students will present on the topic of their choice. 

#### Announcements
- 10\/18\/2018: HW2 posted, Due Oct 23
- 10\/04\/2018: No class next week (Oct 8) due to Fall break
- 9\/20\/2018: Week 3-5 notes Posted
- 9\/15\/2018: Week 2 notes Posted
- 9\/15\/2018: HW1 Posted
- 8\/31\/2018: Room has been changed to Engineering 2241 (Fusion Lab)
- 8\/31\/2018: First week's lecture notes are posted
- 8\/31\/2018: No Class on September 3
- 4\/20\/2018: First class is on Aug 27 at 4:30pm


#### Paper Presentations
[Matrix](https://docs.google.com/spreadsheets/d/1920jK8ghmRJsXYUb0Bw0vRCvlefgQ3KM6HPhKs9fWN4/edit?usp##sharing)
- Dec 3:
     -- [slides)](https://arxiv.org/pdf/1809.07238.pdf Pose Estimation for Non-Cooperative Spacecraft Rendezvous Using Convolutional Neural Networks) by McKennon-Kelly Ryan ([](files/McKennon-Kelly_PaperReviews_3.pptx)
     -- [learning](https://www.nature.com/articles/nature14236 Human-level control through deep reinforcement) by Dave Prentiss
     -- [Residuals](https://arxiv.org/pdf/1605.07648.pdf FractalNet: Ultra-Deep Neural Networks without) by Jing Liu
    -- [Recognition](https://arxiv.org/pdf/1512.03385.pdf Deep Residual Learning for Image) by Jing Liu
    -- [Approach](https://arxiv.org/pdf/1706.06279.pdf Short-Term Forecasting of Passenger Demand under On-Demand Ride Services: A Spatio-Temporal Deep Learning) by Wenjie Li 
    -- [(Lem](https://www.kdd.org/kdd2016/papers/files/rpp1081-duA.pdf Recurrent Marked Temporal Point Processes: Embedding Event History to Vector) by Liming) Zhang

- Nov 26:

    -- [Segmentation](https://arxiv.org/pdf/1505.04597.pdf U-Net: Convolutional Networks for Biomedical Image) by Steven Guan
    -- [Networks](https://arxiv.org/pdf/1608.06993.pdf Densely Connected Convolutional)  by Steven Guan
    -- [slides)](https://arxiv.org/pdf/1605.06376.pdf Fast ε-free Inference of Simulation Models with Bayesian Conditional Density Estimation) by Brett Patterson ([](files/simulation_models1.pptx)
    -- [slides)](https://www.deeplearningbook.org/contents/inference.html Approximate Inference) by Brett Patterson ([](files/approx_inference1.pptx)

- Nov 19:
    -- [(Lem](https://www.kdd.org/kdd2016/papers/files/rfp0908-zhangA.pdf GMove: Group-Level Mobility Modeling  Using Geo-Tagged Social Media) by Liming) Zhang
    -- [](files/07949028.pdf Deep Convolutional Neural Network for
    Inverse Problems in Imaging) by Steven Guan
    -- [Screenshot](https://arxiv.org/pdf/1705.07962v2.pdf pix2code: Generating Code from a Graphical User Interface) by Nima Latifi
    -- [graph](files/wu2018.pdf Hierarchical travel demand estimation using multiple data sources: A forward and backward propagation algorithmic framework on a layered computational) by Wenjie Li 
    -- [Prediction](https://arxiv.org/pdf/1604.04527.pdf Deep Learning for Short-Term Traffic Flow) by Wenjie Li 
    -- [Classification](https://ieeexplore.ieee.org/document/7580631 Deep Reinforcement Learning With Visual Attention for Vehicle) by Weiwen Zhou
    -- [System](https://arxiv.org/pdf/1707.00802.pdf PBODL : Parallel Bayesian Online Deep Learning for Click-Through Rate Prediction in Tencent Advertising) by Atilla Ay
    -- [problems?](https://arxiv.org/abs/1603.00311 Why does Monte Carlo fail to work properly in high-dimensional optimization) by McKennon-Kelly Ryan
    -- [slides)](https://arc.aiaa.org/doi/10.2514/6.2018-1604 CubeSat Simulation and Detection using Monocular Camera Images and Convolutional Neural Networks) by McKennon-Kelly Ryan ([](./files/McKennon-Kelly_PaperReviews_1and2.pptx)

- Nov 12:
    -- [slides)](https://arxiv.org/abs/1708.04782 StarCraft II: A New Challenge for Reinforcement Learning) by Ashton Harvey ([](files/SC2LE Brief for 12 Nov.pptx)
    -- [](https://arxiv.org/pdf/1707.08110.pdf Deep Forecast:
Deep Learning-based Spatio-Temporal Forecasting) by Brett Patterson 
    -- [Forecasting](https://arxiv.org/pdf/1802.07007.pdf High-Order Graph Convolutional Recurrent Neural Network: A Deep Learning Framework for Network-Scale Traffic Learning and) by Brett Patterson 
    -- [Networks](https://arxiv.org/pdf/1511.06434.pdf Unsupervised Representation Learning with Deep Convolutional Generative Adversarial) by Jing Liu
    -- [(Lem](https://arxiv.org/pdf/1609.03675.pdf Deep Coevolutionary Network: Embedding User and Item Features for Recommendation) by Liming) Zhang
    -- [slides)](https://arxiv.org/pdf/1808.05527.pdf Deep Learning for Energy Markets) by Dave Prentiss ([](files/presentation.pdf)
    -- [Networks](http://disi.unitn.it/~severyn/papers/sigir-2015-short.pdf Twitter Sentiment Analysis with Deep Convolutional Neural) by Yudi Chen



#### Course staff
**Course Materials**:	[folder](https://www.dropbox.com/sh/bjnjaqzjkho7y76/AAAIglU442Yt8skfjzjyrHHya?dl##0 Dropbox)\
**Instructor**: [(vsokolov(at)gmu.edu](http://vsokolov.org Vadim Sokolov)) \
**Office**: [Building](https://goo.gl/maps/iLp2PzxkSxF2 Engineering), Room 2242 \
**Tel**: 703 993-4533 \
**Office hours**: By appointment\
**Lectures**: [Lab](https://goo.gl/maps/YxzosJrvHw32 Nguyen Engineering Building) 2241 (Fusion). 4:30-7:10pm on Mondays\
**Grades**: 40\% homework (individual), 60\% final research project (group)\


#### List of topics
 - Convex Optimization
	 -- Stochastic gradient descent and its variants (ADAM, RMSpropr, Nesterov acceleration)
	 -- Second order methods
	 -- ADMM
	 -- Regularization (l1, l2 and dropout)
	 -- Batch normalization
 - Theory of deep learning 
	 -- Universal approximators
	 -- Curse of dimensionality
	 -- Kernel spaces
	 -- Topology and geometry
 - Computational aspects (accelerated linear algebra, reduced precision calculations, parallelism)
 - Architectures (CNN, LSTM, MLP, VAE)
 - Bayesian DL
 - Deep reinforcement learning
 - Hyperparameter selection and parameter initialization
 - Generative models (GANs)


#### Books
- Deep Learning
([page)](http://www.deeplearningbook.org book)
- Deep Learning with Python
([page)](https://www.manning.com/books/deep-learning-with-python book)
- Learning Deep Architectures for AI ([monograph)](files/bengiofull2009.pdf)

#### Per Topic Resources

###### Section 1: Architectures
- Tuning CNN architecture ([blog)](https://bowenbaker.github.io/metaqnn/)
- Sequence to Sequence Learning with Neural Networks ([paper)](https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf)
- Skip RNN ([paper)](http://www.gitxiv.com/posts/6ozns2NF7odKrHZ3r/skip-rnn blog and)
- Learning the Enigma with Recurrent Neural Networks ([blog)](https://greydanus.github.io/2017/01/07/enigma-rnn/)
- LSTM [blog](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)
- Generative Adversarial Networks ([presentation)](https://channel9.msdn.com/Events/Neural-Information-Processing-Systems-Conference/Neural-Information-Processing-Systems-Conference-NIPS-2016/Generative-Adversarial-Networks)
- GANs at OpenAI ([blog)](https://blog.openai.com/generative-models/?utm_content##buffer50108,utm_medium##social,utm_source##twitter.com,utm_campaign##buffer)
- Adaptive Neural Trees ([paper)](https://arxiv.org/pdf/1807.06699.pdf)
- [Cortex](https://arxiv.org/pdf/1604.03640.pdf Bridging the Gaps Between Residual Learning, Recurrent Neural Networks and Visual)
- [Recognition](https://arxiv.org/pdf/1512.03385v1.pdf Deep Residual Learning for Image)
- [Networks](https://arxiv.org/pdf/1507.06228v2.pdf Training Very Deep)
- [Modeling](https://arxiv.org/pdf/1803.01271.pdf An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence) 
- [solution](https://arxiv.org/pdf/1807.03247.pdf An intriguing failing of convolutional neural networks and the CoordConv)
- [Need](https://arxiv.org/abs/1706.03762 Attention Is All You)
- [Networks](https://arxiv.org/abs/1701.00160 NIPS 2016 Tutorial: Generative Adversarial)
- [Autoencoders](https://towardsdatascience.com/intuitively-understanding-variational-autoencoders-1bfe67eb5daf Intuitively Understanding Variational)
- [WaveNet](https://deepmind.com/blog/wavenet-generative-model-raw-audio/)
- [PixelCNN](http://proceedings.mlr.press/v48/oord16)
- [https://chrisorm.github.io/NGP.html](Neural Processes)


###### Section 2: Optimization
- [Book](https://web.stanford.edu/~boyd/cvxbook/ BV)
- [(1970](http://www.convexoptimization.com/TOOLS/ConvexAnalysisRockafellar.pdf Convex Analysis by Rockafellar))
- [Lecture](https://youtu.be/xpwx0LIz-bs Nesterov's)
- [(1983)](./files/nesterov.pdf Nesterov)
- [(1964)](./files/polyak64.pdf Polyak)
- [Learning](https://papers.nips.cc/paper/3323-the-tradeoffs-of-large-scale-learning.pdf The Tradeoffs of Large Scale)
- [(2004)](https://www.springer.com/us/book/9781402075537 Nesterov)
- HOGWILD!: A Lock-Free Approach to Parallelizing Stochastic Gradient Descent ([paper)](http://i.stanford.edu/hazy/papers/hogwild-nips.pdf)
- SGD ([link)](https://xianblog.wordpress.com/2017/05/10/the-invasion-of-the-stochastic-gradients/)
- [Sampling](https://arxiv.org/pdf/1704.05201.pdf Stein Variational Adaptive Importance)
- [Dynamics](https://www.ics.uci.edu/~welling/publications/papers/stoclangevin_v6.pdf Bayesian Learning via Stochastic Gradient Langevin)
- [Optimization](https://arxiv.org/pdf/1512.07962.pdf Bridging the Gap between Stochastic Gradient MCMC and Stochastic)
- [code)](https://arxiv.org/abs/1806.09055 DARTS: Differentiable Architecture Search) ([](https://t.co/36J7HUbYkD)
- [code)](https://arxiv.org/abs/1611.01578 Neural Architecture Search with Reinforcement Learning) ([](https://github.com/carpedm20/ENAS-pytorch)
- [Search](https://arxiv.org/abs/1802.01548 Regularized Evolution for Image Classifier Architecture)
- [learning](http://proceedings.mlr.press/v28/sutskever13.pdf On the importance of initialization and momentum in deep)
- [Minima](http://www.bioinf.jku.at/publications/older/3304.pdf Flat)
- [Works](https://distill.pub/2017/momentum/ Why Momentum Really)
- [Minima](https://arxiv.org/pdf/1609.04836.pdf On Large-Batch Training for Deep Learning: Generalization Gap and Sharp)
- [Nets](https://arxiv.org/pdf/1703.04933.pdf Sharp Minima Can Generalize For Deep)
- [DNNs](https://arxiv.org/pdf/1802.10026.pdf Loss Surfaces, Mode Connectivity, and Fast Ensembling of)
- [Learning](https://papers.nips.cc/paper/7003-the-marginal-value-of-adaptive-gradient-methods-in-machine-learning.pdf The Marginal Value of Adaptive Gradient Methods in Machine)
- [Acceleration](https://blogs.princeton.edu/imabandit/2015/06/30/revisiting-nesterovs-acceleration/ Revisiting Nesterov’s)

###### Section 3: Theory
- Polyak, Boris, and Pavel Shcherbakov. "Why does Monte Carlo fail to work properly in high-dimensional optimization problems?." Journal of Optimization Theory and Applications 173, no. 2 (2017): 612-627. ([paper)](https://arxiv.org/pdf/1603.00311.pdf)
- Leni, Pierre-Emmanuel, Yohan D. Fougerolle, and Frédéric Truchetet. "Kolmogorov superposition theorem and its application to multivariate function decompositions and image representation." In Signal Image Technology and Internet Based Systems, 2008. SITIS'08. IEEE International Conference on, pp. 344-351. IEEE, 2008. ([paper)](./files/kolmogorov.pdf)
- Klartag, Bo'az. "A central limit theorem for convex sets." Inventiones mathematicae 168, no. 1 (2007): 91-131. ([slides)](https://arxiv.org/pdf/math/0605014.pdf paper), [](http://web.math.unifi.it/users/salani/cortona2007/talks/klartag.pdf)
- Sun, Chen, Abhinav Shrivastava, Saurabh Singh, and Abhinav Gupta. "Revisiting unreasonable effectiveness of data in deep learning era." In Computer Vision (ICCV), 2017 IEEE International Conference on, pp. 843-852. IEEE, 2017.
 ([blog)](https://research.googleblog.com/2017/07/revisiting-unreasonable-effectiveness.html)
- Bengio, Yoshua, Aaron Courville, and Pascal Vincent. "Representation learning: A review and new perspectives." IEEE transactions on pattern analysis and machine intelligence 35, no. 8 (2013): 1798-1828. ([paper)](http://www.iro.umontreal.ca/~lisa/pointeurs/TPAMISI-2012-04-0260-1.pdf)
- Braun, Jürgen. "An application of Kolmogorov's superposition theorem to function reconstruction in higher dimensions." (2009). ([dissertation)](./files/braun_disser.pdf)
- Kolmogorov. "On the Representation of Continuous Functions of Several Variables as Superpositions of Continuous Functions of a Smaller Number of Variables" ([paper)](./files/Kolmogorov1961.pdf)
- Arnold. "On functions of three variables" ([papers)](./file/Arnold2009Collection.pdf collection of)
- Bianchini, Monica, and Franco Scarselli. "On the complexity of shallow and deep neural network classifiers." In ESANN. 2014.([paper)](https://www.elen.ucl.ac.be/Proceedings/esann/esannpdf/es2014-44.pdf)
- Girosi, Federico, and Tomaso Poggio. "Representation properties of networks: Kolmogorov's theorem is irrelevant." Neural Computation 1, no. 4 (1989): 465-469. ([paper)](./files/Girosi89.pdf)
- Kůrková, Věra. "Kolmogorov's theorem and multilayer neural networks." Neural networks 5, no. 3 (1992): 501-506. ([paper)](./files/Kurkova92.pdf)
- Poggio, Tomaso, Hrushikesh Mhaskar, Lorenzo Rosasco, Brando Miranda, and Qianli Liao. "Why and when can deep-but not shallow-networks avoid the curse of dimensionality: a review." International Journal of Automation and Computing 14, no. 5 (2017): 503-519. ([paper)](https://arxiv.org/pdf/1611.00740.pdf)
- Telgarsky, Matus. "Representation benefits of deep feedforward networks." arXiv preprint arXiv:1509.08101 (2015). ([paper)](https://arxiv.org/abs/1509.08101)
- Montufar, Guido F., Razvan Pascanu, Kyunghyun Cho, and Yoshua Bengio. "On the number of linear regions of deep neural networks." In Advances in neural information processing systems, pp. 2924-2932. 2014.  ([paper)](https://arxiv.org/abs/1402.1869)
- Zhang, Chiyuan, Samy Bengio, Moritz Hardt, Benjamin Recht, and Oriol Vinyals. "Understanding deep learning requires rethinking generalization." arXiv preprint arXiv:1611.03530 (2016). ([paper)](https://arxiv.org/abs/1611.03530)
- Lin, Henry W., Max Tegmark, and David Rolnick. "Why does deep and cheap learning work so well?." Journal of Statistical Physics 168, no. 6 (2017): 1223-1247. ([paper)](https://arxiv.org/abs/1608.08225)
- Stéphane Mallat 1: Mathematical Mysteries of Deep Neural Networks ([video)](https://youtu.be/0wRItoujFTA)
- [Learning](https://dspace.mit.edu/bitstream/handle/1721.1/107787/CBMM-Memo-066.pdf?sequence##4 Theory of Deep Learning II: Landscape of the Empirical Risk in Deep)
- [addition](./filed/Kolmogorov1957.pdf  On the representation of continuous functions of many variables by superposition of continuous functions of one variable and)
- [Networks](./files/matus.pdf Representation Power of Feed forward Neural)
- [Networks](https://arxiv.org/pdf/1512.03965.pdf The Power of Depth for Feedforward Neural) 


###### Section 4: Reinforcement Learning
[Optimization](https://arxiv.org/abs/1802.10592 Model-Ensemble Trust-Region Policy)
[Models](https://arxiv.org/abs/1805.12114 Deep Reinforcement Learning in a Handful of Trials using Probabilistic Dynamics)
- [Truth](http://www.argmin.net/2018/02/20/reinforce/ The Policy of)
- [Yet](https://www.alexirpan.com/2018/02/14/rl-hard.html Deep Reinforcement Learning Doesn't Work)

###### Section 5: Bayesian DL
- VAE with a VampPrior ([paper)](https://arxiv.org/pdf/1705.07120.pdf)
- Bayesian DL ([blog)](http://www.datasciencecentral.com/profiles/blogs/a-curated-list-of-resources-dedicated-to-bayesian-deep-learning?utm_content##buffer3671b,utm_medium##social,utm_source##twitter.com,utm_campaign##buffer)
- Recognition Networks for Approximate Inference in BN20 Networks ([paper)](https://arxiv.org/pdf/1301.2295.pdf)
- Non-linear regression models for Approximate Bayesian Computation ([paper)](https://arxiv.org/abs/0809.4178)
- DR-ABC: Approximate Bayesian Computation with Kernel-Based Distribution Regression ([paper)](https://arxiv.org/abs/1602.04805)
- Fast ε-free Inference of Simulation Models with Bayesian Conditional Density Estimation ([paper)](https://arxiv.org/abs/1605.06376)
- Auto-Encoding Variational Bayes ([paper)](https://arxiv.org/abs/1312.6114)
- Composing graphical models with neural networks for structured representations and fast inference ([paper)](https://arxiv.org/abs/1603.06277)
- [Inference](https://arxiv.org/pdf/1802.02538.pdf Yes, but Did It Work?: Evaluating Variational)

###### Section 6: Practical Tricks
- [Averaging](https://towardsdatascience.com/stochastic-weight-averaging-a-new-way-to-get-state-of-the-art-results-in-deep-learning-c639ccf36a)
- - Normalization Propagation: A Parametric Technique for Removing Internal Covariate Shift in Deep Networks ([paper)](https://arxiv.org/pdf/1603.01431.pdf)
- Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift ([paper)](https://arxiv.org/pdf/1502.03167.pdf)
- Auto-Encoding Variational Bayes ([paper)](https://arxiv.org/pdf/1312.6114.pdf)
- Twin Networks: Using the Future as a Regularizer ([paper)](https://arxiv.org/pdf/1708.06742.pdf)
-  Don't Decay the Learning Rate, Increase the Batch Size ([paper)](https://arxiv.org/abs/1711.00489)
- DL Tuning ([blog)](http://theorangeduck.com/page/neural-network-not-working)
- [Survey](https://arxiv.org/pdf/1703.09039.pdf Efficient Processing of Deep Neural Networks: A Tutorial and)


#### Other  Resources
###### Additional Reading List
- 50 Years of Data Science by Donoho ([paper)](./files/50YearsofDataScience.pdf)
- [Overview](https://arxiv.org/pdf/1404.7828.pdf Deep Learning in Neural Networks: An)
- [Networks](https://arxiv.org/pdf/1806.11146.pdf Adversarial Reprogramming of Neural)
- [learning](http://unsupervised.cs.princeton.edu/deeplearningtutorial.html Toward theoretical understanding of deep)

###### Blogs
- Papers with code [link](https://paperswithcode.com)
- Security ([blog)](http://www.cleverhans.io)
- Unsupervised learning ([blog)](https://medium.com/intuitionmachine/navigating-the-unsupervised-learning-landscape-951bd5842df9)
- Cybersecurity ([collection)](https://medium.com/@jason_trost/collection-of-deep-learning-cyber-security-research-papers-e1f856f71042 paper)
- [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html Opt)

###### Videos
- Deep Energy ([blog)](https://deepmind.com/blog/deepmind-ai-reduces-google-data-centre-cooling-bill-40/)
- DL Summer school 2015 ([videos)](http://videolectures.net/deeplearning2015_montreal/)
- DL Representations ([blog)](http://netdissect.csail.mit.edu)
- PyData 2017 ([videos)](https://www.analyticsvidhya.com/blog/2017/05/pydata-amsterdam-2017-machine-learning-deep-learning-data-science/)

###### Other courses with good web presence
- Stanford's CS231n ([page)](http://cs231n.github.io course)
- Stanford's STATS385 ([page)](https://stats385.github.io course)
- [fast.ai](http://www.fast.ai)
- [learning](https://www.cs.ox.ac.uk/people/nando.defreitas/machinelearning/ Nando de Freitas’ course on machine)
- UC Berkeley Stat241B ([lectures)](https://bcourses.berkeley.edu/courses/1409209/pages/lectures)
- UCUC CSE598 ([page)](http://mjt.web.engr.illinois.edu/courses/mlt-f17/ course)
- [DRL](https://github.com/udacity/deep-reinforcement-learning Udacity)



###### Tools
- [TensorFlow](https://www.tensorflow.org)
- [Keras](https://keras.io)
- [(Google](http://playground.tensorflow.org TF Playground))
- [Sony](https://dl.sony.com DL) 
- [profiler](https://jiffyclub.github.io/snakeviz/ SnakeViz) (python)
- [PyTorch](http://pytorch.org)
- [Examples](https://github.com/jeffalstott/pystan_time_series TS Stan)
- [Glow](https://blog.openai.com/glow/ OpenAI)

###### Misc Links
- [projects](https://github.com/ritchieng/the-incredible-pytorch Pytorch resources) (a curated list of tutorials, papers,)
- [medium?](https://www.christies.com/Features/A-collaboration-between-two-artists-one-human-one-a-machine-9332-1.aspx Is artificial intelligence set to become art’s next)


#### Previous instances
- [2017](./2017/index.html Fall)

