---
title: "Final Project Guidelines for SYST/OR 664 CSI 674. Bayesian Inference and Decision Theory"
author: "Vadim Sokolov"
---

The final project can be done in a group (up to 3) or as is an individual project. You have a lot of freedom in choosing a topic for your final project. The only criterion is that it deeply involves applying Bayesian data analysis to a real-world problem. You choose a dataset, an interesting question about it, and address it with Bayesian modeling.


There are four milestones:
1. Project proposal (due April 7)
2. Project Presentation Draft (due April 26)
3. Presentation (April 29).
4. Final Project Report (due May 5)

*The project proposal* is to have 3 paragraphs on 

- Question you are trying to answer and why this question is interesting or important. How your analysis changes decision making process? For example if you are forecasting demand for a product, how would the company change its production process if they had a better forecast?
- Data you are using. If you are using a dataset, where did it come from?
- What model are you going to use for the data analysis?

 The proposal should be up to 1  pages long. 


*The report* is up to 5 pages long, excluding figures or references. If you wish to add more materia, put it into appending. However, the main 5-page body should be self-contained and complete. The report should be written in a clear and concise manner, and should be well-organized. The report should include the following sections:

1. Introduction: Clear description of the problem. Describe the problem you are trying to solve, why it is important or useful, and summarize any important pieces of prior work that you are building upon.
2. Dataset: Clear description/visualization of the data. Describe the dataset or datasets you are working with. Show examples from the datasets. If you collected or constructed your own dataset, explain the process you used to collect the images and labels, and why you made the choices you did in the data collection process.
3. Models/Methods: Clear and thorough description of statistical analysis. Describe the method you are using; this may also contain parts of the implementation of your model, loss function, or other components along with sanity checks to ensure that those components are correctly implemented.
4. Experiments: Clear and thorough interpretation of results. Describe the experiments you did, and key results and figures that you obtained. This may interleave explanations of the experiments you run and figures you generate as a result of those experiments.


You should turn in a .pdf file containing your final report, together wih the notebooks/markdowns containing all the code and the generated results (tables, figures etc) that are included in the report. You must run all cells in your notebook to receive credit; we will not rerun your notebook.



Both project and presentation will be evaluated on technical depth, and writing/presentation quality (50/50). Some points to keep in mind

- Visualizations should be used judiciously to report findings. Do not overload reader with tables/figures. 
- Figures should be appropriately labeled: x-axis, y-axis, legend, and title.
- Figures and tables should be numbered and referenced properly in the write-up. 
- Output of posterior predictive checks should be properly interpreted not merely stated
- At the end, you need to connect your results to the initial question of investigation.
- No more than 10 lines of text per slide. 
