{
  "hash": "8694f6fcd4bc553231171e7a4024ab23",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"AII 600 midterm prep\"\nsubtitle: \"Problem bank. Weeks 1--6. Fall 2026\"\nformat:\n  pdf:\n    header-includes:\n      - \\usepackage{amsmath}\n      - \\usepackage{amssymb}\n  html:\n    toc: true\n    toc-depth: 2\n    theme: cosmo\n    embed-resources: true\n    html-math-method: mathjax\nshowsln: true\n---\n\nWeek 8, 14 October, 2.5 hours, pen and paper. One double-sided cheat sheet, printed or handwritten. A calculator is fine. No laptop, phone, watch, or assistant.\n\nThe exam checks that you can use the basic concepts without an assistant, and that you can think about the modelling assumptions those concepts rest on.\n\n\nThis prep document covers [Foundations](https://vsokolov.org/courses/files/600/01-intro.html), [Estimation](https://vsokolov.org/courses/files/600/02-estimation.html), and linear and logistic regression from [Patterns](https://vsokolov.org/courses/files/600/03-patterns.html). The problems are from the [textbook](https://vsokolov.org/html/_book/) and Labs 1--7, sometimes with new numbers. Labs 5--7 are still coming; rework them on paper when they are posted. Arithmetic stays small enough for paper: a 2-by-2, a binomial with $n=4$, a $z$-score, a posterior from three products. You will not be asked to invert a matrix, run a double sum over a Poisson grid, or prove a derivative. A Judgment item may be a printed plot. Name the pattern, name the assumption that failed, and say which way a number you already computed would move.\n\nWeek 7 (testing, predictive values, expected value) is also on the midterm. That section will be added after 7 October.\n\nOf the 40 points, 25 are Understanding and 15 are Judgment. Problems below are marked U, J, or both. Work them on paper first.\n\n\n# Reading guide\n\nThe textbook is [Bayes, Artificial Intelligence, and Deep Learning](https://vsokolov.org/html/_book/) (Polson and Sokolov). Read the sections named below. The exam is pen and paper, so skip every Computing block and any derivation whose only job is to justify a formula you will not write. The labs and this bank are how you check that the reading stuck.\n\nYou do not need every example. You need the move in the table in the next section: name the concept, write the one-line mechanism, finish the arithmetic, say what it means, and say which way it moves if an assumption changes.\n\nWeek 7 is on the exam. Those problems will be added after 7 October. The reading for it is listed now so you can start.\n\n## Weeks 1--2. Foundations\n\nSlides: [Foundations](https://vsokolov.org/courses/files/600/01-intro.html). Labs 1 and 2.\n\n[Chapter 1. Probability and Uncertainty](https://vsokolov.org/html/_book/01-prob.html). Read from the opening through Independence and the Dutch Book notes: odds as a probability, the hitting streak, random variables, CDFs, expectation and variance, covariance and linear combinations (Tortoise and Hare), binomial / Poisson / Normal including the 1987 crash, joint / marginal / conditional, independence. Skip the inverse-CDF sampling section and Kolmogorov's strong law. Skip the Computing exercises.\n\n[Chapter 2. Bayes' Rule](https://vsokolov.org/html/_book/02-bayes.html). Read Bayes' rule and the law of total probability, the odds form, the prosecutor's fallacy, the island, Nakamura, Sally Clark, Wald, sensitivity and specificity, Alice's mammogram. Skip Naive Bayes as a spam classifier, the Obama election simulation, and the Computing exercises.\n\n## Weeks 3--4. Estimation\n\nSlides: [Estimation](https://vsokolov.org/courses/files/600/02-estimation.html). Labs 3 and 4.\n\nChapter 1, the blocks you may have deferred: discrete and continuous CDFs, named distributions, the weak law and the idea of a sampling distribution.\n\n[Chapter 3. Bayesian Learning](https://vsokolov.org/html/_book/03-bl.html), only the conjugate stories that show up on paper: the coin-toss posterior, beta-binomial, Poisson for counts, Poisson-gamma, Normal with unknown mean. Skip exchangeability as a theorem, mixtures, MCMC, the computational bridge, and Multivariate Normal.\n\n[Chapter 5. A/B Testing](https://vsokolov.org/html/_book/05-ab.html), through confidence intervals (including the z-score and the 1987 crash as a tail, which you already met in Chapter 1). Stop before multiple testing, RCTs, and split-plot designs.\n\n[Chapter 11. Pattern Matching](https://vsokolov.org/html/_book/11-pattern.html), Model Estimation through MSE vs MAE: likelihood, MLE for a Bernoulli, square loss versus absolute loss. Stop at penalized likelihood.\n\n## Weeks 5--6. Patterns\n\nSlides: [Patterns](https://vsokolov.org/courses/files/600/03-patterns.html). Lab 5.\n\n[Chapter 11](https://vsokolov.org/html/_book/11-pattern.html), the rest through Prediction Accuracy (regression and classification metrics). Skip Complex Functions if it is only neural-net notation.\n\n[Chapter 12. Linear Regression](https://vsokolov.org/html/_book/12-regression.html), through residual analysis, log and power transforms (mammal brain/body, Apple), categorical variables and dummy encoding, and the golf earnings example. Stop at quantile regression and Bayes regression. Skip Orange Juice and Newfood as computing.\n\n[Chapter 13. Logistic Regression](https://vsokolov.org/html/_book/13-logistic.html), through model fitting, log-odds, and the confusion matrix. Skim the ROC if you want a picture of TPR against FPR; you will not be asked to draw one. Stop before the kernel trick, GLMs, and Polya-Gamma.\n\nThe Patterns lecture also points at Chapters 14 and 16. Those are not on the midterm.\n\n## Week 7. Testing, predictive values, expected value\n\nSlides: the first half of [Decisions](https://vsokolov.org/courses/files/600/04-decisions.html), 7 October. Labs 6 and 7.\n\nYou already have the predictive-value arithmetic from Chapter 2 (sensitivity, specificity, PPV). Revisit it.\n\n[Chapter 5](https://vsokolov.org/html/_book/05-ab.html), Hypothesis Testing and Confidence Intervals, now as a decision: a significant difference is not yet a launch. Still stop before multiple testing.\n\nExpected value as a decision is [Chapter 1](https://vsokolov.org/html/_book/01-prob.html), Expectation and Variance, including Expectation and Strategy in the exercises (the oil drills). Full utility, paradoxes, and Kelly are Chapter 4, week 9, after the midterm.\n\n## Not on the midterm\n\nDo not spend midterm time on [Chapter 4](https://vsokolov.org/html/_book/04-dec.html) (utility, Ellsberg, Allais, Kelly), [Chapter 6](https://vsokolov.org/html/_book/06-hyp.html), Chapters 7--10, trees, ridge, or anything in Part 3 (deep learning). Chapter 3 past Poisson-gamma, Chapter 12 from quantile regression, and Chapter 13 from the kernel trick are the same: later.\n\nThe appendix on linear algebra is not required. You will not invert $X^TX$.\n\n\n# What you have to be able to do\n\nEach row is a concept and the use of it. If you cannot do the use on paper, on a problem you have not seen, you do not have the concept yet. Rework the lab or book item on paper, without the check cell.\n\n| Concept | What using it looks like | Rework |\n|---------|--------------------------|--------|\n| Complement, overlap, independence | $P(\\text{at least one})$ without adding; when multiplication is good enough and when it is not | Lab 1 cells 5--6; book Dutch Book |\n| Joint, marginal, conditional | Finish a table; $P(Y\\mid X)$ vs $P(X\\mid Y)$; independence as $P(Y\\mid X)=P(Y)$ | Lab 2 Ex 1; book Joint Distributions |\n| Bayes | Prior, likelihood, posterior. $P(D\\mid T)$ is not $P(T\\mid D)$ | Lab 2 Ex 4, 8; book Manchester, Tesla Chip, Lung Cancer, Forensic Match, Sensitivity and Specificity, Floyd Landis, Breathalyzer |\n| Linear combination | $E(aX+bY)$ always; variance needs the covariance | Lab 2 Ex 2; book IBM/Exxon, Expectation and Strategy |\n| Binomial vs Poisson | Name the count from whether there is a list of trials; write $P(X=k)$ for small $n$ | Lab 3 Ex 2--3; book Homicide |\n| Normal | $z=(x-\\mu)/\\sigma$; a quantile; a left-tail probability | Lab 4 Ex 1--2; Problem 17B |\n| Estimate | MoM and MLE for Bernoulli and Poisson are both $\\bar y$; what that number is | Book MLE for Bernoulli; lecture Poisson; Problem 22C |\n| CLT | $\\mathrm{sd}(\\bar X)=\\sigma/\\sqrt{n}$; a 95% interval for a proportion | Lab 4 Ex 4; book Voter CI |\n| OLS | Slope as a rate; $\\hat y$ at a new $x$; a residual plot as the check, not $R^2$ | Book Residual Analysis, Log Transformations, MSE vs MAE; Problems 24D, 25B, 26B |\n| Dummy variables | $k$ levels, $k-1$ columns; the reference is a choice | lecture |\n| Logistic | $p=\\sigma(x^T\\beta)$; $\\beta$ is log-odds, not a change in $p$; a threshold is a loss | Book Log-Odds; Lab 2 Ex 8 as the 2-by-2 |\n| Modelling assumption | Name it; why it was used; what would make it false; which way the number moves | Lab 2 Ex 7 written; Lab 3 Ex 5 written; Book: Expectation and Strategy, Lung Cancer, Forensic Match (g), Sensitivity and Specificity, Floyd Landis, Breathalyzer, MSE vs MAE; Problems 17B, 22C, 24D, 25B, 26B |\n\nThe orange in-class stops are the same moves. If you skipped a stop, the lab is where it went.\n\nThe cheat sheet is for the one line you will write, not a second copy of the notes. Do not copy a lab answer onto it. A short $\\Phi$ table is useful: $\\Phi(-1.645)\\approx 0.05$, $\\Phi(-1)\\approx 0.159$, $\\Phi(1.96)\\approx 0.975$.\n\nAn assumption item is looking for four sentences, not a disclaimer.\n\n1. Name the assumption (independence, iid, Poisson mean $=$ variance, linear mean, constant spread, Normal tails, $P(\\text{data}\\mid H)$ known, 0.5 threshold, sold-houses only).\n2. Why it was used (it makes the model multiply, or gives $\\hat\\lambda=\\bar y$, or makes OLS $=$ MLE).\n3. What in this problem would make it false.\n4. Which way the reported number moves, or whether the number is still good enough for the purpose. Sally Clark vs a clean shift is the template: same assumption, two purposes, two verdicts.\n\n\n# 1. Probability, independence, expectation\n\nFrom [Foundations](https://vsokolov.org/courses/files/600/01-intro.html) and Lab 1. Book Chapter 1.\n\nA probability is a number you will bet at, and it has to add to one on a partition. Independence lets you multiply; that is a modelling choice, not a fact about the world. Expectation always plugs in linearly; variance does not, unless the covariance is zero.\n\nYou should be able to: write $P(\\text{at least one})$ from the complement; say when the product is good enough (a clean shift) and when it is not (Sally Clark); compute $E(aX+bY)$ and $\\mathrm{Var}(aX+bY)$ from means, variances, and one covariance.\n\n## Problem 1. A clean shift (U, J)\n\nLab 1 Cell 6 and the hitting-streak stop, new numbers. Book: independence is the same move as Dutch Book is for additivity --- a rule you use, then judge.\n\nA warehouse scanner misses a package with probability $0.08$. Eight packages pass in a row. Call the shift clean if none are missed.\n\na. Assuming misses are independent, what is $P(\\text{clean shift})$?\n\nb. Give one reason consecutive scans are not independent.\n\nc. Why might you still use the independence model for this probability, and name one example from class where multiplying as if independent is not good enough.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $P(\\text{clean})=(0.92)^8\\approx 0.513$.\n\nb. A jam, a bad label batch, or a lighting change hits several packages in a row. One miss can also mean the next packages are rushed.\n\nc. Independence gives a number we can compute from one rate, and for \"how unusual is a clean shift?\" that number is close enough. Sally Clark is the counterexample: treating two SIDS deaths as independent turns $1/850{,}000$ into $1/73{,}000{,}000$ and makes the mother look guilty.\n:::\n:::\n\n## Problem 2. Dutch Book (U)\n\nBook Chapter 1, Dutch Book and Coherence.\n\nA racetrack analyst quotes $P(\\text{Alpha})=0.50$, $P(\\text{Beta})=0.35$, $P(\\text{Gamma})=0.25$ for a three-horse race. Exactly one horse wins.\n\na. Which axiom do the quotes violate?\n\nb. Should you buy or sell equal contracts on all three, and what is the sure profit on a $\\pm 100$ stake?\n\nc. She revises Gamma to $0.15$. Is the book now coherent under the equal-stake construction?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The three outcomes partition the sample space, so coherence (normalisation plus additivity) requires the prices to sum to $1$. They sum to $1.10$.\n\nb. Sell. Take $S=-100$: collect $110$ up front, pay $100$ on whichever horse wins, profit $\\$10$ in every world.\n\nc. Yes. The prices now sum to $1$, so the equal-stake gain $G=S(1-\\sum P(A_i))$ is zero.\n:::\n:::\n\n## Problem 3. A mix of two salespeople (U)\n\nLab 2 Exercise 2; in-class stop.\n\nYou split Saturday's leads: half to Tortoise, half to Hare. $P=\\tfrac12 T+\\tfrac12 H$ is the average per rep. $E(T)=E(H)=1.5$, $\\mathrm{Var}(T)=0.25$, $\\mathrm{Var}(H)=2.25$, $\\mathrm{Cov}(T,H)=-0.75$.\n\nCompute $E(P)$ and $\\mathrm{Var}(P)$. Compare $\\mathrm{Var}(P)$ to $\\mathrm{Var}(T)$. What did the covariance do?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n$E(P)=1.5$.\n$$\n\\mathrm{Var}(P)=\\tfrac14\\cdot 0.25+\\tfrac14\\cdot 2.25+2\\cdot\\tfrac12\\cdot\\tfrac12\\cdot(-0.75)=0.0625+0.5625-0.375=0.25.\n$$\nSame mean and same variance as Tortoise alone. Without the covariance you would have $0.625$, worse than Tortoise. Perfect negative correlation is what cancels Hare's noise.\n:::\n:::\n\n## Problem 3B. Oil: expected payoff is not the decision (J)\n\nBook Chapter 1, Expectation and Strategy.\n\nAn oil company can use a standard drill or a more expensive horizontal drill. Chance of a small / moderate / large find: $0.2$, $0.5$, $0.3$. Payoffs in \\$millions:\n\n| | small | moderate | large |\n|--|------:|---------:|------:|\n| Standard | 20 | 30 | 40 |\n| Horizontal | $-20$ | 40 | 80 |\n\na. Expected payoff and variance for each strategy. Which maximises expected payoff?\n\nb. If you are risk averse, which do you choose, and what assumption about \"maximise $E(X)$\" just failed?\n\nc. A geological study would reveal the size of the find before you choose the drill. What is the most you should pay for that study? What did you assume about the study?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Standard: $E=31$, $\\mathrm{Var}=49$. Horizontal: $E=40$, $\\mathrm{Var}=1200$. Horizontal maximises expected payoff.\n\nb. Standard. Maximising $E(X)$ treats a sure 31 and a 40-with-a-possible-loss-of-20 as ranked only by the mean. Risk aversion is a different loss.\n\nc. With the study you pick standard on small ($20$ beats $-20$), horizontal otherwise: $0.2\\cdot 20+0.5\\cdot 40+0.3\\cdot 80=48$. Willing to pay $48-40=8$ million. You assumed the study is perfect, and that you will actually switch the drill once you see the result.\n:::\n:::\n\n## Problem 4. True or false (U)\n\nBook Chapter 1, True/False Variance and Expectation. Answer each in one sentence.\n\na. If $\\mathrm{Cov}(X,Y)=0$, then $X$ and $Y$ are independent.\n\nb. If $X$ and $Y$ are independent, $\\mathrm{Var}(2X-Y)=2\\mathrm{Var}(X)-\\mathrm{Var}(Y)$.\n\nc. $E(X+Y)=E(X)+E(Y)$ only if $X$ and $Y$ are independent.\n\nd. $E(\\bar X)=\\mu$.\n\ne. Correlation lies in $[0,1]$.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. False. Uncorrelated does not imply independent, except in special cases (joint Normal).\n\nb. False. $\\mathrm{Var}(2X-Y)=4\\mathrm{Var}(X)+\\mathrm{Var}(Y)$ under independence.\n\nc. False. Linearity of expectation does not need independence.\n\nd. True.\n\ne. False. Correlation is in $[-1,1]$.\n:::\n:::\n\n\n# 2. Joint tables, Bayes, evidence\n\nLab 2 and the second half of Foundations. Book Chapter 2.\n\nA joint table is three distributions in one grid: joint, row/column sums (marginals), and ratios (conditionals). Bayes is the same ratio with names: prior, likelihood, posterior. $P(D\\mid T)$ is not $P(T\\mid D)$. The prosecutor's fallacy is reporting the second and calling it the first.\n\nYou should be able to: finish a table and read $P(Y\\mid X)$ and $P(X\\mid Y)$ from different denominators; update a two-type prior with a binomial likelihood; turn a 2-by-2 of counts into TPR and into PPV, and say which number Alice needs after a positive.\n\n## Problem 5. Joint table (U, J)\n\nBook Chapter 1, Joint Distributions. Same move as Lab 2 Exercise 1.\n\nA credit-card book of $10{,}000$ customers:\n\n| bal \\ def | 0 | 1 |\n|-----------|---|---|\n| 1 (low)   | 8,940 | 64 |\n| 2         | 651 | 136 |\n| 3 (high)  | 76 | 133 |\n\na. Marginal distribution of `def`.\n\nb. Conditional distribution of `bal` given `def` $=1$.\n\nc. Predict status for a customer with a high balance. Compare to low balance.\n\nd. A product team wants to pitch only to `bal` $=3$ because \"that is where the defaults are.\" Using the numbers: who does that mix up, and what would you check before restricting the book?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $P(\\mathrm{def}=0)=0.9667$, $P(\\mathrm{def}=1)=0.0333$.\n\nb. Given default: $64/333\\approx 0.192$, $136/333\\approx 0.408$, $133/333\\approx 0.399$.\n\nc. $P(\\mathrm{def}=1\\mid\\mathrm{bal}=3)=133/209\\approx 0.636$. $P(\\mathrm{def}=1\\mid\\mathrm{bal}=1)=64/9004\\approx 0.007$. About ninety times more likely at high balance.\n\nd. The team is mixing $P(\\mathrm{bal}\\mid\\mathrm{def})$ with $P(\\mathrm{def}\\mid\\mathrm{bal})$. Most defaults are not in the high-balance cell in count terms (64 and 136 sit elsewhere); the *rate* is high at `bal` $=3$. Restricting the pitch to high balance misses current customers in bands 1 and 2 and bothers a slice that is only 64% default, not \"the defaulters.\" Check the purpose: collections vs a wellbeing product are different losses.\n:::\n:::\n\n## Problem 6. Manchester (U)\n\nBook Chapter 2, Manchester.\n\nSomeone in a bar is supporting Manchester United. $P(\\text{born within 20 miles})=1/20$. If born there, they support United with probability $7/10$; otherwise $1/10$. What is $P(\\text{born there}\\mid\\text{supports United})$?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n$$\nP(B\\mid U)=\\frac{(7/10)(1/20)}{(7/10)(1/20)+(1/10)(19/20)}=\\frac{0.035}{0.130}\\approx 0.269.\n$$\nMost United shirts in a typical bar were not born in Manchester.\n:::\n:::\n\n## Problem 7. Tesla chip (U)\n\nBook Chapter 2, Tesla Chip.\n\nThirty percent of chips from Matsushita (3% defective), 20% Philips (5%), 50% Hitachi (4%). A chip is defective. Posterior on each manufacturer?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\n$P(D)=0.30\\cdot 0.03+0.20\\cdot 0.05+0.50\\cdot 0.04=0.039$.\n\n$P(\\text{Matsushita}\\mid D)=9/39$, $P(\\text{Philips}\\mid D)=10/39$, $P(\\text{Hitachi}\\mid D)=20/39$.\n:::\n:::\n\n## Problem 7B. You did not need the incidence (J)\n\nBook Chapter 2, Lung Cancer.\n\nWomen who smoke are about 13 times more likely to develop lung cancer than women who do not. In 2016, $17.9\\%$ of women smoked.\n\na. $P(\\text{smoker}\\mid\\text{lung cancer})$. Let $y=0.179$ be the smoking rate and $x$ the rate of lung cancer among nonsmokers. Show that $x$ cancels.\n\nb. Most people guess a number well below $74\\%$. What did they treat as the answer instead of $P(\\text{smoker}\\mid\\text{cancer})$?\n\nc. The $13$ is a relative risk from a population. What would make it the wrong likelihood ratio for *this* woman?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Smokers with cancer are proportional to $13xy$, nonsmokers with cancer to $x(1-y)$. Then\n$$\nP(S\\mid C)=\\frac{13y}{13y+(1-y)}=\\frac{13\\cdot 0.179}{13\\cdot 0.179+0.821}\\approx 0.74.\n$$\nThe absolute risk $x$ cancels. You needed the relative risk and the smoking rate, not $P(\\text{cancer})$.\n\nb. They answered $P(\\text{cancer}\\mid\\text{smoker})$, or the smoking rate $17.9\\%$, or \"$13$ times more likely so it must be nearly certain.\" The question is the other conditional.\n\nc. This woman is not a draw from the CDC table: age, asbestos, a family history, or a clinic that already selected for respiratory disease. Then the $13$ is someone else's likelihood ratio, and $74\\%$ is not her posterior.\n:::\n:::\n\n## Problem 8. The island (U, J)\n\nLab 2 Exercise 4; Book Chapter 2, Island Problem.\n\nA man is arrested on an island of $1{,}001$ people. The crime-scene trait occurs in $1$ in $10{,}000$ people; it matches him. Uniform prior. $P(\\text{match}\\mid\\text{guilty})=1$.\n\nThe prosecutor tells the jury: \"The match probability is 1 in 10,000, so there is a 99.99% chance he is guilty.\"\n\na. Prior odds he is innocent.\n\nb. Posterior odds of innocence, and $P(\\text{guilty}\\mid\\text{match})$.\n\nc. One sentence to the jury.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $O(I)=1000/1=1000$.\n\nb. Bayes factor for innocence is $10^{-4}$, so $O(I\\mid E)=0.1$. Then $P(I\\mid E)=0.1/1.1\\approx 0.091$, so $P(G\\mid E)\\approx 0.91$.\n\nc. The prosecutor reported $1-P(\\text{match}\\mid\\text{innocent})$, not $P(\\text{guilty}\\mid\\text{match})$. Expected matches among the other 1,000 people: $0.1$. That $0.1$ is why the posterior is $0.91$, not $0.9999$, and not a conviction.\n:::\n:::\n\n## Problem 8B. A match is not a conviction (J)\n\nBook Chapter 2, Forensic Match.\n\n$P(E\\mid G)=0.90$, $P(E\\mid\\text{innocent})=0.02$. Prior $P(G)=1/200$.\n\na. Bayes factor for a match, posterior odds, and $P(G\\mid E)$.\n\nb. A second, conditionally independent eyewitness has Bayes factor $3$. Posterior probability after both?\n\nc. Is $40\\%$ enough to convict \"beyond a reasonable doubt\"? What assumption about the eyewitness would make the $3$ too large?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $\\mathrm{BF}=0.90/0.02=45$. Prior odds $1/199$. Posterior odds $45/199\\approx 0.226$, so $P(G\\mid E)=45/244\\approx 0.184$.\n\nb. $O=3\\times 45/199=135/199$, $P=135/334\\approx 0.404$.\n\nc. No. A $45\\times$ match and a $3\\times$ witness still leave the prior in charge. If the eyewitness is more likely to pick the person who already matched (not conditionally independent given guilt), you multiplied a Bayes factor you did not have. Same machine as the island and Nakamura.\n:::\n:::\n\n## Problem 9. A closer (U, J)\n\nLab 2 Exercise 6.\n\nHalf the bootcamp convert 70% of qualified leads, half convert 30%. First week: 3 closes out of 4. Equal priors.\n\na. Likelihood ratio $P(\\text{3 of 4}\\mid 70\\%)/P(\\text{3 of 4}\\mid 30\\%)$.\n\nb. $P(\\text{70\\% closer}\\mid\\text{3 of 4})$.\n\nc. One sentence to the sales manager: put them on the enterprise book, or is four leads still \"too small to say\"?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The $\\binom{4}{3}$ cancels: $0.7^2/0.3^2\\approx 5.44$.\n\nb. $5.44/(1+5.44)\\approx 0.845$.\n\nc. Four leads moved you from 50% to 85%. That is not \"too small to say.\" The enterprise book is a 15% chance you just promoted the 30% closer. Say that, then decide.\n:::\n:::\n\n## Problem 9B. Likelihoods you treated as known (J)\n\nLab 2 Exercise 7, written part. The arithmetic is in the lab; this is the assumption.\n\nNew products have high sales 8% of the time. If sales are high, a focus group is positive 70% of the time; if low, 15%. You treat those two numbers as $P(\\text{Pos}\\mid H)$ and $P(\\text{Pos}\\mid L)$, then report $P(H\\mid\\text{Pos})\\approx 0.29$.\n\na. What two distinct things can go wrong when you take focus-group reactions as $P(\\text{Pos}\\mid H)$? Who is in the room is one class of problem; what people say versus what they do is another.\n\nb. If the people who show up are already more enthusiastic than the market, which of $P(\\text{Pos}\\mid H)$ and $P(\\text{Pos}\\mid L)$ moves, and what happens to $P(H\\mid\\text{Pos})$?\n\nc. The 8% is the number to beat. Is 29% a launch? What would you need to know about the cost of a failed launch versus a missed hit?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The room is not the market: volunteers, staff, or a city that already likes the category. And a stated \"I would buy\" is not a sale. Either way you have estimated a different likelihood than the one the posterior needs.\n\nb. Both likelihoods of a positive reaction go up if the room is more enthusiastic than the market. The likelihood ratio $P(\\text{Pos}\\mid H)/P(\\text{Pos}\\mid L)$ can rise or fall; if the low-sales group becomes almost as positive as the high-sales group, the Bayes factor shrinks and $P(H\\mid\\text{Pos})$ falls toward the 8% prior. The usual failure is that a positive stops distinguishing.\n\nc. 29% is not a launch on its own. A failed launch that is costly relative to a missed hit wants a higher posterior than 29%; a cheap test with a large upside can live with 29%. The 8% is the prior, not the decision.\n:::\n:::\n\n## Problem 10. Mammogram (U, J)\n\nLab 2 Exercise 8; Alice in lecture.\n\nPrevalence 1%, detection rate 80%, false-positive rate 10%. In 1,000 people like Alice: 10 have cancer, 8 true positives, 99 false positives, 2 false negatives, 891 true negatives.\n\na. TPR, FNR, FPR, TNR from the 2-by-2.\n\nb. $P(\\text{cancer}\\mid\\text{positive})$.\n\nc. A radiologist says \"the test is 80% accurate.\" Which of your four rates is that, and why is it not the number Alice needs after a positive?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $\\mathrm{TPR}=8/10=0.8$, $\\mathrm{FNR}=0.2$, $\\mathrm{FPR}=99/990=0.1$, $\\mathrm{TNR}=0.9$.\n\nb. $8/(8+99)=8/107\\approx 0.075$.\n\nc. \"80% accurate\" is sensitivity, $P(T\\mid D)$. Alice needs $P(D\\mid T)\\approx 7.5\\%$. Most positives are the 99 false alarms from the 990 without cancer.\n:::\n:::\n\n## Problem 10B. Should Nvidia use the test? (J)\n\nBook Chapter 2, Sensitivity and Specificity.\n\nA chip is defective with probability $0.1\\%$. The test always flags a defective chip, and flags a good chip with probability $1\\%$.\n\na. Sensitivity and specificity.\n\nb. $P(\\text{defective}\\mid\\text{flagged})$ and $P(\\text{flagged})$.\n\nc. Advise Nvidia whether to scrap every flagged chip. What loss did you just use, and what would flip the advice?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Sensitivity $1$, specificity $0.99$.\n\nb. $P(D\\mid T)=0.001/(0.001+0.01\\cdot 0.999)\\approx 0.091$. About $1.1\\%$ of chips are flagged.\n\nc. Do not scrap them all: $91\\%$ of flags are good chips. That advice assumes a good chip is costly to throw away relative to a defective one that ships. Flip it if a defective chip in the wild is catastrophic (a recall, a car) compared with the cost of a spare: then flag-and-retest, or a second test on the $1.1\\%$, rather than \"the sensitivity is 100% so ship only the negatives.\"\n:::\n:::\n\n## Problem 10C. Eight tests, one rider (J)\n\nBook Chapter 2, Floyd Landis.\n\nLandis gave eight urine samples. Specificity $95\\%$. Treat the eight tests as independent given innocence.\n\na. $P(\\text{all eight negative}\\mid\\text{innocent})$. Then $P(\\text{at least one positive}\\mid\\text{innocent})$.\n\nb. What did independence do, and why might consecutive samples from one rider not be independent?\n\nc. In court, is \"at least one positive\" under independence a probability of guilt? What else do you need?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $0.95^8\\approx 0.663$, so $P(\\text{at least one FP}\\mid\\text{innocent})=1-0.95^8\\approx 0.337$.\n\nb. Independence lets you raise $0.95$ to the 8th. One lab, one rider, one stage: a contaminated kit or a lab shift hits several samples together. Then $P(\\text{at least one FP})$ is closer to $0.05$ than to $0.34$.\n\nc. No. That is $P(E\\mid\\text{innocent})$, the prosecutor's number. You still need a prior and $P(E\\mid\\text{guilty})$. Eight opportunities inflate the chance of a flag under innocence; they do not, by themselves, convict.\n:::\n:::\n\n## Problem 10D. The prior moved (J)\n\nBook Chapter 2, Breathalyzer Test.\n\nSensitivity $99\\%$, specificity $90\\%$, prior that the driver is over the limit $10\\%$.\n\na. $P(\\text{over}\\mid\\text{positive})$.\n\nb. At Christmas the prior is $20\\%$. Same posterior?\n\nc. The device did not change. What did, and for a checkpoint that tests everyone, which prior is the right one?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $0.99\\cdot 0.10/(0.99\\cdot 0.10+0.10\\cdot 0.90)=0.099/0.189\\approx 0.524$.\n\nb. $0.99\\cdot 0.20/(0.198+0.10\\cdot 0.80)=0.198/0.278\\approx 0.712$.\n\nc. The base rate. A random checkpoint uses the population prior (10% on an ordinary night, 20% at Christmas). A stop after weaving is a different prior, and the $52\\%$ is the wrong number for that stop.\n:::\n:::\n\n## Problem 11. Alarm, explaining away (U, J)\n\nLab 3 Exercise 1.\n\n$p(b)=2\\cdot 10^{-4}$, $p(e)=10^{-2}$, $p(r=1\\mid e=1)=0.5$, $p(r=1\\mid e=0)=0$, and\n\n| $p(a=1\\mid b,e)$ | $b$ | $e$ |\n|:---:|:---:|:---:|\n| 0 | 0 | 0 |\n| 0.1 | 0 | 1 |\n| 1 | 1 | 0 |\n| 1 | 1 | 1 |\n\na. $P(a=1\\mid b=0)$ and $P(b=1\\mid a=1)$. The second is Bayes with two causes.\n\nb. Same posterior if $p(b)=10^{-3}$. What did raising the prior do?\n\nc. The radio reports a small earthquake. Does $P(b=1\\mid a=1,r=1)$ go up or down from $P(b=1\\mid a=1)$? Why, in two sentences, and why is that not \"the alarm was a false positive\"?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $P(a=1\\mid b=0)=0.1\\cdot 0.01=0.001$. Then\n$$\nP(b=1\\mid a=1)=\\frac{2\\cdot 10^{-4}}{2\\cdot 10^{-4}+0.001\\cdot(1-2\\cdot 10^{-4})}\\approx 0.167.\n$$\n\nb. About $0.50$. A larger prior on burglary, with the same likelihood, raises the posterior. That is Bayes, not a new alarm model.\n\nc. Down. The radio is an alternative cause of the same alarm (explaining away). The sensor still sounded; burglary is just no longer the remaining explanation.\n:::\n:::\n\n## Problem 12. Holes you can see (U, J)\n\nLab 2 Exercise 3; Wald.\n\n316 planes returned. Cockpit: 36 returned, 21 down. Engine: 29 returned, 31 down. Someone counted 36 cockpit holes on the planes that came back and wants cockpit armor.\n\na. Among the planes you can see, how common is cockpit damage?\n\nb. Among planes that took a cockpit hit, how often did the plane come back? Same question for engine.\n\nc. Which of those numbers goes in the brief? One sentence on what $36/316$ is actually describing.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $36/316\\approx 0.114$.\n\nb. Cockpit: $36/57\\approx 0.63$ came back. Engine: $29/60\\approx 0.48$.\n\nc. Armor goes where returning was rare given the hit. The 11% is holes on the planes you can see. The 63% vs 48% is the decision.\n:::\n:::\n\n\n# 3. Binomial, Poisson, Normal\n\nLabs 3 and 4, and the last block of Foundations. Book Chapter 1, named distributions.\n\nA binomial is a list of independent yes/no trials. A Poisson is a count with a rate and no such list. The Normal is a location and a scale; a $z$-score is a change of units. $P(X\\le x)=\\Phi((x-\\mu)/\\sigma)$. A large count can borrow the bell.\n\nYou should be able to: name Binomial or Poisson from the story; write $P(X=k)$ for $n=4$ by hand; standardise a Normal and read a tail or a quantile; say which way a tail probability moves if the left tail is heavier than the bell; read a histogram against a fitted density and say where the model is lying.\n\n## Problem 13. Name the count (U)\n\nLab 3 Exercise 2.\n\nFor each, say Binomial or Poisson, and why.\n\na. 80 independently tested circuit boards. $X=$ number that fail.\n\nb. Cardiac-arrest calls to 911 between midnight and 6am.\n\nc. A subscriber is shown 12 thumbnails. $X=$ number they click. Each click independent with the same $p$.\n\nd. Goals Hull scores against Man U on Saturday.\n\nThen one calculation: overnight calls $\\mathrm{Poisson}(\\lambda=2.2)$. Write $P(X=0)$ and compute it. Why is that the right model rather than $\\mathrm{Binomial}(n,p)$ for some $n$?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Binomial: a list of 80 independent yes/no trials.\n\nb. Poisson: a rate, no list of trials.\n\nc. Binomial: 12 independent clicks.\n\nd. Poisson: a rate of goals, not 90 independent minute-trials with a fixed $p$.\n\n$P(X=0)=e^{-2.2}\\approx 0.111$. There is no roster of \"potential calls\" with a success probability. The Poisson is the count that remains when you only have a rate.\n:::\n:::\n\n## Problem 14. Four at-bats (U)\n\nLab 3 Exercise 3, first number. Lecture self-check.\n\nJoe DiMaggio, $p=0.325$ per at-bat. Treat four at-bats as independent Bernoulli trials.\n\na. Name the distribution of $X=$ hits in a game.\n\nb. Write $P(X>2)$ as two binomial terms, then compute it. Do not paste $0.104$ from a slide.\n\nc. What did independence do for you, and what would a hot-hand (a hit raising the next $p$) do to this probability?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $X\\sim\\mathrm{Binomial}(4,0.325)$.\n\nb. $P(X=3)+P(X=4)=\\binom{4}{3}(0.325)^3(0.675)+(0.325)^4\\approx 0.0927+0.0112=0.104$.\n\nc. Independence lets the pmf factor. A hot-hand raises $P(X>2)$: the mass on 3 and 4 hits moves up relative to the independent calculation. The 56-game streak is this 10% stacked, not a typical night.\n:::\n:::\n\n## Problem 15. Two independent Poissons (U)\n\nLab 3 Exercise 4, the one term you can write by hand.\n\nHull (home) $X\\sim\\mathrm{Poisson}(0.71)$, Man U (away) $Y\\sim\\mathrm{Poisson}(2.41)$, independent.\n\na. Why is independence of $X$ and $Y$ a modelling choice here?\n\nb. $P(X=0,Y=1)$, the $0$--$1$ that actually happened. Write it as a product of two Poisson pmfs.\n\nc. If the two teams' scores were positively dependent (a high-scoring night for both), would $P(0\\text{--}1)$ go up or down?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Goals by one side can affect the other (red cards, sitting on a lead). Independence is what lets $P(X=x,Y=y)=P(X=x)P(Y=y)$.\n\nb. $P(0,1)=e^{-0.71}\\cdot e^{-2.41}\\cdot 2.41\\approx 0.106$.\n\nc. Down. Positive dependence puts more mass on $(0,0)$ and on high--high, and less on mixed scores such as $0$--$1$.\n:::\n:::\n\n## Problem 16. Warranty (U, J)\n\nLab 4 Exercise 1.\n\nLife $L\\sim N(10,3^2)$ years. The warranty pays if $L<5$. A shipment has 80 independent components.\n\na. $p=P(L<5)$. Write the $z$-score. Name the distribution of $X=$ number of claims in the shipment, and write $E(X)$.\n\nb. If lives have a heavier left tail than this Normal, which way does $E(X)$ move? Which of the two models did you change, and which did you keep?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $z=(5-10)/3=-5/3\\approx -1.67$, so $p=\\Phi(-1.67)\\approx 0.048$. $X\\sim\\mathrm{Binomial}(80,p)$, $E(X)=80p\\approx 3.8$.\n\nb. A heavier left tail raises $p$, so $E(X)$ rises. You changed the model for $L$. The binomial layer that turns $p$ into a count is the same.\n:::\n:::\n\n## Problem 17. A month in the book (U, J)\n\nLab 4 Exercise 2.\n\nMonthly return $X\\sim N(0.008,0.035^2)$.\n\na. $P(X<-0.08)$.\n\nb. $z$-score of a $-12\\%$ month.\n\nc. The $1\\%$ quantile of $X$.\n\nd. The officer wants $P(X<-0.08)=0.05$ without changing the mean. What $\\sigma$ would that take? Use $\\Phi^{-1}(0.05)\\approx -1.645$, not $1.96$.\n\ne. The 1987 crash was a 5-sigma month under a Normal fitted to earlier data. Is $P(X<-0.08)$ under the Normal too small, too large, or could it go either way?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $z=(-0.08-0.008)/0.035=-2.51$, so $P\\approx 0.006$.\n\nb. $z=(-0.12-0.008)/0.035\\approx -3.66$.\n\nc. $q=0.008+0.035\\cdot\\Phi^{-1}(0.01)\\approx -0.073$.\n\nd. $(-0.08-0.008)/\\sigma=-1.645$ gives $\\sigma\\approx 0.0535$. The book's $0.035$ is too tight if a 5% month is the risk the officer actually wants to price.\n\ne. A heavier-tailed histogram than the bell makes far-left probabilities larger than the Normal says, so $0.006$ is too small. That is the crash lesson, not a maybe.\n:::\n:::\n\n## Problem 17B. The histogram is not a bell (J)\n\nLecture: Normal tails; Lab 4 Exercise 2. Same monthly returns as Problem 17, now as a picture.\n\nThe histogram is 80 months. The dashed curve is $N(0.008, 0.035^2)$, the model from Problem 17, scaled to the same bins.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Monthly returns. Histogram of 80 months; dashed curve is the Normal used in Problem 17, scaled to the same bins.](midterm-prep_files/figure-pdf/unnamed-chunk-1-1.pdf)\n:::\n:::\n\n\na. Where does the histogram disagree with the dashed curve? (The dotted vertical line is $-8\\%$, the event in Problem 17a.)\n\nb. Is $P(X<-0.08)\\approx 0.006$ from the Normal too small, too large, or could it go either way?\n\nc. Collecting 800 months instead of 80, still from this world, would make the histogram look more like the dashed curve. True or false, and what did you just assume?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The centre is a bit too peaked, and both tails have mass the Normal put at nearly zero. Several months sit left of $-8\\%$, where the dashed curve is already on the floor.\n\nb. Too small. The left tail of the histogram is heavier than $\\Phi(-2.51)$.\n\nc. False. A larger $n$ makes the histogram closer to the *true* density, which here is not Normal. The dashed curve is the wrong family, not a noisy estimate of the right one. The 1987 lesson is the same: more months will not manufacture a bell. The eight months left of $-8\\%$ are already a larger left tail than $\\Phi(-2.51)\\approx 0.006$ allows.\n:::\n:::\n\n## Problem 18. A large count (U)\n\nLab 4 Exercise 3.\n\n$n=400$ people, each buys independently with $p=0.12$. $X=$ number who buy.\n\na. Name the distribution of $X$. Write $E(X)$ and $\\mathrm{sd}(X)$.\n\nb. Using the Normal with that mean and sd, $P(X\\ge 60)$ is $P(Z\\ge ?)$. What is the $z$? You may leave the tail as $1-\\Phi(z)$.\n\nc. Why is a Normal even in the conversation? The $X_i$ are 0--1.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $X\\sim\\mathrm{Binomial}(400,0.12)$. $E(X)=48$, $\\mathrm{sd}(X)=\\sqrt{400\\cdot 0.12\\cdot 0.88}=\\sqrt{42.24}\\approx 6.50$.\n\nb. $z=(60-48)/6.50\\approx 1.85$. $P\\approx 1-\\Phi(1.85)$. (A continuity correction uses $59.5$ instead of $60$; that is optional on the exam.)\n\nc. CLT: a sum of many independent Bernoulli trials is approximately Normal. The binomial is already that sum. You are not claiming each person is Normal.\n:::\n:::\n\n\n# 4. Estimation: CDF, moments, likelihood, CLT\n\n[Estimation](https://vsokolov.org/courses/files/600/02-estimation.html). Book Chapters 1.4, 1.6, 3, 5 (through CIs), 11.4.\n\nAn estimate is a function of the data, hence random. Method of moments matches $E(X^k)$ to the sample moment. Maximum likelihood picks the $\\theta$ that makes the observed sample most probable. For Bernoulli and Poisson both methods return $\\bar y$. The CLT is why $\\bar X$ looks Normal even when $X_i$ does not, and why the standard error falls as $1/\\sqrt{n}$.\n\nYou should be able to: read $P(X=x)$ from a CDF; write $\\hat\\lambda=\\bar X$ and say whether that is MoM, MLE, or both; turn $\\hat p$ and $n$ into a 95% interval; say what happens to the interval if $n$ quadruples; compare a bar of observed counts to the Poisson (or binomial) those counts were supposed to follow.\n\n## Problem 19. CDF and a leftover delivery (U)\n\nBook Chapter 1, Conditional Probability (delivery times).\n\nDelivery day $X\\in\\{1,\\ldots,7\\}$ with CDF\n\n| $x$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 |\n|-----|---|---|---|---|---|---|---|\n| $P(X\\le x)$ | 0.10 | 0.20 | 0.70 | 0.75 | 0.80 | 0.90 | 1 |\n\na. Fill $P(X=x)$.\n\nb. $P(X=4\\mid X\\ge 4)$.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Differences of the CDF: $0.10,0.10,0.50,0.05,0.05,0.10,0.10$.\n\nb. $P(X=4\\mid X\\ge 4)=0.05/(1-0.70)=0.05/0.30=1/6$.\n:::\n:::\n\n## Problem 20. Method of moments (U)\n\nLecture: Poisson alpha particles; Normal body temperature.\n\na. $X_1,\\ldots,X_n$ iid $\\mathrm{Poisson}(\\lambda)$. Write the MoM estimator of $\\lambda$.\n\nb. $Y_i$ iid $N(\\mu,\\sigma^2)$. Write the MoM estimators of $\\mu$ and $\\sigma^2$. How does $\\hat\\sigma^2$ differ from R's `var()`?\n\nc. Five counts: $2,0,3,1,4$. Compute $\\hat\\lambda_{\\mathrm{MoM}}$. Is this also the MLE? Why, in one sentence?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $E(X)=\\lambda$, so $\\hat\\lambda=\\bar X$.\n\nb. $\\hat\\mu=\\bar Y$, $\\hat\\sigma^2=\\frac1n\\sum(Y_i-\\bar Y)^2$. R's `var()` uses $n-1$. MoM uses $n$. For large $n$ they agree; the MLE for $\\sigma^2$ is also the $n$ version.\n\nc. $\\hat\\lambda=10/5=2$. Yes: for Poisson, MLE and MoM are both the sample mean, because $E(X)=\\lambda$ is also the score equation from $\\ell(\\lambda)=\\sum y_i\\log\\lambda-n\\lambda$.\n:::\n:::\n\n## Problem 21. Bernoulli MLE (U)\n\nBook Chapter 11, MLE for Bernoulli.\n\n$y_1,\\ldots,y_n\\in\\{0,1\\}$, $P(Y=1)=\\theta$.\n\na. Likelihood $L(\\theta)$.\n\nb. Log-likelihood $\\ell(\\theta)$.\n\nc. MLE.\n\nd. Second derivative: why is it a maximum?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $L(\\theta)=\\theta^{\\sum y_i}(1-\\theta)^{n-\\sum y_i}$.\n\nb. $\\ell(\\theta)=\\sum y_i\\log\\theta+(n-\\sum y_i)\\log(1-\\theta)$.\n\nc. $\\hat\\theta=\\bar y$.\n\nd. $\\ell''(\\theta)=-\\sum y_i/\\theta^2-(n-\\sum y_i)/(1-\\theta)^2<0$ wherever both counts are positive.\n:::\n:::\n\n## Problem 22. Poisson MLE and a Gamma prior (U, J)\n\nBook Chapter 3, Poisson MLE vs Bayes, paper parts.\n\nClicks per minute, $n=20$, $\\sum y_i=79$ (so $\\bar y=3.95$). Poisson $\\lambda$.\n\na. Write $\\ell(\\lambda)$ and show $\\hat\\lambda_{\\mathrm{MLE}}=\\bar y$.\n\nb. Historical mean and variance of $\\lambda$ were both $4$. A $\\mathrm{Gamma}(\\alpha,\\beta)$ prior (shape-rate) has mean $\\alpha/\\beta$ and variance $\\alpha/\\beta^2$. One choice of $(\\alpha,\\beta)$? Posterior mean?\n\nc. After a few days, about 20% of minutes are zero. The Poisson with $\\lambda\\approx 4$ has $P(X=0)=e^{-4}\\approx 0.018$. What did the 20% do to the model, and would you keep a single Poisson?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $\\ell(\\lambda)=\\sum y_i\\log\\lambda-n\\lambda$, derivative $\\sum y_i/\\lambda-n=0$, so $\\hat\\lambda=\\bar y=3.95$.\n\nb. $\\alpha/\\beta=4$ and $\\alpha/\\beta^2=4$ gives $\\beta=1$, $\\alpha=4$. Posterior is $\\mathrm{Gamma}(4+79,1+20)=\\mathrm{Gamma}(83,21)$, mean $83/21\\approx 3.95$. Twenty observations have already drowned a prior with virtual count $5$.\n\nc. Too many zeros for a Poisson with that mean. A single Poisson cannot match a high mean and a large atom at zero. A zero-inflated Poisson, or two rates, is the alternative. The MLE did not \"fail at arithmetic\"; the family is wrong.\n:::\n:::\n\n## Problem 22B. iid, then a flash sale (J)\n\nThe Poisson MLE $\\hat\\lambda=\\bar y$ used 20 consecutive minutes as iid draws from one $\\lambda$.\n\na. What does iid do for that estimator?\n\nb. Minutes 16--20 were a flash sale. The first 15 minutes averaged 3.2 clicks; the last five averaged 6.2. What is $\\hat\\lambda$ if you pool, and what is it if you keep only the ordinary minutes?\n\nc. For staffing an ordinary minute tomorrow, which number do you take, and what assumption would have to be true for the pooled 3.95 to be the right forecast?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. iid is what lets the likelihood factor as $\\prod e^{-\\lambda}\\lambda^{y_i}/y_i!$ and what makes the MLE a single mean. Without it you do not have one $\\lambda$.\n\nb. Pooled: $(15\\cdot 3.2+5\\cdot 6.2)/20=3.95$. Ordinary only: $3.2$.\n\nc. Take $3.2$ for an ordinary minute. The pooled 3.95 is the right forecast only if tomorrow is a 1-in-4 flash-sale world, or if you do not know whether a sale is on and you want the mixture. iid was false for the purpose of \"ordinary tomorrow.\"\n:::\n:::\n\n## Problem 22C. Observed versus the Poisson you fitted (J)\n\nLecture: alpha-particle observed vs expected. Same move as Problem 22c, as a picture.\n\n100 minutes of click counts. The bars are the observed frequencies. The points are $100\\times\\mathrm{Poisson}(\\hat\\lambda)$ with $\\hat\\lambda=\\bar y$, the MLE.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Clicks per minute. Bars: observed. Points: expected under Poisson(mean).](midterm-prep_files/figure-pdf/unnamed-chunk-2-1.pdf)\n:::\n:::\n\n\na. What did $\\mathrm{Poisson}(\\bar y)$ get wrong, and where?\n\nb. The MLE is still $\\bar y$. Why is that not a defence of the model?\n\nc. Name one data-generating story that would produce this plot. Would you keep a single Poisson for staffing?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Too many zeros: the bar at 0 is far above the point. The middle counts (3--6) are a bit low relative to the Poisson, which spent its mean on a unimodal shape that the extra zeros forced $\\bar y$ down from.\n\nb. $\\hat\\lambda=\\bar y$ is the best Poisson. The plot is a check of the *family*. A good MLE of a wrong model still misses the atom at zero.\n\nc. A flash sale mixed with idle minutes, or a two-rate mixture, or a point mass of \"the site is down.\" For staffing an ordinary minute you want the non-zero component, not one Poisson whose mean is a compromise between idle and busy. Same verdict as 22c and 22B, now from the picture.\n:::\n:::\n\n## Problem 23. CLT and a confidence interval (U, J)\n\nLab 4 Exercise 4; Book Chapter 5, Voter: CI.\n\na. $X_1,\\ldots,X_{36}$ iid $\\mathrm{Poisson}(3)$. $\\mathrm{sd}(\\bar X)$? Approximate $P(\\bar X>3.5)$ by a Normal with that sd.\n\nb. A poll of $n=1000$ voters, $400$ say they will vote for the candidate. True or false: a 95% CI for the proportion includes $45\\%$.\n\nc. How large a sample do you need so that a 95% interval for a mean, with $\\sigma=8$ known, has half-width $1$?\n\nd. The poll in (b) was 1,000 landline respondents on a weekday afternoon. Name the sampling assumption the interval needs, and one way that sample would miss the population of actual voters. Does the interval get too narrow, or is the centre in the wrong place?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $\\mathrm{Var}(X_i)=3$, $\\mathrm{sd}(\\bar X)=\\sqrt{3/36}=1/\\sqrt{12}\\approx 0.289$. $P(\\bar X>3.5)\\approx 1-\\Phi((3.5-3)/0.289)=1-\\Phi(1.73)\\approx 0.042$.\n\nb. False. $\\hat p=0.40$, $\\mathrm{se}=\\sqrt{0.4\\cdot 0.6/1000}\\approx 0.0155$, interval $0.40\\pm 1.96\\cdot 0.0155=(0.370,0.430)$. $0.45$ is outside.\n\nc. $1.96\\cdot 8/\\sqrt{n}=1$ gives $\\sqrt{n}=15.68$, $n\\approx 246$.\n\nd. The interval assumes a random sample from the population of voters. A weekday landline sample misses mobile-only and working-hour voters. That is bias in the centre, not a too-narrow interval. A larger $n$ of the same sample would make you more sure of the wrong number.\n:::\n:::\n\n\n# 5. Linear regression\n\n[Patterns](https://vsokolov.org/courses/files/600/03-patterns.html), through log transforms and OLS. Book Chapter 12, up to residual analysis and log-log.\n\nThe model is $E(y\\mid x)=\\beta_0+\\beta_1 x$ (or more columns). OLS picks $\\beta$ to minimise squared residuals. The slope is a rate: the change in predicted $y$ for a one-unit change in $x$. A log-log fit is the same model after a change of representation, $y=ax^b$. Dummy variables: $k$ levels need $k-1$ columns; the omitted level is the reference, and that is a choice.\n\n$R^2$ answers a narrow question. It is not \"is this model good.\" A residual plot is the check.\n\nYou should be able to: interpret $\\hat\\beta_1$ and form $\\hat y$ at a new $x$; say what a parabola, a fan, or an outlier in $e$ vs $\\hat y$ means; turn $y=ax^b$ into a linear equation in logs and interpret $b$; say what happens to fitted values if you change the dummy reference; look at a scatter of two groups and say what a single line is averaging.\n\n## Problem 24. OLS and a residual plot (U, J)\n\nBook Chapter 12, Residual Analysis and OLS Derivation (d).\n\n```\nlm(price ~ sqft)     # price in $1000s\n\n(Intercept)  50.23    (se 12.35)\nsqft          0.1234  (se 0.0089)\nResidual se  45.67 on 98 df\nR-squared     0.662\n```\n\na. Interpret the slope in dollars per square foot.\n\nb. Predicted price for a 2,000 sq ft house.\n\nc. For simple regression, $\\hat\\beta_1=S_{xy}/S_{xx}$. What does that say $\\hat\\beta_1$ is made of?\n\nd. A residual plot against fitted values shows a clear parabola. What would you do, and why is $R^2=0.66$ not an argument to keep the linear specification?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Each additional square foot is associated with $\\$123.40$ in predicted price.\n\nb. $50.23+0.1234\\cdot 2000=297.03$ thousand, about $\\$297{,}000$.\n\nc. It is the sample covariance of $x$ and $y$ over the sample variance of $x$. The slope is a scaled association, not a causal claim.\n\nd. A parabola in the residuals means the linear mean is wrong. Add a square, or log $y$, or log-log, and look at the new residuals. $R^2=0.66$ can be large while the mean is still bent; $R^2$ does not see the pattern in $e$ vs $\\hat y$.\n:::\n:::\n\n## Problem 24B. Who is in the sample (J)\n\nThe same `price ~ sqft` fit is on 100 houses that *sold* last year.\n\na. Name two modelling assumptions besides \"the mean is linear in sqft.\"\n\nb. Houses that did not sell are missing. If unsold houses are larger and overpriced, which way is $\\hat\\beta_1$ pulled relative to the slope for *listed* houses?\n\nc. You will use $\\hat y$ to advise a seller on asking price. What would have to be true for that use, and what would make you refuse?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The 100 sales are like draws from the population you care about (iid, or at least exchangeable). Errors have constant spread. sqft is not standing in for omitted size-correlates (lot, school, renovation) that you will not have at prediction time.\n\nb. Large unsold houses sit above the sold cloud in asking price but never enter $y$. The sold line is fitted only on houses whose price was accepted. That usually flattens or tilts the sold slope relative to listed asking prices: you see completed trades, not the full asking curve. The direction to write: $\\hat\\beta_1$ is a slope among *accepted* prices, so it is not the slope of list price on sqft.\n\nc. The advice is for a house that will sell on the same market as last year's sales. Refuse if the house is in a different segment (new build, distressed, a size outside the 100) or if the residual plot already said the linear mean is wrong. The $R^2$ does not settle this.\n:::\n:::\n\n## Problem 24C. MSE or MAE (J)\n\nBook Chapter 11, MSE vs MAE.\n\nPredictions $\\hat y=(2,3,4,5,20)$, actual $y=(2,4,4,6,6)$.\n\na. MSE and MAE.\n\nb. Which metric did the $20$ dominate, and what assumption about the cost of error is MSE making?\n\nc. For house prices, when would you report MAE (or a median regression) rather than OLS?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Errors $0,-1,0,-1,-14$. $\\mathrm{MSE}=(0+1+0+1+196)/5=39.6$. $\\mathrm{MAE}=(0+1+0+1+14)/5=3.2$.\n\nb. MSE. Squaring treats a \\$14 miss as 196 times a \\$1 miss. That is the right loss if big misses are disproportionately costly (and if you believe the Normal likelihood, which is the same square).\n\nc. When a few mansions or data errors should not own the fit: listing prices, a median asking price, or when the residual plot already shows a heavy tail. OLS/MSE is the default only if that square is the loss you actually have.\n:::\n:::\n\n## Problem 24D. Four residual plots (J)\n\nBook Chapter 12, Residual Analysis (d); lecture PGA and mammal residual checks.\n\nEach panel is residuals against fitted values from `lm(y ~ x)` on $n=80$ points. The same axes labels on all four.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals versus fitted values. Four different data-generating stories, one linear fit each.](midterm-prep_files/figure-pdf/unnamed-chunk-3-1.pdf)\n:::\n:::\n\n\na. For each panel, name the pattern in one phrase (none / curved mean / fan / one outlier).\n\nb. Which modelling assumption of OLS failed in B, in C, and in D? (A is the control.)\n\nc. You need a price at $x=8$. In which panel do you refuse the linear $\\hat y$, and in which do you keep the line but change the loss or how you talk about uncertainty?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. A none (random scatter around 0). B curved mean (a U or parabola). C fan (spread grows with fitted). D one large positive residual.\n\nb. B: $E(y\\mid x)$ is not linear in $x$. C: constant error variance. D: the square loss (and the implicit Normal) treats that point as an ordinary Gaussian miss; it is not. A is the case where those three are still plausible.\n\nc. Refuse B: the line is the wrong mean, so $\\hat y$ at $x=8$ is systematically off. Keep the line in C and D only with a change of use: in C report a spread that grows with $x$, or transform; in D use MAE / median regression, or drop a data error after you have named it, rather than let one point own $\\hat\\beta$. $R^2$ is not in any of the four pictures, and would not have told B from A.\n:::\n:::\n\n## Problem 25. Log-log as a power law (U, J)\n\nBook Chapter 12, Log Transformations. Same move as mammal brain/body and Apple growth in lecture.\n\nAdvertising $x$ and revenue $y$ (both in \\$millions) follow $y=ax^b$. Data: $(x,y)=(1,5),(2,8),(4,14),(8,25),(16,45)$.\n\nA log-log fit gives $\\log y=1.564+0.798\\log x$ (natural logs).\n\na. Transform the power law to a linear model.\n\nb. What are $\\hat a$ and $\\hat b$? Interpret $b$.\n\nc. Predict revenue at $x=10$.\n\nd. Why might you prefer this to OLS of $y$ on $x$ in the original scale, even if the raw $R^2$ looks fine?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $\\log y=\\log a+b\\log x$.\n\nb. $\\hat b=0.798$, $\\hat a=e^{1.564}\\approx 4.78$. A 1% increase in advertising is associated with about a 0.80% increase in revenue: diminishing returns. Doubling $x$ multiplies $y$ by $2^{0.798}\\approx 1.74$, not $2$.\n\nc. $\\hat y=4.78\\cdot 10^{0.798}\\approx 30.0$ million.\n\nd. The original scale is multiplicative and the residual spread usually fans with $x$. Log-log makes the mean linear and often stabilises the spread. $R^2$ on the raw scale is not comparable to $R^2$ on the log scale, and a high raw $R^2$ can hide the fan.\n:::\n:::\n\n## Problem 25B. Two scatters, same $n$ (J)\n\nBook Chapter 12, Log Transformations; lecture mammal brain/body and Apple.\n\nAdvertising $x$ and revenue $y$, 60 campaigns. Left: $y$ against $x$ with the OLS line. Right: $\\log y$ against $\\log x$ with its OLS line.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Left: revenue against advertising, linear fit. Right: the same campaigns after a log-log transform.](midterm-prep_files/figure-pdf/unnamed-chunk-4-1.pdf)\n:::\n:::\n\n\na. What does the left plot say about $E(y\\mid x)$ and about $\\mathrm{Var}(y\\mid x)$?\n\nb. Why is the right plot the *same* power-law model after a change of representation, not a different theory of revenue?\n\nc. The left-hand $R^2$ is large. Is that an argument to keep the linear specification?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. The mean is bent (diminishing returns) and the vertical spread fans with $x$. Both are the signature of a multiplicative $y=ax^b\\varepsilon$. The fan is the easier one to see; the curve is why the left-hand line overshoots the middle campaigns.\n\nb. $\\log y=\\log a+b\\log x+\\log\\varepsilon$ is $y=ax^b$ written so that OLS can see a straight mean. The slope on the right *is* $b$. You did not switch from \"revenue depends on advertising\" to a new mechanism; you changed the representation until the mean was linear.\n\nc. No. A large $R^2$ can sit on a bent mean with a fan. The residual plot (or the left scatter itself) is the check. Same lesson as Problem 24d and as the mammal plot in lecture.\n:::\n:::\n\n## Problem 26. Dummy variables (U)\n\nLecture: $k$ levels, $k-1$ columns.\n\nA house has `style` $\\in\\{\\text{colonial}, \\text{ranch}, \\text{split}\\}$. You fit\n$$\n\\mathrm{price}=\\beta_0+\\beta_1\\mathrm{sqft}+\\beta_2\\mathbf{1}_{\\mathrm{ranch}}+\\beta_3\\mathbf{1}_{\\mathrm{split}}+\\varepsilon.\n$$\n\na. Why not three style dummies plus an intercept?\n\nb. What is $\\beta_2$? What house is $\\beta_0+\\beta_1\\mathrm{sqft}$ describing?\n\nc. You recode and drop `ranch` instead of `colonial`. Which fitted values change? Which coefficients change?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Three dummies plus an intercept are linearly dependent (the dummy trap). The design matrix is singular.\n\nb. $\\beta_2$ is the difference in expected price between ranch and colonial, at the same sqft. The intercept line is colonial.\n\nc. Fitted values do not change: it is a reparameterisation of the same column space. The intercept and the remaining dummy coefficients absorb the new reference. You cannot compare $\\beta_2$ across the two fits without translating.\n:::\n:::\n\n## Problem 26B. Two clouds, one line (J)\n\nLecture dummy variables; same house-price setting as Problem 26.\n\nLeft: ranch and colonial on the same scatter, one OLS line through all 80 houses. Right: the same points, two parallel lines (one intercept per style, common slope on sqft).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Price against living area. Grey: colonial. Black: ranch. Left: one line. Right: two intercepts, common slope.](midterm-prep_files/figure-pdf/unnamed-chunk-5-1.pdf)\n:::\n:::\n\n\na. What is the single line on the left averaging, and why is that slope the wrong rate for a ranch?\n\nb. What did the dummy do on the right that the left plot could not?\n\nc. You will quote $\\hat\\beta_{\\mathrm{sqft}}$ to a seller. Which plot's slope do you send, and what would make you refuse even the right-hand picture?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. It is a compromise between two clouds that sit in different parts of the sqft range. Ranch is larger and more expensive, so the pooled line climbs from colonial on the left to ranch on the right. The dollars-per-square-foot on the left is partly a style mix, not a size effect.\n\nb. It let the intercept jump for ranch and kept a common slope. The vertical gap is $\\beta_{\\mathrm{ranch}}$, the number Problem 26 asked for.\n\nc. Send the right-hand slope, with the style named. Refuse if the two clouds are not parallel (style changes the rate, not just the intercept), if \"ranch\" is standing in for lot or school, or if this house is not in the same market as these 80 sales. Same sample warning as 24B.\n:::\n:::\n\n## Problem 27. True or false, linear regression (U)\n\nBook Chapter 12, True/False: Linear Regression. Also Book Chapter 11, MSE vs MAE (c)--(d).\n\na. OLS minimises the sum of absolute residuals.\n\nb. Adding a predictor cannot decrease $R^2$.\n\nc. Multicollinearity biases OLS.\n\nd. If $y_i=x_i^T\\beta+\\varepsilon_i$ with iid Normal errors, MLE for $\\beta$ is OLS.\n\ne. MAE is more affected by a single huge residual than MSE is.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. False. OLS is squared residuals. Absolute residuals are LAD / MAE.\n\nb. True. In-sample $R^2$ cannot fall when you add a column. That is why it is not a model-selection criterion.\n\nc. False. OLS stays unbiased. The variance of $\\hat\\beta$ blows up.\n\nd. True. The Normal log-likelihood is $-\\frac{1}{2\\sigma^2}\\sum(y_i-x_i^T\\beta)^2$ plus a constant.\n\ne. False. MSE squares the residual; the outlier dominates MSE more than MAE.\n:::\n:::\n\n\n# 6. Logistic regression\n\nPatterns, logistic block. Book Chapter 13, pen-and-pencil. Labs 5--7 when posted: rework those on paper too.\n\n$p=\\sigma(x^T\\beta)$ is a probability in $(0,1)$. The coefficient is a change in log-odds, not in $p$. A threshold of $0.5$ treats the two errors as equally costly. That is a decision, whether or not anyone wrote down the loss.\n\nYou should be able to: turn a linear predictor into $p$ with $\\sigma$; interpret $e^{\\beta}$ as an odds ratio; fill TPR, FPR, precision from a 2-by-2; say why accuracy is the wrong summary when the base rate is small; move the threshold when the two errors have different costs.\n\n## Problem 28. From log-odds to a probability (U)\n\nBook Chapter 13, Sigmoid. You need the function, not a derivative.\n\n$\\sigma(z)=1/(1+e^{-z})$. A fitted logit is $z=-0.5+0.4x$.\n\na. What is $p$ at $x=0$? At $x=0$, what does $z=0$ mean when it occurs?\n\nb. Show, in one line, that $\\sigma(-z)=1-\\sigma(z)$. Why does that matter for a \"no event\" probability?\n\nc. If $x$ increases by 1, what happens to the odds? To $p$? (The second answer is not a constant.)\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. $z=-0.5$, $p=\\sigma(-0.5)\\approx 0.378$. $z=0$ means $p=1/2$, a coin flip under the model, which here is at $x=0.5/0.4=1.25$, not at $x=0$.\n\nb. $1-\\sigma(z)=e^{-z}/(1+e^{-z})=\\sigma(-z)$. $P(\\text{no event})=1-p=\\sigma(-z)$.\n\nc. Odds are multiplied by $e^{0.4}\\approx 1.49$. Probability follows the sigmoid, so the same $+0.4$ in log-odds moves $p$ a lot near $0.5$ and almost not at all near $0$ or $1$.\n:::\n:::\n\n## Problem 29. Log-odds (U, J)\n\nBook Chapter 13, Log-Odds Interpretation.\n\n$$\n\\log\\frac{p}{1-p}=-1.5+0.8\\,\\mathrm{usage}-2.0\\,\\mathrm{annual}.\n$$\n`annual` $=1$ for an annual contract, $0$ for month-to-month. Usage in hours.\n\na. $P(\\text{churn})$ for 5 hours, month-to-month.\n\nb. Odds ratio for switching to annual, usage held fixed.\n\nc. How much would usage need to rise to double the odds of churning?\n\nd. A product manager hears \"annual cuts churn by 2.0.\" What did they mix up, and what sentence would you send instead?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Log-odds $= -1.5+4=2.5$, $p=\\sigma(2.5)\\approx 0.924$.\n\nb. $e^{-2}\\approx 0.135$. Annual multiplies the odds of churn by $0.135$, an 86% reduction in *odds*, not a 2-point drop in probability.\n\nc. $e^{0.8\\Delta}=2$ gives $\\Delta=\\log 2/0.8\\approx 0.87$ hours.\n\nd. $-2.0$ is a log-odds coefficient. The probability drop depends on where you start on the sigmoid. Send: \"holding usage fixed, an annual contract multiplies churn odds by $0.14$.\" Then give $p$ at a usage the manager actually has.\n:::\n:::\n\n## Problem 30. Confusion matrix and a threshold (U, J)\n\nBook Chapter 13, Confusion Matrix and Metrics. Same accounting as Lab 2's 1,000 mammograms, now with a cost.\n\n| | Predicted fraud | Predicted legit |\n|--|--|--|\n| Actual fraud | 85 | 15 |\n| Actual legit | 50 | 4,850 |\n\na. Accuracy, precision, recall.\n\nb. Why is accuracy a poor metric here?\n\nc. Missing a fraud costs $\\$500$; a false alarm costs $\\$10$. Which error should the threshold lean toward, and which way do you move it from $0.5$?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. Accuracy $=4935/5000=0.987$. Precision $=85/135\\approx 0.630$. Recall $=85/100=0.85$.\n\nb. Predicting \"all legit\" is already $0.98$ accurate and catches no fraud. The base rate is 2%.\n\nc. FN is 50 times costlier than FP, so raise recall: lower the threshold. You will flag more legitimate transactions. That is the loss, not a defect in the probability model.\n:::\n:::\n\n## Problem 30B. What the coefficient assumed (J)\n\nA logistic default model on last year's book:\n$$\n\\log\\frac{p}{1-p}=-3.0+0.02\\,\\mathrm{balance}-0.8\\,\\mathrm{student}.\n$$\n`student` $=1$ if the borrower is a student.\n\na. Holding balance fixed, what did the model assume the $-0.8$ is?\n\nb. Students have higher balances on average. If you drop `balance` and refit with `student` alone, which way does the student coefficient typically move, and what assumption just failed?\n\nc. A 0.5 threshold on $p$ is used to deny credit. What loss did that assume, and who is hurt if false denials are costlier than missed defaults?\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. It assumed that, at the same balance, students have lower log-odds of default than non-students. That is a ceteris-paribus association in this book, not \"being a student causes lower default.\"\n\nb. The student coefficient typically rises (becomes less negative, or positive). Students look riskier in the margin because they carry more balance. The assumption that failed is \"the other variables in the linear predictor hold the comparison fixed.\" Omitting the confounder changes the meaning of $\\beta$.\n\nc. Equal cost of false deny and missed default. If false denials are costlier, raise the threshold (deny only at higher $p$). Students with high balances are the group the omitted-variable version would punish.\n:::\n:::\n\n## Problem 31. True or false, logistic (U)\n\nBook Chapter 13, True/False: Logistic Regression.\n\na. A logistic coefficient is the change in probability for a one-unit increase in the predictor.\n\nb. The decision boundary $\\{x:p(x)=1/2\\}$ is linear in the features that enter $x^T\\beta$.\n\nc. If the model gives $P(Y=1)=0.7$, changing the classification threshold does not change that probability.\n\nd. The odds ratio $e^{\\beta}$ can be negative.\n\n::: {.content-hidden unless-meta=\"showsln\"}\n::: {.callout-tip collapse=\"true\"}\n## Solution\n\na. False. It is a change in log-odds. Probability is the sigmoid of that.\n\nb. True. $\\{x:x^T\\beta=0\\}$ is a hyperplane in those coordinates.\n\nc. True. The probability is the model. The threshold is a later decision.\n\nd. False. $e^{\\beta}>0$ always. It can be less than 1.\n:::\n:::\n\n\n# How to sit the exam\n\nEvery scored item is a concept plus a use. Write the name of the move, then the arithmetic, then one sentence in the setting of the question. If the condition named in the prompt changes, say which way the number moves.\n\nAssumption items are the Judgment points. Use the four sentences from the front: name it, why it was used, what would make it false here, which way the number moves or whether it is still good enough. Independence is allowed when the order of magnitude is the point (a clean shift) and not when the product is the conviction (Sally Clark). iid is allowed when tomorrow looks like these minutes, and not when a flash sale sat in the sample. A 0.5 threshold is allowed when the two errors cost the same. A residual plot, a histogram against a Normal, or observed counts against a Poisson is the same four sentences, starting from what you can see.\n\nYou will not be asked to invert $X^TX$, expand a Poisson double sum, or quote a library function. If a calculation needs $\\Phi$, a four-point table on the cheat sheet is enough.\n",
    "supporting": [
      "midterm-prep_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}