<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Bayes’ Rule – Bayes, Artificial Intelligence, and Deep Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-bl.html" rel="next">
<link href="./01-prob.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b4985e4eddee1e63d72746df2b00da28.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script>
  // Load MathJax with custom macros
  window.MathJax = {
    tex: {
      macros: {
        Cov: ["\\mathrm{Cov}\\left(#1\\right)", 1],
        Cor: ["\\mathrm{Cor}\\left(#1\\right)", 1],
        Var: ["\\mathrm{Var}\\left(#1\\right)", 1],
        sd: ["\\mathrm{sd}\\left(#1\\right)", 1],
        E: ["\\mathrm{E}_{#1}\\left(#2\\right)", 2, ""],
        prob: ["\\mathrm{P}\\left(#1\\right)", 1],
        defeq: "\\stackrel{\\mathrm{def}}{=}",
        mini: "\\operatorname*{minimize}"
      }
    }
  };
</script>

<style>
  /* Custom styling for math content */
  .MathJax {
    font-size: 1em !important;
  }

  /* Ensure consistent math rendering */
  mjx-container[jax="CHTML"] {
    line-height: 1.2;
  }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="2&nbsp; Bayes’ Rule – Bayes, Artificial Intelligence, and Deep Learning">
<meta property="og:description" content="">
<meta property="og:image" content="fig/anand-prior.png">
<meta property="og:site_name" content="Bayes, Artificial Intelligence, and Deep Learning">
<meta name="twitter:title" content="2&nbsp; Bayes’ Rule – Bayes, Artificial Intelligence, and Deep Learning">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="fig/anand-prior.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-prob.html">Bayes</a></li><li class="breadcrumb-item"><a href="./02-bayes.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bayes’ Rule</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bayes, Artificial Intelligence, and Deep Learning</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Bayes,-Artificial-Intelligence,-and-Deep-Learning.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Bayes,-Artificial-Intelligence,-and-Deep-Learning.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern AI Playbook</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability and Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-bayes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bayes’ Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-bl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bayesian Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Utility, Risk and Decisions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">A/B Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-hyp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-gp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gaussian Processes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-rl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Reinforcement Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">AI</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Unreasonable Effectiveness of Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-pattern.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Pattern Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Logistic Regression and Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Tree Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Forecasting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-select.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-theoryai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Statistical Learning Theory and Regularization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-theorydl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Theory of Deep Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-qnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Quantile Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Natural Language Processing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Large Language Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-robots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">AI Agents</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-linalg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Linear Algebra and Multivariate Normal Toolkit</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#law-of-total-probability" id="toc-law-of-total-probability" class="nav-link active" data-scroll-target="#law-of-total-probability"><span class="header-section-number">2.1</span> Law of Total Probability</a></li>
  <li><a href="#intuition-and-simple-examples" id="toc-intuition-and-simple-examples" class="nav-link" data-scroll-target="#intuition-and-simple-examples"><span class="header-section-number">2.2</span> Intuition and Simple Examples</a></li>
  <li><a href="#real-world-bayes" id="toc-real-world-bayes" class="nav-link" data-scroll-target="#real-world-bayes"><span class="header-section-number">2.3</span> Real World Bayes</a></li>
  <li><a href="#first-application-naive-bayes" id="toc-first-application-naive-bayes" class="nav-link" data-scroll-target="#first-application-naive-bayes"><span class="header-section-number">2.4</span> First Application: Naive Bayes</a></li>
  <li><a href="#sec-sensitivity" id="toc-sec-sensitivity" class="nav-link" data-scroll-target="#sec-sensitivity"><span class="header-section-number">2.5</span> Sensitivity and Specificity</a>
  <ul class="collapse">
  <li><a href="#medical-diagnostics" id="toc-medical-diagnostics" class="nav-link" data-scroll-target="#medical-diagnostics">Medical Diagnostics</a></li>
  </ul></li>
  <li><a href="#advanced-applications" id="toc-advanced-applications" class="nav-link" data-scroll-target="#advanced-applications"><span class="header-section-number">2.6</span> Advanced Applications</a></li>
  <li><a href="#graphical-representation-of-conditional-independence" id="toc-graphical-representation-of-conditional-independence" class="nav-link" data-scroll-target="#graphical-representation-of-conditional-independence"><span class="header-section-number">2.7</span> Graphical Representation of Conditional Independence</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a>
  <ul class="collapse">
  <li><a href="#pen-and-pencil" id="toc-pen-and-pencil" class="nav-link" data-scroll-target="#pen-and-pencil">Pen-and-Pencil</a></li>
  <li><a href="#computing" id="toc-computing" class="nav-link" data-scroll-target="#computing">Computing</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-prob.html">Bayes</a></li><li class="breadcrumb-item"><a href="./02-bayes.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bayes’ Rule</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bayes’ Rule</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>“<em>When the facts change, I change my mind. What do you do, sir?</em>”—John Maynard Keynes</p>
</blockquote>
<p>One of the key questions in the theory of learning is: <em>How do you update your beliefs in the presence of new information?</em> Bayes’ rule provides the answer. Conditional probability can be interpreted as updating your probability of event <span class="math inline">\(A\)</span> after you have learned the new information that <span class="math inline">\(B\)</span> has occurred. In this sense, probability is also the language of how you’ll change opinions in the light of new evidence.</p>
<p>Probability rules allow us to change our mind if the facts change. For example, suppose that we have evidence <span class="math inline">\(E = \{ E_1 , E_2 \}\)</span> consisting of two pieces of information and that we are interested in identifying a <em>cause</em> <span class="math inline">\(C\)</span>. Bayes’ rule simply lets you calculate this conditional probability <span class="math inline">\(P(C\mid E_1,E_2)\)</span> in a sequential fashion. First, conditioning on the information contained in <span class="math inline">\(E_1\)</span> lets us calculate <span class="math display">\[
P( C\mid E_1 ) = \frac{ P(  E_1 \mid C ) P( C) }{ P( E_1 ) }
\]</span> Then, using the posterior probability <span class="math inline">\(P( C\mid E_1 )\)</span> as the “new” prior for the next piece of information <span class="math inline">\(E_2\)</span> lets us find <span class="math display">\[
P( C\mid E_1 , E_2 ) = \frac{ P(  E_2 \mid E_1 , C ) P( C \mid E_1 ) }{ P( E_2 \mid E_1 ) }
\]</span> Hence, we see that we need assessments of the two conditional probabilities <span class="math inline">\(P( E_1 \mid C )\)</span> and <span class="math inline">\(P( E_2 \mid E_1 , C )\)</span>. In many situations, the latter will be simply <span class="math inline">\(P( E_2 \mid C )\)</span> and not involve <span class="math inline">\(E_1\)</span>. The events <span class="math inline">\(( E_1, E_2 )\)</span> will be said to be conditionally independent given <span class="math inline">\(C\)</span>.</p>
<p>This concept generalizes to a sequence of events where <span class="math inline">\(E = \{ E_1,\ldots E_n \}\)</span>. When learning from data, we will use this property all the time. An illustrative example will be the Black Swan problem, which we discuss later.</p>
<p>Bayes’ rule is a fundamental concept in probability theory and statistics. It describes how to update our <em>beliefs</em> about an event based on <em>new evidence</em>. We start with an initial belief about the probability of an event (called the <em>prior probability</em>). We then observe some conditional information (e.g., evidence). We use Bayes’ rule to update our initial belief based on the evidence, resulting in a new belief called the <em>posterior probability</em>. Remember, the formula is</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Bayes’ Rule
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
P(A\mid B) = \dfrac{P(B\mid A) P(A)}{P(B)}
\]</span></p>
</div>
</div>
<p>where:</p>
<ul>
<li><span class="math inline">\(P(A\mid B)\)</span> is the <em>posterior probability</em> of event <span class="math inline">\(A\)</span> occurring given that <span class="math inline">\(B\)</span> is known to happen for sure. This is the probability we’re trying to find.</li>
<li><span class="math inline">\(P(B\mid A)\)</span> is the <em>likelihood</em> of observing event <span class="math inline">\(B\)</span> if event <span class="math inline">\(A\)</span> has occurred.</li>
<li><span class="math inline">\(P(A)\)</span> is the <em>prior probability</em> of event <span class="math inline">\(A\)</span> occurring. This is our initial belief about the probability of <span class="math inline">\(A\)</span> before we see any evidence.</li>
<li><span class="math inline">\(P(B)\)</span> is the <em>marginal probability</em> of observing event <span class="math inline">\(B\)</span>. This is the probability of observing B regardless of whether <span class="math inline">\(A\)</span> occurs.</li>
</ul>
<p>The ability to use Bayes’ rule sequentially is key in many applications, when we need to update our beliefs in the presence of new information. For example, Bayesian learning was used by mathematician Alan Turing in England at Bletchley Park to break the German Enigma code - a development that helped the Allies win the Second World War <span class="citation" data-cites="simpson2010edward">(<a href="references.html#ref-simpson2010edward" role="doc-biblioref">Simpson 2010</a>)</span>. Turing called his algorithm Banburismus, it is a process he invented which used sequential conditional probability to infer information about the likely settings of the Enigma machine.</p>
<p>Dennis Lindley argued that we should all be trained in Bayes’ rule and that conditional probability can be simply viewed as disciplined probability accounting. Akin to how market odds change as evidence changes. However, human intuition is rarely naturally calibrated for Bayesian reasoning; it is a skill that must be learned, much like literacy.</p>
<section id="law-of-total-probability" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="law-of-total-probability"><span class="header-section-number">2.1</span> Law of Total Probability</h2>
<p>The Law of Total Probability is a fundamental rule relating marginal probabilities to conditional probabilities. It’s particularly useful when you’re dealing with a set of mutually exclusive and collectively exhaustive events.</p>
<p>Suppose you have a set of events <span class="math inline">\(B_1, B_2, ..., B_n\)</span> that are mutually exclusive (i.e., no two events can occur at the same time) and collectively exhaustive (i.e., at least one of the events must occur). The Law of Total Probability states that for any other event <span class="math inline">\(A\)</span>, the probability of <span class="math inline">\(A\)</span> occurring can be calculated as the sum of the probabilities of <span class="math inline">\(A\)</span> occurring given each <span class="math inline">\(B_i\)</span>, multiplied by the probability of each <span class="math inline">\(B_i\)</span> occurring.</p>
<p>Mathematically, it is expressed as: <span class="math display">\[
P(A) = \sum_{i=1}^{n} P(A\mid  B_i) P(B_i)
\]</span></p>
<div id="exm-total" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.1 (Total Probability)</strong></span> Let’s consider a simple example to illustrate this. Suppose you have two bags of balls. Bag 1 contains 3 red and 7 blue balls, while Bag 2 contains 6 red and 4 blue balls. You randomly choose one of the bags and then randomly draw a ball from that bag. What is the probability of drawing a red ball?</p>
<p>Here, the events <span class="math inline">\(B_1\)</span> and <span class="math inline">\(B_2\)</span> can be choosing Bag 1 and Bag 2, respectively. You want to find drawing a red ball (event <span class="math inline">\(A\)</span>).</p>
<p>Applying the law:</p>
<ul>
<li><span class="math inline">\(P(A\mid B_1)\)</span> is the probability of drawing a red ball from Bag 1, which is <span class="math inline">\(\frac{3}{10}\)</span>.</li>
<li><span class="math inline">\(P(A\mid B_2)\)</span> is the probability of drawing a red ball from Bag 2, which is <span class="math inline">\(\frac{6}{10}\)</span>.</li>
<li>Assume the probability of choosing either bag is equal, so <span class="math inline">\(P(B_1) = P(B_2) = \frac{1}{2}\)</span>.</li>
</ul>
<p>Using the Law of Total Probability: <span class="math display">\[
P(A) = P(A\mid B_1) \times P(B_1) + P(A\mid B_2) \times P(B_2)= \frac{3}{10} \times \frac{1}{2} + \frac{6}{10} \times \frac{1}{2} = \frac{9}{20}
\]</span></p>
<p>So, the probability of drawing a red ball in this scenario is <span class="math inline">\(\frac{9}{20}\)</span>.</p>
</div>
<p>This law is particularly useful in complex probability problems where direct calculation of probability is difficult. By breaking down the problem into conditional probabilities based on relevant events, it simplifies the calculation and helps to derive a solution.</p>
</section>
<section id="intuition-and-simple-examples" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="intuition-and-simple-examples"><span class="header-section-number">2.2</span> Intuition and Simple Examples</h2>
<div id="exm-intuition" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.2 (Intuition)</strong></span> Our intuition is not well trained to make use of Bayes’ rule. Suppose I tell you that Steve was selected at random from a representative sample, and that he is 6 feet 2 inches tall and an excellent basketball player. He goes to the gym every day and practices hard playing basketball. Do you think Steve is a custodian at a factory or an NBA player? Most people assume Steve is an NBA player, which is wrong. The ratio of NBA players to custodians is very small, probabilistically Steve is more likely to be a custodian. Let’s look at it graphically. The key is to provide the right conditioning and to consider the prior probability! Even though the ratio of people who practice basketball hard is much higher among NBA players (it is 1) when compared to custodians, the larger number of the population means we still have more custodians in the US than NBA players.</p>
<p><span class="math display">\[\begin{align*}
P(\text{Practice hard}  \mid  \text{Play in NBA}) \approx  1\\
P( \text{Play in NBA}  \mid  \text{Practice hard}) \approx  0.
\end{align*}\]</span></p>
<p>Even though you practice hard, the odds of playing in the NBA are low (about <span class="math inline">\(450\)</span> players out of <span class="math inline">\(8\)</span> billion). But given you’re in the NBA, you no doubt practice very hard. To understand this further, let’s look at the conditional probability implication and apply Bayes’ rule <span class="math display">\[
P \left ( \text{Play in NBA}  \mid  \text{Practice hard}  \right ) = \dfrac{P  \left ( \text{Practice hard}  \mid  \text{Play in NBA} \right )}{P(\text{Practice hard})}P( \text{Play in NBA}).
\]</span> This is written in the form <span class="math display">\[
\text{Posterior} = \frac{\text{Likelihood}}{\text{Marginal}}\times \text{Prior} = \text{Bayes factor} \times \text{Prior}.
\]</span> The Likelihood/Marginal ratio is called the Bayes factor. As we will see in the text, one of the key advantages over classical is the ability to sequentially update our beliefs as new evidence appears. It allows for disciplined probability accounting in “real-time”. With the advent of prediction markets and data science, it has become increasingly important to be able to update our beliefs as new evidence appears.</p>
<p>The initial (a.k.a. prior) probability <span class="math inline">\(P(\text{Play in NBA} ) = 450/(8 \cdot 10^9) = 5.625 \times 10^{-8}\)</span>. This uses a global population of around 8 billion as the reference population. (The 7-foot example below uses US playing-age males as the reference, giving a different prior; the choice of reference population is part of the model specification.) <span class="math display">\[
P   \left ( \text{Play in NBA}  \mid  \text{Practice hard}  \right ) \approx  0,
\]</span> <span class="math inline">\(P(\text{practice hard})\)</span> is not that small and <span class="math inline">\(P(\text{practice hard} \mid \text{play in NBA})=1\)</span>. Hence, when one ‘reverses the conditioning’ one gets a very small probability. This makes sense!</p>
<p>The Steve example illustrates how our intuition fails us, but let’s consider an even more striking case that demonstrates the power of Bayes’ rule with extreme probabilities. Consider the question: what is the probability that a randomly selected 7-foot-tall American male plays in the NBA?</p>
<p>Most people’s intuition suggests this probability should be quite high - after all, being exceptionally tall seems like the primary qualification for professional basketball. However, Bayes’ rule reveals a more nuanced picture that depends critically on the base rates involved.</p>
<p>To calculate <span class="math inline">\(P(\text{NBA player} \mid \text{7 feet tall})\)</span> using Bayes’ rule, we need to carefully estimate each component:</p>
<p><span class="math display">\[P(\text{NBA} \mid \text{7ft}) = \frac{P(\text{7ft} \mid \text{NBA}) \times P(\text{NBA})}{P(\text{7ft})}\]</span></p>
<p>The prior probability <span class="math inline">\(P(\text{NBA})\)</span> represents the baseline chance of being an NBA player. With approximately 450 active players drawn from roughly 40 million American males of playing age, this gives us <span class="math inline">\(P(\text{NBA}) \approx 1.1 \times 10^{-5}\)</span>.</p>
<p>The likelihood <span class="math inline">\(P(\text{7ft} \mid \text{NBA})\)</span> asks what fraction of NBA players are 7 feet or taller. Historically, this has been around 17% of the league, so <span class="math inline">\(P(\text{7ft} \mid \text{NBA}) \approx 0.17\)</span>.</p>
<p>The marginal probability <span class="math inline">\(P(\text{7ft})\)</span> requires us to estimate how rare 7-foot-tall men are in the general population. If male height followed a normal distribution with mean 69 inches and standard deviation 3 inches, a <span class="math inline">\(z\)</span>-score of 5.0 would give roughly 1 in 3.5 million, but the normal distribution dramatically underestimates the frequency of extreme heights because real height distributions have heavier tails. Empirical estimates suggest roughly 1 in 35,000 playing-age American males are 7 feet or taller, giving us <span class="math inline">\(P(\text{7ft}) \approx 2.87 \times 10^{-5}\)</span>.</p>
<p>Applying Bayes’ rule: <span class="math display">\[P(\text{NBA} \mid \text{7ft}) = \frac{0.17 \times 1.1 \times 10^{-5}}{2.87 \times 10^{-5}} \approx 0.065\]</span></p>
<p>This yields approximately 6.5% - a dramatic increase from the baseline probability of 0.001%, yet still surprisingly low given our intuitions.</p>
<p>Let’s also consider a direct count-based calculation. As of September 2025, there are 39 players in the NBA who are 7 feet tall or taller, out of a total of 450 NBA players. This means the probability that a randomly selected NBA player is at least 7 feet tall is:</p>
<p><span class="math display">\[
P(\text{7ft} \mid \text{NBA}) = \frac{39}{450} = 0.0867
\]</span></p>
<p>This empirical estimate is slightly different from the earlier historical average, but it still highlights the rarity of extreme height even among elite basketball players. Substituting this count-based likelihood (<span class="math inline">\(0.0867\)</span>) for the historical <span class="math inline">\(0.17\)</span> in the Bayes calculation would roughly halve the posterior, to about <span class="math inline">\(3.3\%\)</span> rather than <span class="math inline">\(6.5\%\)</span>.</p>
<p>Regardless of the exact calculation, this example powerfully demonstrates how Bayes’ rule forces us to account for base rates. Even when height provides enormous predictive value for NBA success (the likelihood ratio is massive), the extreme rarity of both 7-foot-tall individuals and NBA players means that most 7-footers will not be professional basketball players. This counterintuitive result exemplifies why disciplined probabilistic reasoning through Bayes’ rule is essential for making accurate inferences in the presence of rare events.</p>
</div>
<div id="exm-Craps" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.3 (Craps)</strong></span> Craps is a fast-moving dice game with a complex betting layout. It’s highly volatile, but eventually your bankroll will drift towards zero. Let’s look at the pass line bet. The expectation <span class="math inline">\(E(X)\)</span> governs the long run. When 7 or 11 comes up, you win. When 2, 3, or 12 comes up, this is known as “craps”, you lose. When 4, 5, 6, 8, 9, or 10 comes up, this number is called the “point”, the bettor continues to roll until a 7 (you lose) or the point comes up (you win).</p>
<p>We need to know the probability of winning. The pay-out, probability, and expectation for a $1 bet</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Win</th>
<th>Prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.4929</td>
</tr>
<tr class="even">
<td>-1</td>
<td>0.5071</td>
</tr>
</tbody>
</table>
<p>This leads to an edge in favor of the house as <span class="math display">\[
E(X) = 1 \cdot 0.4929 + (- 1) \cdot  0.5071 = -0.014
\]</span> The house has a 1.4% edge.</p>
<p>To calculate the probability of winning: <span class="math inline">\(P( \text{Win} )\)</span>, let’s use the law of total probability <span class="math display">\[
P( \text{Win} ) = \sum_{ \mathrm{Point} } P ( \text{Win} \mid \mathrm{Point} ) P ( \mathrm{Point} )
\]</span> The set of <span class="math inline">\(P(\text{Point})\)</span> values is given by</p>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Probability</th>
<th style="text-align: left;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">1/36</td>
<td style="text-align: left;">2.78%</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">2/36</td>
<td style="text-align: left;">5.56%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">3/36</td>
<td style="text-align: left;">8.33%</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">4/36</td>
<td style="text-align: left;">11.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">5/36</td>
<td style="text-align: left;">13.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">6/36</td>
<td style="text-align: left;">16.7%</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Probability</th>
<th style="text-align: left;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">5/36</td>
<td style="text-align: left;">13.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">4/36</td>
<td style="text-align: left;">11.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">3/36</td>
<td style="text-align: left;">8.33%</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">2/36</td>
<td style="text-align: left;">5.56%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">1/36</td>
<td style="text-align: left;">2.78%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The conditional probabilities <span class="math inline">\(P( \text{Win} \mid \mathrm{Point} )\)</span> are harder to calculate <span class="math display">\[
P( \text{Win} \mid 7 \; \mathrm{or} \; 11 ) = 1 \; \; \mathrm{and} \; \; P( \text{Win} \mid 2 ,
3 \; \mathrm{or} \; 12 ) = 0
\]</span> We still have to work out all the probabilities of winning given the point. Suppose the point is <span class="math inline">\(4\)</span> <span class="math display">\[
P( \text{Win} \mid 4 ) = P ( 4 \; \mathrm{before} \; 7 ) = \dfrac{P(4)}{P(7)+P(4)} = \frac{3}{9} =
\frac{1}{3}
\]</span> There are 6 ways of getting a 7, 3 ways of getting a 4, for a total of 9 possibilities. Now do all of them and sum them up. You get <span class="math display">\[
P( \text{Win}) = 0.4929
\]</span> Hence, the casino has a slight edge of 1.4% in the long run!</p>
</div>
<div id="exm-jar" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.4 (Coin Jar)</strong></span> Large jar containing 1024 fair coins and one two-headed coin. You pick one at random and flip it <span class="math inline">\(10\)</span> times and get all heads. What’s the probability that the coin is the two-headed coin? The probability of initially picking the two headed coin is 1/1025. There is a 1/1024 chance of getting <span class="math inline">\(10\)</span> heads in a row from a fair coin. Therefore, it’s a <span class="math inline">\(50/50\)</span> bet.</p>
<p>Let’s do the formal Bayes’ rule math. Let <span class="math inline">\(E\)</span> be the event that you get <span class="math inline">\(10\)</span> Heads in a row; then</p>
<p><span class="math display">\[
P \left ( \text{two-headed}  \mid  E \right ) = \frac{ P \left ( E  \mid  \text{two-headed}  \right )P \left (  \text{two-headed} \right )}
{P \left ( E  \mid  \text{fair}  \right )P \left ( \text{fair} \right ) + P \left ( E  \mid  \text{two-headed}  \right )P \left ( \text{two-headed} \right )}
\]</span> Therefore, the posterior probability <span class="math display">\[
P \left (  \text{two-headed}  \mid  E \right ) = \frac{ 1 \times \frac{1}{1025} }{ \frac{1}{1024} \times \frac{1024}{1025} + 1 \times \frac{1}{1025} } = 0.50
\]</span> What’s the probability that the next toss is a head? Using the law of total probability gives</p>
<p><span class="math display">\[\begin{align*}
  P( H ) &amp;= P( H  \mid  \text{two-headed} )P( \text{two-headed}  \mid E ) +  P( H  \mid  \text{fair} )P( \text{fair}  \mid E) \\
  &amp; = 1 \times \frac{1}{2} + \frac{1}{2} \times \frac{1}{2} = \frac{3}{4}
\end{align*}\]</span></p>
</div>
<div id="exm-monty" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.5 (Monty Hall Problem)</strong></span> Another example of a situation when calculating probabilities is counterintuitive. The Monty Hall problem was named after the host of the long-running TV show Let’s Make a Deal. The original solution was proposed by Marilyn vos Savant, who had a column with the correct answer that many Mathematicians thought was wrong!</p>
<p>The game set-up is as follows. A contestant is given the choice of 3 doors. There is a prize (a car, say) behind one of the doors and something worthless behind the other two doors: two goats. The game is as follows:</p>
<ol type="1">
<li>You pick a door.</li>
<li>Monty then opens one of the other two doors, revealing a goat. He can’t open your door or show you a car</li>
<li>You have the choice of switching doors.</li>
</ol>
<p>The question is, is it advantageous to switch? The answer is yes. The probability of winning if you switch is 2/3 and if you don’t switch is 1/3.</p>
<p>Conditional probabilities allow us to answer this question. Assume you pick door 1. Let event <span class="math inline">\(A\)</span> denote that the car is behind Door 2, and let event <span class="math inline">\(B\)</span> denote that the host opened Door 3, revealing a goat. We want to calculate <span class="math inline">\(P(A\mid B)\)</span>, the probability the car is behind the door you should switch to. The prior probability that the car is behind Door 2 is <span class="math inline">\(P(A) = 1/3\)</span>. If the car is behind Door 2; the host must open Door 3 (he cannot open Door 1 or show the car behind Door 2), so <span class="math inline">\(P(B\mid A) = 1\)</span>. Bayes’ rule gives us <span class="math display">\[
P(A\mid B) = \frac{P(B\mid A)P(A)}{P(B)} = \frac{1/3}{1/2} = \frac{2}{3}.
\]</span> The overall probability of the host opening Door 3 <span class="math display">\[
P(B) = (1/3 \times 1/2) + (1/3 \times 1) = 1/6 + 1/3 = 1/2.
\]</span></p>
<p>The posterior probability that the car is behind Door 2 after the host opens Door 3 is 2/3. It is to your advantage to switch doors.</p>
</div>
</section>
<section id="real-world-bayes" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="real-world-bayes"><span class="header-section-number">2.3</span> Real World Bayes</h2>
<p>The true power of Bayes’ rule emerges in high-stakes decisions. The following cases (search-and-rescue operations, wartime survival, and legal proceedings) share a common insight: updating beliefs systematically while accounting for base rates and the direction of conditioning.</p>
<div id="exm-Scorpion" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.6 (USS Scorpion Sank 22 May 1968 in the Middle of the Atlantic)</strong></span> Experts placed bets on each casualty and how each would affect the sinking. Undersea soundings gave a prior on location. Bayes’ rule: <span class="math inline">\(L\)</span> is location, and <span class="math inline">\(S\)</span> is scenario <span class="math display">\[
P (L \mid S) = \frac{ P(S \mid L) P(L)}{P(S)}
\]</span> The Navy spent <span class="math inline">\(5\)</span> months looking and found nothing. Built a probability map: within <span class="math inline">\(5\)</span> days, the submarine was found within <span class="math inline">\(220\)</span> yards of the most likely probability!</p>
<p>A similar story happened during the search for an Air France plane that flew from Rio to Paris.</p>
</div>
<div id="exm-Wald" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.7 (Wald and Airplane Safety)</strong></span> Many lives were saved by analysis of conditional probabilities performed by Abraham Wald during the Second World War. He was analyzing damage on the US planes that came back from bombing missions in Germany. Somebody suggested to analyze the distribution of the hits over different parts of the plane. The idea was to find a pattern in the damage and design a reinforcement strategy.</p>
<p>After examining hundreds of damaged airplanes, researchers came up with the following table</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Location</th>
<th style="text-align: right;">Number of Planes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Engine</td>
<td style="text-align: right;">53</td>
</tr>
<tr class="even">
<td style="text-align: right;">Cockpit</td>
<td style="text-align: right;">65</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Fuel system</td>
<td style="text-align: right;">96</td>
</tr>
<tr class="even">
<td style="text-align: right;">Wings, fuselage, etc.</td>
<td style="text-align: right;">434</td>
</tr>
</tbody>
</table>
<p>We can convert those counts to probabilities</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Location</th>
<th style="text-align: right;">Number of Planes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Engine</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: right;">Cockpit</td>
<td style="text-align: right;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Fuel system</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: right;">Wings, fuselage, etc.</td>
<td style="text-align: right;">0.67</td>
</tr>
</tbody>
</table>
<p>We can conclude that the most likely area to be damaged on the returned planes was the wings and fuselage. <span class="math display">\[
P(\mbox{hit on wings or fuselage } \mid \mbox{returns safely}) = 0.67
\]</span> Wald realized that analyzing damages only on survived planes is not the right approach. Instead, he suggested that it is essential to calculate the inverse probability <span class="math display">\[
P(\mbox{returns safely} \mid \mbox{hit on wings or fuselage }) = ?
\]</span> To calculate that, he interviewed many engineers and pilots; he performed a lot of field experiments. He analyzed likely attack angles. He studied the properties of a shrapnel cloud from a flak gun. He suggested to the army that they fire thousands of dummy bullets at a plane sitting on the tarmac. Wald constructed a ‘probability model’ carefully to reconstruct an estimate for the joint probabilities. The table below shows the results.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Hit</th>
<th style="text-align: right;">Returned</th>
<th style="text-align: right;">Shot Down</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Engine</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">57</td>
</tr>
<tr class="even">
<td style="text-align: right;">Cockpit</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">46</td>
</tr>
<tr class="odd">
<td style="text-align: right;">Fuel system</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="even">
<td style="text-align: right;">Wings, fuselage, etc.</td>
<td style="text-align: right;">434</td>
<td style="text-align: right;">33</td>
</tr>
</tbody>
</table>
<p>Which allows us to estimate joint probabilities, for example <span class="math display">\[
P(\mbox{outcome = returns safely} , \mbox{hit  =  engine }) = 53/800 = 0.066
\]</span> We also can calculate the conditional probabilities now <span class="math display">\[
P(\mbox{outcome = returns safely} \mid  \mbox{hit  =  wings or fuselage  }) = \dfrac{434}{434+33} = 0.9293362.
\]</span> Should we reinforce wings or fuselage? Which part of the airplane needs to be reinforced? <span class="math display">\[
P(\mbox{outcome = returns safely} \mid  \mbox{hit  =  engine  }) = \dfrac{53}{53+57} = 0.48
\]</span></p>
</div>
<p>A convenient way to perform Bayes’ rule calculations is using the “odds” form. ::: {.callout-note} ## Bayes’ Rule in Odds Form <span class="math display">\[
\underbrace{O(H \mid E)}_{\text{Posterior Odds}} = \underbrace{\frac{P(E \mid H)}{P(E \mid \neg H)}}_{\text{Bayes factor}} \times \underbrace{O(H)}_{\text{Prior Odds}}
\]</span> ::: Here, the odds of an event <span class="math inline">\(H\)</span> are defined as <span class="math inline">\(O(H) = \frac{P(H)}{P(\neg H)}\)</span>. This separates the contribution of the evidence (Bayes factor) from the prior belief.</p>
<div id="exm-prosecutors-fallacy" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.8 (The Prosecutor’s Fallacy)</strong></span> The Prosecutor’s Fallacy is a logical error that occurs when a prosecutor presents evidence or statistical data in a way that suggests a defendant’s guilt, even though the evidence is not as conclusive as it may seem. This fallacy arises from confounding conditional probabilities, specifically equating the probability of evidence given guilt <span class="math inline">\(P(E\mid G)\)</span> with the probability of guilt given evidence <span class="math inline">\(P(G\mid E)\)</span>. <span class="math display">\[
P(E\mid G) \ne P(G\mid E)
\]</span> A classic example involves DNA evidence. Suppose you’re serving on a jury in a city with a population of 10 million. A defendant is accused of a crime based on a DNA match found at the scene. A forensic scientist testifies that the probability of an innocent person’s DNA matching the sample is one in a million (<span class="math inline">\(P(E\mid \bar G) = 10^{-6}\)</span>).</p>
<p>The prosecutor argues that this means there is only a one in a million chance the defendant is innocent. This is the fallacy. You are charged with assessing <span class="math inline">\(P(G \mid E)\)</span> - the probability of guilt given the match.</p>
<p>Let’s apply Bayes’ rule.</p>
<ul>
<li><span class="math inline">\(P(G) \approx 1/10^7\)</span> (Prior probability, assuming a random citizen).</li>
<li><span class="math inline">\(P(E\mid \bar G) = 10^{-6}\)</span> (False positive rate).</li>
<li><span class="math inline">\(P(E\mid G) \approx 1\)</span> (Sensitivity).</li>
</ul>
<p><span class="math display">\[
P(G\mid E) = \frac{P(E\mid G)P(G)}{P(E\mid G)P(G) + P(E\mid \bar G)P(\bar G)}
\]</span> <span class="math display">\[
P(G\mid E) \approx \frac{1 \cdot 10^{-7}}{1 \cdot 10^{-7} + 10^{-6} \cdot 1} = \frac{10^{-7}}{1.1 \times 10^{-6}} \approx \frac{1}{11} \approx 0.09
\]</span></p>
<p>Despite the “one in a million” match rarity, the probability of guilt is only about 9%! There are 10 million people, so we expect about 10 innocent matches (<span class="math inline">\(10^7 \times 10^{-6}\)</span>) and 1 guilty match. Thus, out of 11 matches, only 1 is guilty. The prosecutor’s argument ignores the base rate.</p>
</div>
<div id="exm-island" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.9 (Island Problem)</strong></span> There are <span class="math inline">\(N+1\)</span> people on the island, and one is a criminal. We have the probability of a trait of a criminal equal to <span class="math inline">\(p\)</span>, which is <span class="math inline">\(p = P(E\mid I)\)</span>, the probability of evidence, given innocence. Then we have a suspect who is matching the trait, and we need to find the probability of being guilty, given the evidence, <span class="math inline">\(P(G \mid E)\)</span>. It is easier to do Bayes’ rule in the odds form. There are three components to the calculations: the prior odds of innocence, <span class="math display">\[
O ( I ) = P (I) / P ( G ),
\]</span> the Bayes factor, <span class="math display">\[
\frac{P(E\mid G)}{P(E\mid I)}.
\]</span> and the posterior odds of guilt. <span class="math display">\[
    O(G\mid E) = \dfrac{P(G\mid E)}{P(I\mid E)} = \dfrac{1}{Np}.
\]</span></p>
<p>Cromwell’s rule states that the use of prior probability of 1 or 0 should be avoided except when it is known for certain that the probability is 1 or 0. It is named after Oliver Cromwell who wrote to the General Assembly of the Church of Scotland in 1650 “<em>I beseech you, in the bowels of Christ, think it possible that you may be mistaken.</em>” In other words, using Bayes’ rule <span class="math display">\[
P(G\mid E) = \dfrac{P(E\mid G)}{P(E)}P(G),
\]</span> if <span class="math inline">\(P(G)\)</span> is zero, it does not matter what the evidence is. Symmetrically, the probability of innocence is zero if the evidence is certain. In other words, if <span class="math inline">\(P(E\mid I) = 0\)</span>, then <span class="math inline">\(P(I\mid E) = 0\)</span>. This is a very strong statement. It is not always true, but it is a good rule of thumb; it is a good way to avoid the prosecutor’s fallacy.</p>
</div>
<div id="exm-nakamura" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.10 (Nakamura’s Alleged Cheating)</strong></span> In our paper <span class="citation" data-cites="maharaj2023kramnik">Maharaj, Polson, and Sokolov (<a href="references.html#ref-maharaj2023kramnik" role="doc-biblioref">2023</a>)</span>, we provide a statistical analysis of the recent controversy between Vladimir Kramnik (ex-world champion) and Hikaru Nakamura. Kramnik called into question Nakamura’s 45.5 out of 46 win streak in a 3+0 online blitz contest at chess.com. In this example, we reproduce this paper and assess the weight of evidence using an a priori probabilistic assessment of Viswanathan Anand and the streak evidence of Kramnik. Our analysis shows that Nakamura has a 99.6 percent chance of not cheating given Anand’s prior assumptions.</p>
<p>We start by addressing the argument of Kramnik which is based on the fact that the probability of such a streak is very small. This falls into precisely the <em>Prosecutor’s Fallacy</em>, as discussed in <a href="#exm-prosecutors-fallacy" class="quarto-xref">Example&nbsp;<span>2.8</span></a>. We denote by <span class="math inline">\(G\)</span> the event of being guilty and <span class="math inline">\(I\)</span> the event of innocence. We use <span class="math inline">\(E\)</span> to denote evidence (streak of wins). Kramnik’s argument is that because the probability of observing the streak is very low (<span class="math inline">\(P(E\mid I)\)</span> is small), it implies a high probability of cheating (<span class="math inline">\(P(G\mid E)\)</span> is high). As we have seen, this reasoning is flawed because it neglects the prior probability of cheating. Kramnik’s calculations neglect other relevant factors, such as the prior probability of cheating. The prosecutor’s fallacy can lead to an overestimation of the strength of the evidence and may result in an unjust conviction. In the cheating problem, at the top level of chess, the prior probability of <span class="math inline">\(P(G)\)</span> is small! According to a recent statement by Viswanathan Anand, the probability of cheating is <span class="math inline">\(1/10000\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/anand-prior.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Anand’s Prior</figcaption>
</figure>
</div>
<p>Given the prior ratio of cheaters to non-cheaters is <span class="math inline">\(1/N\)</span>, meaning out of <span class="math inline">\(N+1\)</span> players, there is one cheater, the Bayes calculations require two main terms. The first one is the prior odds of innocence: <span class="math display">\[
O ( I ) = P (I) / P ( G ).
\]</span> Here <span class="math inline">\(P(I)\)</span> and <span class="math inline">\(P(G)\)</span> are the prior probabilities of innocence and guilt, respectively.</p>
<p>The second term is the Bayes factor in favor of innocence, which is the ratio of the probability of the evidence under the innocence hypothesis to the probability of the evidence under the guilt hypothesis: <span class="math display">\[
    L(E\mid I) = \frac{P(E\mid I)}{P(E\mid G)}.
\]</span></p>
<p>The product of the Bayes factor and the prior odds is the posterior odds of innocence, given the evidence: <span class="math display">\[
    O(I\mid E) = O(I) \times L(E\mid I).
\]</span></p>
<p>The odds of innocence is <span class="math display">\[
    O ( I )  = \dfrac{N/(N+1)}{1/(N+1)} = N.
\]</span></p>
<p>The Bayes factor is given by <span class="math display">\[
\frac{P(E\mid I)}{P(E\mid G)} = \dfrac{p}{1} = p.
\]</span> Thus, the posterior odds of innocence are <span class="math display">\[
    O(I\mid E) = Np.
\]</span> There are two numbers we need to estimate to calculate the odds of innocence given the evidence, namely the prior probability of cheating given via <span class="math inline">\(N\)</span> and the probability of a streak <span class="math inline">\(p = P(E\mid I)\)</span>.</p>
<p>There are multiple ways to calculate the probability of a streak. We can use the binomial distribution, the negative binomial distribution, or the Poisson distribution. The binomial distribution is the most natural choice. The probability of a streak of <span class="math inline">\(k\)</span> wins in a row is given by <span class="math display">\[
    P(E\mid I) = \binom{N}{k} q^k (1-q)^{N-k}.
\]</span> Here <span class="math inline">\(q\)</span> is the probability of winning a single game. Thus, for a streak of 45 wins in a row, we have <span class="math inline">\(k = 45\)</span> and <span class="math inline">\(N = 46\)</span>. We encode the outcome of a game as <span class="math inline">\(1\)</span> for a win and <span class="math inline">\(0\)</span> for a loss or a draw. The probability of a win is <span class="math inline">\(q = 0.8916\)</span> (Nakamura’s Estimate, which he reported on his YouTube channel). The probability of a streak is then 0.029. The individual game win probability is calculated from the ELO rating difference between the players.</p>
<p>The ELO rating of Hikaru is 3300, and the average ELO rating of his opponents is 2950, according to Kramnik. The difference of 350 corresponds to the odds of winning of <span class="math inline">\(wo = 10^{350/400} = 10^{0.875} = 7.5\)</span>. The probability of winning a single game is <span class="math inline">\(q = wo/(1+wo) = 0.88\)</span>, close to Nakamura’s own estimate of <span class="math inline">\(0.8916\)</span> that we use here.</p>
<p>Then we use Anand’s prior of <span class="math inline">\(N = 10000\)</span> to get the posterior odds of cheating given the evidence of a streak of 45 wins in a row. The posterior odds of being innocent are 285. The probability of cheating is then <span class="math display">\[
P(G\mid E) = 1/(1+O(I\mid E)) = 0.003491.
\]</span> Therefore, the probability of innocence is <span class="math display">\[
    P(I\mid E) = \frac{Np}{Np+1} = 0.9965.
\]</span></p>
<p>For completeness, we perform a sensitivity analysis and also get the odds of not cheating for <span class="math inline">\(N = 500\)</span>, which should be a high prior probability given the status of the player and the importance of the event. We get <span class="math display">\[
    P(I\mid E) = \frac{Np}{Np+1} = 0.9345.
\]</span></p>
<p>There are several assumptions we made in this analysis.</p>
<ul>
<li>Instead of calculating game-by-game probability of winning, we used the average probability of winning of 0.8916, provided by Nakamura himself. This is a reasonable assumption given the fact that Nakamura is a much stronger player than his opponents. This assumption slightly shifts posterior odds in favor of not cheating. Due to Jensen’s inequality, we have <span class="math inline">\(E(q^{50}) &gt; E(q)^{50}\)</span>. Expected value of the probability of winning a single game is <span class="math inline">\(E(q) = 0.8916\)</span> and the expected value of the probability of a streak of 50 wins is <span class="math inline">\(E(q^{50})\)</span>. We consider the difference between the two to be small. Further, there is some correlation between the games, which also shifts the posterior odds in favor of not cheating. For example, some players are on tilt. Given they lost the first game, they are more likely to lose the second game.</li>
<li>There are many ways to win 3+0, unlike in classical chess. For example, one can win on time. We argue that the probability of winning calculated from the ELO rating difference is underestimated.</li>
</ul>
<p>Next, we can use the Bayes analysis to solve an inverse problem and to find what prior you need to assume and how long of a sequence you need to observe to get 0.99 posterior? Small sample size, we have <span class="math inline">\(p\)</span> close to 1. <a href="#fig-n-p" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> shows the combination of prior (<span class="math inline">\(N\)</span>) and the probability of a streak (<span class="math inline">\(p\)</span>) that gives posterior probability of 0.99.</p>
<p>Indeed, the results of the Bayesian analysis contradict the results of a traditional <span class="math inline">\(p\)</span>-value based approach. A <span class="math inline">\(p\)</span>-value is a measure used in frequentist statistical hypothesis testing. It represents the probability of obtaining the observed results, or results more extreme, assuming that the null hypothesis is true. The null hypothesis is a default position that Nakamura is not cheating, and we compare the ELO-based expected win probability of <span class="math inline">\(q=0.8916\)</span> to the observed one of <span class="math inline">\(s=45/46=0.978\)</span>. Under the null hypothesis, Nakamura should perform at the level predicted by <span class="math inline">\(q\)</span>.</p>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fl">0.8916</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">45</span>, <span class="dv">46</span>, q)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>odds <span class="ot">&lt;-</span> p <span class="sc">*</span> N</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> odds))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">## 1</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="dv">1</span> <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> odds))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">## 0.0035</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(N <span class="sc">*</span> p <span class="sc">/</span> (N <span class="sc">*</span> p <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="do">## 1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">500</span>, <span class="dv">10000</span>, <span class="at">by =</span> <span class="dv">250</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">99</span> <span class="sc">/</span> N, N, <span class="at">xlab =</span> <span class="st">"p"</span>, <span class="at">ylab =</span> <span class="st">"N"</span>, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-n-p" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-n-p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-bayes_files/figure-html/fig-n-p-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-n-p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: The combination of prior (<span class="math inline">\(N\)</span>) and the probability of a streak (<span class="math inline">\(p\)</span>) that gives posterior probability of 0.99.
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>David Hume discussed the problem similar to the Island problem in his “On Miracles” essay. Hume is making the following argument on miracles:</p>
<blockquote class="blockquote">
<p>“<em>…no testimony is sufficient to establish a miracle, unless the testimony be of such a kind, that its falsehood would be more miraculous, than the fact, which it endeavors to establish; and even in that case there is a mutual destruction of arguments, and the superior only gives us an assurance suitable to that degree of force, which remains, after deducting the inferior.</em>”</p>
</blockquote>
<p>One can view this as an application of the Island problem. Assuming the probability of a miracle <span class="math inline">\(A\)</span> is <span class="math inline">\(P( A) = p\)</span> and <span class="math inline">\(P( \text{not } A ) = 1 -p\)</span>. Then Bayes’ rule gives <span class="math display">\[
P( A\mid a ) = \frac{ P( a\mid A) p }{  P( a\mid A) p  +  P( a \mid  \text{not } A) (1-p) }
\]</span> Prosecutor’s fallacy, <span class="math inline">\(P( a\mid \text{not } A)  \neq 1 -  P( a\mid A)\)</span>, in general.</p>
<p>In Hume’s assessment of miracles (has to be something not in the laws of nature), we have <span class="math inline">\(P(A) = 10^{-6}\)</span>. This assessment takes into account background information, <span class="math inline">\(I\)</span>. Rare to have a contradiction to the laws of nature. More informative to write <span class="math inline">\(P( A \mid I )\)</span>. Furthermore, we take <span class="math inline">\(P( a\mid A) =0.99\)</span>. The hardest bit is to assess <span class="math inline">\(P(a \mid \text{not } A )\)</span>. The “frequency” of faked miracles and mankind’s propensity to be marvelous. We assess <span class="math inline">\(P(a \mid \text{not } A )  = 10^{-3}\)</span>. This yields the chance of a miracle to be unlikely as <span class="math display">\[
P( A\mid a ) = \frac{ 0.99 \times 10^{-6}  }{  0.99 \times 10^{-6}    +  10^{-3} (1- 10^{-6}) }   \approx 10^{-3}.
\]</span> Feynman considers the inverse problem: can we learn the laws of nature purely from empirical observation? Uses chess as an example. Is it a miracle that we have two bishops of the same color? No! according to Hume. We just didn’t know the laws of nature (a.k.a. model).</p>
<div id="exm-Sally" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.11 (Sally Clark Case: Independence or Bayes’ Rule?)</strong></span> To show that independence can lead to dramatically different results from Bayes conditional probabilities, consider the Sally Clark case. Sally Clark was accused and convicted of killing her two children who could have both died of SIDS. One explanation is that this was a random occurrence; the other one is that they both died of sudden infant death syndrome (SIDS). How can we use conditional probability to figure out a reasonable assessment of the probability that she murdered her children. First, some known probability assessments</p>
<ol type="1">
<li>The chance of a family of non-smokers having an SIDS death is <span class="math inline">\(1\)</span> in <span class="math inline">\(8{,}500\)</span>.</li>
<li>The chance of a second SIDS death is <span class="math inline">\(1\)</span> in <span class="math inline">\(100\)</span>.</li>
<li>The chance of a mother killing her two children is around <span class="math inline">\(1\)</span> in <span class="math inline">\(1{,}000{,}000\)</span>.</li>
</ol>
<p>Under Bayes <span class="math display">\[\begin{align*}
P(\mathrm{both} \; \; \mathrm{SIDS})   &amp;  = P(\mathrm{first} \; \mathrm{SIDS}) P(\mathrm{Second} \; \;\mathrm{SIDS} \mid \mathrm{first} \; \mathrm{SIDS})\\
&amp;  = \frac{1}{8500} \cdot \frac{1}{100} = \frac{1}{850{,}000}.
\end{align*}\]</span></p>
<p>The <span class="math inline">\(1/100\)</span> comes from taking into account the genetic properties of SIDS. Independence, as implemented by the court, gets you to a probabilistic assessment of <span class="math display">\[
P \left(  \mathrm{both} \; \; \mathrm{SIDS} \right)  = (1/8500) (1/8500) \approx (1/72{,}000{,}000).
\]</span> This is a low probability. It is still not the answer to our question of context. We need a conditional probability; this will come to Bayes’ rule.</p>
<p>First, some general comment on the likelihood ratio calculation used to assess the weight of evidence in favor of guilty v.s. innocent evidence. Under Bayes we’ll find that there’s reasonable evidence that she’d be acquitted. We need the relative odds ratio. Let <span class="math inline">\(I\)</span> denote the event that Sally Clark is innocent and <span class="math inline">\(G\)</span> denotes guilty. Let <span class="math inline">\(E\)</span> denote the evidence. In most cases, <span class="math inline">\(E\)</span> contains a sequence <span class="math inline">\(E_1, E_2, \ldots\)</span> of ‘facts’ and we have to use the likelihood ratios in turn. Bayes’ rule then tells you to combine via multiplicative fashion. If likelihood ratio <span class="math inline">\(&gt;1\)</span>, odds of guilty. If likelihood ratio <span class="math inline">\(&lt;1\)</span>, more likelihood to be <span class="math inline">\(I\)</span>. By Bayes’ rule <span class="math display">\[
\frac{P(I\mid E)}{P(G\mid E)} = \frac{P( E\text{ and } I)}{P( E\text{ and } G)}.
\]</span> If we further decompose <span class="math inline">\(P(E \text{ and } I) = P(E\mid I )P(I)\)</span> then we have to discuss the prior probability of innocence, namely <span class="math inline">\(P(I)\)</span>. Hence, this is one subtle advantage of the above decomposition.</p>
<p>The underlying intuition that Bayes gives us in this example, is that of the two possible explanations of the data, both of which are unlikely, it is the relative likelihood comparison that should matter. Here is a case where the <span class="math inline">\(p\)</span>-value would be non-sensible (<span class="math inline">\(P(E\mid I) \neq P(I\mid E)\)</span>). Effectively comparing two rare event probabilities from the two possible models or explanations.</p>
<p>Hence, putting these two together gives the odds of guilt as <span class="math display">\[
\frac{P(I\mid E)}{P(G\mid E)} = \frac{1/850{,}000}{1/1{,}000{,}000} = 1.18.
\]</span> Solving for the posterior probability yields <span class="math inline">\(46\%\)</span> for the probability of guilty given evidence. <span class="math display">\[
P( G\mid E) = \frac{1}{1 + O(I\mid E)} = 0.46.
\]</span> Basically a <span class="math inline">\(50/50\)</span> bet. Not enough to definitively convict! But remember that our initial prior probability on guilt <span class="math inline">\(P(G)\)</span> was <span class="math inline">\(10^{-6}\)</span>. So now there has been a dramatic increase to a posterior probability of <span class="math inline">\(0.46\)</span>. So it’s not as if Bayes’ rule thinks this is evidence in the suspect’s favor, but the magnitude is still not in the <span class="math inline">\(0.999\)</span> range, though, where most jurors would have to be to feel comfortable with a guilt verdict.</p>
<p>If you use the “wrong” model of independence (as the court did), you get <span class="math display">\[
P \left(  \mathrm{both} \; \; \mathrm{SIDS} \right)  = \frac{1}{8500}
  \cdot\frac{1}{8500} \approx \frac{1}{72{,}000{,}000}.
\]</span> With the independence assumption, you make the assessment <span class="math display">\[
\frac{P(I\mid E)}{P(G\mid E)} = \frac{1}{72} \; \mathrm{ and} \; P( G\mid E) \approx 0.99.
\]</span> Given these probability assumptions, the suspect looks guilty with probability 99%.</p>
<p>Experts also mis-interpret the evidence by saying: <em>1 in 73 million chance that it is someone else</em>. This is clearly false and misleading to the jury and has led to appeals.</p>
</div>
<div id="exm-Simpson" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.12 (O. J. Simpson Case: Dershowitz Fallacy)</strong></span> &nbsp;</p>
<!-- https://rss.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1740-9713.2015.00839.x -->
<p>This example is based on I. J. Good’s, “When batterer turns murderer.” Nature, 15 June 1995, p.&nbsp;541. Alan Dershowitz, on the O. J. Simpson defense team, stated on T.V. and in newspapers that only 1 in 2,500 of men who abuse their wives go on to murder them. He clearly wanted his audience to interpret this to mean that the evidence of abuse by Simpson would only suggest a 0.04% probability of his being guilty of murdering her. He used probability to argue that because so few husbands who batter their wives actually go on to murder their wives. Thus, O.J. is highly likely to be not guilty. This leaves out the most relevant conditioning information that we also know that Nicole Brown Simpson was actually murdered. Both authors believe the jury would be more interested in the probability that the husband is guilty of the murder of his wife given that he abused his wife and his wife was murdered. They both solve this problem by using Bayes’ theorem.</p>
<p>In this example, the notation <span class="math inline">\(B\)</span> represents “woman battered by her husband, boyfriend, or lover”, <span class="math inline">\(M\)</span> represents the event “woman murdered”, and <span class="math inline">\(G\)</span> denotes “woman murdered by her batterer”. Our goal is to show that <span class="math display">\[
% P(M,B \mid M) \neq P(M,B \mid B).
P(G \mid M,B) \neq P(G\mid B).
\]</span></p>
<p>It is not hard to come to a wrong conclusion if you don’t take into account all the relevant conditional information. He intended this information to exonerate O.J. In 1992, the women population of the US was 125 million, and 4936 women were murdered; thus <span class="math display">\[
P(M) = 4936/125{,}000{,}000 = 0.00004 = 1/25{,}000.
\]</span> At the same year, about 3.5 million women were battered <span class="math display">\[
P(B) = 3.5/125 = 0.028.
\]</span> That same year, 1432 women were murdered by their previous batterers, so the marginal probability of that event is <span class="math inline">\(P(G) = 1432/125{,}000{,}000 = 0.00001 = 1/87{,}290\)</span>, and the conditional probability, <span class="math inline">\(P(G \mid B)\)</span>, is 1432 divided by 3.5 million, or <span class="math inline">\(1/2444\)</span>. These are the numbers Dershowitz used to obtain his estimate that about 1 in 2500 battered women go on to be murdered by their batterers.</p>
<p>We need to calculate <span class="math display">\[
P(G \mid M,B) = P(M \mid G,B) P(G) / P(M).
\]</span> We know <span class="math inline">\(P(M \mid G,B) = 1\)</span> and <span class="math inline">\(P(G) / P(M) = 1432/4936 = 0.29\)</span>, or about 1 in 3.5.</p>
<p>Alan Dershowitz provided the jury with an accurate but irrelevant probability. The fact that the woman was murdered increases the probability that she was murdered by her batterer by a factor of 709 (0.29/(1/2444)). <span class="math display">\[
P(G\mid M,B)\approx 709\times P(G\mid B).
\]</span></p>
<p>The argument used by Dershowitz relating to the Simpson case has been discussed by John Paulos in an op-ed article in the Philadelphia Inquirer (15 Oct.&nbsp;1995, C7) and his book “Once Upon a Number,” by I.J. Good in an article in Nature (June 15,1995, p 541) and by Jon Merz and Jonathan Caulkins in an article in Chance Magazine, (Spring 1995, p 14).</p>
</div>
</section>
<section id="first-application-naive-bayes" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="first-application-naive-bayes"><span class="header-section-number">2.4</span> First Application: Naive Bayes</h2>
<p>Use of Bayes’ rule allows us to build our first predictive model, called the Naive Bayes classifier. Naive Bayes is a collection of classification algorithms based on Bayes’ theorem. It is not a single algorithm but a family of algorithms that all share a common principle, that every feature being classified is independent of the value of any other feature. For example, a fruit may be considered to be an apple if it is red, round, and about 3” in diameter. A Naive Bayes classifier considers each of these “features” (red, round, 3” in diameter) to contribute independently to the probability that the fruit is an apple, regardless of any correlations between features. Features, however, aren’t always independent, which is often seen as a shortcoming of the Naive Bayes algorithm, and this is why it’s labeled “naive”.</p>
<div class="cell" data-eval="false" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>

</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fig/fruit.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption>Color, Shape and Size of Fruits.</figcaption>
</figure>
</div>
<p>Although it’s a relatively simple idea, Naive Bayes can often outperform other more sophisticated algorithms and is extremely useful in common applications like spam detection and document classification. In short, the algorithm allows us to predict a class, given a set of features using probability. So in another fruit example, we could predict whether a fruit is an apple, orange, or banana (class) based on its color, shape, etc. (features). In summary, the advantages are:</p>
<ul>
<li>It’s relatively simple to understand and build</li>
<li>It’s easily trained, even with a small dataset</li>
<li>It’s fast!</li>
<li>It’s not sensitive to irrelevant features</li>
</ul>
<p>The main disadvantage is that it assumes every feature is independent, which isn’t always the case.</p>
<p>Let’s say we have data on 1000 pieces of fruit. The fruit being a Banana, Orange, or some Other fruit, and imagine we know 3 features of each fruit: whether it’s long or not, sweet or not, and yellow or not, as displayed in the table below:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fruit</th>
<th>Long</th>
<th>Sweet</th>
<th>Yellow</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Banana</td>
<td>400</td>
<td>350</td>
<td>450</td>
<td>500</td>
</tr>
<tr class="even">
<td>Orange</td>
<td>0</td>
<td>150</td>
<td>300</td>
<td>300</td>
</tr>
<tr class="odd">
<td>Other</td>
<td>100</td>
<td>150</td>
<td>50</td>
<td>200</td>
</tr>
<tr class="even">
<td>Total</td>
<td>500</td>
<td>650</td>
<td>800</td>
<td>1000</td>
</tr>
</tbody>
</table>
<p>From these data, we can calculate marginal probabilities</p>
<ul>
<li>50% of the fruits are bananas</li>
<li>30% are oranges</li>
<li>20% are other fruits</li>
</ul>
<p>Based on our training set, we can also say the following:</p>
<ul>
<li>From 500 bananas, 400 (0.8) are Long, 350 (0.7) are Sweet, and 450 (0.9) are Yellow</li>
<li>Out of 300 oranges, 0 are Long, 150 (0.5) are Sweet, and 300 (1) are Yellow</li>
<li>From the remaining 200 fruits, 100 (0.5) are Long, 150 (0.75) are Sweet, and 50 (0.25) are Yellow So let’s say we’re given the features of a piece of fruit, and we need to predict the class. If we’re told that the additional fruit is Long, Sweet, and Yellow, we can classify it using the following formula and subbing in the values for each outcome, whether it’s a Banana, an Orange, or Other Fruit. The one with the highest probability (score) being the winner.</li>
</ul>
<p>Given the evidence <span class="math inline">\(E\)</span> (<span class="math inline">\(L\)</span> = Long, <span class="math inline">\(S\)</span> = Sweet and <span class="math inline">\(Y\)</span> = Yellow), we can calculate the probability of each class <span class="math inline">\(C\)</span> (<span class="math inline">\(B\)</span> = Banana, <span class="math inline">\(O\)</span> = Orange or <span class="math inline">\(F\)</span> = Other Fruit) using Bayes’ theorem: <span class="math display">\[\begin{align*}
P(B \mid E) = &amp; \frac{P(L \mid B)P(S \mid B)P(Y \mid B)P(B)}{P(L)P(S)P(Y)}\\
=&amp;\frac{0.8\times 0.7\times 0.9\times 0.5}{P(E)}=\frac{0.252}{P(E)}
\end{align*}\]</span></p>
<p>Orange: <span class="math display">\[
P(O\mid E)=0.
\]</span></p>
<p>Other Fruit: <span class="math display">\[\begin{align*}
P(F \mid E) &amp; = \frac{P(L \mid F)P(S \mid F)P(Y \mid F)P(F)}{P(L)P(S)P(Y)}\\
=&amp;\frac{0.5\times 0.75\times 0.25\times 0.2}{P(E)}=\frac{0.01875}{P(E)}
\end{align*}\]</span></p>
<p>In this case, based on the higher score, we can assume this Long, Sweet, and Yellow fruit is, in fact, a Banana.</p>
<p>Notice, we did not have to calculate <span class="math inline">\(P(E)\)</span> because it is a normalizing constant and it cancels out when we calculate the ratio</p>
<p><span class="math display">\[
\dfrac{P(B \mid E)}{P(F \mid E)} = 0.252/0.01875 = 13.44 &gt; 1.
\]</span></p>
<p>Now that we’ve seen a basic example of Naive Bayes in action, you can easily see how it can be applied to Text Classification problems such as spam detection, sentiment analysis, and categorization. By looking at documents as a set of words, which would represent features, and labels (e.g., “spam” and “ham” in the case of spam detection) as classes, we can start to classify documents and text automatically.</p>
<div id="exm-naivebayes" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.13 (Spam Filtering)</strong></span> The original spam filtering algorithm was based on Naive Bayes. The “naive” aspect of Naive Bayes comes from the assumption that inputs (words in the case of text classification) are conditionally independent, given the class label. Naive Bayes treats each word independently, and the model doesn’t capture the sequential or structural information inherent in the language. It does not consider grammatical relationships or syntactic structures. The algorithm doesn’t understand the grammatical rules that dictate how words should be combined to form meaningful sentences. Further, it doesn’t understand the context in which words appear. For example, it may treat the word “bank” the same whether it refers to a financial institution or the side of a river bank. Despite its simplicity and the naive assumption, Naive Bayes often performs well in practice, especially in text classification tasks.</p>
<p>We start by collecting a dataset of emails labeled as “spam” or “not spam” (ham) and calculate the prior probabilities of spam (<span class="math inline">\(P(\text{spam})\)</span>) and not spam (<span class="math inline">\(P(\text{ham})\)</span>) based on the training dataset by simply counting the proportions of each in the data.</p>
<p>Then each email gets converted into a bag-of-words representation (ignoring word order and considering only word frequencies). Then, we create a vocabulary of unique words from the entire dataset <span class="math inline">\(w_1,w_2,\ldots,w_N\)</span> and calculate conditional probabilities <span class="math display">\[
P(\mathrm{word}_i  \mid  \text{spam}) = \frac{\text{Number of spam emails containing }\mathrm{word}_i}{\text{Total number of spam emails}}, ~ i=1,\ldots,n
\]</span> <span class="math display">\[
P(\mathrm{word}_i  \mid  \text{ham}) = \frac{\text{Number of ham emails containing }\mathrm{word}_i}{\text{Total number of ham emails}}, ~ i=1,\ldots,n
\]</span></p>
<p>Now, we are ready to use our model to classify new emails. We do it by calculating the posterior probability using Bayes’ theorem. Say an email has a set of <span class="math inline">\(k\)</span> words <span class="math inline">\(\text{email} = \{w_{e1},w_{e2},\ldots, w_{ek}\}\)</span>, then <span class="math display">\[
P(\text{spam}  \mid  \text{email}) = \frac{P(\text{email}  \mid  \text{spam}) \times P(\text{spam})}{P(\text{email})}
\]</span> Here <span class="math display">\[
P(\text{email}  \mid  \text{spam}) = P( w_{e1}  \mid  \text{spam})P( w_{e2}  \mid  \text{spam})\ldots P( w_{ek}  \mid  \text{spam})
\]</span> We calculate <span class="math inline">\(P(\text{ham} \mid \text{email})\)</span> in a similar way.</p>
<p>Finally, we classify the email as spam or ham based on the class with the highest posterior probability.</p>
<p>Suppose you have a spam email with the word “discount” appearing. Using Naive Bayes, you’d calculate the probability that an email containing “discount” is spam <span class="math inline">\(P(\text{spam} \mid \text{discount})\)</span> and ham <span class="math inline">\(P(\text{ham} \mid \text{discount})\)</span>, and then compare these probabilities to make a classification decision.</p>
<p>While the naive assumption simplifies the model and makes it computationally efficient, it comes at the cost of a more nuanced understanding of language. More sophisticated models, such as transformers, have been developed to address these limitations by considering the sequential nature of language and capturing contextual relationships between words.</p>
<p>In summary, naive Bayes, due to its simplicity and the naive assumption of independence, is not capable of understanding the rules of grammar, the order of words, or the intricate context in which words are used. It is a basic algorithm suitable for certain tasks but may lack the complexity needed for tasks that require a deeper understanding of language structure and semantics.</p>
</div>
</section>
<section id="sec-sensitivity" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-sensitivity"><span class="header-section-number">2.5</span> Sensitivity and Specificity</h2>
<p>Conditional probabilities are used to define two fundamental metrics used for many probabilistic and statistical learning models, namely <em>sensitivity</em> and <em>specificity</em>.</p>
<p>Sensitivity and specificity are two key metrics used to evaluate the performance of diagnostic tests, classification models, or screening tools. These metrics help assess how well a test can correctly identify individuals with a condition (true positives) and those without the condition (true negatives). Let’s break down each term:</p>
<ol type="1">
<li><em>Sensitivity (true‐positive rate or recall)</em> is the ability of a test <span class="math inline">\(T\)</span> to correctly identify individuals who have a particular condition or disease (<span class="math inline">\(D\)</span>), <span class="math inline">\(P ( T=1 \mid D=1 )\)</span>, the probability of a positive test given that the individual has the disease. It is calculated as the ratio of true positives to the sum of true positives and false negatives. <span class="math display">\[
P(T=1\mid D=1) = \dfrac{P(T=1,D=1)}{P(D=1)}.
\]</span> A high sensitivity indicates that the test is good at identifying individuals with the condition, minimizing false negatives.</li>
<li><em>Specificity (true‐negative rate)</em> is the ability of a test to correctly identify individuals who do not have a particular condition or disease, <span class="math inline">\(P (T=0 \mid D=0 )\)</span>. It is calculated as the ratio of true negatives to the sum of true negatives and false positives. <span class="math display">\[
P(T=0\mid D=0) = \dfrac{P(T=0,D=0)}{P(D=0)}
\]</span> A high specificity indicates that the test is good at correctly excluding individuals without the condition, minimizing false positives.</li>
</ol>
<p>Sensitivity and specificity are often trade-offs. Increasing sensitivity might decrease specificity, and vice versa. Thus, depending on the application, you might prefer sensitivity over specificity or vice versa, depending on the consequences of false positives and false negatives in a particular application.</p>
<p>Consider a medical test designed to detect a certain disease. If the test has high sensitivity, it means that it is good at correctly identifying individuals with the disease. On the other hand, if the test has high specificity, it is good at correctly identifying individuals without the disease. The goal is often to strike a balance between sensitivity and specificity based on the specific needs and implications of the test results.</p>
<!-- -   **Sensitivity** measures the true positive rate, or recall, for
  example, the percentage of sick people who are correctly identified
  $P ( T=1 \mid  D=1 )$.
-   **Specificity** measures true negative rate, e.g % of negatives
  corrected identified as such. $P (T=0  \mid  D=0 )$. -->
<p>Sensitivity is often called the power of a procedure (a.k.a. test). Type I and Type II errors are fundamental concepts in hypothesis testing, serving as the duals to specificity and sensitivity.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Type I Error (False Positive Rate)
</div>
</div>
<div class="callout-body-container callout-body">
<p>is the percentage of healthy people who tested positive, <span class="math inline">\(P(T=1\mid D=0)\)</span>, it is the mistake of thinking something is true when it is not.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Type II Error (or False Negative Rate)
</div>
</div>
<div class="callout-body-container callout-body">
<p>is the percentage of sick people who are tested negative, <span class="math inline">\(P(T=0\mid D=1)\)</span>, it is the mistake of thinking something is not true when in fact it is true.</p>
</div>
</div>
<p>We would like to control both conditional probabilities with our test. Also, if someone tests positive, how likely is it that they actually have the disease. There are two ‘errors’ one can make. Falsely diagnosing someone, or not correctly finding the disease.</p>
<p>In the stock market, one can think of a type I error as not selling a losing stock quickly enough, and a type II error as failing to buy a growing stock, e.g., Amazon or Google.</p>
<div id="tbl-sensitivity" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[30,22,25,23]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Sensitivity and Specificity.
</figcaption>
<div aria-describedby="tbl-sensitivity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 23%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(P(T=1\mid D=1)\)</span></td>
<td style="text-align: center;">Sensitivity</td>
<td style="text-align: center;">True Positive Rate</td>
<td style="text-align: center;"><span class="math inline">\(1-\beta\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(P(T=0\mid D=0 )\)</span></td>
<td style="text-align: center;">Specificity</td>
<td style="text-align: center;">True Negative Rate</td>
<td style="text-align: center;"><span class="math inline">\(1-\alpha\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(P(T=1\mid D=0)\)</span></td>
<td style="text-align: center;">1-Specificity</td>
<td style="text-align: center;">False Positive Rate</td>
<td style="text-align: center;"><span class="math inline">\(\alpha\)</span> (type I error)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(P(T=0\mid D =1)\)</span></td>
<td style="text-align: center;">1-Sensitivity</td>
<td style="text-align: center;">False Negative Rate</td>
<td style="text-align: center;"><span class="math inline">\(\beta\)</span> (type II error)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Often it is convenient to write those four values in the form of a two-by-two matrix, called the confusion matrix:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Actual/Predicted</th>
<th>Positive</th>
<th>Negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Positive</td>
<td>TP</td>
<td>FN</td>
</tr>
<tr class="even">
<td>Negative</td>
<td>FP</td>
<td>TN</td>
</tr>
</tbody>
</table>
<p>where: TP: True Positive. FN: False Negative, FP: False Positive, TN: True Negative</p>
<p>We will extensively use the concepts of errors, specificity, and sensitivity later in the book, when describing AB testing and predictive models. These examples illustrate why people can commonly miscalculate and mis-interpret probabilities. Those quantities can be calculated using Bayes’ rule.</p>
<section id="medical-diagnostics" class="level3">
<h3 class="anchored" data-anchor-id="medical-diagnostics">Medical Diagnostics</h3>
<div id="exm-Alice" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.14 (Alice Mammogram)</strong></span> Alice is a 40-year-old woman, what is the chance that she really has breast cancer when she gets a positive mammogram result, given the conditions:</p>
<ol type="1">
<li>The prevalence of breast cancer among people like Alice is 1%.</li>
<li>The test has an 80% detection rate.</li>
<li>The test has a 10% false-positive rate.</li>
</ol>
<p>We want to calculate the posterior probability <span class="math inline">\(P(\text{cancer} \mid \text{positive mammogram})\)</span>.</p>
<div id="fig-alice-mammogram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alice-mammogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/alice_mammogram_flowchart.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alice-mammogram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Frequency Tree: Medical Diagnosis Scenario (Mammogram).
</figcaption>
</figure>
</div>
<p>Using the frequency tree in <a href="#fig-alice-mammogram" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>, we can see that out of 1000 cases:</p>
<ul>
<li>Number of actual cancer cases = 10.</li>
<li>Number of healthy cases = 990.</li>
</ul>
<p>The test detects 8 out of the 10 cancer cases (True Positives). The test falsely flags 100 out of the 990 healthy cases (False Positives). The total number of positive mammograms is thus <span class="math inline">\(8 + 100 = 108\)</span>. The number of these that are actually cancer is 8. Therefore, the posterior probability is: <span class="math display">\[
P(\text{cancer} \mid \text{positive}) = \frac{8}{108} \approx 0.074.
\]</span> There is only about a 7.4% chance Alice has cancer, despite the positive test result.</p>
</div>
<div id="exm-Apple" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.15 (Apple Watch Series 4 ECG and Bayes’ Theorem)</strong></span> The Apple Watch Series 4 can perform a single-lead ECG and detect atrial fibrillation. The software can correctly identify 98% of cases of atrial fibrillation (true positives) and 99% of cases of non-atrial fibrillation (true negatives) <span class="citation" data-cites="Kim2024ZenicorAF Bumgarner2018AppleWatch">(<a href="references.html#ref-Kim2024ZenicorAF" role="doc-biblioref">Kim et al. 2024</a>; <a href="references.html#ref-Bumgarner2018AppleWatch" role="doc-biblioref">Bumgarner et al. 2018</a>)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 27%">
<col style="width: 31%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Predicted</th>
<th style="text-align: center;">atrial fibrillation</th>
<th style="text-align: center;">no atrial fibrillation</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">atrial fibrillation</td>
<td style="text-align: center;">1960</td>
<td style="text-align: center;">980</td>
<td style="text-align: center;">2940</td>
</tr>
<tr class="even">
<td style="text-align: left;">no atrial fibrillation</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">97020</td>
<td style="text-align: center;">97060</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">2000</td>
<td style="text-align: center;">98000</td>
<td style="text-align: center;">100000</td>
</tr>
</tbody>
</table>
<p>However, what is the probability of a person having atrial fibrillation when atrial fibrillation is identified by the Apple Watch Series 4? We use Bayes’ theorem to answer this question. <span class="math display">\[
P(\text{atrial fibrillation}\mid \text{atrial fibrillation is identified }) = \frac{0.01960}{ 0.02940} = 0.6667
\]</span></p>
<p>The conditional probability of having atrial fibrillation when the Apple Watch Series 4 detects atrial fibrillation is about 67% for this population with 2% prevalence.</p>
<p>However, among younger users (under 55), the prevalence of atrial fibrillation is only about 0.1%. Applying Apple’s own reported figures for the device, 98% sensitivity and 99.6% specificity (slightly higher than the 99% used in the table above), to this group, a Bayesian analysis by <span class="citation" data-cites="yazdi2019apple">Yazdi (<a href="references.html#ref-yazdi2019apple" role="doc-biblioref">2019</a>)</span> finds the positive predictive value falls to about 19.6%, meaning the app incorrectly flags atrial fibrillation about 80% of the time. This group constitutes the majority of wearable device users. The calculation illustrates how dramatically the base rate (prevalence) affects the PPV, even when sensitivity and specificity are high.</p>
<p>The electrocardiogram app becomes more reliable in older individuals: the same analysis gives a positive predictive value of 76 percent among users between the ages of 60 and 64, 91 percent among those aged 70 to 74, and 96 percent for those older than 85.</p>
<p>In the case of medical diagnostics, the sensitivity is the ratio of people who have the disease and tested positive to the total number of positive cases in the population <span class="math display">\[
P(T=1\mid D=1) = \dfrac{P(T=1,D=1)}{P(D=1)} = 0.0196/0.02 = 0.98
\]</span> The specificity is given by <span class="math display">\[
P(T=0\mid D=0) = \dfrac{P(T=0,D=0)}{P(D=0)} = 0.9702/0.98 = 0.99.
\]</span> As we see, the test is highly sensitive and specific. However, only 66% of those who are tested positive will have the disease. This is due to the fact that the number of sick people is much less than the number of healthy and presence of type I error.</p>
</div>
</section>
</section>
<section id="advanced-applications" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="advanced-applications"><span class="header-section-number">2.6</span> Advanced Applications</h2>
<div id="exm-election" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.16 (Obama Elections)</strong></span> This example demonstrates a Bayesian approach to election forecasting using polling data from the 2012 US presidential election. The goal is to predict the probability of Barack Obama winning the election by combining polling data across different states.</p>
<p>The data used includes polling data from various pollsters across all 50 states plus DC. Each state has polling percentages for Republican (GOP) and Democratic (Dem) candidates along with their electoral vote counts. The data are aggregated by state, taking the most recent polls available.</p>
<p>The techniques applied involve Bayesian simulation using a Dirichlet distribution to model uncertainty in polling percentages.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Dirichlet Distribution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Dirichlet distribution is a distribution <em>over probabilities</em>. For a <span class="math inline">\(K\)</span>-dimensional vector <span class="math inline">\(\mathbf{x} = (x_1, \ldots, x_K)\)</span> such that <span class="math inline">\(\sum_{i=1}^K x_i = 1\)</span> and <span class="math inline">\(x_i \ge 0\)</span>, the probability density function is: <span class="math display">\[
f(\mathbf{x}; \boldsymbol{\alpha}) = \frac{1}{B(\boldsymbol{\alpha})} \prod_{i=1}^K x_i^{\alpha_i - 1}
\]</span> where <span class="math inline">\(\boldsymbol{\alpha} = (\alpha_1, \ldots, \alpha_K)\)</span> are positive parameters and <span class="math inline">\(B(\boldsymbol{\alpha}) = \frac{\prod_{i=1}^K \Gamma(\alpha_i)}{\Gamma(\sum_{i=1}^K \alpha_i)}\)</span> is the multivariate Beta function. It is used here to sample possible election results (Obama, Romney, Others) that always sum to 100%.</p>
</div>
</div>
<p>Monte Carlo simulation runs 10,000 simulations of the election to estimate win probabilities. The analysis is conducted state-by-state, calculating Obama’s probability of winning each individual state. Electoral college modeling combines state probabilities with electoral vote counts to determine the overall election outcome. The simulation runs the entire election multiple times to account for uncertainty and determines the likelihood of Obama reaching the required 270 electoral votes to win. This approach demonstrates how pattern matching through statistical modeling can be used for prediction, showing how polling data can be transformed into probabilistic forecasts of election outcomes.</p>
<p>We start by loading the data and aggregating it by state. We then run the simulation and plot probabilities by state.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2" data-tbl-cap="Election 2012 Data (first 5 states and last 5 states)." data-layout-align="center" data-null_prefix="true">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">state</th>
<th style="text-align: right;">R.pct</th>
<th style="text-align: right;">O.pct</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alaska</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arizona</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">California</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">55</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">state</th>
<th style="text-align: right;">R.pct</th>
<th style="text-align: right;">O.pct</th>
<th style="text-align: right;">EV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">47</td>
<td style="text-align: left;">Virginia</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">48</td>
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">42</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">49</td>
<td style="text-align: left;">West Virginia</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">50</td>
<td style="text-align: left;">Wisconsin</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">51</td>
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p>Election 2012 Data (first 5 states and last 5 states).</p>
</div>
</div>
</div>
<p>We then plot the probabilities of Obama winning by state.</p>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-bayes_files/figure-html/obama-map-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Probabilities of Obama winning by state.</figcaption>
</figure>
</div>
</div>
</div>
<p>We use those probabilities to simulate the probability of Obama winning the election. First, we calculate the probability of Obama having 270 EV or more</p>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">87</span>) <span class="co"># Crosby</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sim.election <span class="ot">&lt;-</span> <span class="cf">function</span>(win.probs) {</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  winner <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">51</span>, <span class="dv">1</span>, win.probs<span class="sc">$</span>Obama)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(win.probs<span class="sc">$</span>EV <span class="sc">*</span> winner)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>sim.EV <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">10000</span>, <span class="fu">sim.election</span>(win.probs))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>oprob <span class="ot">&lt;-</span> <span class="fu">sum</span>(sim.EV <span class="sc">&gt;=</span> <span class="dv">270</span>) <span class="sc">/</span> <span class="fu">length</span>(sim.EV)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>oprob</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="do">## 0.96</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="cell-output-display">
<div id="fig-election-ev" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-election-ev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-bayes_files/figure-html/fig-election-ev-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-election-ev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Simulated electoral college results from recent state polls in the 2012 United States Presidential Election between Barack Obama and Mitt Romney.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The analysis of the 2012 U.S. Presidential Election data reveals several key insights about the predictive power of state-level polling and the uncertainty inherent in electoral forecasting. The actual result of 332 electoral votes falls within the simulated range, demonstrating the model’s validity. The 270-vote threshold needed to win the presidency is clearly marked and serves as a critical reference point.</p>
<p>We used a relatively simple model to simulate the election outcome. The model uses Dirichlet distributions to capture uncertainty in state-level polling percentages. Obama’s win probabilities vary significantly across states, reflecting the competitive nature of the election. The simulation approach accounts for both sampling uncertainty and the discrete nature of electoral vote allocation. <a href="#fig-election-ev" class="quarto-xref">Figure&nbsp;<span>2.3</span></a> shows the distribution of possible outcomes. The actual Obama total of 332 electoral votes is marked and falls within the reasonable range of simulated outcomes. This validates the probabilistic approach to election forecasting.</p>
<p>This analysis demonstrates how Bayesian methods can be effectively applied to complex prediction problems with multiple sources of uncertainty, providing both point estimates and uncertainty around those estimates.</p>
</div>
</section>
<section id="graphical-representation-of-conditional-independence" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="graphical-representation-of-conditional-independence"><span class="header-section-number">2.7</span> Graphical Representation of Conditional Independence</h2>
<!-- https://cedar.buffalo.edu/~srihari/CSE674/Chap3/3.6-ConditionalIndependence.pdf -->
<p>We can use the telescoping property of conditional probabilities to write the joint probability distribution as a product of conditional probabilities. This is the essence of the chain rule of probability. It is given by <span class="math display">\[
P(x_1, x_2, \ldots, x_n) = P(x_1)P(x_2 \mid x_1)P(x_3 \mid x_1, x_2) \ldots P(x_n \mid x_1, x_2, \ldots, x_{n-1}).
\]</span> The expression on the right-hand side can be simplified if some of the variables are conditionally independent. For example, if <span class="math inline">\(x_3\)</span> is conditionally independent of <span class="math inline">\(x_2\)</span>, given <span class="math inline">\(x_1\)</span>, then we can write <span class="math display">\[
P(x_3 \mid x_1, x_2) =P(x_3 \mid x_1).
\]</span></p>
<p>In a high-dimensional case, when we have a joint distribution over a large number of random variables, we can often simplify the expression by using independence or conditional independence assumptions. Sometimes it is convenient to represent these assumptions in a graphical form. This is the idea behind the concept of a Bayesian network. Essentially, the graph is a compact representation of a set of independencies that hold in the distribution.</p>
<p>Let’s consider an example of a joint distribution with three random variables; we have the following joint distribution: <span class="math display">\[
P(a,b,c) = P(a\mid b,c)P(b\mid c)P(c)
\]</span></p>
<p>Graphically, we can represent the relations between the variables known as a Directed Acyclic Graph (DAG), which is known as a Bayesian network. Each node represents a random variable and the arrows represent the conditional dependencies between the variables. When two nodes are connected, they are not independent. Consider the following three cases:</p>
<div class="quarto-layout-panel" data-layout-ncol="2" data-layout-align="center">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="fig/bayes-net-Page-3.drawio.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><span class="math display">\[
P(b\mid c,a) = P(b\mid c),~ P(a,b,c) = P(a)P(c\mid a)P(b\mid c)
\]</span></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p>Line Structure</p>
</div>
</div>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2" data-layout-align="center">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="fig/bayes-net-Page-1.drawio.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><span class="math display">\[
P(a\mid b,c) = P(a\mid c), ~ P(a,b,c) = P(a\mid c)P(b\mid c)P(c)
\]</span></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p>Lambda Structure</p>
</div>
</div>
</div>
<div class="quarto-layout-panel" data-layout-ncol="2" data-layout-align="center">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="fig/bayes-net-Page-5.drawio.svg" class="img-fluid"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><span class="math display">\[
P(a\mid b) = P(a),~ P(a,b,c) = P(c\mid a,b)P(a)P(b)
\]</span></p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p>V-structure</p>
</div>
</div>
</div>
<p>Although the graph shows us the conditional independence assumptions, we can also derive other independencies from the graph. An interesting question is whether they are connected through a third node. In the first case (a), we have <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> connected through <span class="math inline">\(c\)</span>. Thus, <span class="math inline">\(a\)</span> can influence <span class="math inline">\(b\)</span>. However, once <span class="math inline">\(c\)</span> is known, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are independent. In case (b), the logic here is similar: <span class="math inline">\(a\)</span> can influence <span class="math inline">\(b\)</span> through <span class="math inline">\(c\)</span>, but once <span class="math inline">\(c\)</span> is known, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are independent. In the third case (c), <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are independent, but once <span class="math inline">\(c\)</span> is known, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are not independent. You can formally derive these independencies from the graph by comparing <span class="math inline">\(P(a,b\mid c)\)</span> and <span class="math inline">\(P(a\mid c)P(b\mid c)\)</span>.</p>
<div id="exm-alarm" class="theorem example">
<p><span class="theorem-title"><strong>Example 2.17 (Bayes Home Diagnostics)</strong></span> Suppose that a house alarm system sends me a text notification when some motion inside my house is detected. It detects motion when I have a person inside (burglar) or during an earthquake. Say, from prior data we know that during an earthquake the alarm is triggered in 10% of the cases. Once I receive a text message, I start driving back home. While driving, I hear on the radio about a small earthquake in our area. Now we want to know <span class="math inline">\(P(b \mid a)\)</span> and <span class="math inline">\(P(b \mid a,r)\)</span>. Here <span class="math inline">\(b\)</span> = burglary, <span class="math inline">\(e\)</span> = earthquake, <span class="math inline">\(a\)</span> = alarm, and <span class="math inline">\(r\)</span> = radio message about small earthquake.</p>
<p>The joint distribution is then given by <span class="math display">\[
  P(b,e,a,r) = P(r \mid a,b,e)P(a \mid b,e)P(b\mid e)P(e).
\]</span> Since we know the causal relations, we can simplify this expression <span class="math display">\[
P(b,e,a,r) = P(r \mid e)P(a \mid b,e)P(b)P(e).
\]</span> The <span class="math inline">\(P(a \mid b,e)\)</span> distribution is defined by</p>
<div id="tbl-alarm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-alarm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Conditional probability of alarm given burglary and earthquake.
</figcaption>
<div aria-describedby="tbl-alarm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(P(a=1 \mid b,e)\)</span></th>
<th style="text-align: center;">b</th>
<th style="text-align: center;">e</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Graphically, we can represent the relations between the variables known as a Directed Acyclic Graph (DAG), which is known as a Bayesian network.</p>
<div id="fig-bayes-net" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bayes-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/bayes-net.png" class="img-fluid figure-img" style="width:20.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bayes-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Bayesian network for alarm.
</figcaption>
</figure>
</div>
<p>Now we can easily calculate <span class="math inline">\(P(a=0 \mid b,e)\)</span> from the property of a probability distribution <span class="math inline">\(P(a=1 \mid b,e) + P(a=0 \mid b,e) = 1\)</span>. In addition, we are given <span class="math inline">\(P(r=1 \mid e=1) = 0.5\)</span> and <span class="math inline">\(P(r=1 \mid e=0) = 0\)</span>. Further, based on historic data, we have <span class="math inline">\(P(b) = 2\cdot10^{-4}\)</span> and <span class="math inline">\(P(e) = 10^{-2}\)</span>. Note that causal relations allowed us to have a more compact representation of the joint probability distribution. The original naive representation requires specifying <span class="math inline">\(2^4 - 1 = 15\)</span> parameters.</p>
<p>To answer our original question, calculate <span class="math display">\[
P(b \mid a) = \dfrac{P(a \mid b)P(b)}{P(a)},~~P(a) = P(a=1 \mid b=1)P(b=1) + P(a=1 \mid b=0)P(b=0).
\]</span> We have everything but <span class="math inline">\(P(a \mid b)\)</span>. This is obtained by marginalizing <span class="math inline">\(P(a=1 \mid b,e)\)</span> to yield <span class="math display">\[
P(a \mid b) = P(a \mid b,e=1)P(e=1) + P(a \mid b,e=0)P(e=0).
\]</span> We can calculate <span class="math display">\[
P(a=1 \mid b=1) = 1, ~P(a=1 \mid b=0) = 0.1*10^{-2} + 0 = 10^{-3}.
\]</span> This leads to <span class="math inline">\(P(b \mid a) = 2\cdot10^{-4}/(2\cdot10^{-4} + 10^{-3}(1-2\cdot10^{-4})) = 1/6\)</span>.</p>
<p>This result is somewhat counterintuitive. We get such a low probability of burglary because its prior is very low compared to the prior probability of an earthquake. What will happen to the posterior if we live in an area with higher crime rates, say <span class="math inline">\(P(b) = 10^{-3}\)</span>. <a href="#fig-alarm" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> shows the relationship between the prior and posterior. <span class="math display">\[
P(b \mid a) = \dfrac{P(b)}{P(b) + 10^{-3}(1-P(b))}
\]</span></p>
<div class="cell" data-layout-align="center" data-null_prefix="true">
<div class="cell-output-display">
<div id="fig-alarm" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alarm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="02-bayes_files/figure-html/fig-alarm-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alarm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Relationship between the prior and posterior.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now, suppose that you hear on the radio about a small earthquake while driving. Then, using Bayesian conditioning, <span class="math display">\[
P(b=1 \mid a=1,r=1) =  \dfrac{P(a,r  \mid  b)P(b)}{P(a,r)}
\]</span> and <span class="math display">\[
P(a,r  \mid  b)P(b) = \dfrac{\sum_e P(b=1,e,a=1,r=1)}{\sum_b\sum_eP(b,e,a=1,r=1)}
\]</span> <span class="math display">\[
=\dfrac{\sum_eP(r=1 \mid e)P(a=1 \mid b=1,e)P(b=1)P(e)}{\sum_b\sum_eP(r=1 \mid e)P(a=1 \mid b,e)P(b)P(e)}
\]</span> which is <span class="math inline">\(\approx 0.2\%\)</span> in our case. This effect is called <em>explaining away</em>, namely when new information explains some previously known fact.</p>
</div>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<section id="pen-and-pencil" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="pen-and-pencil">Pen-and-Pencil</h3>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.1 (Manchester)</strong></span> While watching a game of Champions League football in a cafe, you observe someone who is clearly supporting Manchester United in the game. What is the probability that they were actually born within 20 miles of Manchester? Assume that you have the following base rate probabilities</p>
<ol type="a">
<li>The probability that a randomly selected person in a typical local bar environment is born within 20 miles of Manchester is 1/20</li>
<li>The chance that a person born within 20 miles of Manchester actually supports United is 7/10</li>
<li>The probability that a person not born within 20 miles of Manchester supports United with probability 1/10</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.2 (Lung Cancer)</strong></span> According to the Center for Disease Control (CDC), we know that “compared to nonsmokers, men who smoke are about <span class="math inline">\(23\)</span> times more likely to develop lung cancer and women who smoke are about <span class="math inline">\(13\)</span> times more likely” You are also given the information that <span class="math inline">\(17.9\)</span>% of women in 2016 smoke.</p>
<p>If you learn that a woman has been diagnosed with lung cancer, and you know nothing else, what’s the probability she is a smoker?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.3 (Tesla Chip)</strong></span> Tesla purchases a particular chip called the <em>HW 5.0 auto chip</em> from three suppliers: Matsushita Electric, Philips Electronics, and Hitachi. From historical experience, we know that 30% of the chips are purchased from Matsushita; 20% from Philips and the remaining 50% from Hitachi. The manufacturer has extensive histories on the reliability of the chips. We know that 3% of the Matsushita chips are defective; 5% of the Philips and 4% of the Hitachi chips are defective.</p>
<p>A chip is later found to be defective; what is the probability it was manufactured by each of the manufacturers?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.4 (Light Aircraft)</strong></span> Seventy percent of the light aircraft that disappear while in flight in a certain country are subsequently discovered. Of the aircraft that are discovered, 60% have an emergency locator, whereas 90% of the aircraft not discovered do not have such a locator. Suppose that a light aircraft has disappeared. If it has an emergency locator, what is the probability that it will be discovered?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.5 (Floyd Landis)</strong></span> Floyd Landis was disqualified after winning the 2006 Tour de France. This was due to a urine sample that the French national anti-doping laboratory flagged after Landis had won stage <span class="math inline">\(17\)</span> because it showed a high ratio of testosterone to epitestosterone. Because he was among the leaders, he provided <span class="math inline">\(8\)</span> pairs of urine samples—so there were <span class="math inline">\(8\)</span> opportunities for a true positive and <span class="math inline">\(8\)</span> opportunities for a false positive.</p>
<ol type="a">
<li>Assume that the test has a specificity of <span class="math inline">\(95\)</span>%. What’s the probability of all <span class="math inline">\(8\)</span> samples being labeled “negative”?</li>
<li>Now assume the specificity is <span class="math inline">\(99\)</span>%. What’s the false positive rate for the test</li>
<li>Based on these data, explain how you would assess the probability of guilt of Landis in a court hearing.</li>
</ol>
</div>
<div id="exr-forensic-match-odds" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.6 (Forensic Match: The Odds Form of Bayes’ Rule)</strong></span> A crime-scene hair sample is compared to a suspect’s hair using a forensic matching procedure. Validation studies show the procedure returns a “match” (<span class="math inline">\(E\)</span>) with probability <span class="math inline">\(P(E \mid G) = 0.90\)</span> when the suspect really is the source (guilty, <span class="math inline">\(G\)</span>), and with probability <span class="math inline">\(P(E \mid \neg G) = 0.02\)</span> when the suspect is not the source (innocent). Before any forensic evidence is considered, detectives judge from other circumstances that the suspect has a 1-in-200 chance of being guilty.</p>
<p>Work this problem in the odds form of Bayes’ rule, <span class="math inline">\(O(G \mid E) = BF \times O(G)\)</span>, introduced in this chapter.</p>
<ol type="a">
<li>Compute the Bayes factor <span class="math inline">\(BF = P(E \mid G) / P(E \mid \neg G)\)</span> and state in words how many times more likely a match is under guilt than under innocence.</li>
<li>Convert the prior probability of guilt into prior odds <span class="math inline">\(O(G) = P(G)/P(\neg G)\)</span>.</li>
<li>Use the odds form to find the posterior odds of guilt given the match.</li>
<li>Convert the posterior odds back into a posterior probability <span class="math inline">\(P(G \mid E)\)</span>.</li>
<li>Check your answer to (d) against the direct probability form, <span class="math display">\[
P(G \mid E) = \frac{P(E \mid G)P(G)}{P(E \mid G)P(G) + P(E \mid \neg G)P(\neg G)},
\]</span> and confirm the two forms agree.</li>
<li>A second, conditionally independent piece of evidence, an eyewitness identification, carries its own Bayes factor of <span class="math inline">\(3\)</span> in favor of guilt. Starting from the posterior odds in (c), update once more to find <span class="math inline">\(O(G \mid E_1, E_2)\)</span> and the corresponding posterior probability <span class="math inline">\(P(G \mid E_1, E_2)\)</span>.</li>
<li>Even combining both pieces of evidence, is the posterior probability of guilt high enough to convict “beyond a reasonable doubt”? Relate your answer to the reasoning in the Prosecutor’s Fallacy (<a href="#exm-prosecutors-fallacy" class="quarto-xref">Example&nbsp;<span>2.8</span></a>), the Island Problem (<a href="#exm-island" class="quarto-xref">Example&nbsp;<span>2.9</span></a>), and the Nakamura case (<a href="#exm-nakamura" class="quarto-xref">Example&nbsp;<span>2.10</span></a>), and explain why the odds form is especially convenient once there is more than one piece of evidence to combine.</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.7 (BRCA1)</strong></span> Approximately <span class="math inline">\(1\)</span>% of woman aged 40–50 have breast cancer. A woman with breast cancer has a <span class="math inline">\(90\)</span>% chance of a positive mammogram test and a <span class="math inline">\(10\)</span>% chance of a false positive result. Given that someone has a positive test, what’s the posterior probability that they have breast cancer?</p>
<p>If you have the BRCA1 gene mutation, you have a <span class="math inline">\(90\)</span>% chance of developing breast cancer. The prevalence of mutations at BRCA1 has been estimated to be 0.04%–0.200.20% in the general population. The genetic test for a mutation of this gene has a <span class="math inline">\(99.9\)</span>% chance of finding the mutation. The false positive rate is unknown, but you are willing to assume it’s still <span class="math inline">\(10\)</span>%.</p>
<p>Given that someone tests positive for the BRCA1 mutation, what’s the posterior probability that they have breast cancer?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.8 (Another Cancer Test)</strong></span> Bayes is particularly useful when predicting outcomes that depend strongly on prior knowledge.</p>
<p>Suppose that a woman is her forties takes a mammogram test and receives the bad news of a positive outcome. Since not every positive outcome is real, you assess the following probabilities. The base rate for a woman is her forties to have breast cancer is <span class="math inline">\(1.4\)</span>%. The probability of a positive test given breast cancer is <span class="math inline">\(75\)</span>%, and the probability of a false positive is <span class="math inline">\(10\)</span>%.</p>
<p>Given the positive test, what’s the probability that she has breast cancer?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.9 (Bayes’ Rule: Hit and Run Taxi)</strong></span> A certain town has two taxi companies: Blue Birds, whose cabs are blue, and Uber, whose cabs are black. Blue Birds has 15 taxis in its fleet, and Uber has 75. Late one night, there is a hit-and-run accident involving a taxi.</p>
<p>The town’s taxis were all on the streets at the time of the accident. A witness saw the accident and claims that a blue taxi was involved. The witness undergoes a vision test under conditions similar to those on the night in question. Presented repeatedly with a blue taxi and a black taxi, in random order, they successfully identify the color of the taxi 4 times out of 5.</p>
<p>Which company is more likely to have been involved in the accident?</p>
</div>
<div id="exr-gold" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.10 (Gold and Silver Coins)</strong></span> A chest has two drawers. It is known that one drawer has <span class="math inline">\(3\)</span> gold coins and no silver coins. The other drawer is known to contain <span class="math inline">\(1\)</span> gold coin and <span class="math inline">\(2\)</span> silver coins.</p>
<p>You don’t know which drawer is which. You randomly select a drawer and, without looking inside, you pull out a coin. It is gold. Show that the probability that the remaining two coins in the drawer are gold is <span class="math inline">\(75\)</span>%.</p>
</div>
<div id="exr-Monty" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.11 (The Monty Hall Problem)</strong></span> This problem is named after the host of the long-running TV show, <em>Let’s Make a Deal</em>. A contestant is given a choice of 3 doors. There is a prize (a car, say) behind one of the doors and something worthless behind the other two doors (say two goats).</p>
<p>After the contestant chooses a door, Monty opens one of the other two doors, revealing a goat. The contestant has the choice of switching doors. Is it advantageous to switch doors or not?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.12 (Medical Testing for HIV)</strong></span> A controversial issue in recent years has been the possible implementation of random drug and/or disease testing (e.g., testing medical workers for HIV virus, which causes AIDS). In the case of HIV testing, the standard test is the Wellcome ELISA test.</p>
<p>The test’s effectiveness is summarized by the following two attributes:</p>
<ul>
<li>The <em>sensitivity</em> is about 0.993. That is, if someone has HIV, there is a probability of 0.993 that they will test positive.</li>
<li>The <em>specificity</em> is about 0.9999. This means that if someone doesn’t have HIV, there is a probability of 0.9999 that they will test negative.</li>
</ul>
<p>In the general population, incidence of HIV is reasonably rare. It is estimated that the chance that a randomly chosen person has HIV is <span class="math inline">\(0.000025\)</span>.</p>
<p>To investigate the possibility of implementing a random HIV-testing policy with the ELISA test, calculate the following:</p>
<ol type="a">
<li>The probability that someone will test positive and have HIV.</li>
<li>The probability that someone will test positive and not have HIV.</li>
<li>The probability that someone will test positive.</li>
<li>Suppose someone tests positive. What is the probability that they have HIV?</li>
</ol>
<p>In light of the last calculation, do you envision any problems in implementing a random testing policy?</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.13 (The Three Prisoners)</strong></span> An unknown two will be shot, the other freed. Prisoner A asks the warder for the name of one other than himself who will be shot, explaining that as there must be at least one, the warder won’t really be giving anything away. The warder agrees, and says that B will be shot. This cheers A up a little: his judgmental probability for being shot is now 1/2 instead of 2/3.</p>
<p>Show (via Bayes’ theorem) that</p>
<ol type="a">
<li>A is mistaken - assuming that he thinks the warder is as likely to say "C" as "B" when he can honestly say either; but that</li>
<li>A would be right, on the hypothesis that the warder will say "B" whenever he honestly can.</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.14 (The Two Children)</strong></span> You meet Max walking with a boy whom he proudly introduces as his son.</p>
<ol type="a">
<li>What is your probability that his other child is also a boy, if you regard him as equally likely to have taken either child for a walk?</li>
<li>What would the answer be if you regarded him as sure to walk with the boy rather than the girl, if he has one of each?</li>
<li>What would the answer be if you regarded him as sure to walk with the girl rather than the boy, if he has one of each?</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.15 (Medical Exam)</strong></span> As a result of a medical examination, one of the tests revealed a serious illness in a person. This test has a high precision of 99% (the probability of a positive response in the presence of the disease is 99%, the probability of a negative response in the absence of the disease is also 99%). However, the detected disease is quite rare and occurs only in one person per 10,000. Calculate the probability that the person being examined does have an identified disease.</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.16 (The Jury)</strong></span> Assume that the probability is 0.95 that a jury selected to try a criminal case will arrive at the correct verdict whether innocent or guilty. Further, suppose that 80% of people brought to trial are in fact guilty.</p>
<ol type="a">
<li>Given that the jury finds a defendant innocent, what’s the probability that they are in fact innocent?</li>
<li>Given that the jury finds a defendant guilty, what’s the probability that they are in fact guilty?</li>
<li>Do these probabilities sum to one?</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.17 (Oil Company)</strong></span> An oil company has purchased an option on land in Alaska. Preliminary geologic studies have assigned the following probabilities of finding oil <span class="math display">\[
P ( \text{ high   quality   oil} ) = 0.50 \; \;
P ( \text{ medium   quality   oil} ) = 0.20 \; \;
P ( \text{ no   oil} ) = 0.30 \; \;
\]</span> After 200 feet of drilling on the first well, a soil test is taken. The probabilities of finding the particular type of soil identified by the test are as follows: <span class="math display">\[
P ( \text{ soil} \; \mid \; \text{ high   quality   oil} ) = 0.20 \; \;
P ( \text{ soil} \; \mid \; \text{ medium   quality   oil} ) = 0.80 \; \;
P ( \text{ soil} \; \mid \; \text{ no   oil} ) = 0.20 \; \;
\]</span></p>
<ol type="a">
<li>What are the revised probabilities of finding the three different types of oil?</li>
<li>How should the firm interpret the soil test?</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.18 (Hypertension Screening)</strong></span> A screening test for high blood pressure, corresponding to a diastolic blood pressure of <span class="math inline">\(90\)</span> mm Hg or higher, produced the following probability table</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Hypertension</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Test</td>
<td style="text-align: center;">Present</td>
<td>Absent</td>
</tr>
<tr class="even">
<td>+ve</td>
<td style="text-align: center;">0.09</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td>-ve</td>
<td style="text-align: center;">0.03</td>
<td>0.85</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What’s the probability that a random person has hypertension?</li>
<li>What’s the probability that someone tests positive on the test?</li>
<li>Given a person who tests positive, what is the probability that they have hypertension?</li>
<li>What would happen to your probability of having hypertension given you tested positive if you initially thought you had a <span class="math inline">\(50\)</span>% chance of having hypertension.</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.19 (Steroids)</strong></span> Suppose that a hypothetical baseball player (call him “Rafael”) tests positive for steroids. The test has the following sensitivity and specificity</p>
<ol type="a">
<li>If a player is on Steroids, there’s a <span class="math inline">\(95\)</span>% chance of a positive result.</li>
<li>If a player is clean, there’s a <span class="math inline">\(10\)</span>% chance of a positive result.</li>
</ol>
<p>A respected baseball authority (call him “Bud”) claims that <span class="math inline">\(1\)</span>% of all baseball players use Steroids. Another player (call him “Jose”) thinks that there’s a <span class="math inline">\(30\)</span>% chance of all baseball players using Steroids.</p>
<ol type="a">
<li>What’s Bud’s probability that Rafael uses Steroids?</li>
<li>What’s Jose’s probability that Rafael uses Steroids?</li>
</ol>
<p>Explain any probability rules that you use.</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.20 (Breathalyzer Test)</strong></span> A Breathalyzer test is calibrated so that if it is used on a driver whose blood alcohol concentration exceeds the legal limit, it will read positive <span class="math inline">\(99\)</span>% of the time, while if the driver is below the limit it will read negative <span class="math inline">\(90\)</span>% of the time. Suppose that based on prior experience, you have a prior probability that the driver is above the legal limit of <span class="math inline">\(10\)</span>%.</p>
<ol type="a">
<li>If a driver tests positive, what is the posterior probability that they are above the legal limit?</li>
<li>At Christmas, <span class="math inline">\(20\)</span>% of the drivers on the road are above the legal limit. If all drivers were tested, what proportion of those testing positive would actually be above the limit</li>
<li>How does your answer to part <span class="math inline">\(1\)</span> change. Explain</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.21 (Chicago Bearcats)</strong></span> The Chicago bearcats baseball team plays <span class="math inline">\(60\)</span>% of its games at night and <span class="math inline">\(40\)</span>% in the daytime. They win <span class="math inline">\(55\)</span>% of their night games and only <span class="math inline">\(35\)</span>% of their day games. You found out the next day that they won their last game</p>
<ol type="a">
<li>What is the probability that the game was played at night</li>
<li>What is the marginal probability that they will win their next game?</li>
</ol>
<p>Explain clearly any rules of probability that you use.</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.22 (Spam Filter)</strong></span> Several spam filters use Bayes’ rule. Suppose that you empirically find the following probability table for classifying emails with the phrase “buy now” in their title as either “spam” or “not spam”.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Spam</th>
<th style="text-align: center;">Not Spam</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“buy now”</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">0.08</td>
</tr>
<tr class="even">
<td>not “buy now”</td>
<td style="text-align: center;">0.18</td>
<td style="text-align: center;">0.72</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>What is the probability that you will receive an email with spam?</li>
<li>Suppose that you are given a new email with the phrase “buy now” in its title. What is the probability that this new email is spam?</li>
<li>Explain clearly any rules of probability that you use.</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.23 (Chicago Cubs)</strong></span> The Chicago Cubs are having a great season. So far they’ve won <span class="math inline">\(72\)</span> out of the <span class="math inline">\(100\)</span> games played so far. You also have the expert opinion of Bob, the sports analysis. He tells you that he thinks the Cubs will win. Historically, his predictions have a <span class="math inline">\(60\)</span>% chance of coming true.</p>
<ol type="a">
<li>Calculate the probability that the Cubs will win given Bob’s prediction</li>
<li>Suppose you now learn that it’s a home game and that the Cubs win <span class="math inline">\(60\)</span>% of their games at Wrigley field. What’s your updated probability that the Cubs will win their game?</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.24 (Student-Grade Causality)</strong></span> Consider the following probabilistic model. The student does poorly in a class (<span class="math inline">\(c = 1\)</span>) or well (<span class="math inline">\(c = 0\)</span>) depending on the presence/absence of depression (<span class="math inline">\(d = 1\)</span> or <span class="math inline">\(d = 0\)</span>) and whether he/she partied last night (<span class="math inline">\(v = 1\)</span> or <span class="math inline">\(v = 0\)</span>). Participation in the party can also lead to the fact that the student has a headache (<span class="math inline">\(h = 1\)</span>). As a result of the poor student’s performance, the teacher gets upset (<span class="math inline">\(t = 1\)</span>). The probabilities are given by:</p>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(p(c=1\mid d,v)\)</span></th>
<th style="text-align: center;">v</th>
<th style="text-align: center;">d</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.999</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.01</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(p(h=1\mid v)\)</span></th>
<th style="text-align: center;">v</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.9</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(p(t=1\mid c)\)</span></th>
<th style="text-align: center;">c</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.95</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.05</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><span class="math inline">\(p(v=1)=0.2\)</span>, and <span class="math inline">\(p(d=1) = 0.4\)</span>.</p>
<p>Draw the causal relationships in the model. Calculate <span class="math inline">\(p(v=1\mid h=1)\)</span>, <span class="math inline">\(p(v=1\mid t=1)\)</span>, <span class="math inline">\(p(v=1\mid t=1,h=1)\)</span>.</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.25 (True/False)</strong></span> &nbsp;</p>
<ol type="a">
<li>In a sample of <span class="math inline">\(100{,}000\)</span> emails, you found that <span class="math inline">\(550\)</span> are spam. Your next email contains the word “bigger”. From historical experience, you know that half of all spam email contains the word “bigger” and only <span class="math inline">\(2\)</span>% of non-spam emails contain it. The probability that this new email is spam is approximately <span class="math inline">\(12\)</span>%.</li>
<li>Suppose that there’s a <span class="math inline">\(5\)</span>% chance that it snows tomorrow, an <span class="math inline">\(80\)</span>% chance that the Chicago bears play their football game tomorrow given that it snows, and that they are certain to play if it does not snow. The probability that they play tomorrow is then <span class="math inline">\(80\)</span>%.</li>
<li>Bayes’ rule states that <span class="math inline">\(p(A\mid B) =p(B\mid A)\)</span>.</li>
<li>If <span class="math inline">\(P( A  \text{ and }B ) = 0.4\)</span> and <span class="math inline">\(P( B) = 0.8\)</span>, then <span class="math inline">\(P( A\mid B ) = 0.5\)</span>.</li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.26 (Sensitivity and Specificity)</strong></span> The quality of Nvidia’s graphics chips is such that the probability that a randomly chosen chip is defective is only <span class="math inline">\(0.1\)</span>%. You have invented a new technology for testing whether a given chip is defective or not. This test will always identify a defective chip as defective and will only “falsely” identify a good chip as defective with probability <span class="math inline">\(1\)</span>%.</p>
<ol type="a">
<li>What are the sensitivity and specificity of your testing device?</li>
<li>Given that the test identifies a defective chip, what’s the posterior probability that it is actually defective?</li>
<li>What percentage of the chips will the new technology identify as being defective?</li>
<li>Should you advise Nvidia to go ahead and implement your testing device? Explain.</li>
</ol>
</div>
</section>
<section id="computing" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="computing">Computing</h3>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.27 (Presidential Election Prediction)</strong></span> Use polling data to predict the winner of a US presidential election using simulations. You can obtain polling data from sources like <a href="http://www.electoral-vote.com/" class="uri">http://www.electoral-vote.com/</a> or use historical data files (<code>ev.csv</code> for electoral votes, <code>state_abbr.csv</code> for state abbreviations).</p>
<ol type="a">
<li>Load state-level polling averages and electoral vote counts.</li>
<li>Simulate the election 10,000 times, treating each state’s outcome as a random draw from a normal distribution centered at the poll average with a realistic polling error (typically 5-7%).</li>
<li>Report the prediction as a 50% confidence interval for each candidate’s electoral vote count.</li>
<li>Discuss the limitations of assuming independent state-level polling errors.</li>
</ol>
</div>
<div id="exr-naive-bayes-text" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2.28 (Naive Bayes Text Classifier from Scratch)</strong></span> Build a naive Bayes spam filter from scratch, following the same logic as <a href="#exm-naivebayes" class="quarto-xref">Example&nbsp;<span>2.13</span></a>: estimate class priors and per-word likelihoods from a labeled corpus, then combine them through Bayes’ rule to classify new messages. Treating every word in a message as conditionally independent given the class label is exactly the “naive” assumption discussed in the chapter.</p>
<p>Training corpus (6 messages labeled spam, 6 labeled ham):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Spam messages</th>
<th>Ham messages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>win free money now</td>
<td>let us meet for lunch today</td>
</tr>
<tr class="even">
<td>free cash prize claim now</td>
<td>are you free for dinner tonight</td>
</tr>
<tr class="odd">
<td>you win a free prize</td>
<td>can we schedule the meeting today</td>
</tr>
<tr class="even">
<td>claim your free money today</td>
<td>let me know about the project</td>
</tr>
<tr class="odd">
<td>urgent win cash now</td>
<td>meeting agenda for tomorrow project</td>
</tr>
<tr class="even">
<td>free entry win prize now</td>
<td>are we still on for lunch</td>
</tr>
</tbody>
</table>
<p>Held-out test messages, with true labels for scoring accuracy:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Message</th>
<th>True label</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>free money now</td>
<td>spam</td>
</tr>
<tr class="even">
<td>let us schedule dinner</td>
<td>ham</td>
</tr>
<tr class="odd">
<td>win a free prize today</td>
<td>spam</td>
</tr>
<tr class="even">
<td>can you meet for the project meeting</td>
<td>ham</td>
</tr>
<tr class="odd">
<td>claim your prize now</td>
<td>spam</td>
</tr>
<tr class="even">
<td>are you free tomorrow for lunch</td>
<td>ham</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Tokenize each training message on whitespace (after converting to lower case) and build the vocabulary. Estimate the class priors <span class="math inline">\(P(\text{spam})\)</span> and <span class="math inline">\(P(\text{ham})\)</span> from the label proportions, and estimate every per-word likelihood <span class="math inline">\(P(\text{word}\mid \text{spam})\)</span> and <span class="math inline">\(P(\text{word}\mid \text{ham})\)</span> using Laplace (add-one) smoothing, so that no word ever receives zero probability.</li>
<li>For the test message “free money now,” compute the log-posterior <span class="math inline">\(\log P(\text{spam}) + \sum_i \log P(w_i\mid \text{spam})\)</span> and the corresponding quantity for ham explicitly, using your fitted probabilities. Which class wins?</li>
<li>Classify all six held-out test messages using <span class="math inline">\(\arg\max_{c \in \{\text{spam},\text{ham}\}} \left[ \log P(c) + \sum_i \log P(w_i \mid c) \right]\)</span> and report the classifier’s accuracy.</li>
<li>The word “free” appears in both a spam message (“free cash prize claim now”) and a ham message (“are you free for dinner tonight”). Explain why naive Bayes can still classify correctly even though individual words like this one are ambiguous, and give a concrete reason why treating words as conditionally independent given the class is not literally true of English sentences.</li>
<li>(Optional) Cross-check your classifier against <code>e1071::naiveBayes</code> fit on the same data.</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Bumgarner2018AppleWatch" class="csl-entry" role="listitem">
Bumgarner, John M., Chad T. Lambert, Ayman A. Hussein, Daniel J. Cantillon, Bryan Baranowski, Kathy Wolski, Bruce D. Lindsay, Oussama M. Wazni, and Khaldoun G. Tarakji. 2018. <span>“Smartwatch Algorithm for Automated Detection of Atrial Fibrillation.”</span> <em>Journal of the American College of Cardiology</em> 71 (21): 2381–88.
</div>
<div id="ref-Kim2024ZenicorAF" class="csl-entry" role="listitem">
Kim, Young-Hoon, Jaehyung Shim, Hyoung-Seob Park, et al. 2024. <span>“<a href="https://www.ncbi.nlm.nih.gov/pubmed/38412780">Diagnostic Accuracy of Single-Lead Handheld <span>ECG</span> Devices for Atrial Fibrillation Detection</a>.”</span> <em>Journal of Cardiovascular Electrophysiology</em> 35: 614–21.
</div>
<div id="ref-maharaj2023kramnik" class="csl-entry" role="listitem">
Maharaj, Shiva, Nicholas G. Polson, and Vadim Sokolov. 2023. <span>“Kramnik Vs <span>Nakamura</span> or <span>Bayes</span> Vs <span>P-Value</span>.”</span> {{SSRN Scholarly Paper}}. Rochester, NY.
</div>
<div id="ref-simpson2010edward" class="csl-entry" role="listitem">
Simpson, Edward. 2010. <span>“Edward <span>Simpson</span>: <span>Bayes</span> at <span>Bletchley Park</span>.”</span> <em>Significance</em> 7 (2): 76–80.
</div>
<div id="ref-yazdi2019apple" class="csl-entry" role="listitem">
Yazdi, Daniel. 2019. <span>“The <span>Apple Watch</span> 4 Is an Iffy Atrial Fibrillation Detector in Those Under Age 55.”</span> <em>STAT News</em>. <a href="https://www.statnews.com/2019/01/08/apple-watch-iffy-atrial-fibrillation-detector/">https://www.statnews.com/2019/01/08/apple-watch-iffy-atrial-fibrillation-detector/</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./01-prob.html" class="pagination-link" aria-label="Probability and Uncertainty">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability and Uncertainty</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-bl.html" class="pagination-link" aria-label="Bayesian Learning">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bayesian Learning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>