<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Bayesian Hypothesis Testing – Bayes, AI and Deep Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-sp.html" rel="next">
<link href="./05-ab.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-680e7c22d93ef26f016bec9199f8e6d8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
  // Load MathJax with custom macros
  window.MathJax = {
    tex: {
      macros: {
        Cov: ["\\mathrm{Cov}\\left(#1\\right)", 1],
        Cor: ["\\mathrm{Cor}\\left(#1\\right)", 1],
        Var: ["\\mathrm{Var}\\left(#1\\right)", 1],
        sd: ["\\mathrm{sd}\\left(#1\\right)", 1],
        E: ["\\mathrm{E}_{#1}\\left(#2\\right)", 2, ""],
        prob: ["\\mathrm{P}\\left(#1\\right)", 1],
        defeq: "\\stackrel{\\mathrm{def}}{=}",
        mini: "\\operatorname*{minimize}"
      }
    }
  };
</script>

<style>
  /* Custom styling for math content */
  .MathJax {
    font-size: 1em !important;
  }
  
  /* Ensure consistent math rendering */
  mjx-container[jax="CHTML"] {
    line-height: 1.2;
  }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="6&nbsp; Bayesian Hypothesis Testing – Bayes, AI and Deep Learning">
<meta property="og:description" content="">
<meta property="og:image" content="06-hyp_files/figure-html/unnamed-chunk-1-1.png">
<meta property="og:site_name" content="Bayes, AI and Deep Learning">
<meta name="twitter:title" content="6&nbsp; Bayesian Hypothesis Testing – Bayes, AI and Deep Learning">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="06-hyp_files/figure-html/unnamed-chunk-1-1.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-prob.html">Bayes</a></li><li class="breadcrumb-item"><a href="./06-hyp.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Hypothesis Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bayes, AI and Deep Learning</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Modern AI Playbook</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-prob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Probability and Uncertainty</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bayes Rule</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-bl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bayesian Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-dec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Utility, Risk and Decisions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">AB Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-hyp.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Hypothesis Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-gp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Gaussian Processes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-rl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Reinforcement Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">AI</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Unreasonable Effectiveness of Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-pattern.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Pattern Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Linear Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-tree.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Tree Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Forecasting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-rct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Randomized Controlled Trials</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-select.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-theoryai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Theory of AI: From MLE to Bayesian Regularization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-nn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-theorydl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Theory of Deep Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-sgd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Gradient Descent</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-qnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Quantile Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Natural Language Processing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-llm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Large Language Models: A Revolution in AI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-robots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">AI Agents</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Exercises</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#likelihood-principle" id="toc-likelihood-principle" class="nav-link active" data-scroll-target="#likelihood-principle"><span class="header-section-number">6.1</span> Likelihood Principle</a></li>
  <li><a href="#the-bayesian-approach" id="toc-the-bayesian-approach" class="nav-link" data-scroll-target="#the-bayesian-approach"><span class="header-section-number">6.2</span> The Bayesian Approach</a></li>
  <li><a href="#interval-estimation-credible-sets" id="toc-interval-estimation-credible-sets" class="nav-link" data-scroll-target="#interval-estimation-credible-sets"><span class="header-section-number">6.3</span> Interval Estimation: Credible Sets</a></li>
  <li><a href="#alternative-approaches" id="toc-alternative-approaches" class="nav-link" data-scroll-target="#alternative-approaches"><span class="header-section-number">6.4</span> Alternative Approaches</a>
  <ul class="collapse">
  <li><a href="#significance-testing-using-p-values" id="toc-significance-testing-using-p-values" class="nav-link" data-scroll-target="#significance-testing-using-p-values">Significance testing using p-values</a></li>
  <li><a href="#neyman-pearson" id="toc-neyman-pearson" class="nav-link" data-scroll-target="#neyman-pearson">Neyman-Pearson</a></li>
  </ul></li>
  <li><a href="#examples-and-paradoxes" id="toc-examples-and-paradoxes" class="nav-link" data-scroll-target="#examples-and-paradoxes"><span class="header-section-number">6.5</span> Examples and Paradoxes</a></li>
  <li><a href="#prior-sensitivity" id="toc-prior-sensitivity" class="nav-link" data-scroll-target="#prior-sensitivity"><span class="header-section-number">6.6</span> Prior Sensitivity</a></li>
  <li><a href="#model-elaboration-and-nested-model-testing" id="toc-model-elaboration-and-nested-model-testing" class="nav-link" data-scroll-target="#model-elaboration-and-nested-model-testing"><span class="header-section-number">6.7</span> Model Elaboration and Nested Model Testing</a>
  <ul class="collapse">
  <li><a href="#the-dickey-savage-approach-to-nested-models" id="toc-the-dickey-savage-approach-to-nested-models" class="nav-link" data-scroll-target="#the-dickey-savage-approach-to-nested-models">The Dickey-Savage Approach to Nested Models</a></li>
  </ul></li>
  <li><a href="#the-difference-between-p-values-and-bayesian-evidence" id="toc-the-difference-between-p-values-and-bayesian-evidence" class="nav-link" data-scroll-target="#the-difference-between-p-values-and-bayesian-evidence"><span class="header-section-number">6.8</span> The difference between p-values and Bayesian evidence</a></li>
  <li><a href="#jeffreys-decision-rule" id="toc-jeffreys-decision-rule" class="nav-link" data-scroll-target="#jeffreys-decision-rule"><span class="header-section-number">6.9</span> Jeffreys’ Decision Rule</a></li>
  <li><a href="#cromwells-rule" id="toc-cromwells-rule" class="nav-link" data-scroll-target="#cromwells-rule"><span class="header-section-number">6.10</span> Cromwell’s Rule</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01-prob.html">Bayes</a></li><li class="breadcrumb-item"><a href="./06-hyp.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Hypothesis Testing</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Bayesian Hypothesis Testing</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The hypothesis testing problem is as follows. Based on a sample of data, <span class="math inline">\(y\)</span>, generated from <span class="math inline">\(p\left( y \mid \theta\right)\)</span> for <span class="math inline">\(\theta\in\Theta\)</span>, the goal is to determine if <span class="math inline">\(\theta\)</span> lies in <span class="math inline">\(\Theta_{0}\)</span> or in <span class="math inline">\(\Theta_{1}\)</span>, two disjoint subsets of <span class="math inline">\(\Theta\)</span>. In general, the hypothesis testing problem involves an action: accepting or rejecting a hypothesis. The problem is described in terms of a null, <span class="math inline">\(H_{0}\)</span>, and alternative hypothesis, <span class="math inline">\(H_{1}\)</span>, which are defined as <span class="math display">\[
H_{0}:\theta\in\Theta_{0}\;\;\mathrm{and}\;\;H_{1}%
:\theta\in\Theta_{1}\text{.}%
\]</span></p>
<p>Different types of regions generate different types of hypothesis tests. If the null hypothesis assumes that <span class="math inline">\(\Theta_{0}\)</span> is a single point, <span class="math inline">\(\Theta _{0}=\theta_{0}\)</span>, this is known as a simple or “sharp” null hypothesis. If the region consists of multiple points, the hypothesis is called composite; this occurs when the space is unconstrained or corresponds to an interval of the real line. In the case of a single parameter, typical one-sided tests are of the form <span class="math inline">\(H_{0}:\theta&lt;\theta_{0}\)</span> and <span class="math inline">\(H_{1}:\theta&gt;\theta_{0}\)</span>.</p>
<p>There are two correct decisions and two possible types of errors. The correct decisions are accepting a null or an alternative that is true, whereas a Type I error incorrectly rejects a true null and a Type II error incorrectly accepts a false null.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\theta\in\Theta_{0}\)</span></th>
<th><span class="math inline">\(\theta\in\Theta_{1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accept <span class="math inline">\(H_{0}\)</span></td>
<td>Correct decision</td>
<td>Type II error</td>
</tr>
<tr class="even">
<td>Accept <span class="math inline">\(H_{1}\)</span></td>
<td>Type I error</td>
<td>Correct decision</td>
</tr>
</tbody>
</table>
<p>Formally, the probabilities of Type I (<span class="math inline">\(\alpha\)</span>) and Type II (<span class="math inline">\(\beta\)</span>) errors are defined as: <span class="math display">\[
\alpha=P \left[  \text{reject }H_{0} \mid H_{0}\text{
is true }\right]  \text{ and }\beta=P \left[  \text{accept
}H_{0} \mid H_{1}\text{ is true }\right]  \text{.}%
\]</span></p>
<p>It is useful to think of the decision to accept or reject as a decision rule, <span class="math inline">\(d\left( y\right)\)</span>. In many cases, the decision rules form a critical region <span class="math inline">\(R\)</span>, such that <span class="math inline">\(d\left( y\right) =d_{1}\)</span> if <span class="math inline">\(y\in R\)</span>. These regions often take the form of simple inequalities. Next, defining the decision to accept the null as <span class="math inline">\(d\left( y\right) =d_{0}\)</span>, and the decision to accept the alternative as <span class="math inline">\(d_{1},\)</span> the error types are <span class="math display">\[\begin{align*}
\alpha_{\theta}\left(  d\right)   &amp;  =P \left[  d\left(  y\right)
=d_{1} \mid \theta\right]  \text{ if }\theta\in\Theta_{0}\text{ }(H_{0}\text{ is true})\\
\beta_{\theta}\left(  d\right)   &amp;  =P \left[  d\left(  y\right)
=d_{0} \mid \theta\right]  \text{ if }\theta\in\Theta_{1}\text{ }(H_{1}\text{ is true})\text{.}%
\end{align*}\]</span> where both types of errors explicitly depend on the decision and the true parameter value. Notice that both of these quantities are determined by the population properties of the data. In the case of a composite null hypothesis, the size of the test (the probability of making a type I error) is defined as <span class="math display">\[
\alpha = \underset{\theta\in\Theta_{0}}{\sup}~\alpha_{\theta}\left( d\right)
\]</span> and the power is defined as <span class="math inline">\(1-\beta_{\theta}\left( d\right)\)</span>. It is always possible to set either <span class="math inline">\(\alpha_{\theta}\left( d\right)\)</span> or <span class="math inline">\(\beta_{\theta }\left( d\right)\)</span> equal to zero, by finding a test that always rejects the alternative or null, respectively.</p>
<p>The total probability of making an error is <span class="math inline">\(\alpha_{\theta}\left(d\right) +\beta_{\theta}\left(d\right)\)</span>, and ideally one would seek to minimize the total error probability, absent additional information. The optimal action <span class="math inline">\(d^*\)</span> minimizes the posterior expected loss; <span class="math inline">\(d^* = d_0 = 0\)</span> if the posterior probability of hypothesis <span class="math inline">\(H_0\)</span> exceeds 1/2, and <span class="math inline">\(d^* = d_1=1\)</span> otherwise <span class="math display">\[
d^* = 1\left(  P \left(  \theta \in \Theta_0 \mid y\right) &lt; P \left(  \theta \in \Theta_1 \mid y\right)\right)  = 1\left(P \left(  \theta \in \Theta_0 \mid y\right)&lt;1/2\right).
\]</span> Simply speaking, the hypothesis with higher posterior probability is selected.</p>
<p>The easiest way to reduce the error probability is to gather more data, as the additional evidence should lead to more accurate decisions. In some cases, it is easy to characterize optimal tests, those that minimize the sum of the errors. Simple hypothesis tests of the form <span class="math inline">\(H_{0}:\theta=\theta_{0}\)</span> versus <span class="math inline">\(H_{1}:\theta=\theta_{1}\)</span>, are one such case admitting optimal tests. Defining <span class="math inline">\(d^{\ast}\)</span> as a test accepting <span class="math inline">\(H_{0}\)</span> if <span class="math inline">\(a_{0}f\left( y \mid \theta_{0}\right) &gt;a_{1}f\left( y \mid \theta_{1}\right)\)</span> and <span class="math inline">\(H_{1}\)</span> if <span class="math inline">\(a_{0}f\left( y \mid \theta_{0}\right) &lt;a_{1}f\left( y \mid \theta _{1}\right)\)</span>, for some <span class="math inline">\(a_{0}\)</span> and <span class="math inline">\(a_{1}\)</span>. Either <span class="math inline">\(H_{0}\)</span> or <span class="math inline">\(H_{1}\)</span> can be accepted if <span class="math inline">\(a_{0}f\left(y \mid \theta_{0}\right) =a_{1}f\left( y \mid \theta_{1}\right)\)</span>. Then, for any other test <span class="math inline">\(d\)</span>, it is not hard to show that <span class="math display">\[
a_{0}\alpha\left(  d^{\ast}\right)  +a_{1}\beta\left(  d^{\ast}\right)  \leq
a_{0}\alpha\left(  d\right)  +a_{1}\beta\left(  d\right),
\]</span> where <span class="math inline">\(\alpha_{d}=\alpha_{d}\left( \theta\right)\)</span> and <span class="math inline">\(\beta_{d}=\beta_{d}\left( \theta\right)\)</span>. This result highlights the optimality of tests defining rejection regions in terms of the likelihood ratio statistic, <span class="math inline">\(f\left( y \mid \theta_{0}\right)/f\left( y \mid \theta_{1}\right)\)</span>. It turns out that the results are in fact stronger. In terms of decision theoretic properties, tests that define rejection regions based on likelihood ratios are not only admissible decisions, but form a minimal complete class, the strongest property possible.</p>
<p>One of the main problems in hypothesis testing is that there is often a tradeoff between the two goals of reducing type I and type II errors: decreasing <span class="math inline">\(\alpha\)</span> leads to an increase in <span class="math inline">\(\beta\)</span>, and vice-versa. Because of this, it is common to fix <span class="math inline">\(\alpha_{\theta}\left( d\right)\)</span>, or <span class="math inline">\(\sup~\alpha_{\theta}\left( d\right)\)</span>, and then find a test to minimize <span class="math inline">\(\beta_{d}\left( \theta\right)\)</span>. This leads to “most powerful” tests. There is an important result from decision theory: test procedures that use the same size level of <span class="math inline">\(\alpha\)</span> in problems with different sample sizes are inadmissible. This is commonly done where significance is indicated by a fixed size, say 5%. The implications of this will be clearer below in examples.</p>
<section id="likelihood-principle" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="likelihood-principle"><span class="header-section-number">6.1</span> Likelihood Principle</h2>
<p>Given observed data <span class="math inline">\(y\)</span> and likelihood function <span class="math inline">\(l(\theta) = p(y\mid \theta)\)</span>, the likelihood principle states that all relevant experimental information is contained in the likelihood function for the observed <span class="math inline">\(y\)</span>. Furthermore, two likelihood functions contain the same information about <span class="math inline">\(\theta\)</span> if they are proportional to each other. For example, the widely used maximum-likelihood estimation does satisfy the likelihood principle. However, this principle is sometimes violated by non-Bayesian hypothesis testing procedures. The likelihood principle is a fundamental principle in statistical inference, and it is a key reason why Bayesian procedures are often preferred.</p>
<div id="exm-likelihood" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.1 (Testing fairness)</strong></span> Suppose we are interested in testing <span class="math inline">\(\theta\)</span>, the unknown probability of heads for a possibly biased coin. Suppose, <span class="math display">\[
H_0 :~\theta=1/2 \quad\text{v.s.} \quad  H_1 :~\theta&gt;1/2.
\]</span> An experiment is conducted and 9 heads and 3 tails are observed. This information is not sufficient to fully specify the model <span class="math inline">\(p(y\mid \theta)\)</span>. There are two approaches.</p>
<p><em>Scenario 1</em>: Number of flips, <span class="math inline">\(n = 12\)</span> is predetermined. Then number of heads <span class="math inline">\(Y \mid \theta\)</span> is binomial <span class="math inline">\(B(n, \theta)\)</span>, with probability mass function <span class="math display">\[
p(y\mid \theta)= {n \choose y} \theta^{y}(1-\theta)^{n-y} = 220 \cdot \theta^9(1-\theta)^3
\]</span> For a frequentist, the p-value of the test is <span class="math display">\[
P(Y \geq 9\mid H_0)=\sum_{y=9}^{12} {12 \choose y} (1/2)^y(1-1/2)^{12-y} = (1+12+66+220)/2^{12} =0.073,
\]</span> and if you recall the classical testing, <span class="math inline">\(H_0\)</span> is not rejected at level <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<p><em>Scenario 2</em>: The number of tails (successes) <span class="math inline">\(\alpha = 3\)</span> is predetermined; that is, flipping continues until 3 tails are observed. Then, <span class="math inline">\(Y\)</span>, the number of heads (failures) observed until 3 tails appear, follows a Negative Binomial distribution <span class="math inline">\(NB(3, 1- \theta)\)</span>, <span class="math display">\[
p(y\mid \theta)= {\alpha+y-1 \choose \alpha-1} \theta^{y}(1-\theta)^{\alpha} = {3+9-1 \choose 3-1} \theta^9(1-\theta)^3 = 55\cdot \theta^9(1-\theta)^3.
\]</span> For a frequentist, large values of <span class="math inline">\(Y\)</span> are critical and the p-value of the test is <span class="math display">\[
P(Y \geq 9\mid H_0)=\sum_{y=9}^{\infty} {3+y-1 \choose 2} (1/2)^{y}(1/2)^{3} = 0.0327.
\]</span> We used the following identity here <span class="math display">\[
\sum_{x=k}^{\infty} {2+x \choose 2}\dfrac{1}{2^x} = \dfrac{8+5k+k^2}{2^k}.
\]</span> The hypothesis <span class="math inline">\(H_0\)</span> is rejected, and this change in decision is not caused by observations.</p>
<p>According to the Likelihood Principle, all relevant information is in the likelihood <span class="math inline">\(l(\theta) \propto \theta^9(1 - \theta)^3\)</span>, and Bayesians could not agree more!</p>
<p>Edwards, Lindman, and Savage (1963, 193) note: The likelihood principle emphasized in Bayesian statistics implies, among other things, that the rules governing when data collection stops are irrelevant to data interpretation. It is entirely appropriate to collect data until a point has been proven or disproven, or until the data collector runs out of time, money, or patience.</p>
</div>
</section>
<section id="the-bayesian-approach" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-bayesian-approach"><span class="header-section-number">6.2</span> The Bayesian Approach</h2>
<p>Formally, the Bayesian approach to hypothesis testing is a special case of the model comparison results to be discussed later. The Bayesian approach just computes the posterior distribution of each hypothesis. By Bayes rule, for <span class="math inline">\(i=0,1\)</span> <span class="math display">\[
P \left(  H_{i} \mid y\right)  =\frac{p\left(  y \mid H_{i}\right)  P \left(  H_{i}\right)  }{p\left(  y\right)
}\text{,}%
\]</span> where <span class="math inline">\(P \left( H_{i}\right)\)</span> is the prior probability of <span class="math inline">\(H_{i}\)</span>, <span class="math display">\[
p\left( y \mid H_{i}\right) =\int_{\theta \in \Theta_i} p\left( y \mid \theta\right) p\left( \theta \mid H_{i}\right) d\theta
\]</span> is the marginal likelihood under <span class="math inline">\(H_{i}\)</span>, <span class="math inline">\(p\left( \theta \mid H_{i}\right)\)</span> is the parameter prior under <span class="math inline">\(H_{i}\)</span>, and <span class="math display">\[
p\left(  y\right)  = \sum_{i=0,1} p\left(  y \mid H_{i}\right)  P \left( H_{i}\right).
\]</span></p>
<p>If the hypotheses are mutually exclusive, <span class="math inline">\(P \left( H_{0}\right) =1-P \left( H_{1}\right)\)</span>.</p>
<p>The posterior <em>odds</em> of the null to the alternative is <span class="math display">\[
\text{Odds}_{0,1}=\frac{P \left(  H_{0} \mid y\right)  }{P %
\left(  H_{1} \mid y\right)  }=\frac{p\left(  y \mid H_{0}\right)
}{p\left(  y \mid H_{1}\right)  }\frac{P \left(  H_{0}\right)  }{P \left(  H_{1}\right)  }\text{.}%
\]</span></p>
<p>The odds ratio updates the prior odds, <span class="math inline">\(P \left( H_{0}\right) /P \left( H_{1}\right)\)</span>, using the Bayes Factor, <span class="math display">\[
\mathrm{BF}_{0,1}=\dfrac{p\left(y \mid H_{0}\right)}{p\left( y \mid H_{1}\right)}.
\]</span> With exhaustive competing hypotheses, <span class="math inline">\(P \left( H_{0} \mid y\right)\)</span> simplifies to <span class="math display">\[
P \left(  H_{0} \mid y\right)  =\left(  1+\left(  \mathrm{BF}_{0,1}\right)  ^{-1}\frac{\left(  1-P \left(  H_{0}\right)
\right)  }{P \left(  H_{0}\right)  }\right)  ^{-1}\text{,}%
\]</span> and with equal prior probability, <span class="math inline">\(P\left( H_{0} \mid y\right) =\left( 1+\left( \mathrm{BF}_{0,1}\right) ^{-1}\right) ^{-1}\)</span>. Both Bayes factors and posterior probabilities can be used for comparing hypotheses. Jeffreys (1961) advocated using Bayes factors, and provided a scale for measuring the strength of evidence that was given earlier. Bayes factors merely indicate that the null hypothesis is more likely if <span class="math inline">\(\mathrm{BF}_{0,1}&gt;1\)</span>, <span class="math inline">\(p\left( y \mid H_{0}\right) &gt;p\left( y \mid H_{1}\right)\)</span>. The Bayesian approach merely compares density ordinates of <span class="math inline">\(p\left( y \mid H_{0}\right)\)</span> and <span class="math inline">\(p\left( y \mid H_{1}\right)\)</span>, which mechanically involves plugging in the observed data into the functional form of the marginal likelihood.</p>
<p>For a point null, <span class="math inline">\(H_{0}:\theta=\theta_{0}\)</span>, the parameter prior is <span class="math inline">\(p\left( \theta \mid H_{0}\right) =\delta_{\theta_{0}}\left( \theta\right)\)</span> (a Dirac mass at <span class="math inline">\(\theta_{0}\)</span>), which implies that <span class="math display">\[
p\left( y \mid H_{0}\right) =\int p\left( y \mid \theta_{0}\right) p\left( \theta \mid H_{0}\right) d\theta=p\left( y \mid \theta_{0}\right).
\]</span> With a general alternative, <span class="math inline">\(H_{1}:\theta\neq\theta_{0}\)</span>, the probability of the null is <span class="math display">\[
P \left(  \theta=\theta_{0} \mid y\right)  =\frac{p\left(  y \mid \theta
_{0}\right)  P \left(  H_{0}\right)  }{p\left(  y \mid \theta
_{0}\right)  P \left(  H_{0}\right)  +\left(  1-P\left( H_{0}\right)  \right)  \int_{\Theta}p\left(  y \mid \theta,H_{1}\right)  p\left(  \theta \mid H_{1}\right)  d\theta},
\]</span> where <span class="math inline">\(p\left( \theta \mid H_{1}\right)\)</span> is the parameter prior under the alternative. This formula will be used below.</p>
<p>Bayes factors and posterior null probabilities measure the relative weight of evidence of the hypotheses. Traditional hypothesis testing involves an additional decision or action: to accept or reject the null hypothesis. For Bayesians, this typically requires some statement of the utility/loss that codifies the benefits/costs of making a correct or incorrect decision. The simplest situation occurs if one assumes a zero loss of making a correct decision. The loss incurred when accepting the null (alternative) when the alternative is true (false) is <span class="math inline">\(L\left( d_{0} \mid H_{1}\right)\)</span> and <span class="math inline">\(L\left( d_{1} \mid H_{0}\right)\)</span>, respectively.</p>
<p>The Bayesian will accept or reject based on the posterior expected loss. If the expected loss of accepting the null is less than the alternative, the rational decision maker will accept the null. The posterior loss of accepting the null is <span class="math display">\[
\mathbb{E}\left[  \mathcal{L}\mid d_{0},y\right]  =L\left(  d_{0} \mid H_{0}\right)
P \left(  H_{0} \mid y\right)  +L\left(  d_{0} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  =L\left( d_{0} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  ,
\]</span> since the loss of making a correct decision, <span class="math inline">\(L\left( d_{0} \mid H_{0}\right)\)</span>, is zero. Similarly, <span class="math display">\[
\mathbb{E}\left[  \mathcal{L} \mid d_{1},y\right]  =L\left(  d_{1} \mid H_{0}\right)
P \left(  H_{0} \mid y\right)  +L\left(  d_{1} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  =L\left( d_{1} \mid H_{0}\right)  P \left(  H_{0} \mid y\right)  .
\]</span> Thus, the null is accepted if <span class="math display">\[
\mathbb{E}\left[  \mathcal{L} \mid d_{0},y\right]  &lt;\mathbb{E}\left[  \mathcal{L} \mid d_{1},y\right]
\Longleftrightarrow L\left(  d_{0} \mid H_{1}\right)  P \left( H_{1} \mid y\right)  &lt;L\left(  d_{1} \mid H_{0}\right)
P \left(  H_{0} \mid y\right)  ,
\]</span> which further simplifies to <span class="math display">\[
\frac{L\left(  d_{0} \mid H_{1}\right)  }{L\left(  d_{1} \mid H_{0}\right)  }&lt;\frac{P \left(  H_{0} \mid y\right)  }{P \left(  H_{1} \mid y\right)  }.
\]</span> In the case of equal losses, this simplifies to accept the null if <span class="math inline">\(P \left( H_{1} \mid y\right) &lt;P \left( H_{0} \mid y\right)\)</span>. One advantage of Bayes procedures is that the resulting estimators and decisions are always admissible.</p>
<div id="exm-snigma" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.2 (Enigma machine: Code-breaking)</strong></span> Consider an alphabet of <span class="math inline">\(26\)</span> letters. Let <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> be two codes of length <span class="math inline">\(T\)</span>. We will look to see how many letters match (<span class="math inline">\(M\)</span>) and don’t match (<span class="math inline">\(N\)</span>) in these sequences. Even though the codes are describing different sentences, when letters are the same, if the same code is being used then the sequence will have a match. To compute the Bayes factor we need the joint <em>probabilities</em> <span class="math display">\[
P( x,y\mid  H_0 ) \; \; \mathrm{ and} \; \; P( x,y\mid  H_1 ),
\]</span> where under <span class="math inline">\(H_0\)</span> they are different codes, in which case the joint probability is <span class="math inline">\(( 1 / A )^{2T}\)</span>. For <span class="math inline">\(H_1\)</span> we first need to know the chance of the same letter matching. If <span class="math inline">\(p_t\)</span> denotes the frequencies of the use of English letters, then we have this match probability <span class="math inline">\(m = \sum_{i} p_i^2\)</span> which is about <span class="math inline">\(2/26\)</span>. Hence for a particular set of letters <span class="math display">\[
P( x_i , y_i \mid H_1 ) = \frac{m}{A} \; \mathrm{ if} \; x_i =y_i \; \; \mathrm{ and} \; \;  P( x_i , y_i \mid H_1 ) = \frac{1-m}{A(A-1)} \; \mathrm{ if} \; x_i \neq y_i.
\]</span> Hence the log Bayes factor is <span class="math display">\[\begin{align*}
\ln \frac{P( x,y\mid  H_1 )}{P( x,y\mid  H_0 )} &amp; = M \ln \frac{ m/A}{1/A^2} +N \ln \frac{ ( 1-m ) / A(A-1) }{ 1/ A^2} \\
&amp; = M \ln mA  + N \ln \frac{ ( 1-m )A }{A-1 }
\end{align*}\]</span> The first term comes when you get a match and the increase in the Bayes factor is large, <span class="math inline">\(3.1\)</span> (on a <span class="math inline">\(\log_{10}\)</span>-scale), otherwise you get a no-match and the Bayes factor decreases by <span class="math inline">\(- 0.18\)</span>.</p>
<p>Example: <span class="math inline">\(N=4\)</span>, <span class="math inline">\(M=47\)</span> out of <span class="math inline">\(T=51\)</span>, then gives evidence of 2.5 to 1 in favor of <span class="math inline">\(H_1\)</span>.</p>
<p>How long a sequence do you need to look at? Calculate the expected log odds. Turing and Good figured you needed sequences of about length <span class="math inline">\(400\)</span>. Can also look at doubles and triples.</p>
</div>
<div id="exm-credset" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.3 (Signal Transmission)</strong></span> Suppose that the random variable <span class="math inline">\(X\)</span> is transmitted over a noisy communication channel. Assume that the received signal is given by <span class="math display">\[
Y=X+W,
\]</span> where <span class="math inline">\(W\sim N(0,\sigma^2)\)</span> is independent of <span class="math inline">\(X\)</span>. Suppose that <span class="math inline">\(X=1\)</span> with probability <span class="math inline">\(p\)</span>, and <span class="math inline">\(X=-1\)</span> with probability <span class="math inline">\(1-p\)</span>. The goal is to decide between <span class="math inline">\(X=1\)</span> and <span class="math inline">\(X=-1\)</span> by observing the random variable <span class="math inline">\(Y\)</span>. We will assume symmetric loss and will accept the hypothesis with the higher posterior probability. This is also sometimes called the maximum a posteriori (MAP) test.</p>
<p>We assume that <span class="math inline">\(H_0: ~ X = 1\)</span>, thus <span class="math inline">\(Y\mid H_0 \sim N(1,\sigma^2)\)</span>, and <span class="math inline">\(Y\mid H_1 \sim N(-1,\sigma^2)\)</span>. The Bayes factor is simply the likelihood ratio <span class="math display">\[
\dfrac{p(y\mid H_0)}{p(y \mid H_1)} =  \exp\left( \frac{2y}{\sigma^2}\right).
\]</span> The prior odds are <span class="math inline">\(p/(1-p)\)</span>, thus the posterior odds are <span class="math display">\[
\exp\left( \frac{2y}{\sigma^2}\right)\dfrac{p}{1-p}.
\]</span> We choose <span class="math inline">\(H_0\)</span> (true <span class="math inline">\(X\)</span> is 1), if the posterior odds are greater than 1, i.e., <span class="math display">\[
y &gt; \frac{\sigma^2}{2} \log\left( \frac{1-p}{p}\right) = c.
\]</span></p>
<p>Further, we can calculate the error probabilities of our test. <span class="math display">\[
p(d_1\mid H_0) = P(Y&lt;c\mid X=1) = \Phi\left( \frac{c-1}{\sigma}\right),
\]</span> and <span class="math display">\[
p(d_0\mid H_1) = P(Y&gt;c\mid X=-1) = 1- \Phi\left( \frac{c+1}{\sigma}\right).
\]</span> Let’s plot the total error rate as a function of <span class="math inline">\(p\)</span> and assuming <span class="math inline">\(\sigma=0.2\)</span> <span class="math display">\[
P_e = p(d_1\mid H_0) (1-p) + p(d_0\mid H_1) p
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>,<span class="fl">0.99</span>,<span class="fl">0.01</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">2</span><span class="sc">*</span><span class="fu">log</span>((<span class="dv">1</span><span class="sc">-</span>p)<span class="sc">/</span>p)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>Pe <span class="ot">&lt;-</span> <span class="fu">pnorm</span>((c<span class="dv">-1</span>)<span class="sc">/</span>sigma)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>((c<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span>sigma))<span class="sc">*</span>p</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p,Pe,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">xlab=</span><span class="st">"p"</span>,<span class="at">ylab=</span><span class="st">"Total Error Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-hyp_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
<div id="exm-normalhypothesis" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.4 (Hockey: Hypothesis Testing for Normal Mean)</strong></span> The general manager of Washington Capitals (an NHL hockey team) thinks that their star center player Evgeny Kuznetsov is underperforming and is thinking of trading him to a different team. He uses the number of goals per season as a metric of performance. He knows that historically, a top forward scores on average 30 goals per season with a standard deviation of 5, <span class="math inline">\(\theta \sim N(30,25)\)</span>. In the 2022-2023 season Kuznetsov scored 12 goals. For the number of goals <span class="math inline">\(X\mid \theta\)</span> he uses normal likelihood <span class="math inline">\(N(\theta, 36)\)</span>. Kuznetsov’s performance was not stable over the years, thus the high variance in the likelihood. Thus, the posterior is <span class="math inline">\(N(23,15)\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">=</span> <span class="dv">36</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sigma02 <span class="ot">=</span> <span class="dv">25</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="dv">30</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="dv">12</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> sigma02 <span class="sc">+</span> sigma2</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>mu1 <span class="ot">=</span> sigma2<span class="sc">/</span>k<span class="sc">*</span>mu <span class="sc">+</span> sigma02<span class="sc">/</span>k<span class="sc">*</span>y</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>sigma21 <span class="ot">=</span> sigma2<span class="sc">*</span>sigma02<span class="sc">/</span>k</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>mu1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 23</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>sigma21</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 15</code></pre>
</div>
</div>
<p>The manager thinks that Kuznetsov simply had a bad year and his true performance is at least 24 goals per season <span class="math inline">\(H_0: \theta \geq 24\)</span>, <span class="math inline">\(H_1: \theta&lt;24\)</span>. The posterior probability of the <span class="math inline">\(H_0\)</span> hypothesis is</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">24</span>,mu1,<span class="fu">sqrt</span>(sigma21))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.36</code></pre>
</div>
</div>
<p>It is less than 1/2, only 36%. Thus, we should reject the null hypothesis. The posterior odds in favor of the null hypothesis are</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>a<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.56</code></pre>
</div>
</div>
<p>If underestimating (and trading) Kuznetsov is two times more costly than overestimating him (fans will be upset and team spirit might be affected), that is <span class="math inline">\(L(d_1\mid H_0) = 2L(d_0\mid H_1)\)</span>, then we should accept the null when posterior odds are greater than 1/2. This is the case here, 0.55 is greater than 1/2. The posterior odds are in favor of the null hypothesis. Thus, the manager should not trade Kuznetsov.</p>
<p>Kuznetsov was traded to Carolina Hurricanes towards the end of the 2023-2024 season.</p>
<p>Notice, when we try to evaluate a newcomer to the league, we use the prior probability of <span class="math inline">\(\theta \geq 24\)</span>:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">24</span>,mu,<span class="fu">sqrt</span>(sigma02))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.88</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>a<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 7.7</code></pre>
</div>
</div>
<p>Thus, the prior odds in favor of <span class="math inline">\(H_0\)</span> are 7.7.</p>
</div>
<div id="exm-twosided" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.5 (Hypothesis Testing for Normal Mean: Two-Sided Test)</strong></span> In the case of two sided test, we are interested in testing</p>
<ul>
<li><span class="math inline">\(H_0: \theta = m_0\)</span>, <span class="math inline">\(p\left( \theta \mid H_{0}\right) =\delta_{m_{0}}\left( \theta\right)\)</span></li>
<li><span class="math inline">\(H_1: \theta \neq m_0\)</span>, <span class="math inline">\(p\left( \theta \mid H_{1}\right) = N\left( m_{0},\sigma^{2}/n_0\right)\)</span></li>
</ul>
<p>Where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(\sigma^2\)</span> is the variance (known) of the population. Observed samples are <span class="math inline">\(Y = (y_1, y_2, \ldots, y_n)\)</span> with <span class="math display">\[
y_i \mid \theta,\sigma^2 \sim N(\theta, \sigma^2).
\]</span></p>
<p>The Bayes factor can be calculated analytically <span class="math display">\[
BF_{0,1} = \frac{p(Y\mid \theta = m_0, \sigma^2 )}
{\int p(Y\mid \theta, \sigma^2) p(\theta \mid m_0, n_0, \sigma^2)\, d \theta}
\]</span> <span class="math display">\[
\int p(Y\mid \theta, \sigma^2) p(\theta \mid m_0, n_0, \sigma^2)\, d \theta = \frac{\sqrt{n_0}\exp\left\{-\frac{n_0(m_0-\bar y)^2}{2\left(n_0+n\right)\sigma^2}\right\}}{\sqrt{2\pi}\sigma^2\sqrt{\frac{n_0+n}{\sigma^2}}}
\]</span> <span class="math display">\[
p(Y\mid \theta = m_0, \sigma^2 ) = \frac{\exp\left\{-\frac{(\bar y-m_0)^2}{2 \sigma ^2}\right\}}{\sqrt{2 \pi } \sigma }
\]</span> Thus, the Bayes factor is <span class="math display">\[
BF_{0,1} = \frac{\sigma\sqrt{\frac{n_0+n}{\sigma^2}}e^{-\frac{(m_0-\bar y)^2}{2\left(n_0+n\right)\sigma^2}}}{\sqrt{n_0}}
\]</span></p>
<p><span class="math display">\[
BF_{0,1} =\left(\frac{n + n_0}{n_0} \right)^{1/2} \exp\left\{-\frac{1}{2} \frac{n }{n + n_0} Z^2 \right\}
\]</span></p>
<p><span class="math display">\[
Z =  \frac{(\bar{Y} - m_0)}{\sigma/\sqrt{n}}
\]</span></p>
<p>One way to interpret the scaling factor <span class="math inline">\(n_0\)</span> is ro look at the standard effect size <span class="math display">\[
\delta = \frac{\theta - m_0}{\sigma}.
\]</span> The prior of the standard effect size is <span class="math display">\[
\delta \mid H_1 \sim N(0, 1/n_0).
\]</span> This allows us to think about a standardized effect independent of the units of the problem.</p>
<p>Let’s consider now example of Argon discovery.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>air <span class="ot">=</span>    <span class="fu">c</span>(<span class="fl">2.31017</span>, <span class="fl">2.30986</span>, <span class="fl">2.31010</span>, <span class="fl">2.31001</span>, <span class="fl">2.31024</span>, <span class="fl">2.31010</span>, <span class="fl">2.31028</span>, <span class="fl">2.31028</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>decomp <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">2.30143</span>, <span class="fl">2.29890</span>, <span class="fl">2.29816</span>, <span class="fl">2.30182</span>, <span class="fl">2.29869</span>, <span class="fl">2.29940</span>, <span class="fl">2.29849</span>, <span class="fl">2.29889</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Our null hypothesis is that the mean of the difference equals to zero. We assume that measurements made in the lab have normal errors, this the normal likelihood. We empirically calculate the standard deviation of our likelihood. The Bayes factor is</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> air <span class="sc">-</span> decomp</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="fu">length</span>(y)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(air) <span class="sc">+</span> <span class="fu">var</span>(decomp))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>n0 <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> (<span class="fu">mean</span>(y) <span class="sc">-</span> m0)<span class="sc">/</span>(sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>BF <span class="ot">=</span> <span class="fu">sqrt</span>((n <span class="sc">+</span> n0)<span class="sc">/</span>n0)<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span>n<span class="sc">/</span>(n <span class="sc">+</span> n0)<span class="sc">*</span>Z<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>BF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 1.9e-91</code></pre>
</div>
</div>
<p>We have extremely strong evidence in favor <span class="math inline">\(H_1: \theta \ne 0\)</span> hypothesis. The posterior probability of the alternative hypothesis is numerically 1!</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>BF)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 1</code></pre>
</div>
</div>
</div>
<div id="exm-noralhypothesis" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.6 (Hypothesis Testing for Proportions)</strong></span> Let’s look at again at the effectiveness of Google’s new search algorithm. We measure effectiveness by the number of users who clicked on one of the search results. As users send the search requests, they will be randomly processed with Algo 1 or Algo 2. We wait until 2500 search requests were processed by each of the algorithms and calculate the following table based on how often people clicked through</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Algo1</th>
<th style="text-align: center;">Algo2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>success</td>
<td style="text-align: center;">1755</td>
<td style="text-align: center;">1818</td>
</tr>
<tr class="even">
<td>failure</td>
<td style="text-align: center;">745</td>
<td style="text-align: center;">682</td>
</tr>
<tr class="odd">
<td>total</td>
<td style="text-align: center;">2500</td>
<td style="text-align: center;">2500</td>
</tr>
</tbody>
</table>
<p>Here we assume binomial likelihood and use conjugate beta prior, for mathematical convenience. We are putting independent beta priors on the click-through rates of the two algorithms, <span class="math inline">\(p_1\sim Beta(\alpha_1,\beta_1)\)</span> and <span class="math inline">\(p_2\sim Beta(\alpha_2,\beta_2)\)</span>. The posterior for <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> are independent Beta distributions <span class="math display">\[
p(p_1, p_1 \mid y) \propto p_1^{\alpha_1 + 1755 - 1} (1-p_1)^{\beta_1 + 745 - 1}\times p_2^{\alpha_2 + 1818 - 1} (1-p_2)^{\beta_2 + 682 - 1}.
\]</span></p>
<p>The easiest way to explore this posterior is via Monte Carlo simulation of the posterior.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">92</span>) <span class="co">#Kuzy</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> <span class="dv">1755</span>; n1 <span class="ot">&lt;-</span> <span class="dv">2500</span>; alpha1 <span class="ot">&lt;-</span> <span class="dv">1</span>; beta1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="dv">1818</span>; n2 <span class="ot">&lt;-</span> <span class="dv">2500</span>; alpha2 <span class="ot">&lt;-</span> <span class="dv">1</span>; beta2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="dv">10000</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(m, y1 <span class="sc">+</span> alpha1, n1 <span class="sc">-</span> y1 <span class="sc">+</span> beta1)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(m, y2 <span class="sc">+</span> alpha2, n2 <span class="sc">-</span> y2 <span class="sc">+</span> beta2)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> p2 <span class="sc">-</span> p1</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(rd), <span class="at">main=</span><span class="st">"Posterior Difference in Click-Through Rates"</span>, </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">xlab=</span><span class="st">"p2 - p1"</span>, <span class="at">ylab=</span><span class="st">"Density"</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>q <span class="ot">=</span> <span class="fu">quantile</span>(rd, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>##     5%    95% 
## 0.0037 0.0465</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span>q,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-hyp_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="interval-estimation-credible-sets" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="interval-estimation-credible-sets"><span class="header-section-number">6.3</span> Interval Estimation: Credible Sets</h2>
<p>The interval estimators of model parameters are called credible sets. If we use the posterior measure to assess the credibility, the credible set is a set of parameter values that are consistent with the data and gives us is a natural way to measure the uncertainty of the parameter estimate.</p>
<p>Those who are familiar with the concept of classical confidence intervals (CI’s) often make an error by stating that the probability that the CI interval <span class="math inline">\([L, U ]\)</span> contains parameter <span class="math inline">\(\theta\)</span> is <span class="math inline">\(1 - \alpha\)</span>. The right statement seems convoluted, one needs to generate data from such model many times and for each data set to exhibit the CI. Now, the proportion of CI’s covering the unknown parameter is “tends to” <span class="math inline">\(1 - \alpha\)</span>. Bayesian interpretation of a credible set <span class="math inline">\(C\)</span> is natural: The probability of a parameter belonging to the set <span class="math inline">\(C\)</span> is <span class="math inline">\(1 - \alpha\)</span>. A formal definition follows. Assume the set <span class="math inline">\(C\)</span> is a subset of domain of the parameter <span class="math inline">\(\Theta\)</span>. Then, <span class="math inline">\(C\)</span> is credible set with credibility <span class="math inline">\((1 - \alpha)\cdot 100\%\)</span> if <span class="math display">\[
p(\theta \in C \mid y) = \int_{C}p(\theta\mid y)d\theta \ge 1 - \alpha.
\]</span> If the posterior is discrete, then the integral becomes sum (counting measure) and <span class="math display">\[
p(\theta \in C \mid y) = \sum_{\theta_i\in C}p(\theta_i\mid y) \ge 1 - \alpha.
\]</span> This is the definition of a <span class="math inline">\((1 - \alpha)100\%\)</span> credible set, and of course for a given posterior function such set is not unique.</p>
<p>For a given credibility level <span class="math inline">\((1 - \alpha)100\%\)</span>, the shortest credible set is of interest. To minimize size the sets should correspond to highest posterior probability (density) areas. Thus the acronym HPD.</p>
<div id="def-hpd" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 6.1 (Highest Posterior Density (HPD) Credible Set)</strong></span> The <span class="math inline">\((1 - \alpha)100\%\)</span> HPD credible set for parameter <span class="math inline">\(\theta\)</span> is a set <span class="math inline">\(C \subset \Theta\)</span> of the form <span class="math display">\[
C = \{ \theta \in \Theta : p(\theta \mid y) \ge k(\alpha) \},
\]</span> where <span class="math inline">\(k(\alpha)\)</span> is the smallest value such that <span class="math display">\[
P(\theta\in C \mid y) = \int_{C}p(\theta\mid y)d\theta \ge 1 - \alpha.
\]</span> Geometrically, if the posterior density is cut by a horizontal line at the hight <span class="math inline">\(k(\alpha)\)</span>, the set <span class="math inline">\(C\)</span> is projection on the <span class="math inline">\(\theta\)</span> axis of the part of line inside the density, i.e., the part that lies below the density.</p>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-hyp_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div id="lem-hpd" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 6.1</strong></span> The HPD set <span class="math inline">\(C\)</span> minimizes the size among all sets <span class="math inline">\(D \subset \Theta\)</span> for which <span class="math display">\[
P(\theta \in D) = 1 - \alpha.
\]</span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>The proof is essentially a special case of Neyman-Pearson lemma. If <span class="math inline">\(I_C(\theta) = 1(\theta \in C)\)</span> and <span class="math inline">\(I_D(\theta) = 1(\theta \in D)\)</span>, then the key observation is <span class="math display">\[
\left(p(\theta\mid y) - k(\alpha)\right)(I_C(\theta) - I_D(\theta)) \ge 0.
\]</span> Indeed, for <span class="math inline">\(\theta\)</span>’s in <span class="math inline">\(C\cap D\)</span> and <span class="math inline">\((C\cup D)^c\)</span>, the factor <span class="math inline">\(I_C(\theta)-I_D(\theta) = 0\)</span>. If <span class="math inline">\(\theta \in C\cap D^c\)</span>, then <span class="math inline">\(I_C(\theta)-I_D(\theta) = 1\)</span> and <span class="math inline">\(p(\theta\mid y)-k(\alpha) \ge 0\)</span>. If, on the other hand, <span class="math inline">\(\theta \in D\cap C^c\)</span>, then <span class="math inline">\(I_C(\theta)-I_D(\theta) = -1\)</span> and <span class="math inline">\(p(\theta\mid y)-k(\alpha) \le 0\)</span>. Thus, <span class="math display">\[
\int_{\Theta}(p(\theta\mid y) - k(\alpha))(I_C(\theta) - I_D(\theta))d\theta \ge 0.
\]</span> The statement of the theorem now follows from the chain of inequalities, <span class="math display">\[
\int_{C}(p(\theta\mid y) - k(\alpha))d\theta \ge \int_{D}(p(\theta\mid y) - k(\alpha))d\theta
\]</span> <span class="math display">\[
(1-\alpha) - k(\alpha)\text{size}(C) \ge (1-\alpha) - k(\alpha)\text{size}(D)
\]</span> <span class="math display">\[
size(C) \le size(D).
\]</span> The size of a set is simply its total length if the parameter space <span class="math inline">\(\theta\)</span> is one dimensional, total area, if <span class="math inline">\(\theta\)</span> is two dimensional, and so on.</p>
</div>
<p>Note, when the distribution <span class="math inline">\(p(\theta \mid y)\)</span> is unimodal and symmetric using quantiles of the posterior distribution is a good way to obtain the HPD set.</p>
<p>An equal-tailed interval (also called a central interval) of confidence level<br>
<span class="math display">\[
I_{\alpha} = [q_{\alpha/2}, q_{1-\alpha/2}],
\]</span> here <span class="math inline">\(q\)</span>’s are the quantiles of the posterior distribution. This is an interval on whose both right and left side lies <span class="math inline">\((1-\alpha/2)100\%\)</span> of the probability mass of the posterior distribution; hence the name equal-tailed interval.</p>
<p>Usually, when a credible interval is mentioned without specifying which type of the credible interval it is, an equal-tailed interval is meant.</p>
<p>However, unless the posterior distribution is unimodal and symmetric, there are point outsed of the equal-tailed credible interval having a higher posterior density than some points of the interval. If we want to choose the credible interval so that this not happen, we can do it by using the highest posterior density criterion for choosing it.</p>
<div id="exm-Cauchy" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.7 (Cauchy.)</strong></span> Assume that the observed samples</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="sc">-</span><span class="dv">7</span>,<span class="dv">4</span>,<span class="sc">-</span><span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>come from Cauchy distribution. The likelihood is <span class="math display">\[
p(y\mid \theta, \gamma) = \frac{1}{\pi\gamma} \prod_{i=1}^{4} \frac{1}{1+\left(\dfrac{y_i-\theta}{\gamma}\right)^2}.
\]</span> We assume unknown location parameter <span class="math inline">\(\theta\)</span> and scale parameter <span class="math inline">\(\gamma=1\)</span>. For the flat prior <span class="math inline">\(\pi(\theta) = 1\)</span>, the posterior is proportional to the likelihood.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lhood <span class="ot">=</span> <span class="cf">function</span>(theta) <span class="dv">1</span><span class="sc">/</span><span class="fu">prod</span>(<span class="dv">1</span><span class="sc">+</span>(y<span class="sc">-</span>theta)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>,<span class="fl">0.1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">sapply</span>(theta,lhood)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>post <span class="ot">=</span> <span class="dv">10</span><span class="sc">*</span>post<span class="sc">/</span><span class="fu">sum</span>(post)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(theta,post,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">xlab=</span><span class="fu">expression</span>(theta),<span class="at">ylab=</span><span class="st">"Posterior Density"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">c</span>(<span class="fl">0.008475</span>, <span class="fl">0.0159</span>, <span class="fl">0.1</span>, <span class="fl">0.2</span>),<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-hyp_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>The four horizontal lines correspond to four credible sets</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 54%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(k\)</span></th>
<th style="text-align: left;"><span class="math inline">\(C\)</span></th>
<th style="text-align: left;"><span class="math inline">\(P(\theta \in C \mid y)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.008475</td>
<td style="text-align: left;">[-8.498, 5.077]</td>
<td style="text-align: left;">99%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.0159</td>
<td style="text-align: left;">[-8.189, -3.022] <span class="math inline">\(\cup\)</span> [-0.615, 4.755]</td>
<td style="text-align: left;">95%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.1</td>
<td style="text-align: left;">[-7.328, -5.124] <span class="math inline">\(\cup\)</span> [1.591, 3.120]</td>
<td style="text-align: left;">64.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.2</td>
<td style="text-align: left;">[-6.893, -5.667]</td>
<td style="text-align: left;">31.2%</td>
</tr>
</tbody>
</table>
<p>Notice that for <span class="math inline">\(k = 0.0159\)</span> and <span class="math inline">\(k = 0.1\)</span> the credible set is not a compact. This shows that two separate intervals “clash” for the ownership of <span class="math inline">\(\theta\)</span> and this is a useful information. This non-compactness can also point out that the prior is not agreeing with the data. There is no frequentist counterpart for the CI for <span class="math inline">\(\theta\)</span> in the above model.</p>
</div>
</section>
<section id="alternative-approaches" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="alternative-approaches"><span class="header-section-number">6.4</span> Alternative Approaches</h2>
<p>The two main alternatives to the Bayesian approach are significance testing using <span class="math inline">\(p-\)</span>values, developed by Ronald Fisher, and the Neyman-Pearson approach.</p>
<section id="significance-testing-using-p-values" class="level3">
<h3 class="anchored" data-anchor-id="significance-testing-using-p-values">Significance testing using p-values</h3>
<p>Fisher’s approach posits a test statistic, <span class="math inline">\(T\left( y\right)\)</span>, based on the observed data. In Fisher’s mind, if the value of the statistic was highly unlikely to have occured under <span class="math inline">\(H_{0}\)</span>, then the <span class="math inline">\(H_{0}\)</span> should be rejected. Formally, the <span class="math inline">\(p-\)</span>value is defined as <span class="math display">\[
p=P \left[  T\left(  Y\right)  &gt;T\left(  y\right)   \mid H_{0}\right]  ,
\]</span> where <span class="math inline">\(y\)</span> is the observed sample and <span class="math inline">\(Y=\left( Y_{1}, \ldots ,Y_{T}\right)\)</span> is a random sample generated from model <span class="math inline">\(p\left( Y \mid H_{0}\right)\)</span>, that is, the null distribution of the test-statistic in repeated samples. Thus, the <span class="math inline">\(p-\)</span>value is the probability that a data set would generate a more extreme statistic under the null hypothesis, and not the probability of the null, conditional on the data.</p>
<p>The testing procedure is simple. Fisher (1946, p.&nbsp;80) argues that: If P (the p-value) is between* <span class="math inline">\(0.1\)</span> and <span class="math inline">\(0.9\)</span>, there is certainly no reason to suspect the hypothesis tested. If it is below <span class="math inline">\(0.02\)</span>, it is strongly indicated that the hypothesis fails to account for the whole of the facts. We shall not be astray if we draw a line at 0.05 and consider that higher values of <span class="math inline">\(\mathcal{X}^{2}\)</span> indicate a real discrepancy. Defining <span class="math inline">\(\alpha\)</span> as the significance level, the tests rejects <span class="math inline">\(H_{0}\)</span> if <span class="math inline">\(p&lt;\alpha\)</span>. Fisher advocated a fixed significance level of <span class="math inline">\(5\%\)</span>, based largely that <span class="math inline">\(5\%\)</span> is roughly the tail area of a mean zero normal distribution more than two standard deviations from <span class="math inline">\(0\)</span>, indicating a statistically significant departure. In practice, testing with <span class="math inline">\(p-\)</span>values involves identifying a critical value, <span class="math inline">\(t_{\alpha}\)</span>, and rejecting the null if the observed statistic <span class="math inline">\(t\left( y\right)\)</span> is more extreme than <span class="math inline">\(t_{\alpha}\)</span>. For example, for a significance test of the sample mean, <span class="math inline">\(t\left( y\right) =\left( \overline{y}-\theta_{0}\right) /se\left( \overline{y}\right)\)</span>, where <span class="math inline">\(se\left( \overline{y}\right)\)</span> is the standard error of <span class="math inline">\(\overline{y}\)</span>; the <span class="math inline">\(5\%\)</span> critical value is 1.96; and Fisher would reject the null if <span class="math inline">\(t\left( y\right) &gt;t_{\alpha}\)</span>.</p>
<p>Fisher interpreted the <span class="math inline">\(p-value\)</span> as the weight or measure of evidence of the null hypothesis. The alternative hypothesis is noticeable in its absence in Fisher’s approach. Fisher largely rejected the consideration of alternatives, believing that researchers should weigh the evidence or draw conclusions about the observed data rather than making decisions such as accepting or rejecting hypotheses based on it.</p>
<p>There are a number of issues with Fisher’s approach. The first and most obvious criticism is that it is possible to reject the null, when the alternative hypothesis is less likely. This is an inherent problem in using population tail probabilities–essentially rare events. Just because a rare event has occurred does not mean the null is incorrect, unless there is a more likely alternative. This situation often arises in court cases, where a rare event like a murder has occurred. Decisions based on p-values generates a problem called prosecutor’s Fallacy, which is discussed below. Second, Fisher’s approach relies on population properties (the distribution of the statistic under the null) that would only be revealed in repeated samples or asymptotically. Thus, the testing procedure relies on data that is not yet seen, a violation of what is known as the likelihood principle. As noted by Jeffreys’ (1939, pp.&nbsp;315-316): “<em>What the use of P implies, therefore, is that a hypothesis that may be true may be rejected because it has not predicted observable data that have not occurred. This seems a remarkable procedure</em>” <!-- \label{Jeffreys, p. 385}   --></p>
<p>Third, Fisher is agnostic regarding the source of the test statistics, providing no discussion of how the researcher decides to focus on one test statistic over another. In some simple models, the distribution of properly scaled sufficient statistics provides natural test statistics (e.g., the <span class="math inline">\(t-\)</span>test). In more complicated models, Fisher is silent on the sources. In many cases, there are numerous test statistics (e.g., testing for normality), and test choice is clearly subjective. For example, in GMM tests, the choice of test moments is clearly a subjective choice. Finally, from a practical perspective, <span class="math inline">\(p-\)</span>values have a serious deficiency: tests using <span class="math inline">\(p\)</span>-values often appear to give the wrong answer, in the sense that they provide a highly misleading impression of the weight of evidence in many samples. A number of examples of this will be given below, but in all cases, Fisher’s approach tends to over-reject the null hypotheses.</p>
</section>
<section id="neyman-pearson" class="level3">
<h3 class="anchored" data-anchor-id="neyman-pearson">Neyman-Pearson</h3>
<p>The motivation for the Neyman-Pearson (NP) approach was W.S. Gosset, the famous `Student’ who invented the <span class="math inline">\(t-\)</span>test. In analyzing a hypothesis, Student argued that a hypothesis is not rejected unless an alternative is available that provides a more plausible explanation of the data, in which case. Mathematically, this suggests analyzing the likelihood ratio, <span class="math display">\[
\mathcal{LR}_{0,1}=\frac{p\left(  y \mid H_{0}\right)  }{p\left( y \mid H_{1}\right)  }\text{,}%
\]</span> and rejecting the null in favor of the alternative when the likelihood ratio is small enough, <span class="math inline">\(\mathcal{LR}_{0,1}&lt;k\)</span>. This procedures conforms in spirit with the Bayesian approach.</p>
<p>The main problem was one of finding a value of the cut off parameter <span class="math inline">\(k.\)</span> From the discussion above, by varying <span class="math inline">\(k\)</span>, one varies the probabilities of type one and type two errors in the testing procedure. Originally, NP argued this tradeoff should be subjectively specified: “<em>how the balance (between the type I and II errors) should be struck must be left to the investigator</em>” (Neyman and Pearson (1933a, p.&nbsp;296) and “<em>we attempt to adjust the balance between the risks</em> <span class="math inline">\(P_{1}\)</span><span class="math inline">\(P_{2}\)</span> to meet the type of problem before us” (1933b, p.&nbsp;497). This approach, however, was not “objective *, and they then advocated fixing <span class="math inline">\(\alpha\)</span>, the probability of a type I error, in order to determine <span class="math inline">\(k\)</span>. This led to their famous lemma:</p>
<div id="lem-np" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 6.2 (Neyman-Pearson Lemma)</strong></span> Consider the simple hypothesis test of <span class="math inline">\(H_{0}:\theta=\theta_{0}\)</span> versus <span class="math inline">\(H_{1}:\theta =\theta_{1}\)</span> and suppose that the null is rejected if <span class="math inline">\(\mathcal{LR}_{0,1}&lt;k_{\alpha}\)</span>, where <span class="math inline">\(k_{\alpha}\)</span> is chosen to fix the probability of a type I error at <span class="math inline">\(\alpha:\)</span>% <span class="math display">\[
\alpha=P \left[  y:\mathcal{LR}_{0,1}&lt;k_{\alpha} \mid H_{0}\right]  \text{.}%
\]</span> Then, this test is the most powerful test of size <span class="math inline">\(\alpha\)</span> in the sense that any other test with greater power, must have a higher size.</p>
</div>
<p>In the case of composite hypothesis tests, parameter estimation is required under the alternative, which can be done via maximum likelihood, leading to the likelihood ratio <span class="math display">\[
\mathcal{LR}_{0,1}=\frac{p\left(  y \mid H_{0}\right)  }{\underset
{\theta\in\Theta}{\sup}p\left(  y \mid \Theta\right)  }=\frac{p\left( y \mid H_{0}\right)  }{p\left(  y \mid \widehat{\theta}\right)  }\text{,}%
\]</span> where <span class="math inline">\(\widehat{\theta}\)</span> is the MLE. Because of this, <span class="math inline">\(0\leq\mathcal{LR}_{0,1}\leq 1\)</span> for composite hypotheses. In multi-parameter cases, finding the distribution of the likelihood ratio is more difficult, requiring asymptotic approximations to calibrate <span class="math inline">\(k_{\alpha}.\)</span></p>
<p>At first glance, the NP approach appears similar to the Bayesian approach, as it takes into account the likelihood ratio. However, like the <span class="math inline">\(p-\)</span>value, the NP approach has a critical flaw. Neyman and Pearson fix the Type I error, and then minimizes the type II error. In many practical cases, <span class="math inline">\(\alpha\)</span> is set at <span class="math inline">\(5\%\)</span> and the resulting <span class="math inline">\(\beta\)</span> is often very small, close to 0. Why is this a reasonable procedure? Given the previous discussion, this is essentially a very strong prior over the relative benefits/costs of different types of errors. While these assumptions may be warranted in certain settings, it is difficult to a priori understand why this procedure would generically make sense. The next section highlights how the <span class="math inline">\(p-\)</span>value and NP approaches can generate counterintuitive and even absurd results in standard settings.</p>
</section>
</section>
<section id="examples-and-paradoxes" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="examples-and-paradoxes"><span class="header-section-number">6.5</span> Examples and Paradoxes</h2>
<p>This section provides a number of paradoxes arising when using different hypothesis testing procedures. The common strands of the examples will be discussed at the end of the section.</p>
<div id="exm-nptest" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.8 (Neyman-Pearson tests)</strong></span> Consider testing <span class="math inline">\(H_{0}:\mu=\mu_{0}\)</span> versus <span class="math inline">\(H_{1}:\mu=\mu_{1}\)</span>, <span class="math inline">\(y_{t}\sim\mathcal{N}\left( \mu,\sigma^{2}\right)\)</span> and <span class="math inline">\(\mu_{1}&gt;\mu_{0}\)</span>. For this simple test, the likelihood ratio is given by <span class="math display">\[
\mathcal{LR}_{0,1}=\frac{\exp\left(  -\frac{1}{2\sigma^{2}}%
%TCIMACRO{\tsum \nolimits_{t=1}^{T}}%
%BeginExpansion
{\textstyle\sum\nolimits_{t=1}^{T}}
%EndExpansion
\left(  y_{t}-\mu_{0}\right)  ^{2}\right)  }{\exp\left(  -\frac{1}{2\sigma
^{2}}%
%TCIMACRO{\tsum \nolimits_{t=1}^{T}}%
%BeginExpansion
{\textstyle\sum\nolimits_{t=1}^{T}}
%EndExpansion
\left(  y_{t}-\mu_{1}\right)  ^{2}\right)  }=\exp\left(  -\frac{T}{\sigma^{2}%
}\left(  \mu_{1}-\mu_{0}\right)  \left(  \overline{y}-\frac{1}{2}\left( \mu_{0}+\mu_{1}\right)  \right)  \right)  \text{.}%
\]</span> Since <span class="math inline">\(\mathrm{BF}_{0,1}=\mathcal{LR}_{0,1}\)</span>, assuming equal prior probabilities and symmetric losses, the Bayesian accepts <span class="math inline">\(H_{0}\)</span> if <span class="math inline">\(\mathrm{BF}_{0,1}&gt;1\)</span>. Thus, the Bayes procedure rejects <span class="math inline">\(H_{0}\)</span> if <span class="math inline">\(\overline{y}&gt;\frac{1}{2}\left( \mu_{0}+\mu_{1}\right)\)</span> for any <span class="math inline">\(T\)</span> and <span class="math inline">\(\sigma^{2}\)</span>, with <span class="math inline">\(\mu_{0}\)</span>,<span class="math inline">\(\mu_{1}\)</span>, <span class="math inline">\(T,\)</span>and <span class="math inline">\(\sigma^{2}\)</span> determining the strength of the rejction. If <span class="math inline">\(\mathrm{BF}_{0,1}=1\)</span>, there is equal evidence for the two hypotheses.</p>
<p>wedewk dejewoi m</p>
<p>The NP procedure proceeds by first setting <span class="math inline">\(\alpha=0.05,\)</span> and rejects when <span class="math inline">\(\mathcal{LR}_{0,1}\)</span> is large. This is equivalent to rejecting when <span class="math inline">\(\overline{y}\)</span> is large, generating an `optimal’ rejection region of the form <span class="math inline">\(\overline{y}&gt;c\)</span>. The cutoff value <span class="math inline">\(c\)</span> is calibrated via the size of the test, <span class="math display">\[
P \left[  reject\text{ }H_{0} \mid H_{0}\right]
=P \left[  \overline{y}&gt;c \mid \mu_{0}\right]  =P \left[
\frac{\left(  \overline{y}-\mu_{0}\right)  }{\sigma/\sqrt{T}}&gt;\frac{\left( c-\mu_{0}\right)  }{\sigma/\sqrt{T}} \mid H_{0}\right] .
\]</span> The size equals <span class="math inline">\(\alpha\)</span> if <span class="math inline">\(\sqrt{T}\left( c-\mu_{0}\right) /\sigma =z_{\alpha}\)</span>. Thus, the NP test rejects if then if <span class="math inline">\(\overline{y}&gt;\mu _{0}+\sigma z_{\alpha}/\sqrt{T}\)</span>. Notice that the tests rejects regardless of the value of <span class="math inline">\(\mu_{1}\)</span>, which is rather odd, since <span class="math inline">\(\mu_{1}\)</span> does not enter into the size of the test only the power. The probability of a type II error is <span class="math display">\[
\beta=P \left[  \text{accept }H_{0} \mid H_{1}\right]
=P \left[  \overline{y}\leq\mu_{0}+\frac{\sigma}{\sqrt{T}}z_{\alpha
} \mid H_{1}\right]  =\int_{-\infty}^{\mu_{0}+\frac{\sigma}{\sqrt{T}%
}z_{\alpha}}p\left(  \overline{y} \mid \mu_{1}\right)  d\overline{y}\text{,}%
\]</span> where <span class="math inline">\(p\left( \overline{y} \mid \mu_{1}\right) \sim\mathcal{N}\left( \mu _{1},\sigma^{2}/T\right)\)</span>.</p>
<p>These tests can generate strikingly different conclusions. Consider a test of <span class="math inline">\(H_{0}:\mu=0\)</span> versus <span class="math inline">\(H_{1}:\mu=5\)</span>, based on <span class="math inline">\(T=100\)</span> observations drawn from <span class="math inline">\(y_{t}\sim\mathcal{N}\left( \mu,10^{2}\right)\)</span> with <span class="math inline">\(\overline{y}=2\)</span>. For NP, since <span class="math inline">\(\sigma/\sqrt{T}=1\)</span>, <span class="math inline">\(\overline{y}\)</span> is two standard errors away from <span class="math inline">\(0\)</span>, thus <span class="math inline">\(H_{0}\)</span> is rejected at the 5% level (the same conclusion holds for <span class="math inline">\(p-\)</span>values). Since <span class="math inline">\(p(\overline {y}=2 \mid H_{0})=0.054\)</span> and <span class="math inline">\(p(\overline{y}=2 \mid H_{1})=0.0044\)</span>, the Bayes factor is <span class="math inline">\(\mathrm{BF}_{0,1}=12.18\)</span> and <span class="math inline">\(P \left( H_{0} \mid y\right) =92.41\%\)</span>. Thus, the Bayesian is quite sure the null is true, while Neyman-Pearson reject the null.</p>
<p>The paradox can be seen in two different ways. First, although <span class="math inline">\(\overline{y}\)</span> is actually closer to <span class="math inline">\(\mu_{0}\)</span> than <span class="math inline">\(\mu_{1}\)</span>, the NP test rejects <span class="math inline">\(H_{0}\)</span>. This is counterintuitive and makes little sense. The problem is one of calibration. The classical approach develops a test such that 5% of the time, a correct null would be rejected. The power of the test is easy to compute and implies that <span class="math inline">\(\beta=0.0012\)</span>. Thus, this testing procedure will virtually never accept the null if the alternative is correct. For Bayesian procedure, assuming the prior odds is <span class="math inline">\(1\)</span> and <span class="math inline">\(L_{0}=L_{1}\)</span>, then <span class="math inline">\(\alpha=\beta=0.0062\)</span>. Notice that the overall probability of making an error is 1.24% in the Bayesian procedure compared to 5.12% in the classical procedure. It should seem clear that the Bayesian approach is more reasonably, absent a specific motivation for inflating <span class="math inline">\(\alpha\)</span>. Second, suppose the null and alternative were reversed, testing <span class="math inline">\(H_{0}:\mu=\mu_{1}\)</span> versus <span class="math inline">\(H_{1}:\mu=\mu_{0}\)</span> In the previous example, the Bayes approach gives the same answer, while NP once again rejects the null hypothesis! Again, this result is counterintuitive and nonsensical, but is common when arbitrarily fixing <span class="math inline">\(\alpha\)</span>, which essentially hardwires the test to over-reject the null.</p>
</div>
<div id="exm-lindleyparadox" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.9 (Lindley’s paradox)</strong></span> Consider the case of testing whether or not a coin is fair, based on observed coin flips, <span class="math display">\[
H_{0}:\theta=\frac{1}{2}\text{ versus }H_{1}:\theta
\neq\frac{1}{2}\text{,}%
\]</span> based on <span class="math inline">\(T\)</span> observations from <span class="math inline">\(y_{t}\sim Ber\left( \theta\right)\)</span>. As an example, <a href="#tbl-lindley" class="quarto-xref">Table&nbsp;<span>6.1</span></a> provides 4 datasets of differing lengths. Prior to considering the formal hypothesis tests, form your own opinion on the strength of evidence regarding the hypothesis in each data set. It is common for individuals, when confronted with this data to conclude that the fourth sample provides the strongest of evidence for the null and the first sample the weakest.</p>
<div id="tbl-lindley" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lindley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Lindley’s paradox
</figcaption>
<div aria-describedby="tbl-lindley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>#1</th>
<th>#2</th>
<th>#3</th>
<th>#4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td># Flips</td>
<td>50</td>
<td>100</td>
<td>400</td>
<td>10,000</td>
</tr>
<tr class="even">
<td># Heads</td>
<td>32</td>
<td>60</td>
<td>220</td>
<td>5098</td>
</tr>
<tr class="odd">
<td>Percentage of heads</td>
<td>64</td>
<td>60</td>
<td>55</td>
<td>50.98</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Fisher’s solution to the problem posits an unbiased estimator, the sample mean, and computes the <span class="math inline">\(t-\)</span>statistic, which is calculated under <span class="math inline">\(H_{0}\)</span>: <span class="math display">\[
t\left(  y\right)  =\frac{\overline{y}-E\left[  \overline{y} \mid \theta
_{0}\right]  }{se\left(  \overline{y}\right)  }=\sqrt{T}\left(  2\widehat
{\theta}-1\right)  \text{,}%
\]</span> where <span class="math inline">\(se\left(\overline{y}\right)\)</span> is the standard error of <span class="math inline">\(\overline{y}\)</span>. The Bayesian solution requires marginal likelihood under the null and alternative, which are <span id="eq-Bernoulli_marginal"><span class="math display">\[
p\left(  y \mid \theta_{0}=1/2\right)  =\prod_{t=1}^{T}p\left(  y_{t} \mid \theta
_{0}\right)  =\left(  \frac{1}{2}\right)  ^{\sum_{t=1}^{T}y_{t}}\left( \frac{1}{2}\right)  ^{T-\sum_{t=1}^{T}y_{t}}=\left(  \frac{1}{2}\right)  ^{T},
\tag{6.1}\]</span></span> and, from <a href="#eq-Bernoulli_marginal" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>, <span class="math inline">\(p\left( y \mid H_{1}\right) =B\left( a_{T},A_{T}\right) /B\left(a,A\right)\)</span> assuming a beta prior distribution.</p>
<p>To compare the results, note first that in the datasets given above, <span class="math inline">\(\widehat{\theta}\)</span> and <span class="math inline">\(T\)</span> generate <span class="math inline">\(t_{\alpha}=1.96\)</span> in each case. Thus, for a significance level of <span class="math inline">\(\alpha=5\%\)</span>, the null is rejected for each sample size. Assuming a flat prior distribution, the Bayes factors are <span class="math display">\[
\mathrm{BF}_{0,1}=\left\{
\begin{array}
[c]{l}%
0.8178\text{ for }N=50\text{ }\\
1.0952\text{ for }N=100\\
2.1673\text{ for }N=400\\
11.689\text{ for }N=10000
\end{array}
\right.  ,
\]</span> showing increasingly strong evidence in favor of <span class="math inline">\(H_{0}\)</span>. Assuming equal prior weight for the hypotheses, the posterior probabilities are 0.45, 0.523, 0.684, and 0.921, respectively. For the smallest samples, the Bayes factor implies roughly equal odds of the null and alternative. As the sample size increase, the weight of evidence favors the null, with a 92% probabability for <span class="math inline">\(N=10K\)</span>.</p>
<p>Next, consider testing <span class="math inline">\(H_{0}:\theta_{0}=0\)</span> vs.&nbsp;<span class="math inline">\(H_{1}:\theta_{0}\neq0,\)</span> based on <span class="math inline">\(T\)</span> observations from <span class="math inline">\(y_{t}\sim \mathcal{N}\left( \theta_{0},\sigma^{2}\right)\)</span>, where <span class="math inline">\(\sigma^{2}\)</span> is known. This is the formal example used by Lindley to generate his paradox. Using <span class="math inline">\(p-\)</span>values, the hypothesis is rejected if the <span class="math inline">\(t-\)</span>statistic is greater than <span class="math inline">\(t_{\alpha}\)</span>. To generate the paradox, consider datasets that are exactly <span class="math inline">\(t_{\alpha}\)</span> standard errors away from <span class="math inline">\(\overline{y}\)</span>, that is, <span class="math inline">\(\overline {y}^{\ast}=\theta_{0}+\sigma t_{\alpha}/\sqrt{n}\)</span>, and a uniform prior over the interval <span class="math inline">\(\left( \theta_{0}-I/2,\theta_{0}+I/2\right)\)</span>. If <span class="math inline">\(p_{0}\)</span> is the probability of the null, then, <span class="math display">\[\begin{align*}
P \left(  \theta=\theta_{0} \mid \overline{y}^{\ast}\right)   &amp;
=\frac{\exp\left(  -\frac{1}{2}\frac{T\left(  \overline{y}^{\ast}-\theta
_{0}\right)  ^{2}}{\sigma^{2}}\right)  p_{0}}{\exp\left(  -\frac{1}{2}%
\frac{T\left(  \overline{y}^{\ast}-\theta_{0}\right)  ^{2}}{\sigma^{2}%
}\right)  p_{0}+\left(  1-p_{0}\right)  \int_{\theta_{0}-I/2}^{\theta_{0}%
+I/2}\exp\left(  -\frac{1}{2}\frac{T\left(  \overline{y}^{\ast}-\theta\right)
^{2}}{\sigma^{2}}\right)  I^{-1}d\theta}\\
&amp;  =\frac{\exp\left(  -\frac{1}{2}t_{\alpha}^{2}\right)  p_{0}}{\exp\left( -\frac{1}{2}t_{\alpha}^{2}\right)  p_{0}+\frac{\left(  1-p_{0}\right)  }%
{I}\int_{\theta_{0}-I/2}^{\theta_{0}+I/2}\exp\left(  -\frac{1}{2}\left( \frac{\left(  \overline{y}^{\ast}-\theta\right)  }{\sigma/\sqrt{T}}\right)^2
\right)  d\theta}\\
&amp;  \geq\frac{\exp\left(  -\frac{1}{2}t_{\alpha}^{2}\right)  p_{0}}{\exp\left( -\frac{1}{2}t_{\alpha}^{2}\right)  p_{0}+\frac{\left(  1-p_{0}\right)  }%
{I}\sqrt{2\pi\sigma^{2}/T}}\rightarrow1\text{ as }T\rightarrow\infty\text{.}%
\end{align*}\]</span> In large samples, the posterior probability of the null approaches 1, whereas Fisher always reject the null. It is important to note that this holds for any <span class="math inline">\(t_{\alpha}\)</span>, thus even if the test were performed at the 1% level or lower, the posterior probability would eventually reject the null.</p>
</div>
</section>
<section id="prior-sensitivity" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="prior-sensitivity"><span class="header-section-number">6.6</span> Prior Sensitivity</h2>
<p>One potential criticism of the previous examples is the choice of the prior distribution. How do we know that, somehow, the prior is not biased against rejecting the null generating the paradoxes? Under this interpretation, the problem is not with the <span class="math inline">\(p-\)</span>value but rather with the Bayesian procedure. One elegant way of dealing with the criticism is search over priors and prior parameters that minimize the probabability of the null hypothesis, thus biasing the Bayesian procedure against accepting the null hypothesis.</p>
<p>To see this, consider the case of testing <span class="math inline">\(H_{0}:\mu_{0}=0\)</span> vs.&nbsp;<span class="math inline">\(H_{1}:\mu_{0}\neq0\)</span> with observations drawn from <span class="math inline">\(y_{t} \sim\mathcal{N}\left( \theta_{0},\sigma^{2}\right)\)</span>, with <span class="math inline">\(\sigma\)</span> known. With equal prior null and alternative probability, the probability of the null is <span class="math inline">\(p\left( H_{0} \mid y\right) =\left( 1+\left( \mathrm{BF}_{0,1}\right) ^{-1}\right) ^{-1}\)</span>. Under the null, <span class="math display">\[
p\left(  y \mid H_{0}\right)  =\left(  \frac{1}{2\pi\sigma^{2}}\right)
^{\frac{T}{2}}\exp\left(  -\frac{1}{2}\left(  \frac{\left(  \overline
{y}-\theta_{0}\right)  }{\sigma/\sqrt{T}}\right)  ^{2}\right)  \text{.}%
\]</span> The criticism applies to the priors under the alternative. To analyze the sensitivity, consider four classes of priors under the alternative: (a) the class of normal priors, <span class="math inline">\(p\left( \theta \mid H_{1}\right) \sim\mathcal{N}\left( a,A\right)\)</span>; (b) the class of all symmetric unimodal prior distributions; (c) the class of all symmetric prior distributions; and (d) the class of all proper prior distributions. These classes provide varying degrees of prior information, allowing a thorough examination of the strength of evidence.</p>
<p>In the first case, consider the standard conjugate prior distribution, <span class="math inline">\(p\left( \mu \mid H_{1}\right) \sim\mathcal{N}\left( \mu_{0},A\right)\)</span>. Under the alternative, <span class="math display">\[\begin{align*}
p\left(  y \mid H_{1}\right)   &amp;  =\int p\left(  y \mid \mu,H_{1}\right)  p\left(  \mu \mid H_{1}\right)  d\mu\\
&amp;  =\int p\left(  \overline{y} \mid \mu,H_{1}\right)  p\left( \mu \mid H_{1}\right)  d\mu\text{,}%
\end{align*}\]</span> using the fact that <span class="math inline">\(\overline{y}\)</span> is a sufficient statistic. Noting that <span class="math inline">\(p\left( \overline{y} \mid \mu,H_{1}\right) \sim N\left( \mu ,\sigma^{2}/T\right)\)</span> and <span class="math inline">\(p\left( \mu \mid H_{1}\right) \sim N\left( \mu_{0},A\right)\)</span>, we can use the “substitute” instead of integrate trick to assert that <span class="math display">\[
\overline{y}=\mu_{0}+\sqrt{A}\eta+\sqrt{\sigma^{2}/T}\varepsilon\text{,}%
\]</span> where <span class="math inline">\(\eta\)</span> and <span class="math inline">\(\varepsilon\)</span> are standard normal. Then, <span class="math inline">\(p\left( \overline{y} \mid H_{1}\right) \sim\mathcal{N}\left( \mu_{0},A+\sigma^{2}/T\right)\)</span>. Thus, <span class="math display">\[
\mathrm{BF}_{0,1}=\frac{p\left(  y \mid H_{0}\right)  }{p\left( y \mid H_{1}\right)  }=\frac{p\left(  \overline{y} \mid H_{0}\right)
}{p\left(  \overline{y} \mid H_{1}\right)  }=\frac{\left(  \sigma^{2}/T\right)
^{-\frac{1}{2}}}{\left(  \sigma^{2}/T+A\right)  ^{-\frac{1}{2}}}\frac
{\exp\left(  -\frac{1}{2}t^{2}\right)  }{\exp\left(  -\frac{1}{2}\frac
{z^{2}\sigma^{2}/T}{A+\sigma^{2}/T}\right)  }\text{.} \label{BF_normal}%
\]</span> To operationalize the test, <span class="math inline">\(A\)</span> must be selected. <span class="math inline">\(A\)</span> is chosen to minimizing the posterior probabilities of the null, with <span class="math inline">\(P_{norm}\left( H_{0} \mid y\right)\)</span> being the resulting lower bound on the posterior probability of the null. For <span class="math inline">\(z\geq1\)</span>, the lower bound on the posterior probability of the null is <span class="math display">\[
P_{norm}\left(  H_{0} \mid y\right)  =\left[
1+\sqrt{e}\exp\left(  -.5t^{2}\right)  \right]  ^{-1},
\]</span> which is derived in a reference cited in the notes. This choice provides a maximal bias of the Bayesian approach toward rejecting the null. It is important to note that this is not a reasonable prior, as it was intentionally constructed to bias the null toward rejection.</p>
<p>For the class of all proper prior distributions, it is also easy to derive the bound. From equation above, minimizing the posterior probability is equivalent to minimizing the Bayes factor, <span class="math display">\[
\mathrm{BF}_{0,1}=\frac{p\left(  y \mid H_{0}\right)  }{p\left( y \mid H_{1}\right)  }\text{.}%
\]</span> Since <span class="math display">\[
p\left(  y \mid H_{1}\right)  =\int p\left(  y \mid \theta,H_{1}\right)  p\left(  \theta \mid H_{1}\right)  d\theta\leq p\left( y \mid \widehat{\theta}_{MLE},H_{1}\right)  \text{,}%
\]</span> where <span class="math inline">\(\widehat{\theta}_{MLE}=\arg\underset{\theta\neq0}{\max}p\left( y \mid \theta\right)\)</span>. The maximum likelihood estimator, maximizes the probability of the alternative, and provides a lower bound on the Bayes factor, <span class="math display">\[
\underline{\mathrm{BF}}_{0,1}=\frac{p\left(  y \mid H_{0}\right)
}{\underset{\theta\neq0}{\sup}p\left(  y \mid \theta\right)  }\text{.}%
\]</span> In this case, the bound is particularly easy to calculate and is given by <span class="math display">\[
P_{all}\left(  H_{0} \mid y\right)  =\left( 1+\exp\left(  -\frac{t^{2}}{2}\right)  \right)  ^{-1}\text{.}%
\]</span> A reference cited in the notes provides the bounds for the second and third cases, generating <span class="math inline">\(P_{s,u}\left( H_{0} \mid y\right)\)</span> and <span class="math inline">\(P_{s}\left( H_{0} \mid y\right)\)</span>, respectively. All of the bounds only depend on the <span class="math inline">\(t-\)</span>statistic and constants.</p>
<p><a href="#tbl-berger" class="quarto-xref">Table&nbsp;<span>6.2</span></a> reports the <span class="math inline">\(t-\)</span>statistics and associated <span class="math inline">\(p-\)</span>values, with the remaining columns provide the posterior probability bounds. For the normal prior and choosing the prior parameter <span class="math inline">\(A\)</span> to minimize the probability of the null, the posterior probability of the null is much larger than the <span class="math inline">\(p-\)</span>value, in every case. For the standard case of a <span class="math inline">\(t-\)</span>statistic of 1.96, <span class="math inline">\(P\left( H_{0} \mid y\right)\)</span> is more than six times greater than the <span class="math inline">\(p-\)</span>value. For <span class="math inline">\(t=2.576\)</span>, <span class="math inline">\(P\left( H_{0} \mid y\right)\)</span> is almost 13 times greater than the <span class="math inline">\(p-\)</span>value. These probabilities fall slightly for more general priors. For example, for the class of all priors, a t-statistic of 1.96/2.576 generates a lower bound for the posterior probability of 0.128/0.035<span class="math inline">\(,\)</span> more than 2/3 times the <span class="math inline">\(p-\)</span>value.</p>
<div id="tbl-berger" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-berger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Comparison of strength of evidence against the point null hypothesis. The numbers are reproduced from Berger (1986).
</figcaption>
<div aria-describedby="tbl-berger-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(t\)</span>-stat</th>
<th style="text-align: center;"><span class="math inline">\(p\)</span>-value</th>
<th style="text-align: center;"><span class="math inline">\(P_{norm}\left(H_{0} \mid y\right)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P_{s,u}\left( H_{0} \mid y\right)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P_{s}\left(H_{0} \mid y\right)\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P_{all}\left(H_{0} \mid y\right)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.645</td>
<td style="text-align: center;">0.100</td>
<td style="text-align: center;">0.412</td>
<td style="text-align: center;">0.39</td>
<td style="text-align: center;">0.34</td>
<td style="text-align: center;">0.205</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.960</td>
<td style="text-align: center;">0.050</td>
<td style="text-align: center;">0.321</td>
<td style="text-align: center;">0.29</td>
<td style="text-align: center;">0.227</td>
<td style="text-align: center;">0.128</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2.576</td>
<td style="text-align: center;">0.010</td>
<td style="text-align: center;">0.133</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">0.068</td>
<td style="text-align: center;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.291</td>
<td style="text-align: center;">0.001</td>
<td style="text-align: center;">0.0235</td>
<td style="text-align: center;">0.018</td>
<td style="text-align: center;">0.0088</td>
<td style="text-align: center;">0.0044</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="model-elaboration-and-nested-model-testing" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="model-elaboration-and-nested-model-testing"><span class="header-section-number">6.7</span> Model Elaboration and Nested Model Testing</h2>
<p>An <em>elaborated model</em> in Bayesian statistics refers to a model that extends or generalizes a simpler, baseline (or “underlying”) model by introducing additional parameters or structure. The purpose of elaboration is to capture more complex features of the data, account for possible deviations from the assumptions of the simpler model, or to allow for greater flexibility in modeling.</p>
<p>Formally, suppose we start with a baseline model <span class="math inline">\(f(y \mid \theta)\)</span>, where <span class="math inline">\(\theta\)</span> is a parameter of interest. An elaborated model introduces an additional parameter (or set of parameters) <span class="math inline">\(\lambda\)</span>, resulting in a family of models <span class="math inline">\(f(y \mid \theta, \lambda)\)</span> indexed by <span class="math inline">\(\lambda \in \Lambda\)</span>. The original model is recovered as a special case for some fixed value <span class="math inline">\(\lambda_0\)</span> (i.e., <span class="math inline">\(f(y \mid \theta) = f(y \mid \theta, \lambda_0)\)</span>). The set <span class="math inline">\(\Lambda\)</span> describes the ways in which the model can be elaborated.</p>
<p>When we use elaborated models then we need to compare nested models (where the simpler model is a special case of the more complex one). In Bayesian analysis, inference in an elaborated model involves integrating over the additional parameters, reflecting uncertainty about both the original and the elaborating parameters.</p>
<p>Applying the usual Bayesian paradigm (disciplined probability accounting) to the elaborated framework, we see that inference about <span class="math inline">\(\theta\)</span> is determined by <span class="math display">\[
p(\theta \mid y) = \int_\Lambda p(\theta \mid \lambda, y) p(\lambda \mid y) d\lambda
\]</span> where <span class="math display">\[
\begin{aligned}
p(\theta \mid \lambda, y) &amp;\propto p(y \mid \theta, \lambda) p(\theta \mid \lambda) \\
p(\lambda \mid y) &amp;\propto p(y \mid \lambda) p(\lambda) \\
\text{where } p(y \mid \lambda) &amp;= \int p(y \mid \theta, \lambda) p(\theta \mid \lambda) d\theta
\end{aligned}
\]</span></p>
<p>For consistency with the elaborated and underlying model, we take <span class="math inline">\(p(\theta \mid \lambda_0) = p(\theta)\)</span>. Since <span class="math inline">\(\lambda\)</span> labels the form of departure from the initial model <span class="math inline">\(M_0: \lambda = \lambda_0\)</span>, the form of <span class="math inline">\(p(\lambda)\)</span> should be chosen to reflect this departure.</p>
<p>A classical example is the exponential power elaboration of the traditional normal family, allowing for robustness. Here <span class="math inline">\(\lambda \in (0,3)\)</span> indexes the power and <span class="math inline">\(\lambda_0 = 2\)</span> is the Normal case.</p>
<p>The posterior mean is simply a weighted average with respect to <span class="math inline">\(p(\lambda \mid y)\)</span>: <span class="math display">\[
\E{\theta \mid y} = \int \E{\theta \mid \lambda, y} p(\lambda \mid y) d\lambda = \E[\lambda \mid y]{\E{\theta \mid \lambda, y}}
\]</span></p>
<section id="the-dickey-savage-approach-to-nested-models" class="level3">
<h3 class="anchored" data-anchor-id="the-dickey-savage-approach-to-nested-models">The Dickey-Savage Approach to Nested Models</h3>
<p>Suppose that <span class="math inline">\(M_0 \subset M\)</span>. Let <span class="math inline">\((\theta, \psi)\)</span> have matching priors such that <span class="math display">\[
p(\psi \mid \theta = 0, M) = p(\psi \mid M_0)
\]</span> where <span class="math inline">\(\theta = 0\)</span> corresponds to <span class="math inline">\(M_0\)</span>. That is, <span class="math inline">\(p(y \mid \theta = 0, \psi, M) = p(y \mid \psi, M_0)\)</span>.</p>
<p>Then, we can calculate <em>solely under model</em> <span class="math inline">\(M\)</span> the Bayes factor as follows: <span class="math display">\[
BF = \frac{p(\theta = 0 \mid y, M)}{p(\theta = 0 \mid M)} = \frac{p(y \mid M_0)}{p(y \mid M)}
\]</span></p>
<p>This is a ratio of posterior ordinates, valid as long as models are nested. By definition of marginals: <span class="math display">\[
\begin{aligned}
p(y \mid \theta = 0, M) &amp;= \int p(y \mid \theta = 0, \psi, M) p(\psi \mid \theta = 0, M) d\psi \\
&amp;= \int p(y \mid \psi, M_0) p(\psi \mid M_0) d\psi \\
&amp;= p(y \mid M_0)
\end{aligned}
\]</span></p>
<p>This elegant result shows that Bayes factors for nested models can be computed entirely within the larger model framework.</p>
</section>
</section>
<section id="the-difference-between-p-values-and-bayesian-evidence" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="the-difference-between-p-values-and-bayesian-evidence"><span class="header-section-number">6.8</span> The difference between p-values and Bayesian evidence</h2>
<p>Suppose that you routinely reject two-sided hypotheses at a fixed level of significance, <span class="math inline">\(\alpha = 0.05\)</span>. Furthermore, suppose that half the experiments under the null are actually true: <span class="math inline">\(p(H_0) = p(H_1) = \frac{1}{2}\)</span>.</p>
<p>The observed p-value is not a probability in any real sense. The observed t-value is a realization of a statistic that happens to be <span class="math inline">\(N(0,1)\)</span> under the null hypothesis. Suppose that we observe <span class="math inline">\(t = 1.96\)</span>.</p>
<p>Then the <em>maximal evidence</em> against the null hypothesis, which corresponds to <span class="math inline">\(t = 0\)</span>, will be achieved by evaluating the likelihood ratio at the observed t-ratio. We get <span class="math display">\[
\frac{p(y \mid H_0)}{p(y \mid H_1)} \geq \frac{p(y \mid \theta = \theta_0)}{p(y \mid \theta = \hat{\theta})}
\]</span></p>
<p>Technically, <span class="math inline">\(p(y \mid H_1) = \int p(y \mid \theta) p(\theta \mid H_1) d\theta \leq p(y \mid \hat{\theta})\)</span>.</p>
<p>For testing, this gives: <span class="math display">\[
\frac{p(y \mid H_0)}{p(y \mid H_1)} \geq \frac{\frac{1}{\sqrt{2\pi}} e^{-\frac{1}{2} \cdot 1.96^2}}{\frac{1}{\sqrt{2\pi}} e^{-\frac{1}{2} \cdot 0^2}} = 0.146
\]</span></p>
<p>In terms of probabilities, with <span class="math inline">\(p(H_0) = p(H_1)\)</span>, we have: <span class="math display">\[
p(H_0 \mid y) = \frac{1}{1 + \frac{p(y \mid H_1)}{p(y \mid H_0)} \frac{p(H_1)}{p(H_0)}} \geq 0.128
\]</span></p>
<p>Hence, there’s still a 12.8% chance that the null is true! That’s very different from the p-value of 5%.</p>
<p>Moreover, among experiments with p-values of 0.05, at least 30% will actually turn out to be true nulls! Put another way, the probability of rejecting a true null <em>conditional</em> on the observed <span class="math inline">\(p = 0.05\)</span> is at least 30%. You are throwing away good null hypotheses and claiming you have found effects!</p>
</section>
<section id="jeffreys-decision-rule" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="jeffreys-decision-rule"><span class="header-section-number">6.9</span> Jeffreys’ Decision Rule</h2>
<p>Jeffreys (1961) provided a famous rule for hypothesis testing. Consider testing <span class="math inline">\(H_0: \beta = 0\)</span> versus <span class="math inline">\(H_1: \beta \neq 0\)</span> with a t-statistic <span class="math inline">\(\frac{\hat{\beta}}{s_{\hat{\beta}}}\)</span>. Jeffreys proposed the rule: <span class="math display">\[
\frac{\hat{\beta}}{s_{\hat{\beta}}} &gt; \log\left(\frac{2n}{\pi}\right)
\]</span></p>
<p>This follows from a Bayes factor of <span class="math inline">\(BF = 1\)</span>, corresponding to a Cauchy <span class="math inline">\(C^+(0, \sigma)\)</span> prior. The critical relationship is: <span class="math display">\[
\sqrt{\frac{2n}{\pi}} \exp\left(-\frac{1}{2} \frac{\hat{\beta}^2}{s_{\hat{\beta}}^2}\right) = 1
\]</span></p>
<p>This follows from the Dickey-Savage density ratio: <span class="math display">\[
BF = \frac{p(\theta = 0 \mid y)}{p(\theta = 0)} = \frac{\sqrt{n/(2\pi\sigma)} e^{-\frac{1}{2}t^2}}{1/(\pi\sigma)}
\]</span></p>
<p>As the Cauchy prior has density ordinate <span class="math inline">\(p(\theta = 0) = 1/(\pi\sigma)\)</span>.</p>
<p>We have the following critical values, as opposed to the usual 1.96:</p>
<table class="caption-top table">
<caption>Jeffreys’ decision rule critical values</caption>
<thead>
<tr class="header">
<th><span class="math inline">\(n\)</span></th>
<th><span class="math inline">\(\hat{\beta}/\sigma_{\hat{\beta}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>1.16</td>
</tr>
<tr class="even">
<td>10</td>
<td>1.85</td>
</tr>
<tr class="odd">
<td>100</td>
<td>4.15</td>
</tr>
<tr class="even">
<td>100,000</td>
<td>11.06</td>
</tr>
</tbody>
</table>
<p>For instance, when <span class="math inline">\(n = 10\)</span>, we have <span class="math inline">\(\hat{\beta}/\sigma_{\hat{\beta}} = \log(20/\pi) = 1.85\)</span>, and for <span class="math inline">\(n = 100\)</span>, we have <span class="math inline">\(\hat{\beta}/\sigma_{\hat{\beta}} = \log(200/\pi) = 4.15\)</span>.</p>
<p>Jeffreys then explains the consequences of this sample-size dependence: traditional fixed critical values like 1.96 do not properly account for the evidence provided by larger sample sizes.</p>
</section>
<section id="cromwells-rule" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="cromwells-rule"><span class="header-section-number">6.10</span> Cromwell’s Rule</h2>
<p>The discussion of hypothesis testing throughout this chapter reveals a fundamental tension between the desire for certainty and the reality of uncertainty in statistical inference. This tension is captured by <strong>Cromwell’s Rule</strong>, a principle that serves as a philosophical foundation for Bayesian hypothesis testing.</p>
<p>We can write Bayes rule for updating models as follows: <span class="math display">\[
p(M \mid D) = \frac{p(D \mid M)}{p(D)} p(M)
\]</span></p>
<p>Hence if <span class="math inline">\(p(M) = 0\)</span>, then <span class="math inline">\(p(M \mid D) = 0\)</span> for all <span class="math inline">\(D\)</span>!</p>
<p>This mathematical result has profound implications: if you assign zero prior probability to a hypothesis, no amount of evidence can ever change your mind. The posterior probability remains zero regardless of how strongly the data might support that hypothesis.</p>
<p>This principle is named after Oliver Cromwell’s famous plea to the Church of Scotland in 1650:</p>
<blockquote class="blockquote">
<p><em>I beseech you, in the bowels of Christ, think it possible you may be mistaken</em></p>
</blockquote>
<p>Cromwell’s appeal for intellectual humility resonates deeply with the Bayesian approach to hypothesis testing. The rule suggests that we should never assign zero probability to hypotheses that could conceivably be true, as doing so makes us unable to learn from any amount of contradictory evidence.</p>
<p>The rule emphasizes the importance of careful prior specification. As we saw in the section on prior sensitivity, even when we try to bias our priors against the null hypothesis, the resulting posterior probabilities often remain substantially higher than corresponding p-values. Cromwell’s Rule reminds us that assigning zero probability to any reasonable hypothesis is not just mathematically problematic—it’s epistemologically unsound.</p>
<p>Cromwell’s Rule further aligns with the likelihood principle discussed earlier. Just as the likelihood principle states that all relevant experimental information is contained in the likelihood function, Cromwell’s Rule ensures that we remain open to learning from all possible evidence. By avoiding zero prior probabilities, we maintain the ability to update our beliefs based on observed data.</p>
<p>This principle serves as a philosophical foundation that unifies the various approaches to hypothesis testing discussed in this chapter, emphasizing the importance of intellectual humility and the willingness to learn from evidence in statistical inference.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-ab.html" class="pagination-link" aria-label="AB Testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">AB Testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-sp.html" class="pagination-link" aria-label="Stochastic Processes">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>