---
title: "Business Statistics 41000 - Booth MBA"
---

 
Instructor: [Vadim Sokolov](../../index.qmd) \
vadim.sokolov@chicagobooth.edu \
TA:  Ayman Moawad\
aymoawad@uchicago.edu\

**[Syllabus](syllabus.html)**\
**[Datasets](https://www.dropbox.com/sh/bvh3pkmlbwfv5qh/AAAK3D6F5HPN9hD7ExMh4dqGa?dl=0)**\ \
**[All examples](https://rpubs.com/dunduk/816606)**\

Course Textbook: OpenIntro Statistics [pdf](https://www.dropbox.com/s/2g08xr3s54qqzq9/openintro-statistics.pdf?dl=1), [tablet](https://www.dropbox.com/s/5fra8q8ifvu0f5z/os4_tablet.pdf?dl=1)

## Class Notes
- Section 1: Introduction and Probability: [notes](notes/41000section1E.pdf), [code](code/sec1.R)
-  Section 2: Statistics and Data: [notes](notes/41000section2E.pdf), [code](code/sec2.R sec2.R), [epl](code/epl-mu.R), [abtesting](code/abtesting.R)
- Section 3: Regression:  [notes](notes/41000section3E.pdf), [code](code/utils.R), [housing](code/housing.R), [mammals](code/mammals.R)
- Section 4: Classification: [notes](notes/41000section4E.pdf), [tree notes](notes/section7-trees.pdf) [newfood](code/newfood.R), [OJ](code/oj.R ), [PGA](code/pga.R pga.R), [Tennis](notes/tennis.html), [logistic](code/logistic.R)
- Section 5: AI and Deep Learning: [notes](notes/41000section5E.pdf), Examples: [MNIST](code/mnist.R);  [NN for Circle Data](code/nn-circle.R), [IMDB](notes/nlp-imdb.html), [Trump Tweets](notes/trump-tweets.html notebook), [trump-tweets.R](code/trump-tweets.R)


## HW
- [HW1](hw/hw1.pdf HW1) ([code](code/hwk1s.R))
- [HW2](hw/hw2.pdf HW2)  ([code](code/hwk2s.R))
- [HW3](hw/hw3.pdf HW3)  ([code](code/hwk3s.R))
- [HW4](hw/hw4.pdf HW4)  ([code](code/hwk4s.R)
- [Final Project](hw/bordeaux-project.pdf) ([code](code/project-starter.R))

## Midterm
- [Questions](hw/midterm/midtermBayes.pdf Bayes)
- [Questions](hw/midterm/midtermTF.pdf True/False)
- [Midterm 1](hw/midterm/exam1.pdf)
- [Midterm 2](hw/midterm/exam2.pdf)
- [Midterm 3](hw/midterm/midterm3.pdf )
- [Midterm 4](hw/midterm/midsol.pdf)
- [Midterm 5](hw/midterm/midterm5.pdf)
- [Midterm 6](hw/midterm/midtermsol.pdf)
- [Midterm 7](hw/midterm/midterm7.pdf)
- [Midterm 8](hw/midterm/midterm8.pdf)
- [Midterm 9](hw/midterm/midterm9.pdf)
- [Midterm 10](hw/midterm/midterm10.pdf)
- [Midterm 11](hw/midterm/midterm11.pdf)


## R
I made a quick introduciton to R, video is [here](https://youtu.be/Kh0AVf8LPNw ) and here are the [slides](https://rpubs.com/dunduk/733654).\

To get RStudio on you computer, you need to first download and install [RStudio](https://mirror.las.iastate.edu/CRAN/) then you need to download and install [R](https://rstudio.com/products/rstudio/download/).

Further,  I recommend doing those two courses on DataCamp. 

- [Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r )
- [Introduction to Data](https://www.datacamp.com/courses/introduction-to-data)\


In addition, Booth offers access to an online R tutorial on LinkedinLearning. To access the training, go to: [here](https://linkedinlearning.uchicago.edu) and login using your CNetID and password. You may find it helpful to work through the following R courses offered on LinkedInLearning:

- Code Clinic: R with Mark Niemann-Ross
- R Statistics Essential Training with Barton Poulson
- Up and Running with R with Barton Poulson

## Demos
- [Portfolio Variance](https://www.wolframcloud.com/obj/987d3af6-58d9-4902-811e-76765657148a)
- [Binomial](https://www.wolframcloud.com/obj/fd1f2a6c-9ce2-4428-a381-62cfbf9127d3)
- [Normal Distribution](https://www.wolframcloud.com/obj/e7f4f473-69e4-4508-b2a1-39bbb11c272f)


## Other Materials and Links
- [AI in Tennis](https://finance.yahoo.com/video/ibm-serving-ai-technology-tennis-150742376.html)
- [Kraft-Heinz blog store](https://builtin.com/artificial-intelligence/kraft-heinz-machine-learning-ai ) 
- [Kraft-Heinz WSJ](https://blogs.wsj.com/cio/2017/10/03/kraft-heinz-cio-spends-on-ai-robots-to-cut-costs/) 
- [Frito-Lay potato peeling](https://www.automationworld.com/products/data/blog/13319607/how-fritolay-applies-machine-learning )
- [Tyson](https://thefeed.blog/2018/11/07/tyson-foods-as-a-technology-company/ )
- [Anheuser-Busch InBev payments](https://www.wsj.com/articles/ab-inbev-taps-machine-learning-to-root-out-corruption-11579257001)
- [Walmart smart](https://corporate.wamart.com/newsroom/2019/04/25/walmarts-new-intelligent-retail-lab-shows-a-glimpse-into-the-future-of-retail-irl)
- [The State of Data Science and MachineLearning](https://www.kaggle.com/surveys/2017)
- [Model Interpretability](http://nautil.us/issue/40/learning/is-artificial-intelligence-permanently-inscrutable)
- [Data Sceince Survey](https://www.dropbox.com/s/dtpabgu0o9z5t8z/2015-data-science-salary-survey.pdf?dl=1)
- [J. M. Keynes's Investment Performance: A Note](https://www.dropbox.com/s/b34zjdupyc247v5/keynes.pdf?dl=1 )
- [Bayes Search](https://www.youtube.com/watch?v=WH-HWWkCMeU)
- [How Y'all (NY) Times](http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html)
- [Monte Hall](https://youtu.be/4Lb-6rxZxx0?si=TtNG25dPl_iV_rio)
- [EPL](../files/speigelhalter-EPL.pdf) 
- [Data Cleaning](https://whatsthebigdata.com/2016/05/01/data-scientists-spend-most-of-their-time-cleaning-data/)
- [Airbnb Random Forest](http://nerds.airbnb.com/unboxing-the-random-forest-classifier)
- [Facebook regrsssion](https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/) 
- [Youtube Deep learning](https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html)
- [Uber: time series](https://eng.uber.com/telematics/)
- [Exploratory Data Analysis](http://www.itl.nist.gov/div898/handbook/eda/eda.htm)
- [Overfitting](http://memosisland.blogspot.de/2017/08/understanding-overfitting-inaccurate.html)
- [2016 Election](https://arxiv.org/abs/1704.01171)

## Deep Learning
 - [Course by Jeremy Howard on coding aspects of deep learnig](http://course.fast.ai/ )
  - [Short introduction into deep leanring](https://youtu.be/vq2nnJ4g6N0)
  - [Architectures](http://www.asimovinstitute.org/neural-network-zoo/)
  - [Keras](https://keras.io/)
  - [ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)
 - [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html)
 - [Momentum](http://distill.pub/2017/momentum/)
 - [Backprop](http://cs231n.stanford.edu/slides/2016/winter1516_lecture4.pdf)



 