

## Business Statistics 41000: Syllabus

**Course Site:**[vsokolov.org\/courses\/41000](http://vsokolov.org/courses/41000)\
**Instructor**: Vadim Sokolov\
**Phone**: (815) 793 1428\
**Email**: vadim.sokolov@chicagobooth.edu


#### Course Information
This course focuses on the application of data analytics in business decisions. You will learn how to visualize data sets, use tools of statistics to gain insights and to predict. You will learn how to make decisions when future is uncertain. It covers both basic underlying concepts and practical computational skills.  We will apply those skills to analyze a variety of complex real-world problems.  The techniques covered include (i) graphical data visualization; (ii) probability and A/B testing; (iii) decisions under uncertainty; (iv) predictive models: linear, logistic and multiple regression; (v) deep learning

#### Lecture Notes
The course website provides a self-contained set of notes for the course and has datasets, R code, and midterm examples. 
 
I recommend [OpenIntro](https://www.openintro.org/stat/textbook.php) stats. It is free and available online!

#### Evaluation
Midterm 35\% \+  take-home final project 35\% \+ Homework 30\%.  \\

There are four homework assignments (every other week). Students are encouraged to form groups (of at most three) for homework. You can either submit as a group or individually. Homework assignments should be submitted online to Canvas and should have a clear and professional presentation. You can submit homework late with no penalty before they get graded (you are simply taking a chance that your HW won't be graded if submitted past due). Homeworks will be graded on a check plus, check, check minus basis.\\

The final take-home project can be done individually or in a group. The project will be graded 50\% on writing and presentation and 50\% on statistical analysis.\\

Re-grade requests should be written, detailing the reason for a re-grade. The whole exam will be subject to regrade. Regrade requests should be on a timely basis and are accepted up to a week after the work has been returned.


#### Computing
We will use R in the class. I recommend investing the time to learn R. The course website provides many resources to help you achieve this goal. R is the dominant software package for real world Predictive Analytics and is used throughout other courses. This open-source software is available for free download at www.r-project.org and you can find documentation there.\\

We will demonstrate data analysis in class. The website contains code filed for the code that generated the lecture notes. You may use either software for your project.


#### Prerequisites 
There are no prerequisites for the course. For a first class assignment reading the chapters 1-4 of the textbook will give you a good idea of the level of the class.

#### Schedule 
See course website.

\\\\
Students must adhere to our Booth Honor Code standards "I pledge my honor that I
have not violated the Honor Code during this examination or assignment".
