<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 1. Bayes AI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="01-hw_files/libs/clipboard/clipboard.min.js"></script>
<script src="01-hw_files/libs/quarto-html/quarto.js"></script>
<script src="01-hw_files/libs/quarto-html/popper.min.js"></script>
<script src="01-hw_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="01-hw_files/libs/quarto-html/anchor.min.js"></script>
<link href="01-hw_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-hw_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="01-hw_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="01-hw_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="01-hw_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 1. Bayes AI</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 1 (Joint Distributions)</strong></span> A credit card company collects data on <span class="math inline">\(10,000\)</span> users. The data contained two variables: an indicator of he customer status: whether they are in default (<code>def</code> =1) or if they are current with their payments (<code>def</code> =0). Moreover, they have a measure of their loan balance relative to income with three categories: a low balance (<code>bal</code>=1), medium (<code>bal</code>=2) and high (<code>bal</code>=3). The data are given in the following table:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: center;">def</td>
<td></td>
</tr>
<tr class="even">
<td>bal</td>
<td style="text-align: center;">0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>1</td>
<td style="text-align: center;">8,940</td>
<td>64</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: center;">651</td>
<td>136</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: center;">76</td>
<td>133</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Compute the marginal distribution of customer status</li>
<li>What is the conditional distribution of bal given <code>def</code> =1</li>
<li>Make a prediction for the status of a customer with a high balance</li>
</ol>
<p><strong>Solution</strong>:</p>
<ol type="a">
<li>The marginal distribution of customer status is given by the sum of the rows of the table.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">def0=</span><span class="fu">c</span>(<span class="dv">8940</span>,<span class="dv">651</span>,<span class="dv">76</span>),<span class="at">def1=</span><span class="fu">c</span>(<span class="dv">64</span>,<span class="dv">136</span>,<span class="dv">133</span>),<span class="at">row.names =</span> <span class="fu">c</span>(<span class="st">"bal1"</span>,<span class="st">"bal2"</span>,<span class="st">"bal3"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(d,<span class="dv">2</span>,sum)<span class="sc">/</span><span class="dv">10000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> def0  def1 
0.967 0.033 </code></pre>
</div>
</div>
<ol start="2" type="a">
<li>The conditional distribution of <code>bal</code> given <code>def</code> =1 is given by the ratio of the joint (elements of the table) to the marginal (sum of the <code>def</code> =1 column)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>d[,<span class="st">"def1"</span>]<span class="sc">/</span><span class="fu">sum</span>(d[,<span class="st">"def1"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.19 0.41 0.40</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>The prediction for the status of a customer with a high balance is the conditional distribution over <code>def</code> =1, given balance. <span class="math display">\[
P(def\mid bal) = \frac{P(def \text{ and } bal)}{P(bal)}
\]</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>balmarginal <span class="ot">=</span> <span class="fu">apply</span>(d,<span class="dv">1</span>,sum)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>d1b3 <span class="ot">=</span> d[<span class="st">"bal3"</span>,<span class="st">"def1"</span>]<span class="sc">/</span>balmarginal[<span class="st">"bal3"</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>d1b1 <span class="ot">=</span> d[<span class="st">"bal1"</span>,<span class="st">"def1"</span>]<span class="sc">/</span>balmarginal[<span class="st">"bal1"</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(d1b3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>bal3 
0.64 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(d1b1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bal1 
0.0071 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The ratio is </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>d1b3<span class="sc">/</span>d1b1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>bal3 
  90 </code></pre>
</div>
</div>
<p>Person with high balance has 63% chance of being in default, while a person with low balance has 0.7% chance of being in default, 90-times less likely!</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 2 (Marginal)</strong></span> The table below is taken from the Hoff text and shows the joint distribution of occupations taken from a 1983 study of social mobility by <span class="citation" data-cites="logan1983multivariate">Logan (<a href="#ref-logan1983multivariate" role="doc-biblioref">1983</a>)</span>. Each cell is P(father’s occupation, son’s occupation).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">farm =</span> <span class="fu">c</span>(<span class="fl">0.018</span>,<span class="fl">0.002</span>,<span class="fl">0.001</span>,<span class="fl">0.001</span>,<span class="fl">0.001</span>),<span class="at">operatives=</span><span class="fu">c</span>(<span class="fl">0.035</span>,<span class="fl">0.112</span>,<span class="fl">0.066</span>,<span class="fl">0.018</span>,<span class="fl">0.029</span>),<span class="at">craftsman=</span><span class="fu">c</span>(<span class="fl">0.031</span>,<span class="fl">0.064</span>,<span class="fl">0.094</span>,<span class="fl">0.019</span>,<span class="fl">0.032</span>),<span class="at">sales=</span><span class="fu">c</span>(<span class="fl">0.008</span>,<span class="fl">0.032</span>,<span class="fl">0.032</span>,<span class="fl">0.010</span>,<span class="fl">0.043</span>),<span class="at">professional=</span><span class="fu">c</span>(<span class="fl">0.018</span>,<span class="fl">0.069</span>,<span class="fl">0.084</span>,<span class="fl">0.051</span>,<span class="fl">0.130</span>), <span class="at">row.names =</span> <span class="fu">c</span>(<span class="st">"farm"</span>,<span class="st">"operative"</span>,<span class="st">"craftsman"</span>,<span class="st">"sales"</span>,<span class="st">"professional"</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>d <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">farm</th>
<th style="text-align: right;">operatives</th>
<th style="text-align: right;">craftsman</th>
<th style="text-align: right;">sales</th>
<th style="text-align: right;">professional</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">farm</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">operative</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">craftsman</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">sales</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">professional</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.13</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li>Find the marginal distribution of fathers’ occupations.</li>
<li>Find the marginal distribution of sons’ occupations.</li>
<li>Find the conditional distribution of the son’s occupation given that the father is a farmer.</li>
<li>Find the conditional distribution of the father’s occupation given that the son is a farmer.</li>
<li>Comment on these results. What do they say about changes in farming in the population from which these data are drawn?</li>
</ol>
<p><strong>Solution</strong>:</p>
<ol type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(d,<span class="dv">1</span>,sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        farm    operative    craftsman        sales professional 
       0.110        0.279        0.277        0.099        0.235 </code></pre>
</div>
</div>
<ol start="2" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(d,<span class="dv">2</span>,sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        farm   operatives    craftsman        sales professional 
       0.023        0.260        0.240        0.125        0.352 </code></pre>
</div>
</div>
<ol start="3" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>d[<span class="st">"farm"</span>,]<span class="sc">/</span><span class="fu">sum</span>(d[<span class="st">"farm"</span>,])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     farm operatives craftsman sales professional
farm 0.16       0.32      0.28 0.073         0.16</code></pre>
</div>
</div>
<ol start="4" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>d[,<span class="st">"farm"</span>]<span class="sc">/</span><span class="fu">sum</span>(d[,<span class="st">"farm"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.783 0.087 0.043 0.043 0.043</code></pre>
</div>
</div>
<ol start="5" type="a">
<li></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dd <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">son=</span><span class="fu">as.double</span>(d[<span class="st">"farm"</span>,]<span class="sc">/</span><span class="fu">sum</span>(d[<span class="st">"farm"</span>,])),<span class="at">father=</span><span class="fu">as.double</span>(d[,<span class="st">"farm"</span>]<span class="sc">/</span><span class="fu">sum</span>(d[,<span class="st">"farm"</span>])))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="at">height =</span> <span class="fu">t</span>(<span class="fu">as.matrix</span>(dd)),<span class="at">beside=</span><span class="cn">TRUE</span>,<span class="at">legend=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01-hw_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart allows us to visualize the marginal distributions of occupations of fathers and sons. The striking feature of this chart is that in the sons, the proportion of farmers has greatly decreased and the proportion of professionals has increased. From Part d, we see that of the sons who are farmers, 78% had fathers who are farmers. On the other hand, Part c shows that only 16% of the fathers who farmed produced sons who farmed. This is higher than the 2.3% of sons in the general population who became farmers, showing that sons of farmers went into farming at a rate higher than the general population of the study. However, most of the sons of farmers went into another profession. There was a great deal of movement out of farming and very little movement into farming from the fathers’ to the sons’ generation.</p>
<p>To determine the validity of inference outside the sample, we would need to know more about how the study was designed. We do not know how the sample was selected or what steps were taken to ensure it was representative of the population being studied. We also are not given the sample size, so we don’t know the accuracy of our probability estimates. The paper from which the table was taken, cited in the problem, provides more detail on the study.</p>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 3 (Joint and Conditional)</strong></span> A cable television company has <span class="math inline">\(10000\)</span> subscribers in a suburban community. The company offers two premium channels, HBO and Showtime. Suppose <span class="math inline">\(2750\)</span> subscribers receive HBO and <span class="math inline">\(2050\)</span> receive Showtime and <span class="math inline">\(6200\)</span> do not receive any premium channel.</p>
<ol type="a">
<li>What is the probability that a randomly selected subscriber receives both HBO and Showtime.</li>
<li>What is the probability that a randomly selected subscriber receives HBO but not Showtime.</li>
</ol>
<p>You now obtain a new dataset, categorized by gender, on the proportions of people who watch HBO and Showtime given below</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Cable</th>
<th style="text-align: left;">Female</th>
<th style="text-align: left;">Male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HBO</td>
<td style="text-align: left;">0.14</td>
<td style="text-align: left;">0.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Showtime</td>
<td style="text-align: left;">0.17</td>
<td style="text-align: left;">0.21</td>
</tr>
</tbody>
</table>
<ol start="3" type="a">
<li>Conditional on being female, what’s the probability you receive HBO?</li>
<li>Conditional on being female, what’s the probability you receive Showtime?</li>
</ol>
<p><strong>Solution</strong>:</p>
<ol type="a">
<li>We can calculate the number of people who receive both HBO and Showtime by calculating how many were “double counted” in the HBO and Showtime counts.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">10000</span> <span class="sc">-</span> <span class="dv">6200</span> <span class="sc">-</span> <span class="dv">2750</span> <span class="sc">-</span> <span class="dv">2050</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1000</code></pre>
</div>
</div>
<p>Thus, the answer is <span class="math inline">\(1000/10000 = 0.1\)</span>.</p>
<ol type="a">
<li><span class="math inline">\(\frac{2750-1000}{10000}=\frac{1750}{10000}=0.175\)</span></li>
<li><span class="math inline">\(P(HBO|F)=\frac{0.14}{0.14+0.17}=0.4516\)</span></li>
<li><span class="math inline">\(P(Show|F)=\frac{0.17}{0.14+0.17}=0.5484\)</span></li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 4 (Conditionals and Expectations)</strong></span> The following probability table describes the daily sales volume, <span class="math inline">\(X\)</span>, in thousands of dollars for a salesperson for the number of years <span class="math inline">\(Y\)</span> of sales experience for a particular company.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Y</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X</td>
<td style="text-align: center;">1</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr class="even">
<td>10</td>
<td style="text-align: center;">0.14</td>
<td>0.03</td>
<td>0.03</td>
<td>0</td>
</tr>
<tr class="odd">
<td>20</td>
<td style="text-align: center;">0.05</td>
<td>0.10</td>
<td>0.12</td>
<td>0.07</td>
</tr>
<tr class="even">
<td>30</td>
<td style="text-align: center;">0.10</td>
<td>0.06</td>
<td>0.25</td>
<td>0.05</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Verify that this is a legal probability table.</li>
<li>What is the probability of at least two years experience?</li>
<li>Calculate the mean daily sales volume</li>
<li>Given a salesperson has three years experience, calculate the mean daily sales volume.</li>
<li>A salesperson is paid $1000 per week plus 2% of total sales. What is the expected compensation for a salesperson?</li>
</ol>
<p><strong>Solution</strong>:</p>
<ol type="a">
<li>All probabilities are between zero and one, and the entire table adds to one</li>
<li><span class="math inline">\(P(Y\geq 2)=0.19+0.40+0.12=0.71\)</span></li>
<li><span class="math inline">\(E(X) = 10 \times 0.20 + 20 \times 0.34 + 30 \times 0.46 = 22.6\)</span>, that is $22,600</li>
<li>First, the conditional probability distribution <span class="math inline">\(p( X|Y)\)</span> is given by, <span class="math inline">\(0.03 /0.4 , 0.12/0.4 , 0.25/0.4\)</span>. Hence <span class="math inline">\(E(X|Y=3)=10\times 0.075+20\times 0.3+30\times 0.625=25.5,\)</span> that is $25,500</li>
<li>Assuming a 5-day workweek, <span class="math inline">\(E(Comp)=1000+0.02E(X_{1}+X_{2}+X_{3}+X_{4}+X_{5})=1000+0.02\cdot 5\cdot E(X)=1000+0.02\cdot 5\cdot 22600=\$3,260\)</span>. With a 7-day week, <span class="math inline">\(E(Comp)=1000+0.02\cdot 7\cdot 22600=\$4,164\)</span></li>
</ol>
</div>
<div id="exr-" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 5 (Marjorie Visit)</strong></span> Marjorie is worried about whether it is safe to visit a vulnerable relative during a pandemic. She is considering whether to take an at-home test for the virus before visiting her relative. Assume the test has sensitivity 85% and specificity 92%. That is, the probability that the test will be positive is about 85% if an individual is infected with the virus, and the probability that test will be negative is about 92% if an individual is not infected.</p>
<p>Further, assume the following losses for Marjorie</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Event</th>
<th style="text-align: left;">Loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Visit relative, not infected</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Visit relative, infected</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Do not visit relative, not infected</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Do not visit relative, infected</td>
<td style="text-align: left;">5</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Assume that about 2 in every 1,000 persons in the population is currently infected. What is the posterior probability that an individual with a positive test has the disease?</li>
<li>Suppose case counts have decreased substantially to about 15 in 100,000. What is the posterior probability that an individual with a positive test has the disease?</li>
<li>Suppose Marjorie is deciding whether to visit her relative and if so whether to test for the disease before visiting. If the prior probability that Marjorie has the disease is 200 in 100,000, find the policy that minimizes expected loss. That is, given each of the possible test results, should Marjorie visit her relative? Find the EVSI. Repeat for a prior probability of 15 in 100,000. Discuss.</li>
<li>For the decision of whether Marjorie should visit her relative, find the range of prior probabilities for which taking the at-home test results in lower expected loss than ignoring or not taking the test (assuming the test is free). Discuss your results.</li>
</ol>
<p><strong>Solution</strong>:</p>
<ol type="a">
<li>For a person in the given population, we have the following probabilities for the test outcome:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: left;">Positive</th>
<th style="text-align: left;">Negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Disease present</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease absent</td>
<td style="text-align: left;">0.08</td>
<td style="text-align: left;">0.92</td>
</tr>
</tbody>
</table>
<p>Prior Probability: P(Disease present) = 0.002 and P(Disease absent)=0.998</p>
<p>We can calculate the posterior probability that the individual has the disease as follows:</p>
<p>First, we calculate the probability of a positive test (this will be the denominator of Bayes Rule):</p>
<p>P(Positive) = P(Positive | Present) * P(Present)+P(Positive | Absent) * P(Absent) = 0.85<em>0.002 + 0.08</em>0.998 = 0.08154</p>
<p>Then, we calculate the posterior probability that the individual is has the disease by applying Bayes rule:</p>
<p>P(Present | Positive) = P(Positive | Present) * P(Present)/P(Positive) = 0.85*0.002/0.08154 = 0.0208</p>
<p>The posterior probability that an individual who tests positive has the disease is 0.0208.</p>
<ol start="2" type="a">
<li>The sensitivity and specificity of the test are the same as above:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Condition</th>
<th style="text-align: left;">Positive</th>
<th style="text-align: left;">Negative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Condition present0.85</td>
<td style="text-align: left;">0.15</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease absent</td>
<td style="text-align: left;">0.08</td>
<td style="text-align: left;">0.92</td>
</tr>
</tbody>
</table>
<p>But the prior probability is different:</p>
<p>P(Disease present) = 0.00015 and P(Disease absent)=0.99985</p>
<p>Again, we calculate the probability of a positive test (this will be the denominator of Bayes Rule):</p>
<p>P(Positive) = P(Positive | Present) * P(Present)+P(Positive | Absent) * P(Absent) = 0.85<em>0.00015 + 0.08</em>0.99985 = 0.0801155</p>
<p>Then, we calculate the posterior probability that the individual is has the disease by applying Bayes rule:</p>
<p>P(Present | Positive) = P(Positive | Present) * P(Present)/P(Positive) = 0.85*0.00015/0.0801155 = 0.00159</p>
<p>The posterior probability that an individual who tests positive has the disease is 0.00159.</p>
<p>In both cases, the posterior probability that the individual has the disease is small, even after taking the at-home test. But it is important to note that the probability has increased by more than a factor of 10, from 2 in 1000 to more than 2% in the first case, and from 15 in 100,000 to more than 15 in 10,000 in the second case. When the prior probability is lower, so is the posterior probability.</p>
<p>Some students who are inexperienced with Bayesian reasoning are surprised at how small the posterior probability is after a positive test. Untrained people often expect the probability to be closer to 85%, the sensitivity of the test. I have found that a good way to explain these results to people who have trouble with it is to ask them to imagine a population of 100,000 people. For part a, we would expect 200 have the disease. Of these, we expect about 85%, or 170 people, to test positive, and 15%, or only 30 people, to test negative. So the test identified most of the ill people. But now let’s consider the 99,800 people who do not have the disease. We expect only 8% of these to test positive, but this is 7984 people testing positive. We expect 92%, or 91,816 people, to test negative. Of those who test positive, 170 have the disease and 7,984 do not. So even though most ill people test positive and most well people test negative, because there are so many more people who do not have the disease, most of the ones testing positive actually do not have the disease.</p>
<p>A helpful way to visualize the role of the prior probability is to plot the posterior probability as a function of the prior probability (this was not required as part of the assignment). For prior probabilities near zero, a positive test increases the probability of the disease, but it remains very low because the positives are dominated by false positives. But once the prior probability reaches 10%, there is a better than even chance that someone testing positive has the disease; at a 20% prior probability, the posterior probability is over 70%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">seq</span>(<span class="fl">0.0001</span>, <span class="fl">0.2</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">=</span> <span class="fl">0.85</span><span class="sc">*</span>p<span class="sc">/</span>(<span class="fl">0.85</span><span class="sc">*</span>p <span class="sc">+</span> <span class="fl">0.08</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p, posterior, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlab =</span> <span class="st">"Prior Probability"</span>, <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01-hw_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="a">
<li>We will consider two different prior probabilities:</li>
</ol>
<p>High prevalence: P(Present) = 0.002 and P( Absent ) = 0.998<br>
Low prevalence: P(Present) = 0.00015 and P( Absent ) = 0.99985</p>
<p>To calculate EVSI, we do the following:</p>
<p>Calculate the expected loss if we do not do the test. To do this, we use the prior probability to calculate the expected loss if we visit and if we don’t. The minimum of these is the expected loss if we do not do the test.</p>
<p>EL[visit] = 100<em>p + 0</em>(1-p)<br>
EL[no visit] = 5<em>p + 1</em>(1-p)</p>
<p>Here, p is either 0.002 (part a) or 0.00015 (part b)</p>
<p>Calculate the expected loss if we do the test as follows:</p>
<ol type="a">
<li>Assume the test is positive. Using the posterior probability of disease, calculate the expected loss of visiting and not visiting. The minimum of these is the expected loss if the test is positive.</li>
<li>Assume the test is negative. Using the posterior probability of disease, calculate the expected loss of visiting and not visiting. The minimum of these is the expected loss if the test is negative.</li>
<li>Use the Law of Total Probability to find the probability of a positive test. (We already found this in Problems 1 and 2 – it’s the denominator of Bayes Rule.) Combine the results from a and b using the probability of disease as follows:<br>
E(L | test) = P(positive)E(L | positive)+P(negative)E(L | negative)</li>
</ol>
<p>Now, the EVSI is how much doing the test reduces our expected loss:</p>
<p>EVSI = E(L | no test) - E(L | test)</p>
<p>We will now apply these steps for the two base rates. The table below shows the results.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">High prevalence</th>
<th style="text-align: left;">Low prevalence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Probability of positive test</td>
<td style="text-align: left;">0.08154</td>
<td style="text-align: left;">0.08012</td>
</tr>
<tr class="even">
<td style="text-align: left;">Posterior probability of disease given positive test</td>
<td style="text-align: left;">0.0208</td>
<td style="text-align: left;">0.00159</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Posterior probability of disease given negative test</td>
<td style="text-align: left;">0.00033</td>
<td style="text-align: left;">0.0000245</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expected loss – no test</td>
<td style="text-align: left;">Visit: 0.2 No visit: 1.008</td>
<td style="text-align: left;">Visit: 0.015 No visit: 1.0006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expected loss if positive</td>
<td style="text-align: left;">Visit: 2.0849 No visit: 1.0834</td>
<td style="text-align: left;">Visit: 0.15915 No visit: 1.00637</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expected loss if negative</td>
<td style="text-align: left;">Visit: 0.03266 No visit: 1.00131</td>
<td style="text-align: left;">Visit: 0.00245 No visit: 1.0001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Expected loss with test</td>
<td style="text-align: left;">0.11834</td>
<td style="text-align: left;">0.015</td>
</tr>
<tr class="even">
<td style="text-align: left;">Expected loss – no test</td>
<td style="text-align: left;">Visit: 0.2 No visit: 1.008</td>
<td style="text-align: left;">Visit: 0.015 No visit: 1.0006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EVSI</td>
<td style="text-align: left;">0.2-0.11834 = 0.08166</td>
<td style="text-align: left;">0.015-0.015 = 0</td>
</tr>
</tbody>
</table>
<p>In the high prevalence case, it is better to test and follow the test result. The EVSI is 0.08166; there is 0.08166 lower loss from testing than from not testing. In the low prevalence case, however, the optimal decision is to visit no matter what the result of the test, because the posterior probability is so low even if the test is positive. Therefore, the expected loss is the same for doing or not doing the test because we ignore the test result and visit anyway. Therefore, the EVSI is zero in the low prevalence case.</p>
<ol start="4" type="a">
<li>Prior Probability: P(Disease present) = p and P( Disease absent ) = 1- p</li>
</ol>
<p>If we do not do the test, we cannot use the test result, so we have two choices: visit or do not visit. The expected loss of visiting is: E(L|V) = 100p + 0(1-p) = 100p<br>
The expected loss of not visiting (lose 5 if ill, 1 if not ill): E(L|N) = 5p + (1-p)</p>
<p>Now consider the strategy of doing the test and visiting if the test is negative. We get the following losses</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Patient status</th>
<th style="text-align: left;">Test result</th>
<th style="text-align: left;">Action</th>
<th style="text-align: left;">Loss (L)</th>
<th style="text-align: left;">Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No disease</td>
<td style="text-align: left;">Negative</td>
<td style="text-align: left;">visit</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">(1-p)*0.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">No disease</td>
<td style="text-align: left;">Positive</td>
<td style="text-align: left;">no visit</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">(1-p)*0.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Negative</td>
<td style="text-align: left;">visit</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">p*0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">Disease</td>
<td style="text-align: left;">Positive</td>
<td style="text-align: left;">no visit</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">p*0.85</td>
</tr>
</tbody>
</table>
<p>The total expected loss of this strategy is:<br>
E(L|T) = 0 + 1<em>0.08</em>(1-p) + 100<em>0.15</em>p + 5*0.85p = 0.08 + 19.17p</p>
<p>Find strategy regions. With a little algebra, we can find where the lines intersect and then find the regions of optimality. These are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 71%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Range</th>
<th style="text-align: left;">Policy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(0 \le p &lt; 0.00099\)</span></td>
<td style="text-align: left;">Optimal policy is visit regardless of test</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(0.00099 &lt; p &lt; 0.0606\)</span></td>
<td style="text-align: left;">Optimal policy is to do the test and visit if negative</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(0.0606 &lt; p \le 1\)</span></td>
<td style="text-align: left;">Optimal policy is to stay home regardless of test</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p>The graph below shows the plots of expected loss for the three policies. I show results only for probabilities up to 0.1 in order to have a better view of the results for small probabilities.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fu">seq</span>(<span class="fl">0.0001</span>, <span class="fl">0.1</span>, <span class="at">length.out =</span> <span class="dv">100</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ELV <span class="ot">=</span> <span class="dv">100</span><span class="sc">*</span>p</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>ELN <span class="ot">=</span> <span class="dv">5</span><span class="sc">*</span>p <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span>p)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>ELT <span class="ot">=</span> <span class="fl">0.08</span> <span class="sc">+</span> <span class="fl">19.17</span><span class="sc">*</span>p</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p, ELV, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlab =</span> <span class="st">"Prior Probability"</span>, <span class="at">ylab =</span> <span class="st">"Expected Loss"</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(p, ELN, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(p, ELT, <span class="at">col =</span> <span class="st">"green"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Visit"</span>, <span class="st">"No Visit"</span>, <span class="st">"Test and Visit if Negative"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>, <span class="st">"green"</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="01-hw_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Therefore, in the range of values 0.00099 &lt; p &lt; 0.0606, doing the test has lower expected loss than either just visiting or just staying home. For the high prevalence situation, the prior probability of 0.002 is larger than 0.00099 and lower than 0.0606, so it is optimal to take the test and follow the result. For the low prevalence situation, the prior probability of 0.00015 is below 0.00099, and it is optimal just to visit without considering the test. That is, in very low prevalence situations, there is no point in doing the test, because even if it is positive, the posterior probability would still be low enough that it is optimal to visit. On the other hand, if Marjorie is experiencing symptoms or knows she has been exposed, that would increase the probability of having the disease. Even in a low prevalence situation, if symptoms or exposure increase the prior probability to above 0.00099 but below 0.0606, then she should take the test and follow the result. If symptoms or exposure increase the prior probability to above 0.0606, then she should not bother with the test and just stay home.</p>
</div>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-logan1983multivariate" class="csl-entry" role="listitem">
Logan, John A. 1983. <span>“A Multivariate Model for Mobility Tables.”</span> <em>American Journal of Sociology</em> 89 (2): 324–49.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>