<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.37">

  <meta name="author" content="Vadim Sokolov   George Mason University   Spring 2025">
  <title>Bayes AI</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link rel="stylesheet" href="style.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="site_libs/quarto-diagram/mermaid.min.js"></script>
  <script src="site_libs/quarto-diagram/mermaid-init.js"></script>
  <link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="center">
  <h1 class="title" style="font-size:40px;">Bayes AI</h1>
  <p class="subtitle" style="color:blue;font-size:50px;">Unit 6: Markov Chain Monte Carlo</p>
<img style="height: 350px;" src="fig/page/07-mcmc.jpg">
  <p class="author">Vadim Sokolov <br> George Mason University <br> Spring 2025</p>

<p style="font-size:10px;"> 
<a href="https://vsokolov.org/courses/664.html">Course Page</a>, <a href="https://vsokolov.org/html/664/slides/">Slides</a>
</p>


</section>
<section id="mcmc-simulation" class="slide level2">
<h2>MCMC Simulation</h2>
<p>Suppose that <span class="math inline">\(X \sim F_X ( x )\)</span> and let <span class="math inline">\(Y = g (X)\)</span>.</p>
<p>How do we find <span class="math inline">\(F_Y ( y )\)</span> and <span class="math inline">\(f_Y ( y )\)</span> ?</p>
<ul>
<li>von Neumann</li>
</ul>
<p>Given a uniform <span class="math inline">\(U\)</span>, how do we find <span class="math inline">\(X= g(U)\)</span>?</p>
<ul>
<li>In the bivariate case <span class="math inline">\((X,Y) \rightarrow (U,V)\)</span>.</li>
</ul>
<p>We need to find <span class="math inline">\(f_{(U,V)} ( u , v )\)</span> from <span class="math inline">\(f_{X,Y}(x,y)\)</span></p>
<ul>
<li>Applications: Simulation, MCMC and PF.</li>
</ul>
</section>
<section id="transformations" class="slide level2">
<h2>Transformations</h2>
<p>The cdf identity gives <span class="math display">\[
F_Y ( y) = \mathbb{P} ( Y \leq y ) = \mathbb{P} ( g( X) \leq y )
\]</span></p>
<ul>
<li>Hence if the function <span class="math inline">\(g ( \cdot )\)</span> is monotone we can invert to get</li>
</ul>
<p><span class="math display">\[
F_Y ( y ) = \int_{ g( x) \leq y } f_X ( x ) dx
\]</span></p>
<ul>
<li>If <span class="math inline">\(g\)</span> is increasing <span class="math inline">\(F_Y ( y ) = P( X \leq g^{-1} ( y ) ) = F_X ( g^{-1} ( y ) )\)</span></li>
</ul>
<p>If <span class="math inline">\(g\)</span> is decreasing <span class="math inline">\(F_Y ( y ) = P( X \geq g^{-1} ( y ) ) = 1 - F_X ( g^{-1} ( y ) )\)</span></p>
</section>
<section id="transformation-identity" class="slide level2 scrollable">
<h2>Transformation Identity</h2>
<ol type="1">
<li>Theorem 1: Let <span class="math inline">\(X\)</span> have pdf <span class="math inline">\(f_X ( x)\)</span> and let <span class="math inline">\(Y=g(X)\)</span>. Then if <span class="math inline">\(g\)</span> is a monotone function we have</li>
</ol>
<p><span class="math display">\[
f_Y ( y) = f_X ( g^{-1} ( y ) ) \left  | \frac{ d}{dy}  g^{-1} ( y ) \right |
\]</span> There’s also a multivariate version of this that we’ll see later.</p>
<ul>
<li><p>Suppose <span class="math inline">\(X\)</span> is a continuous rv, what’s the pdf for <span class="math inline">\(Y = X^2\)</span>?</p></li>
<li><p>Let <span class="math inline">\(X \sim N ( 0 ,1 )\)</span>, what’s the pdf for <span class="math inline">\(Y = X^2\)</span>?</p></li>
</ul>
</section>
<section id="probability-integral-transform" class="slide level2">
<h2>Probability Integral Transform</h2>
<p>theorem Suppose that <span class="math inline">\(U \sim U[0,1]\)</span>, then for any continuous distribution function <span class="math inline">\(F\)</span>, the random variable <span class="math inline">\(X= F^{-1} (U)\)</span> has distribution function <span class="math inline">\(F\)</span>.</p>
<ul>
<li>Remember that for <span class="math inline">\(u \in [0,1]\)</span>, <span class="math inline">\(\mathbb{P} \left ( U \leq u \right ) = u\)</span>, so we have</li>
</ul>
<p><span class="math display">\[
\mathbb{P} \left (X \leq x \right )= \mathbb{P} \left ( F^{-1} (U) \leq x \right )= \mathbb{P} \left ( U \leq F(x) \right )=F(x)
\]</span> Hence, <span class="math inline">\(X = F_X^{-1}(U)\)</span>.</p>
</section>
<section id="normal" class="slide level2">
<h2>Normal</h2>
<p>Sometimes thare are short-cut formulas to generate random draws</p>
<p>Normal <span class="math inline">\(N(0,I_2)\)</span>: <span class="math inline">\(x_1,x_2\)</span> uniform on <span class="math inline">\([0,1]\)</span> then <span class="math display">\[
\begin{aligned}
y_1 = &amp; \sqrt{-2\log x_1}\cos(2\pi x_2)\\
y_2 = &amp; \sqrt{-2\log x_1}\sin(2\pi x_2)
\end{aligned}
\]</span></p>
</section>
<section id="simulation-and-transformations" class="slide level2">
<h2>Simulation and Transformations</h2>
<p>An important application is how to transform multiple random variables?</p>
<ul>
<li>Suppose that we have random variables:</li>
</ul>
<p><span class="math display">\[
( X , Y ) \sim  f_{ X , Y} ( x , y )
\]</span> A transformation of interest given by: <span class="math display">\[
U = g ( X , Y )
\; \; {\rm and} \; \;
V = h ( X , Y )
\]</span></p>
<ul>
<li>The problem is how to compute <span class="math inline">\(f_{ U , V } ( u , v )\)</span> ? Jacobian</li>
</ul>
<p><span class="math display">\[
J = \frac{ \partial ( x , y ) }{ \partial ( u , v ) }  = \left |  \begin{array}{cc}
\frac{ \partial x }{ \partial u} &amp; \frac{ \partial x }{ \partial v} \\
\frac{ \partial y }{ \partial u} &amp; \frac{ \partial y }{ \partial v}
\end{array} \right |
\]</span></p>
</section>
<section id="bivariate-change-of-variable" class="slide level2">
<h2>Bivariate Change of Variable</h2>
<ul>
<li><em>Theorem:</em> (change of variable)</li>
</ul>
<p><span class="math display">\[
f_{ U , V } ( u , v ) = f_{ X , Y} ( h_1 ( u , v )  , h_2 ( u , v ) )
\left |  \frac{ \partial ( x , y ) }{ \partial ( u , v ) } \right |
\]</span> The last term is the Jacobian.</p>
<p>This can be calculated in two ways.</p>
<p><span class="math display">\[
\left |  \frac{ \partial ( x , y ) }{ \partial ( u , v ) } \right | =
1 / \left |  \frac{ \partial ( u , v ) }{ \partial ( x , y ) } \right |
\]</span></p>
<ul>
<li>So we don’t always need the inverse transformation <span class="math inline">\(( x , y ) = ( g^{-1} ( u , v )  , h^{-1} ( u , v ) )\)</span></li>
</ul>
</section>
<section id="inequalities-and-identities" class="slide level2 smaller scrollable">
<h2>Inequalities and Identities</h2>
<ol type="1">
<li>Markov</li>
</ol>
<p><span class="math display">\[
\mathbb{P} \left ( g( X ) \geq c \right ) \leq \frac{ \mathbb{E} ( g(X) ) }{c }
\; \; {\rm  where} \; \;   g( X) \geq 0
\]</span></p>
<ol start="2" type="1">
<li>Chebyshev</li>
</ol>
<p><span class="math display">\[
\mathbb{P} \left ( | X - \mu | \geq c \right ) \leq \frac{ Var(X) }{c^2 }
\]</span></p>
<ol start="3" type="1">
<li>Jensen</li>
</ol>
<p><span class="math display">\[
\mathbb{E} \left ( \phi ( X ) \right ) \leq \phi \left ( \mathbb{E}( X ) \right )
\]</span></p>
<ol start="4" type="1">
<li>Cauchy-Schwarz <span class="math display">\[
corr (X,Y) \leq 1
\]</span></li>
</ol>
<p>Chebyshev follows from Markov. Mike Steele and Cauchy-Schwarz.</p>
</section>
<section id="markov-inequality" class="slide level2">
<h2>Markov Inequality</h2>
<p>Let <span class="math inline">\(f\)</span> be non-decreasing <span class="math display">\[
\begin{aligned}
P ( Z &gt; t ) &amp;= P ( f(Z) \geq f(t) ) \\
&amp; = E \left (  \mathbb{I}  ( f( Z) \geq f(t )  ) \right ) \\
&amp; \leq E \left (  \mathbb{I}  ( f( Z) \geq f(t ) )  \frac{f(Z)}{f(t) }  \right ) \\
&amp; =  E\left  (  \frac{f(Z)}{f(t) }  \right )
\end{aligned}
\]</span></p>
</section>
<section id="concentration-inequalities" class="slide level2">
<h2>Concentration Inequalities</h2>
<p>Law of Large Numbers <span class="math display">\[
\lim_{ n \rightarrow \infty } \mathbb{P} \left ( | Z - E(Z) | &gt; n \epsilon  \right ) = 0 \; \; \forall \epsilon &gt; 0
\]</span></p>
<p>Central Limt Theorem (CLT) <span class="math display">\[
\lim_{ n \rightarrow \infty } \mathbb{P} \left ( n^{- 1/2} ( | Z - E(Z) |  ) &gt;  \epsilon  \right ) = \Phi ( x )
\]</span></p>
<p>Posterior Concentration</p>
</section>
<section id="hoeffding-and-bernstein" class="slide level2">
<h2>Hoeffding and Bernstein</h2>
<p>Let <span class="math inline">\(Z= \sum_{i=1}^n X_i\)</span>.</p>
<p>Hoeffding <span class="math display">\[
P ( Z &gt; E(Z) +  t ) \leq \exp \left  ( - \frac{ t^2}{2n} \right )
\]</span></p>
<p>Bernstein <span class="math display">\[
P ( Z &gt; E(Z) +  t ) \leq \exp  \left ( - \frac{ t^2}{ 2 ( Var(Z) + t/3 ) } \right )
\]</span> Large Deviations (Varadhan)</p>
</section>
<section id="special-distributions" class="slide level2 scrollable">
<h2>Special Distributions</h2>
<p>See <em>Common Distributions</em></p>
<ol type="1">
<li><p>Bernoulli and Binomial</p></li>
<li><p>Hypergeometric</p></li>
<li><p>Poisson</p></li>
<li><p>Negative Binomial</p></li>
<li><p>Normal Distribution</p></li>
<li><p>Gamma Distribution</p></li>
<li><p>Beta Distribution</p></li>
<li><p>Multinomial Distribution</p></li>
<li><p>Bivariate Normal Distribution</p></li>
<li><p>Wishart Distribution</p></li>
</ol>
<p><span class="math inline">\(\ldots\)</span></p>
</section>
<section id="example-markov-dependence" class="slide level2">
<h2>Example: Markov Dependence</h2>
<ul>
<li>We can always factor a joint distribution as</li>
</ul>
<p><span class="math display">\[
p( X_n , X_{n-1} , \ldots , X_1 )  = p( X_n | X_{n-1} , \ldots , X_1 ) \ldots p( X_2 | X_1 ) p( X_1 )
\]</span></p>
<ul>
<li>A process has the <em>Markov Property</em> if</li>
</ul>
<p><span class="math display">\[
p( X_n | X_{n-1} , \ldots , X_1 ) = p( X_n | X_{n-1} )
\]</span></p>
<ul>
<li>Only the current history matter when determining the probabilities.</li>
</ul>
</section>
<section id="a-real-world-probability-model-hidden-markov-models" class="slide level2">
<h2>A real world probability model: Hidden Markov Models</h2>
<p>Are stock returns a random walk?</p>
<p>Hidden Markov Models (Baum-Welch, Viterbi)</p>
<ul>
<li>Daily returns on the SP500 stock market index.</li>
</ul>
<p>Build a hidden Markov model to predict the ups and downs.</p>
<ul>
<li><p>Suppose that stock market returns on the next four days are <span class="math inline">\(X_1 , \ldots , X_4\)</span>.</p></li>
<li><p>Let’s empirical determine conditionals and marginals</p></li>
</ul>
</section>
<section id="sp500-data" class="slide level2">
<h2>SP500 Data</h2>
<p>Marginal and Bivariate Distributions</p>
<ul>
<li>Empirically, what do we get? Daily returns from <span class="math inline">\(1948-2007\)</span>.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(x\)</span></th>
<th style="text-align: center;">Down</th>
<th style="text-align: center;">Up</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P( X_i ) = x\)</span></td>
<td style="text-align: center;">0.474</td>
<td style="text-align: center;">0.526</td>
</tr>
</tbody>
</table>
<ul>
<li>Finding <span class="math inline">\(p( X_2 | X_1 )\)</span> is twice as much computational effort: counting <span class="math inline">\(UU,UD,DU,DD\)</span> transitions.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(X_i\)</span></th>
<th style="text-align: left;">Down</th>
<th style="text-align: center;">Up</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(X_{i-1} = Down\)</span></td>
<td style="text-align: left;">0.519</td>
<td style="text-align: center;">0.481</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(X_{i-1} = Up\)</span></td>
<td style="text-align: left;">0.433</td>
<td style="text-align: center;">0.567</td>
</tr>
</tbody>
</table>
</section>
<section id="conditioned-on-two-days" class="slide level2">
<h2>Conditioned on two days</h2>
<ul>
<li>Let’s do <span class="math inline">\(p( X_3 | X_2 , X_1 )\)</span></li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"><span class="math inline">\(X_{i-2}\)</span></th>
<th style="text-align: left;"><span class="math inline">\(X_{i-1}\)</span></th>
<th style="text-align: left;">Down</th>
<th style="text-align: center;">Up</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Down</td>
<td style="text-align: left;">Down</td>
<td style="text-align: left;">0.501</td>
<td style="text-align: center;">0.499</td>
</tr>
<tr class="even">
<td style="text-align: left;">Down</td>
<td style="text-align: left;">Up</td>
<td style="text-align: left;">0.412</td>
<td style="text-align: center;">0.588</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Up</td>
<td style="text-align: left;">Down</td>
<td style="text-align: left;">0.539</td>
<td style="text-align: center;">0.461</td>
</tr>
<tr class="even">
<td style="text-align: left;">Up</td>
<td style="text-align: left;">Up</td>
<td style="text-align: left;">0.449</td>
<td style="text-align: center;">0.551</td>
</tr>
</tbody>
</table>
<ul>
<li>We could do the distribution <span class="math inline">\(p( X_2 , X_3 | X_1 )\)</span>. This is a joint, marginal and conditional distribution all at the same time.</li>
</ul>
<p><em>Joint</em> because more than one variable <span class="math inline">\(( X_2 , X_3 )\)</span>, <em>marginal</em> because it ignores <span class="math inline">\(X_4\)</span> and <em>conditional</em> because its given <span class="math inline">\(X_1\)</span>.</p>
</section>
<section id="joint-probabilities" class="slide level2">
<h2>Joint Probabilities</h2>
<ul>
<li><p>Under Markov dependence <span class="math display">\[
\begin{aligned}
P( UUD ) &amp; = p( X_1 = U) p( X_2 = U | X_1 = U) p( X_3 | X_2 = U , X_1 = U ) \\
&amp; = ( 0.526 ) ( 0.567 ) ( 0.433)
\end{aligned}
\]</span></p></li>
<li><p>Under independence we would have got <span class="math display">\[
\begin{aligned}
P(UUD) &amp; = P( X_1 = U) p( X_2 = U) p( X_3 = D ) \\
&amp; = (.526)(.526)(.474) \\
&amp; = 0.131
\end{aligned}
\]</span></p></li>
</ul>
</section>
<section id="markov-chain-monte-carlo" class="slide level2">
<h2>Markov Chain Monte Carlo</h2>
<ul>
<li>Think od shuffling problem</li>
<li>There are 52! possible permutations of this deck.</li>
<li>Naive approach: generate a vector with all possible permutations and draw an element of this vector with probability 1/52!.</li>
</ul>
<div style="margin-top: 50; font-size: 2em; color: red; text-align: center">
<p><span class="math inline">\(52! \approx 10^{68}\)</span></p>
</div>
<p>slightly less then number of particles in the observed universe (<span class="math inline">\(10^{80}\)</span>).</p>
</section>
<section id="bayes-rule" class="slide level2">
<h2>Bayes rule</h2>
<p><span class="math display">\[
p(\theta \mid X,Y) = \dfrac{p(Y \mid \theta,X)p(\theta)}{\int p(Y \mid \theta,X)p(\theta)d\theta}.
\]</span></p>
<ul>
<li>MCMC algorithms generate a Markov chain <span class="math display">\[
\left\{ \theta ^{\left( g\right)}\right\} _{g=1}^{G}
\]</span> whose stationary distribution is <span class="math inline">\(p\left( \theta \mid X,Y\right)\)</span>. Thus, the key to Bayesian inference is simulation rather than optimization.</li>
</ul>
<p><span class="math display">\[
\begin{split}
\widehat{E}\left( f\left( \theta\right)  \mid X,Y\right)&amp;=G^{-1}\sum_{g=1}^{G}f\left( \theta ^{\left( g\right) }\right)\\
&amp; \approx \int f\left( \theta\right) p\left( \theta \mid X,Y\right)d\theta=E\left( f\left( \theta\right)  \mid X,Y\right).
\end{split}
\]</span></p>
</section>
<section id="mcmc-for-discrete-random-variables" class="slide level2">
<h2>MCMC for Discrete Random Variables</h2>
<p><span class="math display">\[
P(X_{k+1} = i \mid X_k = j) = p_{ij}.
\]</span></p>
<ul>
<li>Transition matrix <span class="math inline">\(P = \{p_{ij}\}_{i,j=1}^n\)</span> is column stochastic, i.e.&nbsp;<span class="math inline">\(p_{ij} \ge 0\)</span> and <span class="math inline">\(\sum_j p_{ij} = 1\)</span>.</li>
<li>Let <span class="math inline">\(\pi_k \in R^n\)</span> be the distribution of the random variable <span class="math inline">\(X_k\)</span> at time <span class="math inline">\(k\)</span>, <span class="math inline">\(\pi_{ki} = P(X_k=i)\)</span></li>
<li><span class="math inline">\(\pi_{k+1} = P\pi_k\)</span>.</li>
<li>The limiting distribution is <span class="math inline">\(\pi = P\pi\)</span>, i.e.&nbsp;<span class="math inline">\(\pi\)</span> is an eigenvector of <span class="math inline">\(P\)</span> with eigenvalue 1.</li>
<li>The limiting distribution is unique and it is the first eigenvector of <span class="math inline">\(P\)</span>. The limiting distribution is also called a stationary distribution.</li>
</ul>
</section>
<section id="mcmc-for-discrete-random-variables-1" class="slide level2">
<h2>MCMC for Discrete Random Variables</h2>
<ul>
<li>Power method <span class="math inline">\(\pi^{k+1} = P^k\pi^0\)</span> to <span class="math inline">\(\pi\)</span> (Google’s PageRank).</li>
<li>Perron-Frobenius theorem: if <span class="math inline">\(p_{ij}&gt;0\)</span> then <span class="math inline">\(\pi\)</span> always exists and it is unique and <span class="math display">\[
\Vert \pi^k - \pi\Vert \le c |\lambda_2|^k,
\]</span></li>
<li><span class="math inline">\(\lambda_2\)</span> is the second largest eigenvalue of <span class="math inline">\(P\)</span> (the first eigenvalue is always 1) - <span class="math inline">\(\pi\)</span> as the average time of visiting vertex <span class="math inline">\(i\)</span> under random walk.</li>
</ul>
<p>The mixing time of the Markov chain is given by <span class="math display">\[
T=\dfrac{1}{\log(1/\lambda_2)}
\]</span> It is roughly, number of steps over which deviation from equilibrium distribution decreases by factor <span class="math inline">\(e\)</span>.</p>
</section>
<section id="three-state-example" class="slide level2">
<h2>Three-State Example</h2>
<div class="cell" data-reveal="true" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource default number-lines code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a></a>graph LR</span>
<span id="cb1-2"><a></a>    1 --0.5--&gt; 1</span>
<span id="cb1-3"><a></a>    1 --0.25--&gt; 2</span>
<span id="cb1-4"><a></a>    1 --0.25--&gt; 3</span>
<span id="cb1-5"><a></a>    2 --0.2--&gt; 1</span>
<span id="cb1-6"><a></a>    2 --0.1--&gt; 2</span>
<span id="cb1-7"><a></a>    2 --0.7--&gt; 3</span>
<span id="cb1-8"><a></a>    3 --0.25--&gt; 2</span>
<span id="cb1-9"><a></a>    3 --0.25--&gt; 1</span>
<span id="cb1-10"><a></a>    3 --0.5--&gt; 3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">graph LR
    1 --0.5--&gt; 1
    1 --0.25--&gt; 2
    1 --0.25--&gt; 3
    2 --0.2--&gt; 1
    2 --0.1--&gt; 2
    2 --0.7--&gt; 3
    3 --0.25--&gt; 2
    3 --0.25--&gt; 1
    3 --0.5--&gt; 3
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a> P <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.2</span>, <span class="fl">0.25</span>),</span>
<span id="cb2-2"><a></a>            <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.1</span>, <span class="fl">0.25</span>),</span>
<span id="cb2-3"><a></a>            <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.7</span>, <span class="fl">0.50</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check that it is column-stochastic</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a> <span class="fu">colSums</span>(P)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 1</code></pre>
</div>
</div>
</section>
<section id="power-iterations" class="slide level2">
<h2>Power Iterations</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="co"># Power iterations</span></span>
<span id="cb5-2"><a></a>iterate.P <span class="ot">&lt;-</span> <span class="cf">function</span>(x, P, n) {</span>
<span id="cb5-3"><a></a>    res <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, n<span class="sc">+</span><span class="dv">1</span>, <span class="fu">length</span>(x))</span>
<span id="cb5-4"><a></a>    res[<span class="dv">1</span>,] <span class="ot">&lt;-</span> x</span>
<span id="cb5-5"><a></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n)</span>
<span id="cb5-6"><a></a>        res[i<span class="sc">+</span><span class="dv">1</span>,] <span class="ot">&lt;-</span> x <span class="ot">&lt;-</span> P <span class="sc">%*%</span> x</span>
<span id="cb5-7"><a></a>    res</span>
<span id="cb5-8"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s start with a random vector <span class="math inline">\(x = (1, 0, 0)\)</span> and iterate <span class="math inline">\(x \leftarrow P x\)</span> for <span class="math inline">\(n=10\)</span> steps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>n  <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb6-2"><a></a>y <span class="ot">=</span> <span class="fu">iterate.P</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>), P, n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="power-iterations-1" class="slide level2">
<h2>Power Iterations</h2>
<p>We can compare the results to the eigenvector calculated using built-in (QR decomposition-based) method</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>v <span class="ot">&lt;-</span> <span class="fu">eigen</span>(P, <span class="cn">FALSE</span>)<span class="sc">$</span>vectors[,<span class="dv">1</span>]</span>
<span id="cb7-2"><a></a>v <span class="ot">&lt;-</span> v<span class="sc">/</span><span class="fu">sum</span>(v) <span class="co"># normalize eigenvector</span></span>
<span id="cb7-3"><a></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(v, y[n<span class="sc">+</span><span class="dv">1</span>,]), <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">"Eigenvector"</span>, <span class="st">"Power iterations"</span>), <span class="at">digits=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Eigenvector</th>
<th style="text-align: right;">Power iterations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.32</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.46</td>
</tr>
</tbody>
</table>
<p>Power iterations convergence to eigenvector. Each color corresponds to a component of the eigenvector (stationary distribution vector)</p>
</div>
</div>
</section>
<section id="power-iterations-2" class="slide level2">
<h2>Power Iterations</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">matplot</span>(<span class="dv">0</span><span class="sc">:</span>n, y, <span class="at">type=</span><span class="st">"l"</span>, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">xlab=</span><span class="st">"Step"</span>, <span class="at">ylab=</span><span class="st">"y"</span>, <span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb8-2"><a></a><span class="fu">abline</span>(<span class="at">h=</span>v, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="power-iterations-3" class="slide level2">
<h2>Power Iterations</h2>
<p>We can also find the stationary distribution by doing a simple random walk on the graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>run <span class="ot">&lt;-</span> <span class="cf">function</span>(i, P, n) {</span>
<span id="cb9-2"><a></a>  res <span class="ot">&lt;-</span> <span class="fu">integer</span>(n)</span>
<span id="cb9-3"><a></a>  <span class="cf">for</span> (t <span class="cf">in</span> <span class="fu">seq_len</span>(n))</span>
<span id="cb9-4"><a></a>  res[[t]] <span class="ot">&lt;-</span> i <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">ncol</span>(P), <span class="dv">1</span>, <span class="at">pr=</span>P[,i])</span>
<span id="cb9-5"><a></a>  res</span>
<span id="cb9-6"><a></a>}</span>
<span id="cb9-7"><a></a>samples <span class="ot">&lt;-</span> <span class="fu">run</span>(<span class="dv">1</span>, P, <span class="dv">300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="power-iterations-4" class="slide level2">
<h2>Power Iterations</h2>
<p>Now, we plot the fraction of time that we were in each state over time:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>cummean <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">cumsum</span>(x) <span class="sc">/</span> <span class="fu">seq_along</span>(x)</span>
<span id="cb10-2"><a></a><span class="fu">plot</span>(<span class="fu">cummean</span>(samples <span class="sc">==</span> <span class="dv">1</span>), <span class="at">type=</span><span class="st">"l"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"Step"</span>, <span class="at">ylab=</span><span class="st">"y"</span>, <span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb10-3"><a></a><span class="fu">lines</span>(<span class="fu">cummean</span>(samples <span class="sc">==</span> <span class="dv">2</span>), <span class="at">col=</span><span class="dv">2</span>)</span>
<span id="cb10-4"><a></a><span class="fu">lines</span>(<span class="fu">cummean</span>(samples <span class="sc">==</span> <span class="dv">3</span>), <span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb10-5"><a></a><span class="fu">abline</span>(<span class="at">h=</span>v, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="english-alphabet" class="slide level2">
<h2>English Alphabet</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb11-2"><a></a><span class="co"># http://norvig.com/mayzner.html</span></span>
<span id="cb11-3"><a></a>bg <span class="ot">=</span> <span class="fu">read_json</span>(<span class="st">"data/bigrams.json"</span>, <span class="at">simplifyVector=</span>T)</span>
<span id="cb11-4"><a></a>nbg <span class="ot">=</span> <span class="fu">nrow</span>(bg)</span>
<span id="cb11-5"><a></a>bgm <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>,<span class="at">nrow=</span><span class="dv">26</span>,<span class="at">ncol=</span><span class="dv">26</span>)</span>
<span id="cb11-6"><a></a><span class="fu">rownames</span>(bgm) <span class="ot">=</span> letters; <span class="fu">colnames</span>(bgm) <span class="ot">=</span> letters</span>
<span id="cb11-7"><a></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>nbg) { <span class="co"># from j to i </span></span>
<span id="cb11-8"><a></a>  idx <span class="ot">=</span> <span class="fu">match</span>(<span class="fu">unlist</span>(<span class="fu">strsplit</span>(bg[i,<span class="dv">1</span>], <span class="at">split=</span><span class="st">""</span>)), letters)</span>
<span id="cb11-9"><a></a>  bgm[idx[<span class="dv">2</span>],idx[<span class="dv">1</span>]] <span class="ot">=</span> <span class="fu">as.numeric</span>(bg[i,<span class="dv">2</span>])</span>
<span id="cb11-10"><a></a>}</span>
<span id="cb11-11"><a></a><span class="co"># View(bgm)</span></span>
<span id="cb11-12"><a></a>bgm <span class="ot">=</span> bgm <span class="sc">%*%</span> <span class="fu">diag</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">colSums</span>(bgm))</span>
<span id="cb11-13"><a></a></span>
<span id="cb11-14"><a></a><span class="fu">image</span>(bgm, <span class="at">axes=</span><span class="cn">FALSE</span>)</span>
<span id="cb11-15"><a></a><span class="fu">axis</span>(<span class="dv">3</span>, <span class="at">at=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="at">length=</span><span class="dv">26</span>), <span class="at">labels=</span>letters)</span>
<span id="cb11-16"><a></a><span class="fu">axis</span>(<span class="dv">2</span>, <span class="at">at=</span><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">0</span>, <span class="at">length=</span><span class="dv">26</span>), <span class="at">labels=</span>letters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>ev <span class="ot">=</span> <span class="fu">eigen</span>(bgm)</span>
<span id="cb12-2"><a></a>v <span class="ot">=</span> ev<span class="sc">$</span>vectors[,<span class="dv">1</span>]</span>
<span id="cb12-3"><a></a>v <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(v<span class="sc">/</span><span class="fu">sum</span>(v))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-10-1.png" width="960" class="r-stretch"></section>
<section id="english-alphabet-1" class="slide level2">
<h2>English Alphabet</h2>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="fu">barplot</span>(v, <span class="at">names.arg =</span> letters, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.13</span>))</span>
<span id="cb13-2"><a></a>lf <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"data/letterfreq.txt"</span>)</span>
<span id="cb13-3"><a></a>lf<span class="sc">$</span>freq <span class="ot">=</span> lf<span class="sc">$</span>freq<span class="sc">/</span><span class="fu">sum</span>(lf<span class="sc">$</span>freq)</span>
<span id="cb13-4"><a></a>lf <span class="ot">=</span> lf[<span class="fu">order</span>(lf<span class="sc">$</span>letter),]</span>
<span id="cb13-5"><a></a><span class="fu">barplot</span>(lf<span class="sc">$</span>freq, <span class="at">names.arg =</span> letters, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.13</span>))</span>
<span id="cb13-6"><a></a></span>
<span id="cb13-7"><a></a><span class="fu">barplot</span>(bgm[,<span class="dv">5</span>], <span class="at">names.arg =</span> letters)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-11-1.png" width="960"></p>
<figcaption>From Bigrams</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-11-2.png" width="960"></p>
<figcaption>From Google</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-11-3.png" width="960"></p>
<figcaption>Transitions from letter e</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p>Individual Letter Frequencies</p>
</div>
</div>
</div>
</section>
<section id="how-to-construct-transition-probabilities" class="slide level2 smaller">
<h2>How to Construct Transition Probabilities?</h2>
<ul>
<li>The reverse problem, is how to construct the transition probabilities so that the limiting distribution is <span class="math inline">\(\pi\)</span>.</li>
<li>For example, it is easy to see that any row-stochastic matrix which is symmetric has a uniform limiting distribution, i.e.&nbsp;<span class="math inline">\(\pi = e\)</span>, <span class="math inline">\(e_i = 1/n\)</span>, where <span class="math inline">\(n\)</span> is the number of vertices.</li>
<li><span class="math inline">\(e\)</span> is an eigenvector of <span class="math inline">\(P^T\)</span>, since <span class="math inline">\(P^T\)</span> is row-stochastic, thus sum of each row equals to 1, i.e.&nbsp;<span class="math inline">\(P^T e = e\)</span>.</li>
</ul>
<p>General case balance condition: <span class="math display">\[
\pi_i p_{ij} = \pi_j p_{ji}, ~ i,j=1,\ldots,n,
\]</span> from which follows that <span class="math display">\[
\sum_i p_{ij}\pi_i = \pi_j \sum_i p_{ji} = \pi_j,~j=1,\ldots,n.
\]</span></p>
</section>
<section id="how-to-construct-transition-probabilities-1" class="slide level2 smaller">
<h2>How to Construct Transition Probabilities?</h2>
<p>Thus we need to find a Markov chain in which the transition probabilities satisfy the detailed balance condition (symmetry). Another way to write the condition is <span class="math display">\[
\dfrac{p_{ij}}{p_{ji}} = \dfrac{\pi_j}{\pi_i}.
\]</span> Say we have some “teaser” transition probabilities <span class="math inline">\(p_{ij}^0\)</span> and we assume those are symmetric. We want to find new probabilities <span class="math inline">\(p_{ij} = p_{ij}^0b_{ij}, ~ i\ne j\)</span> and <span class="math inline">\(p_{ii} = 1 - \sum_{j:~j\ne i} p_{ij}\)</span>. We need to choose <span class="math inline">\(b_{ij}\)</span> is such a way so that <span class="math display">\[
\dfrac{p_{ij}}{p_{ji}} = \dfrac{p_{ij}^0b_{ij}}{p_{ji}^0b_{ji}} = \dfrac{b_{ij}}{b_{ji}} = \dfrac{\pi_j}{\pi_i}
\]</span> We can choose <span class="math display">\[
b_{ij} = F\left(\dfrac{\pi_j}{\pi_i}\right)
\]</span></p>
<p>For the detailed balance condition to be satisfied, we need to choose <span class="math inline">\(F: R_+ \rightarrow [0,1]\)</span> such that <span class="math display">\[
\dfrac{F(z)}{F(1/z)} = z.
\]</span></p>
</section>
<section id="how-to-construct-transition-probabilities-2" class="slide level2 scrollable">
<h2>How to Construct Transition Probabilities?</h2>
<p>An example of such a function is <span class="math inline">\(F(z) = \min(z,1)\)</span>. This leads to the Metropolis algorithm</p>
<ol type="1">
<li>When at state <span class="math inline">\(i\)</span>, draw from <span class="math inline">\(p^{0}_{ij}\)</span> to generate next state <span class="math inline">\(j\)</span></li>
<li>Calculate <span class="math inline">\(a_{ij} = \min(1,\pi_i/\pi_j)\)</span> (acceptance probability)</li>
<li>Move to <span class="math inline">\(j\)</span> with probability <span class="math inline">\(a_{ij}\)</span>, stay at <span class="math inline">\(i\)</span> otherwise</li>
</ol>
<p>When move happens, we say step is accepted, otherwise it is rejected. In a more general case (Metropolis-Hastings), when <span class="math inline">\(p^0\)</span> is not symmetric, we calculate <span class="math display">\[
a_{ij} = \min\left(1,\dfrac{\pi_i p^0_{ji}}{\pi_j p^0_{ji}}\right).
\]</span></p>
</section>
<section id="continious-case" class="slide level2 smaller">
<h2>Continious Case</h2>
<p>In the continuous case we use variables <span class="math inline">\(S\)</span> and <span class="math inline">\(T\)</span> instead induces <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. The detailed balance condition becomes <span class="math display">\[
\pi(S)p(T \mid S) = \pi(T)p(S \mid T).
\]</span> Then <span class="math display">\[
\int p(T \mid S)\pi(S)dS = \int p(S \mid T)\pi(T)dS = \pi(T)\int p(S\mid T)dS = \pi(T).
\]</span></p>
<p>The following conditions <span class="math display">\[
\forall S, \forall T:\pi(T)\ne 0:p(T \mid S) &gt;0
\]</span> are sufficient to guarantee uniqueness of <span class="math inline">\(\pi(T)\)</span>.</p>
</section>
<section id="metropolis-hastings-algorithm" class="slide level2">
<h2>Metropolis-Hastings Algorithm</h2>
<p>Specifically, the MH algorithm repeats the following two steps <span class="math inline">\(G\)</span> times: given <span class="math inline">\(\theta ^{\left( g\right) }\)</span> <span class="math display">\[
\begin{aligned}   
&amp;\text{Step 1. Draw }\theta^{\prime} \text{ from a proposal distribution,} p(\theta^{\prime}|\theta ^{(g)}) \\  
&amp;\text{Step 2. Accept } \theta^{\prime} \text{ with probability } \alpha \left(\theta ^{(g)},\theta^{\prime}\right) \text{,}
\end{aligned}
\]</span> where <span class="math display">\[
\alpha \left( \theta ^{(g)},\theta^{\prime}\right) =\min \left(     \frac{\pi(\theta^{\prime})}{\pi (\theta ^{(g)})}\frac{q(\theta^{(g)}|\theta^{\prime})}{q(\theta^{\prime}|\theta ^{(g)})},1\right) \text{.}
\]</span></p>
</section>
<section id="metropolis-hastings-algorithm-1" class="slide level2">
<h2>Metropolis-Hastings Algorithm</h2>
<p>Implementation of the accept-reject step:</p>
<ul>
<li>Draw a uniform random variable, <span class="math inline">\(U\sim U \left[ 0,1\right]\)</span>, and set <span class="math inline">\(\theta ^{\left( g+1\right) }=\theta^{\prime}\)</span></li>
<li>if <span class="math inline">\(U&lt;\alpha \left( \theta ^{(g)},\theta^{\prime}\right)\)</span>, leaving <span class="math inline">\(\theta ^{\left( g\right) }\)</span> unchanged (<span class="math inline">\(\theta^{\left( g+1\right) }=\theta^{(g)}\)</span>).</li>
<li>It is important to note that the denominator in the acceptance probability cannot be zero, provided the algorithm is started from a <span class="math inline">\(\pi\)</span> - positive point since <span class="math inline">\(q\)</span> is always positive. The MH algorithmonly requires that <span class="math inline">\(\pi\)</span> can be evaluated up to proportionality.</li>
<li>The output of the algorithm, <span class="math inline">\(\left\{ \theta ^{\left( g\right) }\right\}_{g=1}^{\infty }\)</span>, is clearly a Markov chain. The key theoretical property is that the Markov chain, under mild regularity, has <span class="math inline">\(\pi \left( \theta\right)\)</span> as its limiting distribution. We discuss two important specialcases that depend on the choice of <span class="math inline">\(q\)</span>.</li>
</ul>
</section>
<section id="independence-mh" class="slide level2">
<h2>Independence MH</h2>
<p>One special case draws a candidate <em>independently</em> of the previous state, <span class="math inline">\(q(\theta^{\prime}|\theta ^{(g)})=q(\theta^{\prime})\)</span>. In this independence MH algorithm, the acceptance criterion simplifies to <span class="math display">\[
\alpha \left( \theta ^{(g)},\theta^{\prime}\right) =\min \left( \frac{\pi        (\theta^{\prime})}{\pi (\theta ^{(g)})}\frac{q(\theta ^{(g)})}{q(\theta       ^{\prime})},1\right).
\]</span> Even though <span class="math inline">\(\theta\)</span> is drawn independently of the previous state, the sequence generated is not being independent, since <span class="math inline">\(\alpha\)</span> depends on previous draws. The criterion implies a new draw is always accepted if target density ratio <span class="math inline">\(\pi (\theta^{\prime})/\pi (\theta ^{(g)})\)</span>, increases more than the proposal ratio, <span class="math inline">\(q(\theta ^{(g)})/q(\theta^{\prime})\)</span>. When this is not satisfied, a balanced coin is flipped to decide whether or not toaccept the proposal.</p>
</section>
<section id="random-walk-metropolis" class="slide level2">
<h2>Random-walk Metropolis</h2>
<p>Random-walk (RW) Metropolis is the polar opposite of the independence MH algorithm. It draws a candidate from the following RW model, <span class="math display">\[
\theta^{\prime}=\theta ^{\left( g\right) }+\sigma \varepsilon _{g+1},
\]</span> where <span class="math inline">\(\varepsilon _{t}\)</span> is an independent, mean zero, and symmetric error term, typically taken to be a normal or <span class="math inline">\(t-\)</span>distribution, and <span class="math inline">\(\sigma\)</span> is a scaling factor. The algorithm must be tuned via the choice of <span class="math inline">\(\sigma\)</span>, the scaling factor. Symmetry implies that <span class="math display">\[
q\left( \theta^{\prime}|\theta ^{\left( g\right) }\right) =q\left( \theta    ^{\left( g\right) }|\theta^{\prime}\right),
\]</span> and <span class="math display">\[
\alpha \left( \theta ^{(g)},\theta^{\prime}\right) =\min \left( \pi    (\theta^{\prime})/\pi (\theta ^{(g)}),1\right).
\]</span></p>
</section>
<section id="implementation" class="slide level2">
<h2>Implementation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb14-2"><a></a>mh <span class="ot">=</span> <span class="cf">function</span>(target, proposal, n, x0) {</span>
<span id="cb14-3"><a></a>  x <span class="ot">=</span> x0; p <span class="ot">=</span> <span class="fu">length</span>(x0)</span>
<span id="cb14-4"><a></a>  samples <span class="ot">=</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow=</span>n, <span class="at">ncol=</span>p)</span>
<span id="cb14-5"><a></a>  accept <span class="ot">=</span> <span class="fu">rep</span>(<span class="dv">0</span>, n)</span>
<span id="cb14-6"><a></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb14-7"><a></a>    x_new <span class="ot">=</span> <span class="fu">proposal</span>(x)</span>
<span id="cb14-8"><a></a>    a <span class="ot">=</span> <span class="fu">min</span>(<span class="dv">1</span>,<span class="fu">target</span>(x_new) <span class="sc">/</span> <span class="fu">target</span>(x))</span>
<span id="cb14-9"><a></a>    <span class="co"># print(c(x, x_new, a))</span></span>
<span id="cb14-10"><a></a>    <span class="cf">if</span> (<span class="fu">runif</span>(<span class="dv">1</span>) <span class="sc">&lt;</span> a) {accept[i]<span class="ot">=</span><span class="dv">1</span>; x <span class="ot">=</span> x_new}</span>
<span id="cb14-11"><a></a>    samples[i,] <span class="ot">=</span> x</span>
<span id="cb14-12"><a></a>    <span class="co"># print(accept[i])</span></span>
<span id="cb14-13"><a></a>  }</span>
<span id="cb14-14"><a></a>  <span class="fu">list</span>(<span class="at">samples =</span> samples, <span class="at">accept =</span> accept)</span>
<span id="cb14-15"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="apply" class="slide level2">
<h2>Apply</h2>
<p>We apply MCMC to the weighted sum of two normal distributions. This sort of distribution is fairly straightforward to sample from, but let’s draw samples with MCMC.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>p <span class="ot">&lt;-</span> <span class="fl">0.4</span></span>
<span id="cb15-2"><a></a>mu <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb15-3"><a></a>sd <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">5</span>, <span class="dv">2</span>)</span>
<span id="cb15-4"><a></a>target <span class="ot">&lt;-</span> <span class="cf">function</span>(x)</span>
<span id="cb15-5"><a></a>    p     <span class="sc">*</span> <span class="fu">dnorm</span>(x, mu[<span class="dv">1</span>], sd[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb15-6"><a></a>    (<span class="dv">1</span><span class="sc">-</span>p) <span class="sc">*</span> <span class="fu">dnorm</span>(x, mu[<span class="dv">2</span>], sd[<span class="dv">2</span>])</span>
<span id="cb15-7"><a></a><span class="fu">curve</span>(<span class="fu">target</span>(x), <span class="at">col=</span><span class="st">"red"</span>, <span class="sc">-</span><span class="dv">4</span>, <span class="dv">8</span>, <span class="at">n=</span><span class="dv">301</span>, <span class="at">las=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"></section>
<section id="apply-1" class="slide level2">
<h2>Apply</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb16-2"><a></a>proposal <span class="ot">=</span> <span class="cf">function</span>(x) x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="fl">0.25</span>)</span>
<span id="cb16-3"><a></a>r <span class="ot">=</span> <span class="fu">mh</span>(target, proposal, <span class="dv">2000</span>, <span class="at">x0=</span><span class="dv">0</span>)</span>
<span id="cb16-4"><a></a><span class="fu">hist</span>(r<span class="sc">$</span>samples[r<span class="sc">$</span>accept<span class="sc">==</span><span class="dv">1</span>,], <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">breaks=</span><span class="dv">35</span>, <span class="at">col=</span><span class="st">"lightblue"</span>, <span class="at">main=</span><span class="st">"Metropolis-Hastings"</span>, <span class="at">xlab=</span><span class="st">"x"</span>)</span>
<span id="cb16-5"><a></a><span class="fu">curve</span>(<span class="fu">target</span>(x), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-14-1.png" width="960" class="r-stretch"></section>
<section id="bivariate" class="slide level2">
<h2>Bivariate</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">set.seed</span>(<span class="dv">92</span>)</span>
<span id="cb17-2"><a></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-3"><a></a><span class="co"># Metropolis-Hastings for Bivariate Normal distribution</span></span>
<span id="cb17-4"><a></a><span class="co"># Target distribution</span></span>
<span id="cb17-5"><a></a>mu <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb17-6"><a></a>sigma <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">1</span>), <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb17-7"><a></a>target <span class="ot">=</span> <span class="cf">function</span>(x) <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span><span class="fu">t</span>(x<span class="sc">-</span>mu) <span class="sc">%*%</span> <span class="fu">solve</span>(sigma) <span class="sc">%*%</span> (x<span class="sc">-</span>mu))</span>
<span id="cb17-8"><a></a><span class="fu">library</span>(mixtools)</span>
<span id="cb17-9"><a></a><span class="fu">ellipse</span>(mu, sigma, <span class="at">npoints =</span> <span class="dv">1000</span>, <span class="at">newplot =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-10"><a></a>proposal <span class="ot">=</span> <span class="cf">function</span>(x) x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">2</span>, <span class="dv">0</span>, .<span class="dv">5</span>)</span>
<span id="cb17-11"><a></a>n <span class="ot">=</span> <span class="dv">5000</span> <span class="co"># Number of samples</span></span>
<span id="cb17-12"><a></a>x <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb17-13"><a></a>samples <span class="ot">=</span> <span class="fu">matrix</span>(<span class="dv">0</span>, n, <span class="dv">2</span>)</span>
<span id="cb17-14"><a></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb17-15"><a></a>  x_new <span class="ot">=</span> <span class="fu">proposal</span>(x)</span>
<span id="cb17-16"><a></a>  a <span class="ot">=</span> <span class="fu">target</span>(x_new) <span class="sc">/</span> <span class="fu">target</span>(x)</span>
<span id="cb17-17"><a></a>  <span class="cf">if</span> (i<span class="sc">&lt;</span><span class="dv">50</span>) {</span>
<span id="cb17-18"><a></a>  <span class="cf">if</span> (<span class="fu">runif</span>(<span class="dv">1</span>) <span class="sc">&gt;</span> a) {<span class="fu">arrows</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>], x_new[<span class="dv">1</span>], x_new[<span class="dv">2</span>], <span class="at">col=</span> <span class="st">'red'</span>)} <span class="cf">else</span>  {<span class="fu">arrows</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>], x_new[<span class="dv">1</span>], x_new[<span class="dv">2</span>], <span class="at">col=</span> <span class="st">'green'</span>); x <span class="ot">=</span> x_new}</span>
<span id="cb17-19"><a></a>  }</span>
<span id="cb17-20"><a></a>  <span class="cf">if</span> (<span class="fu">runif</span>(<span class="dv">1</span>) <span class="sc">&lt;</span> a) x <span class="ot">=</span> x_new</span>
<span id="cb17-21"><a></a></span>
<span id="cb17-22"><a></a>  samples[i,] <span class="ot">=</span> x</span>
<span id="cb17-23"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/bivariatemcmc-1.png" width="960" class="r-stretch quarto-figure-center"><p class="caption">Paths of random samples generated by Metropolis algorithm. Red are the rejected steps and green are accepted ones</p></section>
<section id="bivariate-1" class="slide level2">
<h2>Bivariate</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>samples[,<span class="dv">1</span>], <span class="at">y=</span>samples[,<span class="dv">2</span>])) <span class="sc">+</span> <span class="fu">geom_point</span>()<span class="sc">+</span> <span class="fu">geom_density_2d</span>(<span class="at">size=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"></section>
<section id="gibbs-samples-clifford-hammersley" class="slide level2">
<h2>Gibbs Samples: Clifford-Hammersley</h2>
<ul>
<li>Clifford-Hammersley (CH) theorem: high-dimensional joint distribution, <span class="math inline">\(p\left( \theta\mid X,Y\right)\)</span>, is completely characterized by a larger number of lower dimensional conditional distributions. Given this characterization, MCMC methods iteratively sample from these conditional distributions using standard sampling methods.</li>
<li>Example: bivariate posterior distribution <span class="math inline">\(p\left( \theta_1,\theta_{2} \mid X,Y \right)\)</span>, e.g.&nbsp;<span class="math inline">\(\theta_1\)</span> as traditional static parameters and <span class="math inline">\(\theta_2\)</span> as latent variables.</li>
</ul>
<p>CH: <span class="math inline">\(p\left( \theta_1,\theta_2\right)\)</span> is determined by <span class="math inline">\(p\left( \theta_{1} \mid \theta_{2}\right)\)</span> and <span class="math inline">\(p\left( \theta_{2} \mid \theta_{1}\right)\)</span>, given <span class="math inline">\(p\left( \theta_{1},\theta_2\right)\)</span>, <span class="math inline">\(p\left( \theta_{1}\right)\)</span> and <span class="math inline">\(p\left( \theta_{2}\right)\)</span> have positive mass for all points</p>
</section>
<section id="besag-formula" class="slide level2">
<h2>Besag formula</h2>
<p>For any pairs <span class="math inline">\((\theta_{1},\theta_{2})\)</span> and <span class="math inline">\((\theta_1^{\prime},\theta_2^{\prime})\)</span>, <span class="math display">\[
\frac{p(\theta_1,\theta_2)}{p(\theta_1^{\prime},\theta_2^{\prime})}=\frac{p(\theta_1 \mid \theta_2^{\prime})p(\theta_2 \mid \theta_1)}{p\left( \theta_1^{\prime} \mid \theta_2^{\prime}\right) p\left( \theta_2^{\prime} \mid \theta_2\right) }.
\]</span> The proof uses the fact that <span class="math inline">\(p\left( \theta_1,\theta_2\right)=p\left( \theta_2 \mid \theta_1\right) p\left( \theta_1\right)\)</span> (applied to both <span class="math inline">\((\theta_1,\theta_2)\)</span> and <span class="math inline">\((\theta_1^{\prime},\theta_2^{\prime})\)</span>) and the Bayes rule: <span class="math display">\[
p\left( \theta_1\right) =\frac{p\left( \theta_1 \mid \theta_2^{\prime            }\right) p\left( \theta_2^{\prime}\right) }{p\left( \theta_2^{\prime} \mid \theta_1\right) }\text{.}
\]</span></p>
</section>
<section id="clifford-hammersley-the-general-version" class="slide level2">
<h2>Clifford-Hammersley: The general version</h2>
<ul>
<li>Partitioning a vector as <span class="math inline">\(\theta =\left( \theta_{1},\theta_{2},\theta_{3},\ldots ,\theta_{K}\right)\)</span>, then the general CH theorem states that <span class="math display">\[
p\left( \theta _{i} \mid \theta _{-i}\right) := p\left( \theta    _{i} \mid \theta_1,\theta_1,\ldots,\theta_{i-1},\theta _{i+1},...,\theta    _{K}\right) ,
\]</span> for <span class="math inline">\(i=1,...,K\)</span>, completely characterize <span class="math inline">\(p\left( \theta_1,\ldots,\theta_{K}\right)\)</span>.</li>
</ul>
</section>
<section id="latent-variable-models" class="slide level2">
<h2>Latent Variable Models</h2>
<ul>
<li>Fixed parameters <span class="math inline">\(\theta\)</span>, and latent variables, <span class="math inline">\(x\)</span>. In this case, then CH <span class="math display">\[
p\left( \theta,x \mid y\right)
\]</span> is completely characterized by <span class="math inline">\(p\left( \theta  \mid x,y\right)\)</span> and <span class="math inline">\(p\left( x \mid \theta ,y\right)\)</span>.</li>
<li>The distribution <span class="math inline">\(p\left( \theta \mid x,y\right)\)</span> is the posterior distribution of the parameters, conditional on the observed data and the latent variables. Similarly, <span class="math inline">\(p\left( x \mid \theta,y\right)\)</span> is the smoothing distribution of the latent variables.</li>
</ul>
</section>
<section id="gibbs-sampler" class="slide level2">
<h2>Gibbs Sampler</h2>
<ul>
<li>The Gibbs sampler simulates multi-dimensional posterior distributions by iteratively sampling from the lower-dimensional conditional posteriors.</li>
<li>Unlike the previous MH algorithms, the Gibbs sampler updates the chain one component at a time, instead of updating the entire vector.</li>
<li>This requires either that the conditional posteriors distributions is discrete, or a recognizable distribution (e.g.&nbsp;Normal) for which standard sampling algorithms apply, or that resampling methods, such as accept-reject, can be used.</li>
</ul>
</section>
<section id="gibbs-sampler-1" class="slide level2">
<h2>Gibbs Sampler</h2>
<p>In the case of <span class="math inline">\(p\left( \theta_1,\theta_2\right)\)</span>, given current draws,<span class="math inline">\(\left( \theta_1^{\left( g\right) },\theta_2^{\left( g\right)}\right)\)</span>, the Gibbs sampler consists of <span class="math display">\[
\begin{aligned}
\text{1. Draw }\theta_1^{\left( g+1\right) } &amp;\sim &amp;p\left( \theta   _1|\theta_2^{\left( g\right) }\right) \\    
\text{2. Draw }\theta_2^{\left( g+1\right) } &amp;\sim &amp;p\left( \theta_2|\theta_1^{\left( g+1\right) }\right) ,
\end{aligned}
\]</span> repeating <span class="math inline">\(G\)</span> times.</p>
</section>
<section id="gibbs-sampler-2" class="slide level2">
<h2>Gibbs Sampler</h2>
<ul>
<li>Transition kernel from state <span class="math inline">\(\theta\)</span> to state <span class="math inline">\(\theta ^{\prime}\)</span> is <span class="math display">\[
p\left( \theta ,\theta^{\prime}\right) =p\left( \theta_{1}^{\prime}|\theta_2\right) p\left( \theta_2^{\prime}|\theta_{1}^{\prime}\right)
\]</span></li>
<li>The limiting (statiobnary) distribution <span class="math inline">\(\pi\)</span>, satisfies <span class="math display">\[
\pi \left( \theta^{\prime}\right) =\int p\left( \theta ,\theta^{\prime}\right)  d\theta.
\]</span></li>
</ul>
</section>
<section id="gibbs-sampler-3" class="slide level2">
<h2>Gibbs Sampler</h2>
<p>It is easy to verify that the stationary distribution of the Markov chain generated by the Gibbs sampler is the posterior distribution, <span class="math inline">\(\pi \left(\theta \right) =p\left( \theta_1,\theta_2\right)\)</span>: <span class="math display">\[
\begin{aligned}    
\int p\left( \theta ,\theta^{\prime}\right) d\theta &amp;=&amp;p\left( \theta_2^{\prime}|\theta_1^{\prime    }\right) \int_{\theta_2}\int_{\theta_1}p\left( \theta_1^{\prime}|\theta_2\right) p\left( \theta_1,\theta_2\right) d\theta_{1}d\theta_2 \\
&amp;=&amp;p\left( \theta_2^{\prime}|\theta_1^{\prime}\right) \int_{\theta_2}p\left( \theta_1^{\prime}|\theta_2\right)  p\left( \theta_{2}\right)  d\theta_2 \\&amp;=&amp;p\left( \theta_2^{\prime}|\theta_1^{\prime}\right) p\left( \theta_{1}^{\prime}\right) =p\left( \theta_1^{\prime},\theta_2^{\prime}\right) =\pi \left( \theta^{\prime}\right) \text{.}
\end{aligned}
\]</span></p>
</section>
<section id="gibbs-sampler-4" class="slide level2">
<h2>Gibbs Sampler</h2>
<p>The ergodic theorem holds: for a sufficiently integrable function <span class="math inline">\(l\)</span> and for all starting points <span class="math inline">\(\theta ,\)</span> <span class="math display">\[
\underset{G\rightarrow \infty }{\lim }\frac{1}{G}\sum_{g=1}^{G}f\left(\theta ^{\left( g\right) }\right) =\int f\left( \theta \right) \pi \left(\theta \right) d\theta =E\left[ f\left( \theta \right) \right]
\]</span> - Run for an initial length, often called the burn-in - Then a secondary sample of size <span class="math inline">\(G\)</span> is created for Monte Carlo inference</p>
</section>
<section id="gibbs-sample-for-normal-gamma" class="slide level2">
<h2>Gibbs sample for Normal-Gamma</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="co"># summary statistics of sample</span></span>
<span id="cb19-2"><a></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb19-3"><a></a>ybar <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb19-4"><a></a>s2 <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb19-5"><a></a></span>
<span id="cb19-6"><a></a><span class="co"># sample from the joint posterior (mu, tau | data)</span></span>
<span id="cb19-7"><a></a>mu <span class="ot">&lt;-</span> tau <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">11000</span>)</span>
<span id="cb19-8"><a></a>T <span class="ot">&lt;-</span> <span class="dv">1000</span>    <span class="co"># burnin</span></span>
<span id="cb19-9"><a></a>tau[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># initialisation</span></span>
<span id="cb19-10"><a></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">11000</span>)</span>
<span id="cb19-11"><a></a>{   </span>
<span id="cb19-12"><a></a>    mu[i] <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">mean =</span> ybar, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> (n <span class="sc">*</span> tau[i <span class="sc">-</span> <span class="dv">1</span>])))    </span>
<span id="cb19-13"><a></a>    tau[i] <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(<span class="at">n =</span> <span class="dv">1</span>, <span class="at">shape =</span> n <span class="sc">/</span> <span class="dv">2</span>, <span class="at">scale =</span> <span class="dv">2</span> <span class="sc">/</span> ((n <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> s2 <span class="sc">+</span> n <span class="sc">*</span> (mu[i] <span class="sc">-</span> ybar)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb19-14"><a></a>}</span>
<span id="cb19-15"><a></a>mu <span class="ot">&lt;-</span> mu[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span>T)]   <span class="co"># remove burnin</span></span>
<span id="cb19-16"><a></a>tau <span class="ot">&lt;-</span> tau[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span>T)] <span class="co"># remove burnin</span></span>
<span id="cb19-17"><a></a><span class="fu">hist</span>(mu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-16-1.png" width="960"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a></a><span class="fu">hist</span>(tau)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-16-2.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="hybrid-chains" class="slide level2">
<h2>Hybrid chains</h2>
<ul>
<li><p>Given a partition of the vector <span class="math inline">\(\theta\)</span> via CH, a hybrid MCMC algorithm updates the chain one subset at a time, either by direct draws (Gibbs steps) or via MH. - Thus, a hybrid algorithm combines the features of the MH algorithm and the Gibbs sampler, providing significant flexibility in designing MCMC algorithms for different models.</p></li>
<li><p><span class="math inline">\(p\left( \theta_2|\theta_1\right)\)</span> is recognizable and can be directly sampled.</p></li>
<li><p><span class="math inline">\(p\left( \theta_1|\theta_2\right)\)</span> can only be evaluated and not directly sampled.</p></li>
<li><p>MH accept/reject based on <span class="math display">\[
\alpha \left( \theta_1^{(g)},\theta_1^{\prime}\right) =\min \left(     \frac{p\left( \theta_1^{\prime}|\theta_2^{\left( g\right) }\right) }{p\left( \theta_1^{\left ( g \right ) }|\theta_2^{\left( g\right) }\right) }\frac{q\left( \theta_1^{\left( g\right)        }|\theta_1^{\prime},\theta_2^{\left( g\right) }\right) }{q\left( \theta_1^{\prime}|\theta_1^{\left( g\right) },\theta    _2^{\left( g\right) }\right) },1\right) .
\]</span></p></li>
</ul>
</section>
<section id="hybrid-chains-1" class="slide level2">
<h2>Hybrid chains</h2>
<p>The general hybrid algorithm is as follows. Given <span class="math inline">\(\theta_1^{\left(g\right) }\)</span> and <span class="math inline">\(\theta_2^{\left( g\right) }\)</span>, for <span class="math inline">\(g=1,\ldots, G\)</span>, <span class="math display">\[
\begin{aligned}    
1.\text{ Draw }\theta_1^{\left( g+1\right) } &amp;\sim &amp;MH\left[ q\left(    \theta_1|\theta_1^{\left( g\right) },\theta_2^{\left( g\right)    }\right) \right] \\    
2.\text{ Draw }\theta_2^{\left( g+1\right) } &amp;\sim &amp;p\left( \theta_2|\theta_1^{\left( g+1\right) }\right) .
\end{aligned}
\]</span> In higher dimensional cases, a hybrid algorithm consists of any combination of Gibbs and Metropolis steps. Hybrid algorithms significantly increase the applicability of MCMC methods, as the only requirement is that the model generates posterior conditionals that can either be sampled or evaluated.</p>
</section>
<section id="hamiltonian-monte-carlo" class="slide level2">
<h2>Hamiltonian Monte-Carlo</h2>
<ul>
<li>Add a momentum to the Metropolis Sampling.</li>
<li>Gradient of the un-normalized posterior to better navigate the surface defined by the posterior.</li>
<li>Momentum variable <span class="math inline">\(r\)</span> for each model variable <span class="math inline">\(\theta\)</span>. <span class="math display">\[
p(\theta,r) \propto \exp\left(L(\theta) - 0.5 r^Tr\right),
\]</span></li>
<li><span class="math inline">\(L\)</span> is the logarithm of the joint density of the variables of interest (negative potential energy)</li>
<li><span class="math inline">\(0.5 r^Tr\)</span> is the kinetic energy of the particle</li>
<li><span class="math inline">\(p(\theta,r)\)</span> is the total negative energy</li>
</ul>
</section>
<section id="hamiltonian-monte-carlo-1" class="slide level2">
<h2>Hamiltonian Monte-Carlo</h2>
<p>We can simulate the evolution over time of the Hamiltonian dynamics of this system via the “leapfrog” integrator, which proceeds according to the updates <span class="math display">\[
\begin{aligned}
r^{+/2} &amp; = r + (\epsilon/2) \nabla_{\theta}L(\theta) \\
\theta^{+} &amp; = \theta + (\epsilon/2) r^{+/2}\\
r^{+} &amp; = r^{+/2} + (\epsilon/2)\nabla_{\theta}L(\theta^{+}).
\end{aligned}
\]</span></p>
</section>
<section id="hierarchical-bayesian-model" class="slide level2">
<h2>Hierarchical Bayesian Model</h2>
<p>We consider the following model: <span class="math display">\[\begin{align*}
    \tau &amp;\sim \mathrm{Gamma}(0.5, 0.5) \\
    \lambda_d &amp;\sim \mathrm{Gamma}(0.5, 0.5) \\
    \beta_d &amp;\sim \mathcal{N}(0, 20) \\
    y_n &amp;\sim \mathrm{Bernoulli}(\sigma((\tau \lambda \odot \beta)^T x_n))),
\end{align*}\]</span></p>
<ul>
<li><span class="math inline">\(\tau\)</span> is a scalar global coefficient scale</li>
<li><span class="math inline">\(\lambda\)</span> is a vector of local scales</li>
<li><span class="math inline">\(\beta\)</span> is the vector of unscaled coefficients,</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a></a><span class="im">import</span> tensorflow_probability.substrates.jax <span class="im">as</span> tfp</span>
<span id="cb21-2"><a></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb21-3"><a></a><span class="im">import</span> jax.numpy <span class="im">as</span> jnp</span>
<span id="cb21-4"><a></a>tfd <span class="op">=</span> tfp.distributions</span>
<span id="cb21-5"><a></a><span class="im">import</span> jax</span>
<span id="cb21-6"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="apply-to-iris-data" class="slide level2">
<h2>Apply to Iris Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb22-2"><a></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb22-3"><a></a><span class="im">import</span> numpy <span class="im">as</span> np  </span>
<span id="cb22-4"><a></a>iris <span class="op">=</span> pd.read_csv(<span class="st">"data/iris.csv"</span>)</span>
<span id="cb22-5"><a></a><span class="bu">print</span>(iris.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(150, 5)</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a></a><span class="bu">print</span>(iris.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a></a>y <span class="op">=</span> iris[<span class="st">'variety'</span>]<span class="op">==</span><span class="st">"Setosa"</span></span>
<span id="cb26-2"><a></a>x <span class="op">=</span> iris[<span class="st">"sepal.length"</span>].values</span>
<span id="cb26-3"><a></a>plt.scatter(x,y)</span>
<span id="cb26-4"><a></a>x <span class="op">=</span> np.c_[np.ones(<span class="dv">150</span>),x]</span>
<span id="cb26-5"><a></a><span class="bu">print</span>(x.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(150, 2)</code></pre>
</div>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"></section>
<section id="log-density-function" class="slide level2">
<h2>Log Density Function</h2>
<p>For Hamiltonian MC, we only need to evaluate the joint log-density pointwise</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a></a><span class="kw">def</span> joint_log_prob(x, y, tau, lamb, beta):</span>
<span id="cb28-2"><a></a>    lp <span class="op">=</span> tfd.Gamma(<span class="fl">0.5</span>, <span class="fl">0.5</span>).log_prob(tau)</span>
<span id="cb28-3"><a></a>    lp <span class="op">+=</span> tfd.Gamma(<span class="fl">0.5</span>, <span class="fl">0.5</span>).log_prob(lamb).<span class="bu">sum</span>() </span>
<span id="cb28-4"><a></a>    lp <span class="op">+=</span> tfd.Normal(<span class="fl">0.</span>, <span class="dv">20</span>).log_prob(beta).<span class="bu">sum</span>() </span>
<span id="cb28-5"><a></a>    logits <span class="op">=</span> x <span class="op">@</span> (tau <span class="op">*</span> lamb <span class="op">*</span> beta)</span>
<span id="cb28-6"><a></a>    lp <span class="op">+=</span> tfd.Bernoulli(logits).log_prob(y).<span class="bu">sum</span>() </span>
<span id="cb28-7"><a></a>    <span class="cf">return</span> lp   </span>
<span id="cb28-8"><a></a></span>
<span id="cb28-9"><a></a>tau <span class="op">=</span> np.random.rand(<span class="dv">1</span>)[<span class="dv">0</span>]</span>
<span id="cb28-10"><a></a>lamb <span class="op">=</span> np.random.rand(<span class="dv">2</span>)</span>
<span id="cb28-11"><a></a>beta <span class="op">=</span> np.random.rand(<span class="dv">2</span>)</span>
<span id="cb28-12"><a></a>joint_log_prob(x, y, tau, lamb, beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Array(-124.43358, dtype=float32)</code></pre>
</div>
</div>
</section>
<section id="change-of-variables" class="slide level2">
<h2>Change of Variables</h2>
<p><span class="math display">\[
z\triangleq T^{-1}(\theta),\qquad \pi(z) = \pi(\theta) \left| \frac{\partial T}{\partial z} (z) \right|,
\]</span></p>
<p>Taking the logarithm of both sides, we get <span class="math display">\[
\log \pi(z) = \log \pi(\theta) + \log \left| \frac{\partial T }{\partial z}(z) \right|
\]</span> Use <span class="math inline">\(T(z)=e^z\)</span>, and <span class="math inline">\(\log|\frac{\partial T}{\partial z}(z)| = z\)</span></p>
</section>
<section id="change-of-variables-in-code" class="slide level2">
<h2>Change of Variables in Code</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a></a><span class="kw">def</span> unconstrained_joint_log_prob(x, y, theta):</span>
<span id="cb30-2"><a></a>    ndims <span class="op">=</span> x.shape[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb30-3"><a></a>    unc_tau, unc_lamb, beta <span class="op">=</span> jnp.split(theta, [<span class="dv">1</span>, <span class="dv">1</span> <span class="op">+</span> ndims])</span>
<span id="cb30-4"><a></a>    unc_tau <span class="op">=</span> unc_tau.reshape([]) </span>
<span id="cb30-5"><a></a>    <span class="co"># Make unc_tau a scalar </span></span>
<span id="cb30-6"><a></a>    tau <span class="op">=</span> jnp.exp(unc_tau)</span>
<span id="cb30-7"><a></a>    ldj <span class="op">=</span> unc_tau</span>
<span id="cb30-8"><a></a>    lamb <span class="op">=</span> jnp.exp(unc_lamb)</span>
<span id="cb30-9"><a></a>    ldj <span class="op">+=</span> unc_lamb.<span class="bu">sum</span>()</span>
<span id="cb30-10"><a></a>    <span class="cf">return</span> joint_log_prob(x, y, tau, lamb, beta) <span class="op">+</span> ldj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="lets-check-out-function" class="slide level2">
<h2>Let’s check out function</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a></a><span class="im">from</span> functools <span class="im">import</span> partial</span>
<span id="cb31-2"><a></a>target_log_prob <span class="op">=</span> partial(unconstrained_joint_log_prob, x, y)</span>
<span id="cb31-3"><a></a>theta <span class="op">=</span> np.r_[tau,lamb,beta]</span>
<span id="cb31-4"><a></a>target_log_prob(theta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Array(-709.7654, dtype=float32)</code></pre>
</div>
</div>
</section>
<section id="automatic-differentiation" class="slide level2">
<h2>Automatic Differentiation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a></a>target_log_prob_and_grad <span class="op">=</span> jax.value_and_grad(target_log_prob)</span>
<span id="cb33-2"><a></a>tlp, tlp_grad <span class="op">=</span> target_log_prob_and_grad(theta)</span>
<span id="cb33-3"><a></a><span class="bu">print</span>(tlp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>-709.7654</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a></a>tlp_grad</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Array([ -695.4309  ,   -40.476734,  -655.5988  ,  -141.32121 ,
       -1626.3228  ], dtype=float32)</code></pre>
</div>
</div>
</section>
<section id="hamiltonian-monte-carlo-2" class="slide level2">
<h2>Hamiltonian Monte Carlo</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a></a><span class="kw">def</span> leapfrog_step(target_log_prob_and_grad, step_size, i, leapfrog_state):</span>
<span id="cb37-2"><a></a>    z, m, tlp, tlp_grad <span class="op">=</span> leapfrog_state</span>
<span id="cb37-3"><a></a>    m <span class="op">+=</span> <span class="fl">0.5</span> <span class="op">*</span> step_size <span class="op">*</span> tlp_grad</span>
<span id="cb37-4"><a></a>    z <span class="op">+=</span> step_size <span class="op">*</span> m</span>
<span id="cb37-5"><a></a>    tlp, tlp_grad <span class="op">=</span> target_log_prob_and_grad(z)</span>
<span id="cb37-6"><a></a>    m <span class="op">+=</span> <span class="fl">0.5</span> <span class="op">*</span> step_size <span class="op">*</span> tlp_grad</span>
<span id="cb37-7"><a></a>    <span class="cf">return</span> z, m, tlp, tlp_grad</span>
<span id="cb37-8"><a></a></span>
<span id="cb37-9"><a></a><span class="kw">def</span> hmc_step(target_log_prob_and_grad, num_leapfrog_steps, step_size, z, seed):</span>
<span id="cb37-10"><a></a>    m_seed, mh_seed <span class="op">=</span> jax.random.split(seed)</span>
<span id="cb37-11"><a></a>    tlp, tlp_grad <span class="op">=</span> target_log_prob_and_grad(z)</span>
<span id="cb37-12"><a></a>    m <span class="op">=</span> jax.random.normal(m_seed, z.shape)</span>
<span id="cb37-13"><a></a>    energy <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> jnp.square(m).<span class="bu">sum</span>() <span class="op">-</span> tlp</span>
<span id="cb37-14"><a></a>    new_z, new_m, new_tlp, _ <span class="op">=</span> jax.lax.fori_loop(</span>
<span id="cb37-15"><a></a>        <span class="dv">0</span>,</span>
<span id="cb37-16"><a></a>        num_leapfrog_steps,</span>
<span id="cb37-17"><a></a>        partial(leapfrog_step, target_log_prob_and_grad, step_size),</span>
<span id="cb37-18"><a></a>        (z, m, tlp, tlp_grad)) </span>
<span id="cb37-19"><a></a>    new_energy <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> jnp.square(new_m).<span class="bu">sum</span>() <span class="op">-</span> new_tlp</span>
<span id="cb37-20"><a></a>    log_accept_ratio <span class="op">=</span> energy <span class="op">-</span> new_energy</span>
<span id="cb37-21"><a></a>    is_accepted <span class="op">=</span> jnp.log(jax.random.uniform(mh_seed, [])) <span class="op">&lt;</span> log_accept_ratio</span>
<span id="cb37-22"><a></a>    <span class="co"># select the proposed state if accepted</span></span>
<span id="cb37-23"><a></a>    z <span class="op">=</span> jnp.where(is_accepted, new_z, z)</span>
<span id="cb37-24"><a></a>    hmc_output <span class="op">=</span> {<span class="st">"z"</span>: z,</span>
<span id="cb37-25"><a></a>                  <span class="st">"is_accepted"</span>: is_accepted,</span>
<span id="cb37-26"><a></a>                  <span class="st">"log_accept_ratio"</span>: log_accept_ratio}</span>
<span id="cb37-27"><a></a>    <span class="co"># hmc_output["z"] has shape [num_dimensions]</span></span>
<span id="cb37-28"><a></a>    <span class="cf">return</span> z, hmc_output</span>
<span id="cb37-29"><a></a></span>
<span id="cb37-30"><a></a><span class="kw">def</span> hmc(target_log_prob_and_grad, num_leapfrog_steps, step_size, num_steps, z,</span>
<span id="cb37-31"><a></a>        seed):</span>
<span id="cb37-32"><a></a>    <span class="co"># create a seed for each step</span></span>
<span id="cb37-33"><a></a>    seeds <span class="op">=</span> jax.random.split(seed, num_steps)</span>
<span id="cb37-34"><a></a>    <span class="co"># this will repeatedly run hmc_step and accumulate the outputs</span></span>
<span id="cb37-35"><a></a>    _, hmc_output <span class="op">=</span> jax.lax.scan(</span>
<span id="cb37-36"><a></a>        partial(hmc_step, target_log_prob_and_grad, num_leapfrog_steps, step_size),</span>
<span id="cb37-37"><a></a>        z, seeds)</span>
<span id="cb37-38"><a></a>    <span class="co"># hmc_output["z"] now has shape [num_steps, num_dimensions]</span></span>
<span id="cb37-39"><a></a>    <span class="cf">return</span> hmc_output</span>
<span id="cb37-40"><a></a></span>
<span id="cb37-41"><a></a><span class="kw">def</span> scan(f, state, xs):</span>
<span id="cb37-42"><a></a>  output <span class="op">=</span> []</span>
<span id="cb37-43"><a></a>  <span class="cf">for</span> x <span class="kw">in</span> xs:</span>
<span id="cb37-44"><a></a>    state, y <span class="op">=</span> f(state, x)</span>
<span id="cb37-45"><a></a>    output.append(y)</span>
<span id="cb37-46"><a></a>  <span class="cf">return</span> state, jnp.stack(output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="hmc" class="slide level2">
<h2>HMC</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a></a>num_leapfrog_steps<span class="op">=</span><span class="dv">30</span></span>
<span id="cb38-2"><a></a>step_size <span class="op">=</span> <span class="fl">0.008</span></span>
<span id="cb38-3"><a></a><span class="im">from</span> jax <span class="im">import</span> random</span>
<span id="cb38-4"><a></a>seed <span class="op">=</span> random.PRNGKey(<span class="dv">92</span>)</span>
<span id="cb38-5"><a></a>num_samples<span class="op">=</span><span class="dv">10000</span></span>
<span id="cb38-6"><a></a>hmc_output <span class="op">=</span> hmc(target_log_prob_and_grad, num_leapfrog_steps, step_size,</span>
<span id="cb38-7"><a></a>    num_samples, theta, seed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="inspect-the-results" class="slide level2">
<h2>Inspect the results</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a></a>ndims <span class="op">=</span> x.shape[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb39-2"><a></a>thetap <span class="op">=</span> hmc_output[<span class="st">'z'</span>]</span>
<span id="cb39-3"><a></a>taup, lambp, betap <span class="op">=</span> jnp.split(thetap, [<span class="dv">1</span>, <span class="dv">1</span> <span class="op">+</span> ndims],axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb39-4"><a></a>skip <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb39-5"><a></a>slope <span class="op">=</span> betap[skip:,<span class="dv">1</span>]</span>
<span id="cb39-6"><a></a>intercept <span class="op">=</span> betap[skip:,<span class="dv">0</span>]</span>
<span id="cb39-7"><a></a>plt.hist(slope,bins<span class="op">=</span><span class="dv">50</span>)<span class="op">;</span></span>
<span id="cb39-8"><a></a>plt.hist(intercept,bins<span class="op">=</span><span class="dv">50</span>)<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-23-3.png" width="960" class="r-stretch"></section>
<section id="inspect-the-results-1" class="slide level2">
<h2>Inspect the results</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a></a><span class="bu">print</span>(np.quantile(slope,[<span class="fl">0.05</span>,<span class="fl">0.95</span>,<span class="fl">0.5</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[-14.41534266  -1.4132225   -5.69631028]</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a></a><span class="bu">print</span>(np.quantile(intercept,[<span class="fl">0.05</span>,<span class="fl">0.95</span>,<span class="fl">0.5</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[17.03002386 37.44243698 26.76435947]</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a></a><span class="bu">print</span>(np.mean(intercept),np.mean(slope))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>26.635332 -6.905437</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a></a>y <span class="ot">=</span> iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">"setosa"</span></span>
<span id="cb46-2"><a></a><span class="fu">glm</span>(y<span class="sc">~</span>iris<span class="sc">$</span>Sepal.Length, <span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:  glm(formula = y ~ iris$Sepal.Length, family = binomial)

Coefficients:
      (Intercept)  iris$Sepal.Length  
            27.83              -5.18  

Degrees of Freedom: 149 Total (i.e. Null);  148 Residual
Null Deviance:      191 
Residual Deviance: 72   AIC: 76</code></pre>
</div>
</div>
</section>
<section id="hierarchical-model" class="slide level2">
<h2>Hierarchical Model</h2>
<p>We will use the Normal-Normal model with kown variance and unknowm mean <span class="math display">\[
\begin{aligned}
\mu \sim &amp; \mathrm{Normal}(0,1) \\
x\mid \mu \sim &amp; \mathrm{Normal}(\mu,1)
\end{aligned}
\]</span></p>
</section>
<section id="lets-sample" class="slide level2">
<h2>Let’s sample</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a></a>n <span class="ot">=</span><span class="dv">20</span></span>
<span id="cb48-2"><a></a>data<span class="ot">=</span> <span class="fu">sort</span>(<span class="fu">rnorm</span>(n,<span class="dv">0</span>))</span>
<span id="cb48-3"><a></a><span class="co"># hist(data)</span></span>
<span id="cb48-4"><a></a>samples <span class="ot">=</span> <span class="dv">15000</span></span>
<span id="cb48-5"><a></a>proposal_width <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb48-6"><a></a>mu_current <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb48-7"><a></a>sigma <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb48-8"><a></a>mu0 <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb48-9"><a></a>sigma0 <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb48-10"><a></a>posterior <span class="ot">=</span> <span class="fu">c</span>(mu_current)</span>
<span id="cb48-11"><a></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>samples) {</span>
<span id="cb48-12"><a></a>  mu_proposal <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">1</span>,mu_current, proposal_width)</span>
<span id="cb48-13"><a></a>  likelihood_current <span class="ot">=</span>  <span class="fu">prod</span>(<span class="fu">dnorm</span>(data,mu_current,  sigma))</span>
<span id="cb48-14"><a></a>  likelihood_proposal <span class="ot">=</span> <span class="fu">prod</span>(<span class="fu">dnorm</span>(data,mu_proposal, sigma))</span>
<span id="cb48-15"><a></a>  prior_current <span class="ot">=</span>  <span class="fu">dnorm</span>(mu_current,mu0, sigma0)</span>
<span id="cb48-16"><a></a>  prior_proposal <span class="ot">=</span> <span class="fu">dnorm</span>(mu_proposal,mu0, sigma0)</span>
<span id="cb48-17"><a></a></span>
<span id="cb48-18"><a></a>  p_current <span class="ot">=</span> likelihood_current <span class="sc">*</span> prior_current</span>
<span id="cb48-19"><a></a>  p_proposal <span class="ot">=</span> likelihood_proposal <span class="sc">*</span> prior_proposal</span>
<span id="cb48-20"><a></a>  <span class="co"># Accept proposal?</span></span>
<span id="cb48-21"><a></a>  p_accept <span class="ot">=</span> p_proposal <span class="sc">/</span> p_current</span>
<span id="cb48-22"><a></a>  accept <span class="ot">=</span> (<span class="fu">runif</span>(<span class="dv">1</span>) <span class="sc">&lt;</span> p_accept)</span>
<span id="cb48-23"><a></a>  <span class="cf">if</span> (accept) {</span>
<span id="cb48-24"><a></a>      mu_current <span class="ot">=</span> mu_proposal</span>
<span id="cb48-25"><a></a>      posterior <span class="ot">=</span> <span class="fu">c</span>(posterior,mu_current)</span>
<span id="cb48-26"><a></a>  }</span>
<span id="cb48-27"><a></a>}</span>
<span id="cb48-28"><a></a>posterior <span class="ot">=</span> posterior[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>)]</span>
<span id="cb48-29"><a></a><span class="fu">plot</span>(posterior, <span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-26-1.png" width="960"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a>mu_post <span class="ot">=</span> (mu0 <span class="sc">/</span> sigma0<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">sum</span>(data) <span class="sc">/</span> sigma<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (<span class="fl">1.</span> <span class="sc">/</span> sigma0<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> n <span class="sc">/</span> sigma<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb49-2"><a></a>sigma_post <span class="ot">=</span> <span class="fu">sqrt</span>((<span class="fl">1.</span> <span class="sc">/</span> sigma0<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> n <span class="sc">/</span> sigma<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span>(<span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb49-3"><a></a><span class="fu">sprintf</span>(<span class="st">"Analytical mean: %.2f. MCMC Mean: %.2f"</span>, mu_post, <span class="fu">mean</span>(posterior))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Analytical mean: 0.03. MCMC Mean: 0.03"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">sprintf</span>(<span class="st">"Analytical sd: %.2f. MCMC sd: %.2f"</span>, sigma_post, <span class="fu">sd</span>(posterior))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Analytical sd: 0.22. MCMC sd: 0.23"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a>x <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="at">by=</span><span class="fl">0.01</span>)</span>
<span id="cb53-2"><a></a>dpost <span class="ot">=</span> <span class="fu">dnorm</span>(x,mu_post,sigma_post)</span>
<span id="cb53-3"><a></a><span class="fu">hist</span>(posterior, <span class="at">freq =</span> F, <span class="at">breaks=</span><span class="dv">30</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">main=</span><span class="st">"Posterior Mean"</span>)</span>
<span id="cb53-4"><a></a><span class="fu">lines</span>(<span class="fu">density</span>(posterior), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">main=</span><span class="st">"Posterior Mean"</span>)</span>
<span id="cb53-5"><a></a><span class="fu">lines</span>(x,dpost, <span class="at">type=</span><span class="st">'l'</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="06-mcmc_files/figure-revealjs/unnamed-chunk-26-2.png" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="lets-compare-to-hmc" class="slide level2">
<h2>Let’s compare to HMC</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a></a><span class="fu">library</span>(brms)</span>
<span id="cb54-2"><a></a>d <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">y=</span>data, <span class="at">sigma0=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">20</span>))</span>
<span id="cb54-3"><a></a>fit <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> d, </span>
<span id="cb54-4"><a></a>            <span class="at">family =</span> gaussian,</span>
<span id="cb54-5"><a></a>            y <span class="sc">|</span> <span class="fu">se</span>(sigma0) <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb54-6"><a></a>    <span class="at">prior =</span> <span class="fu">c</span>(<span class="fu">prior</span>(<span class="fu">normal</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">class =</span> Intercept)),</span>
<span id="cb54-7"><a></a>    <span class="at">iter =</span> <span class="dv">1000</span>, <span class="at">refresh =</span> <span class="dv">0</span>, <span class="at">chains =</span> <span class="dv">4</span>)</span>
<span id="cb54-8"><a></a>posterior <span class="ot">=</span> <span class="fu">as_draws_array</span>(fit, <span class="at">variable =</span> <span class="st">"b_Intercept"</span>)</span>
<span id="cb54-9"><a></a><span class="fu">hist</span>(posterior, <span class="at">freq =</span> F, <span class="at">breaks=</span><span class="dv">30</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">main=</span><span class="st">"Posterior Mean"</span>)</span>
<span id="cb54-10"><a></a><span class="fu">lines</span>(<span class="fu">density</span>(posterior), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">2</span>), <span class="at">main=</span><span class="st">"Posterior Mean"</span>)</span>
<span id="cb54-11"><a></a><span class="fu">lines</span>(x,dpost, <span class="at">type=</span><span class="st">'l'</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="06-mcmc_files/figure-revealjs/brm-1.png" width="960" class="r-stretch"></section>
<section id="problems-of-metropolis-hastings-algorithm" class="slide level2">
<h2>Problems of Metropolis-Hastings algorithm</h2>
<p>MH is very simple and quite general. At the same time</p>
<ul>
<li>too large step size <span class="math inline">\(\sigma\)</span> leads to a large fraction of rejected samples, while too small <span class="math inline">\(\sigma\)</span> makes very small steps, thus it takes long time to ‘explore the distribution’ (check this in demonstration!)</li>
<li>in high-dimensional spaces (very important use-case), MH explores the space very inefficiently because of it’s random-walk behavior. Guessing good direction in 1000 dimensions is incomparably harder than doing this for 2 dimensions!</li>
<li>MH can’t travel long distances (significantly larger than <span class="math inline">\(\sigma\)</span>) between isolated local minimums</li>
</ul>
<p>Sampling high-dimensional distributions with MH becomes very inefficient in practice. A more efficient scheme is called Hamiltonian Monte Carlo (HMC).</p>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1226,

        height: 920,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>