<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.37">

  <meta name="author" content="Vadim Sokolov   George Mason University   Spring 2025">
  <title>Bayes AI</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link rel="stylesheet" href="style.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="center">
  <h1 class="title" style="font-size:40px;">Bayes AI</h1>
  <p class="subtitle" style="color:blue;font-size:50px;">Unit 4: Bayesian Hypothesis Tests</p>
<img style="height: 350px;" src="fig/page/05-hypothesis.jpg">
  <p class="author">Vadim Sokolov <br> George Mason University <br> Spring 2025</p>

<p style="font-size:10px;"> 
<a href="https://vsokolov.org/courses/664.html">Course Page</a>, <a href="https://vsokolov.org/html/664/slides/">Slides</a>
</p>


</section>
<section id="bayesian-hypothesis-testing" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>Given sample of data, <span class="math inline">\(y\)</span>, generated from <span class="math inline">\(p\left( y \mid \theta\right)\)</span> for <span class="math inline">\(\theta\in\Theta\)</span></li>
<li>Determine if <span class="math inline">\(\theta\)</span> lies in <span class="math inline">\(\Theta_{0}\)</span> or in <span class="math inline">\(\Theta_{1}\)</span></li>
<li>Two disjoint subsets of <span class="math inline">\(\Theta\)</span>. In general, the hypothesis testing problem involves an action: accepting or rejecting a hypothesis.</li>
<li>A null, <span class="math inline">\(H_{0}\)</span>, and alternative hypothesis, <span class="math inline">\(H_{1}\)</span>, which are defined as <span class="math display">\[
H_{0}:\theta\in\Theta_{0}\;\;\mathrm{and}\;\;H_{1}%
:\theta\in\Theta_{1}\text{.}%
\]</span></li>
</ul>
</section>
<section id="bayesian-hypothesis-testing-1" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li><span class="math inline">\(\Theta _{0}=\theta_{0}\)</span>: simple or “sharp” null hypothesis.</li>
<li>Composite, otherwise</li>
<li>Single parameter: typical one-sided tests are of the form <span class="math inline">\(H_{0}:\theta&lt;\theta_{0}\)</span> and <span class="math inline">\(H_{1}:\theta&gt;\theta_{0}\)</span>.</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 36%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><span class="math inline">\(\theta\in\Theta_{0}\)</span></th>
<th><span class="math inline">\(\theta\in\Theta_{1}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accept <span class="math inline">\(H_{0}\)</span></td>
<td>Correct decision</td>
<td>Type II error</td>
</tr>
<tr class="even">
<td>Accept <span class="math inline">\(H_{1}\)</span></td>
<td>Type I error</td>
<td>Correct decision</td>
</tr>
</tbody>
</table>
</section>
<section id="bayesian-hypothesis-testing-errors" class="slide level2 smaller">
<h2>Bayesian Hypothesis Testing: Errors</h2>
<p>Formally, the probabilities of Type I (<span class="math inline">\(\alpha\)</span>) and Type II (<span class="math inline">\(\beta\)</span>) errors are defined as: <span class="math display">\[
\alpha=P \left[  \text{reject }H_{0} \mid H_{0}\text{
is true }\right]  \text{ and }\beta=P \left[  \text{accept
}H_{0} \mid H_{1}\text{ is true }\right]  \text{.}%
\]</span></p>
<ul>
<li>It is useful to think of the decision to accept or reject as a decision rule, <span class="math inline">\(d\left( y\right)\)</span>.</li>
<li>In many cases, the decision rules form a critical region <span class="math inline">\(R\)</span>, such that <span class="math inline">\(d\left( y\right) =d_{1}\)</span> if <span class="math inline">\(y\in R\)</span>.</li>
<li>These regions are often take the form of simple inequalities.</li>
</ul>
<p><span class="math display">\[\begin{align*}
\alpha_{\theta}\left(  d\right)   &amp;  =P \left[  d\left(  y\right)
=d_{1} \mid \theta\right]  \text{ if }\theta\in\Theta_{0}\text{ }(H_{0}\text{ is true})\\
\beta_{\theta}\left(  d\right)   &amp;  =P \left[  d\left(  y\right)
=d_{0} \mid \theta\right]  \text{ if }\theta\in\Theta_{1}\text{ }(H_{1}\text{ is true})\text{.}%
\end{align*}\]</span> Errors explicitly depend on the decision and the true parameter value</p>
</section>
<section id="bayesian-hypothesis-testing-2" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>The size of the test (the probability of making a type I error) is defined as <span class="math display">\[
\alpha = \underset{\theta\in\Theta_{0}}{\sup}~\alpha_{\theta}\left( d\right)
\]</span></li>
<li>The power is defined as <span class="math inline">\(1-\beta_{\theta}\left( d\right)\)</span>.</li>
<li>It is always possible to set either <span class="math inline">\(\alpha_{\theta}\left( d\right)\)</span> or <span class="math inline">\(\beta_{\theta }\left( d\right)\)</span> equal to zero, by finding a test that always rejects alternative or null, respectively.</li>
<li>The total probability of making an error is <span class="math inline">\(\alpha_{\theta}\left(d\right) +\beta_{\theta}\left(d\right)\)</span>, want to minimize</li>
</ul>
</section>
<section id="bayesian-hypothesis-testing-3" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>The optimal action <span class="math inline">\(d^*\)</span> minimizes the posterior expected loss, is <span class="math inline">\(d^* = d_0 = 0\)</span> if the posterior probability of hypothesis <span class="math inline">\(H_0\)</span> exceeds 1/2, and <span class="math inline">\(d^* = d_1=1\)</span> else <span class="math display">\[
d^* = 1\left(  P \left(  \theta \in \Theta_0 \mid y\right) &lt; P \left(  \theta \in \Theta_1 \mid y\right)\right)  = 1\left(P \left(  \theta \in \Theta_0 \mid y\right)&lt;1/2\right).
\]</span></li>
<li>Simply speaking, the hypothesis with higher posterior probability is selected.</li>
<li>More data reduces the error probability</li>
<li>Sometimes we can derive optimal&nbsp;tests, those that minimize the sum of the errors.</li>
</ul>
</section>
<section id="bayesian-hypothesis-testing-4" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>Simple hypothesis tests <span class="math inline">\(H_{0}:\theta=\theta_{0}\)</span> versus <span class="math inline">\(H_{1}:\theta=\theta_{1}\)</span> admit optimal tests</li>
<li>Defining <span class="math inline">\(d^{\ast}\)</span> as a test accepting <span class="math inline">\(H_{0}\)</span> if <span class="math inline">\(a_{0}f\left( y \mid \theta_{0}\right) &gt;a_{1}f\left( y \mid \theta_{1}\right)\)</span> and <span class="math inline">\(H_{1}\)</span> if <span class="math inline">\(a_{0}f\left( y \mid \theta_{0}\right) &lt;a_{1}f\left( y \mid \theta _{1}\right)\)</span>, for some <span class="math inline">\(a_{0}\)</span> and <span class="math inline">\(a_{1}\)</span>.</li>
<li>Either <span class="math inline">\(H_{0}\)</span> or <span class="math inline">\(H_{1}\)</span> can be accepted if <span class="math inline">\(a_{0}f\left(y \mid \theta_{0}\right) =a_{1}f\left( y \mid \theta_{1}\right)\)</span>. Then, for any other test <span class="math inline">\(d\)</span>, it is not hard to show that <span class="math display">\[
a_{0}\alpha\left(  d^{\ast}\right)  +a_{1}\beta\left(  d^{\ast}\right)  \leq
a_{0}\alpha\left(  d\right)  +a_{1}\beta\left(  d\right),
\]</span> where <span class="math inline">\(\alpha_{d}=\alpha_{d}\left( \theta\right)\)</span> and <span class="math inline">\(\beta_{d}=\beta_{d}\left( \theta\right)\)</span>.</li>
</ul>
</section>
<section id="bayesian-hypothesis-testing-5" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>This result highlights the optimality of tests defining rejection regions in terms of the likelihood ratio statistic, <span class="math inline">\(f\left( y \mid \theta_{0}\right)/f\left( y \mid \theta_{1}\right)\)</span>.</li>
<li>It turns out that the results are in fact stronger.</li>
<li>In terms of decision theoretic properties, tests that define rejection regions based on likelihood ratios are not only admissible decisions, but form a minimal complete class, the strongest property possible.</li>
</ul>
</section>
<section id="bayesian-hypothesis-testing-6" class="slide level2">
<h2>Bayesian Hypothesis Testing</h2>
<ul>
<li>Tradeoff between the two goals of reducing type I and type II errors: decreasing <span class="math inline">\(\alpha\)</span> leads to an increase in <span class="math inline">\(\beta\)</span>, and vice-versa.</li>
<li>It is common to fix <span class="math inline">\(\alpha_{\theta}\left( d\right)\)</span>, or <span class="math inline">\(\sup~\alpha_{\theta}\left( d\right)\)</span>, and then find a test to minimize <span class="math inline">\(\beta_{d}\left( \theta\right)\)</span>.</li>
<li>This leads to “most powerful” tests.</li>
<li>Important result from decision theory: test procedures that use the same size level of <span class="math inline">\(\alpha\)</span> in problems with different sample sizes are inadmissible.</li>
<li>This is commonly done where significance is indicated by a fixed size, say 5%. The implications of this will be clearer below in examples.</li>
</ul>
</section>
<section id="testing-fairness" class="slide level2">
<h2>Testing fairness</h2>
<p>Suppose we are interested in testing <span class="math inline">\(\theta\)</span>, the unknown probability of heads for possibly biased coin. Suppose, <span class="math display">\[
H_0 :~\theta=1/2 \quad\text{v.s.} \quad  H_1 :~\theta&gt;1/2.
\]</span> An experiment is conducted and 9 heads and 3 tails are observed. This information is not sufficient to fully specify the model <span class="math inline">\(p(y\mid \theta)\)</span>. There are two approaches.</p>
</section>
<section id="testing-fairness-1" class="slide level2 smaller">
<h2>Testing fairness</h2>
<p><strong>Scenario 1</strong>: Number of flips, <span class="math inline">\(n = 12\)</span> is predetermined. Then number of heads <span class="math inline">\(Y \mid \theta\)</span> is binomial <span class="math inline">\(B(n, \theta)\)</span>, with probability mass function <span class="math display">\[
p(y\mid \theta)= {n \choose x} \theta^x(1−\theta)^{n−x} = 220 \cdot \theta^9(1−\theta)^3
\]</span> For a frequentist, the p-value of the test is <span class="math display">\[
P(Y \geq 9\mid H_0)=\sum_{y=9}^{12} {12 \choose y} (1/2)^y(1−1/2)^{12−y} = (1+12+66+220)/2^{12} =0.073,
\]</span> and if you recall the classical testing, the <span class="math inline">\(H_0\)</span> is not rejected at level <span class="math inline">\(\alpha = 0.05\)</span>.</p>
</section>
<section id="testing-fairness-2" class="slide level2 smaller">
<h2>Testing fairness</h2>
<p><strong>Scenario 2</strong>: Number of tails (successes) <span class="math inline">\(\alpha = 3\)</span> is predetermined, i.e, the flipping is continued until 3 tails are observed. Then, <span class="math inline">\(Y\)</span> - number of heads (failures) until 3 tails appear is Negative Binomial <span class="math inline">\(NB(3, 1− \theta)\)</span>, <span class="math display">\[
p(y\mid \theta)= {\alpha+y-1 \choose \alpha-1} \theta^{y}(1−\theta)^{\alpha} = {3+9-1 \choose 3-1} \theta^9(1−\theta)^3 = 55\cdot \theta^9(1−\theta)^3.
\]</span> For a frequentist, large values of <span class="math inline">\(Y\)</span> are critical and the p-value of the test is <span class="math display">\[
P(Y \geq 9\mid H_0)=\sum_{y=9}^{\infty} {3+y-1 \choose 2} (1/2)^{x}(1/2)^{3} = 0.0327.
\]</span> We used the following identity here <span class="math display">\[
\sum_{x=k}^{\infty} {2+x \choose 2}\dfrac{1}{2^x} = \dfrac{8+5k+k^2}{2^k}.
\]</span> The hypothesis <span class="math inline">\(H_0\)</span> is rejected, and this change in decision is not caused by observations.</p>
<p>This is the violation of the likelihoood principle.</p>
</section>
<section id="the-bayesian-approach" class="slide level2">
<h2>The Bayesian Approach</h2>
<p>Compute the posterior distribution of each hypothesis <span class="math inline">\(H_i: \theta \in \Theta_i, ~ i=1,2\)</span>. By Bayes rule <span class="math display">\[
P \left(  H_{i} \mid y\right)  =\frac{p\left(  y \mid H_{i}\right)  P \left(  H_{i}\right)  }{p\left(  y\right)}
\]</span> where <span class="math inline">\(P \left( H_{i}\right)\)</span> is the prior probability of <span class="math inline">\(H_{i}\)</span>, <span class="math display">\[
p\left( y \mid H_{i}\right) =\int_{\theta \in \Theta_i} p\left( y \mid \    \theta\right) p\left( \theta \mid H_{i}\right) d\theta
\]</span> is the marginal likelihood under <span class="math inline">\(H_{i}\)</span>, <span class="math inline">\(p\left( \theta \mid H_{i}\right)\)</span> is the parameter prior under <span class="math inline">\(H_{i}\)</span>, and <span class="math display">\[
p\left(  y\right)  = \sum_{i=1,2} p\left(  y \mid H_{i}\right)  P \left( H_{i}\right).
\]</span></p>
</section>
<section id="the-bayesian-approach-1" class="slide level2 smaller">
<h2>The Bayesian Approach</h2>
<p>If the hypothesis are mutually exclusive, <span class="math inline">\(P \left( H_{0}\right) =1-P \left( H_{1}\right)\)</span>. <span class="math display">\[
\text{Odds}_{0,1}=\frac{P \left(  H_{0} \mid y\right)  }{P %
\left(  H_{1} \mid y\right)  }=\frac{p\left(  y \mid H_{0}\right)
}{p\left(  y \mid H_{1}\right)  }\frac{P \left(  H_{0}\right)  }{P \left(  H_{1}\right)  }\text{.}%
\]</span></p>
<p>The odds ratio updates the prior odds, <span class="math inline">\(P \left( H_{0}\right) /P \left( H_{1}\right)\)</span>, using the Bayes Factor, <span class="math display">\[
\mathcal{BF}_{0,1}=\dfrac{p\left(y \mid H_{0}\right)}{p\left( y \mid H_{1}\right)}.
\]</span> With exhaustive competing hypotheses<span class="math inline">\(,\)</span> <span class="math inline">\(P \left( H_{0} \mid y\right)\)</span> simplifies to <span class="math display">\[
P \left(  H_{0} \mid y\right)  =\left(  1+\left(  \mathcal{BF}_{0,1}\right)  ^{-1}\frac{\left(  1-P \left(  H_{0}\right)
\right)  }{P \left(  H_{0}\right)  }\right)  ^{-1}\text{,}%
\]</span> and with equal prior probability, <span class="math display">\[
p\left( H_{0} \mid y\right) =\left( 1+\left( \mathcal{BF}_{0,1}\right) ^{-1}\right) ^{-1}
\]</span></p>
</section>
<section id="jeffreys-scale" class="slide level2">
<h2>Jeffreys’ Scale</h2>
<p>For <span class="math inline">\(\mathcal{BF}_{0,1}&gt;1\)</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 35%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\mathcal{BF}_{0,1}\)</span></th>
<th><span class="math inline">\(log10(\mathcal{BF}_{0,1})\)</span></th>
<th>Grades of evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(1\)</span> to <span class="math inline">\(10^{1/2}\)</span></td>
<td>0 to 1/2</td>
<td>Barely worth mentioning</td>
</tr>
<tr class="even">
<td><span class="math inline">\(10^{1/2}\)</span> to <span class="math inline">\(10\)</span></td>
<td>1/2 to 1</td>
<td>Substantial</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(10\)</span> to <span class="math inline">\(10^{3/2}\)</span></td>
<td>1 to 3/2</td>
<td>Strong</td>
</tr>
<tr class="even">
<td><span class="math inline">\(10^{3/2}\)</span> to <span class="math inline">\(10^{2}\)</span></td>
<td>3/2 to 2</td>
<td>Very strong</td>
</tr>
<tr class="odd">
<td>&gt; <span class="math inline">\(10^{2}\)</span></td>
<td>&gt; 2</td>
<td>Decisive</td>
</tr>
</tbody>
</table>
</section>
<section id="jeffreys-scale-1" class="slide level2">
<h2>Jeffreys’ Scale</h2>
<p>For <span class="math inline">\(\mathcal{BF}_{0,1}&lt;1\)</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 32%">
<col style="width: 37%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\mathcal{BF}_{0,1}\)</span></th>
<th>$log<span class="math inline">\(10(\mathcal{BF}_{0,1})\)</span></th>
<th>Grades of evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(1\)</span> to <span class="math inline">\(10^{-1/2}\)</span></td>
<td>0 to -1/2</td>
<td>Barely worth mentioning</td>
</tr>
<tr class="even">
<td><span class="math inline">\(10^{-1/2}\)</span> to <span class="math inline">\(10^{-1}\)</span></td>
<td>-1/2 to -1</td>
<td>Substantial</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(10^{-1}\)</span> to <span class="math inline">\(10^{-3/2}\)</span></td>
<td>-1 to -3/2</td>
<td>Strong</td>
</tr>
<tr class="even">
<td><span class="math inline">\(10^{-3/2}\)</span> to <span class="math inline">\(10^{-2}\)</span></td>
<td>-3/2 to -2</td>
<td>Very strong</td>
</tr>
<tr class="odd">
<td>&lt; <span class="math inline">\(10^{-2}\)</span></td>
<td>&lt; -2</td>
<td>Decisive</td>
</tr>
</tbody>
</table>
</section>
<section id="how-to-make-a-decision" class="slide level2 smaller">
<h2>How to make a decision</h2>
<ul>
<li>The loss incurred when accepting the null (alternative) when the alternative is true (false) is <span class="math inline">\(L\left( d_{0} \mid H_{1}\right)\)</span> and <span class="math inline">\(L\left( d_{1} \mid H_{0}\right)\)</span>, respectively.</li>
<li>Assumes a zero loss of making a correct decision</li>
<li>The Bayesian will accept or reject based on the posterior expected loss <span class="math display">\[
\mathbb{E}\left[  \text{Loss}\mid d_{0},y\right]  =L\left(  d_{0} \mid H_{0}\right)
P \left(  H_{0} \mid y\right)  +L\left(  d_{0} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  =L\left( d_{0} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  ,
\]</span> vs <span class="math display">\[
\mathbb{E}\left[  \text{Loss} \mid d_{1},y\right]  =L\left(  d_{1} \mid H_{0}\right)
P \left(  H_{0} \mid y\right)  +L\left(  d_{1} \mid H_{1}\right)  P \left(  H_{1} \mid y\right)  =L\left( d_{1} \mid H_{0}\right)  P \left(  H_{0} \mid y\right)  .
\]</span></li>
</ul>
</section>
<section id="how-to-make-a-decision-1" class="slide level2">
<h2>How to make a decision</h2>
<p><span class="math display">\[
\frac{L\left(  d_{0} \mid H_{1}\right)  }{L\left(  d_{1} \mid H_{0}\right)  }&lt;\frac{P \left(  H_{0} \mid y\right)  }{P \left(  H_{1} \mid y\right)  }.
\]</span> In the case of equal prior probabilities, this reduces to <span class="math display">\[
\frac{L\left(  d_{0} \mid H_{1}\right)  }{L\left(  d_{1} \mid H_{0}\right)  }&lt;\frac{1}{\mathcal{BF}_{0,1}}.
\]</span></p>
</section>
<section id="signal-transmission-example" class="slide level2">
<h2>Signal Transmission Example</h2>
<ul>
<li>Random variable <span class="math inline">\(X\)</span> is transmitted over a noisy communication channel. Assume that the received signal is given by <span class="math display">\[
Y=X+W,
\]</span> where <span class="math inline">\(W\sim N(0,\sigma^2)\)</span> is independent of <span class="math inline">\(X\)</span>.</li>
<li>Suppose that <span class="math inline">\(X=1\)</span> with probability <span class="math inline">\(p\)</span>, and <span class="math inline">\(X=−1\)</span> with probability <span class="math inline">\(1−p\)</span>.</li>
<li>The goal is to decide between <span class="math inline">\(X=1\)</span> and <span class="math inline">\(X=−1\)</span> by observing the random variable <span class="math inline">\(Y\)</span>. We will assume symmetric loss and will accept the hypothesis with the higher posterior probability. This is also sometimes called the maximum a posteriori (MAP) test.</li>
</ul>
</section>
<section id="signal-transmission-example-1" class="slide level2">
<h2>Signal Transmission Example</h2>
<p>We assume that <span class="math inline">\(H_0: ~ X = 1\)</span>, thus <span class="math inline">\(Y\mid X_0 \sim N(1,\sigma^2)\)</span>, and <span class="math inline">\(Y\mid X_1 \sim N(-1,\sigma^2)\)</span>. The Bayes factor is simply the likelihood ratio <span class="math display">\[
\dfrac{p(y\mid H_0)}{p(y \mid H_1)} =  \exp\left( \frac{2y}{\sigma^2}\right).
\]</span> The propr odds are <span class="math inline">\(p/(1-p)\)</span>, thus the posterior odds are <span class="math display">\[
\exp\left( \frac{2y}{\sigma^2}\right)\dfrac{p}{1-p}.
\]</span> We choose <span class="math inline">\(H_0\)</span> (true <span class="math inline">\(X\)</span> is 1), if the posterior odds are greater than 1, i.e., <span class="math display">\[
y &gt; \frac{\sigma^2}{2} \log\left( \frac{p}{1-p}\right) = c.
\]</span></p>
</section>
<section id="signal-transmission-example-2" class="slide level2">
<h2>Signal Transmission Example</h2>
<p>Further, we can calculate the error probabilities of our test. <span class="math display">\[
p(d_1\mid H_0) = P(Y&lt;c\mid X=1) = \Phi\left( \frac{c-1}{\sigma}\right),
\]</span> and <span class="math display">\[
p(d_0\mid H_1) = P(Y&gt;c\mid X=-1) = 1- \Phi\left( \frac{c+1}{\sigma}\right).
\]</span> Let’s plot the total error rate as a function of <span class="math inline">\(p\)</span> and assuming <span class="math inline">\(\sigma=0.2\)</span> <span class="math display">\[
P_e = p(d_1\mid H_0) (1-p) + p(d_0\mid H_1) p
\]</span></p>
</section>
<section id="signal-transmission-example-3" class="slide level2">
<h2>Signal Transmission Example</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb1-2"><a></a>p <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>,<span class="fl">0.99</span>,<span class="fl">0.01</span>)</span>
<span id="cb1-3"><a></a>c <span class="ot">&lt;-</span> sigma<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">2</span><span class="sc">*</span><span class="fu">log</span>(p<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p))</span>
<span id="cb1-4"><a></a>Pe <span class="ot">&lt;-</span> <span class="fu">pnorm</span>((c<span class="dv">-1</span>)<span class="sc">/</span>sigma)<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>((c<span class="sc">+</span><span class="dv">1</span>)<span class="sc">/</span>sigma))<span class="sc">*</span>p</span>
<span id="cb1-5"><a></a><span class="fu">plot</span>(p,Pe,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">xlab=</span><span class="st">"p"</span>,<span class="at">ylab=</span><span class="st">"Total Error Rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="04-hypothesis_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section>
<section id="hockey-hypothesis-testing-for-normal-mean" class="slide level2">
<h2>Hockey: Hypothesis Testing for Normal Mean</h2>
<ul>
<li>General manager of Washington Capitals (an NHL hockey team) thinks that their star center player Evgeny Kuznetsov is underperformed and is thinking of trading him to a different team.</li>
<li>He uses the number of goals per season as a metric of performance.</li>
<li>Prior: a top forward scores on average 30 goals per season with a standard deviation of 5, <span class="math inline">\(\theta \sim N(30,25)\)</span>.</li>
<li>Data: In the 2022-2023 season Kuznetsov scored 12 goals and likelihood <span class="math inline">\(X\mid \theta \sim N(\theta, 36)\)</span>.</li>
<li>Kuznetsov’s performance was not stable over the years, thus high variance in the likelihood. Thus, the posterior is <span class="math inline">\(N(23,15)\)</span>.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>sigma2 <span class="ot">=</span> <span class="dv">36</span></span>
<span id="cb2-2"><a></a>sigma02 <span class="ot">=</span> <span class="dv">25</span></span>
<span id="cb2-3"><a></a>mu<span class="ot">=</span><span class="dv">30</span></span>
<span id="cb2-4"><a></a>y<span class="ot">=</span><span class="dv">12</span></span>
<span id="cb2-5"><a></a>k <span class="ot">=</span> sigma02 <span class="sc">+</span> sigma2</span>
<span id="cb2-6"><a></a>mu1 <span class="ot">=</span> sigma2<span class="sc">/</span>k<span class="sc">*</span>mu <span class="sc">+</span> sigma02<span class="sc">/</span>k<span class="sc">*</span>y</span>
<span id="cb2-7"><a></a>sigma21 <span class="ot">=</span> sigma2<span class="sc">*</span>sigma02<span class="sc">/</span>k</span>
<span id="cb2-8"><a></a>mu1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.62295</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>sigma21</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14.7541</code></pre>
</div>
</div>
</section>
<section id="hockey" class="slide level2">
<h2>Hockey</h2>
<ul>
<li>The manager thinks, that Kuznetsov simply had a bad year and his true performance is at least 24 goals per season <span class="math display">\[
H_0: \theta &gt; 24$, ~H_1: \theta&lt;24
\]</span> The posterior probability of <span class="math inline">\(H_0\)</span> hypothesis is</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>a <span class="ot">=</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="dv">24</span>,mu1,<span class="fu">sqrt</span>(sigma21))</span>
<span id="cb6-2"><a></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3599834</code></pre>
</div>
</div>
<p>It is less than 1/2, only 36%. Thus, we should reject the null hypothesis. The posterior odds in favor of the null hypothesis is</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>a<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5624594</code></pre>
</div>
</div>
</section>
<section id="add-loss" class="slide level2">
<h2>Add Loss</h2>
<ul>
<li>If underestimating (and trading) Kuznetsov is two times more costly than overestimating him (fans will be upset and team spirit might be affected) <span class="math display">\[
L(d_1\mid H_0) = 2L(d_0\mid H_1)
\]</span></li>
<li>Then we should accept the null when posterior odds are greater than 1/2.</li>
</ul>
<p>The posterior odds are in favor of the null hypothesis. Thus, the manager should not trade Kuznetsov.</p>
<p>Kuznetsov was traded to Carolina Hurricanes towards the end of the 2023-2024 season.</p>
</section>
<section id="two-sided-test-for-normal-mean" class="slide level2">
<h2>Two-Sided Test for Normal Mean</h2>
<ul>
<li><p><span class="math inline">\(H_0: \theta = m_0\)</span>, <span class="math inline">\(p\left( \theta \mid H_{0}\right) =\delta_{m_{0}}\left( \theta\right)\)</span></p></li>
<li><p><span class="math inline">\(H_1: \theta \neq m_0\)</span>, <span class="math inline">\(p\left( \theta \mid H_{1}\right) = N\left( m_{0},\sigma^{2}/n_0\right)\)</span></p></li>
<li><p>Where <span class="math inline">\(n\)</span> is the sample size and <span class="math inline">\(\sigma^2\)</span> is the variance (known) of the population. Observed samples are <span class="math inline">\(Y = (y_1, y_2, \ldots, y_n)\)</span> with <span class="math display">\[
y_i \sim N(\theta, \sigma^2).
\]</span></p></li>
</ul>
</section>
<section id="bayes-factor" class="slide level2">
<h2>Bayes Factor</h2>
<p>The Bayes factor can be calculated analytically <span class="math display">\[
BF_{0,1} = \frac{p(Y\mid \theta = m_0, \sigma^2 )}
{\int p(Y\mid \theta, \sigma^2) p(\theta \mid m_0, n_0, \sigma^2)\, d \theta}
\]</span> <span class="math display">\[
\int p(Y\mid \theta, \sigma^2) p(\theta \mid m_0, n_0, \sigma^2)\, d \theta = \frac{\sqrt{n_0}\exp\left\{-\frac{n_0(m_0-\bar y)^2}{2\left(n_0+n\right)\sigma^2}\right\}}{\sqrt{2\pi}\sigma^2\sqrt{\frac{n_0+n}{\sigma^2}}}
\]</span> <span class="math display">\[
p(Y\mid \theta = m_0, \sigma^2 ) = \frac{\exp\left\{-\frac{(\bar y-m_0)^2}{2 \sigma ^2}\right\}}{\sqrt{2 \pi } \sigma }
\]</span></p>
</section>
<section id="bayes-factor-1" class="slide level2 smaller">
<h2>Bayes Factor</h2>
<p>Thus, the Bayes factor is <span class="math display">\[
BF_{0,1} = \frac{\sigma\sqrt{\frac{n_0+n}{\sigma^2}}e^{-\frac{(m_0-\bar y)^2}{2\left(n_0+n\right)\sigma^2}}}{\sqrt{n_0}}
\]</span></p>
<p><span class="math display">\[
BF_{0,1} =\left(\frac{n + n_0}{n_0} \right)^{1/2} \exp\left\{-\frac 1 2 \frac{n }{n + n_0} Z^2 \right\}
\]</span></p>
<p><span class="math display">\[
Z =  \frac{(\bar{Y} - m_0)}{\sigma/\sqrt{n}}
\]</span></p>
<p>One way to interpret the scaling factor <span class="math inline">\(n_0\)</span> is ro look at the standard effect size <span class="math display">\[
\delta = \frac{\theta - m_0}{\sigma}.
\]</span> The prior of the standard effect size is <span class="math display">\[
\delta \mid H_1 \sim N(0, 1/n_0).
\]</span> This allows us to think about a standardized effect independent of the units of the problem.</p>
</section>
<section id="argon-discovery" class="slide level2">
<h2>Argon discovery</h2>
<ul>
<li>In 1894, Lord Rayleigh and Sir William Ramsay discovered a new gas, argon, by removing all the nitrogen and oxygen from a sample of air.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a>air <span class="ot">=</span>    <span class="fu">c</span>(<span class="fl">2.31017</span>, <span class="fl">2.30986</span>, <span class="fl">2.31010</span>, <span class="fl">2.31001</span>, <span class="fl">2.31024</span>, <span class="fl">2.31010</span>, <span class="fl">2.31028</span>, <span class="fl">2.31028</span>)</span>
<span id="cb10-2"><a></a>decomp <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">2.30143</span>, <span class="fl">2.29890</span>, <span class="fl">2.29816</span>, <span class="fl">2.30182</span>, <span class="fl">2.29869</span>, <span class="fl">2.29940</span>, <span class="fl">2.29849</span>, <span class="fl">2.29889</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ul>
<li>Our null hypothesis is that the mean of the difference equals to zero.</li>
<li>We assume that measurements made in the lab have normal errors, this the normal likelihood. We empirically calculate the standard deviation of our likelihood.</li>
</ul>
</section>
<section id="argon-discovery-1" class="slide level2">
<h2>Argon discovery</h2>
<p>The Bayes factor is</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>y <span class="ot">=</span> air <span class="sc">-</span> decomp</span>
<span id="cb11-2"><a></a>n <span class="ot">=</span> <span class="fu">length</span>(y)</span>
<span id="cb11-3"><a></a>m0 <span class="ot">=</span> <span class="dv">0</span></span>
<span id="cb11-4"><a></a>sigma <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(air) <span class="sc">+</span> <span class="fu">var</span>(decomp))</span>
<span id="cb11-5"><a></a>n0 <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb11-6"><a></a>Z <span class="ot">=</span> (<span class="fu">mean</span>(y) <span class="sc">-</span> m0)<span class="sc">/</span>(sigma<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb11-7"><a></a>BF <span class="ot">=</span> <span class="fu">sqrt</span>((n <span class="sc">+</span> n0)<span class="sc">/</span>n0)<span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span>n<span class="sc">/</span>(n <span class="sc">+</span> n0)<span class="sc">*</span>Z<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-8"><a></a>BF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.924776e-91</code></pre>
</div>
</div>
<p>We have extremely strong evidence in favor <span class="math inline">\(H_1: \theta \ne 0\)</span> hypothesis. <span class="math inline">\(P(H_0\mid y) = 1\)</span>.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>a <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span>BF)</span>
<span id="cb13-2"><a></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="ab-testing-google-search" class="slide level2">
<h2>AB Testing: Google Search</h2>
<ul>
<li>Google is testing new search algorithm (Algo2)</li>
<li>Want to know if it is any better compare to the old one (Algo1)</li>
<li>Collected data on 2500 search requests for each algorithm</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">Algo1</th>
<th style="text-align: center;">Algo2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>success</td>
<td style="text-align: center;">1755</td>
<td style="text-align: center;">1818</td>
</tr>
<tr class="even">
<td>failure</td>
<td style="text-align: center;">745</td>
<td style="text-align: center;">682</td>
</tr>
<tr class="odd">
<td>total</td>
<td style="text-align: center;">2500</td>
<td style="text-align: center;">2500</td>
</tr>
</tbody>
</table>
</section>
<section id="ab-testing-google-search-1" class="slide level2">
<h2>AB Testing: Google Search</h2>
<ul>
<li>Assume binomial likelihood and use conjugate beta prior</li>
<li>Independent beta priors on the click-through rates<br>
<span class="math display">\[
p_1\sim Beta(\alpha_1,\beta_1), ~p_2\sim Beta(\alpha_2,\beta_2).
\]</span> The posterior for <span class="math inline">\(p_1\)</span> and and <span class="math inline">\(p_2\)</span> are independent betas <span class="math display">\[
p(p_1, p_1 \mid y) \propto p_1^{\alpha_1 + 1755 - 1} (1-p_1)^{\beta_1 + 745 - 1}\times p_2^{\alpha_2 + 1818 - 1} (1-p_2)^{\beta_2 + 682 - 1}.
\]</span></li>
</ul>
</section>
<section id="ab-testing-google-search-2" class="slide level2">
<h2>AB Testing: Google Search</h2>
<p>The easiest way to explore this posterior is via Monte Carlo simulation of the posterior.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="fu">set.seed</span>(<span class="dv">92</span>) <span class="co">#Kuzy</span></span>
<span id="cb15-2"><a></a>y1 <span class="ot">&lt;-</span> <span class="dv">1755</span>; n1 <span class="ot">&lt;-</span> <span class="dv">2500</span>; alpha1 <span class="ot">&lt;-</span> <span class="dv">1</span>; beta1 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb15-3"><a></a>y2 <span class="ot">&lt;-</span> <span class="dv">1818</span>; n2 <span class="ot">&lt;-</span> <span class="dv">2500</span>; alpha2 <span class="ot">&lt;-</span> <span class="dv">1</span>; beta2 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb15-4"><a></a>m <span class="ot">=</span> <span class="dv">10000</span></span>
<span id="cb15-5"><a></a>p1 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(m, y1 <span class="sc">+</span> alpha1, n1 <span class="sc">-</span> y1 <span class="sc">+</span> beta1)</span>
<span id="cb15-6"><a></a>p2 <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(m, y2 <span class="sc">+</span> alpha2, n2 <span class="sc">-</span> y2 <span class="sc">+</span> beta2)</span>
<span id="cb15-7"><a></a>rd <span class="ot">&lt;-</span> p2 <span class="sc">-</span> p1</span>
<span id="cb15-8"><a></a><span class="fu">plot</span>(<span class="fu">density</span>(rd), <span class="at">main=</span><span class="st">"Posterior Difference in Click-Through Rates"</span>, <span class="at">xlab=</span><span class="st">"p2 - p1"</span>, <span class="at">ylab=</span><span class="st">"Density"</span>)</span>
<span id="cb15-9"><a></a>q <span class="ot">=</span> <span class="fu">quantile</span>(rd, <span class="fu">c</span>(.<span class="dv">05</span>, .<span class="dv">95</span>))</span>
<span id="cb15-10"><a></a><span class="fu">print</span>(q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         5%         95% 
0.003700223 0.046539157 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">abline</span>(<span class="at">v=</span>q,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

</div>
<img data-src="04-hypothesis_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section>
<section id="lindleys-paradox" class="slide level2">
<h2>Lindley’s Paradox</h2>
<p><em>Often evidence which, for a Bayesian statistician, strikingly supports the null leads to rejection by standard classical procedures</em>.</p>
<ul>
<li><span style="color: blue">Do Bayes and Classical always agree?</span></li>
</ul>
<p><span style="color: blue">Bayes</span> computes the probability of the null being true given the data <span class="math inline">\(p ( H_0 | D )\)</span>. That’s not the p-value. <span style="color: blue">Why?</span></p>
<ul>
<li><p>Surely they agree asymptotically?</p></li>
<li><p>How do we model the prior and compute likelihood ratios <span class="math inline">\(L ( H_0 | D )\)</span> in the Bayesianwork?</p></li>
</ul>
</section>
<section id="bayes-t-ratio" class="slide level2">
<h2>Bayes <span class="math inline">\(t\)</span>-ratio</h2>
<p>Edwards, Lindman and Savage (1963)</p>
<p>Simple approximation for the likelihood ratio. <span class="math display">\[
L ( p_0 ) \approx \sqrt{2 \pi} \sqrt{n} \exp \left ( - \frac{1}{2} t^2 \right )
\]</span></p>
<ul>
<li><span style="color: blue">Key:</span> Bayes test will have the factor <span class="math inline">\(\sqrt{n}\)</span></li>
</ul>
<p>This will asymptotically favour the null.</p>
<ul>
<li>There is only a big problem when <span class="math inline">\(2 &lt; t &lt; 4\)</span> – <span style="color: red">but</span> this is typically the most interesting case!</li>
</ul>
</section>
<section id="coin-tossing" class="slide level2">
<h2>Coin Tossing</h2>
<p><span style="color: blue">Intuition</span>: Imagine a coin tossing experiment and you want to determine whether the coin is “fair” <span class="math inline">\(H_0 : p = \frac{1}{2}\)</span>.</p>
<p>There are four experiments.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Expt</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">400</td>
<td style="text-align: center;">10,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">r</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">220</td>
<td style="text-align: center;">5098</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(L(p_0)\)</span></td>
<td style="text-align: center;">0.81</td>
<td style="text-align: center;">1.09</td>
<td style="text-align: center;">2.17</td>
<td style="text-align: center;">11.68</td>
</tr>
</tbody>
</table>
</section>
<section id="coin-tossing-1" class="slide level2">
<h2>Coin Tossing</h2>
<p><span style="color: blue">Implications:</span></p>
<ul>
<li><p>Classical: In each case the <span class="math inline">\(t\)</span>-ratio is approx 2. They we just <span class="math inline">\(H_0\)</span> ( a fair coin) at the 5% level in each experiment.</p></li>
<li><p>Bayes: <span class="math inline">\(L ( p_0 )\)</span> grows to infinity and so they is overwhelming evidence for <span class="math inline">\(H _ 0\)</span>. Connelly shows that the Monday effect disappears when you compute the Bayes version.</p></li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1226,

        height: 920,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>