---
title: "SYST/OR 468. Applied Predictive Analytics"
---

**Department of Systems Engineering and Operations Research**\
**George Mason University**\
**Spring 2019**\

**For course materials click [here](https://www.dropbox.com/sh/0exnfpvz9bxqxdo/AAApUQkcCMAZbeGgvNwJkrLga?dl####0)**\

SYST 468 is an undergraduate course focused on applying statistical and machine learning methodologies to develop predictive models. We will learn both classical methods for regression and classification, such as linear regression and logistic regression as well as new methods such as deep learning. We will consider applications in engineering, finance and artificial intelligence. There will be an emphasis on assumptions and interpretation. Although basics of probability and statistics will be revisited, it is targeted towards students who have completed (and remember the concepts from) a course in introductory statistics. We will make extensive use of computational tools, such as the R language for statistical computing, both for illustration in class and in homework problems. 

#### Announcements
- 04\/08\/2019: HW3 posted, due date April 17. 
- 03\/09\/2019: HW2 posted, due date April 3. 
- 02\/24\/2019: Midterm is on  March 20 (open book)
- 02\/24\/2019: No class on March 13 (Spring Break)
- 02\/24\/2019: H1 Due date is March 6
- 10\/10\/2018: Check back regularly for announcements
- 10\/10\/2018: First Class is on January 23


#### Course staff
**Lecture Notes**:	Will be made available one-day in advance on [Bb](https://mymasonportal.gmu.edu/) \
**Instructor**: [Vadim Sokolov](../index.qmd)\
**Office**: [Eng Building](https://goo.gl/maps/iLp2PzxkSxF2), Room 2242 \
vsokolov(at)gmu.edu \
**Tel**: 703-993-4533 \
**TA**: TBA\


#### Offie hours
Vadim Sokolov: Wed 2:30-4:30pm (at Engineering 2242)\
TA: Jungho Park: Mon 1-3pm (at Egnineering 2216)\


#### Lectures
**Location**: [Planetary Hall](https://goo.gl/maps/8MaM7ezdvaw ) 206\
**Times**: 4:30-7:10pm on Wednesday

#### Grades
**Grade composition**: Grade based on participation in class, in-class midterm, homework assignments, and final project.


#### Textbooks
- Diez, Barr and Cetinkaya-Rundel [Statistics](https://www.openintro.org/stat/textbook.php?stat_book####os OpenIntro), OpenIntro, 2015
- James, Witten, Hastie and Tibshirani, [R](http://www-bcf.usc.edu/~gareth/ISL/index.html An Introduction to Statistical Learning with Applications in), Springer, 2009.
- Additional reading: [List](https://chrisalbon.com/blog/data_science_reading_list.html Data Science Reading)

#### Links
- [Model Interpretability](http://nautil.us/issue/40/learning/is-artificial-intelligence-permanently-inscrutable)
- [Data Sceince Survey](https://www.dropbox.com/s/dtpabgu0o9z5t8z/2015-data-science-salary-survey.pdf?dl####1 )
- [J. M. Keynes's Investment Performance: A Note](https://www.dropbox.com/s/b34zjdupyc247v5/keynes.pdf?dl####1)
- [Bayes Search](https://www.youtube.com/watch?v####WH-HWWkCMeU )
- [How Y'all (NY) Times](http://www.nytimes.com/interactive/2013/12/20/sunday-review/dialect-quiz-map.html)
- [Monte Hall](https://www.youtube.com/watch?v####Zr_xWfThjJ0&app####desktop )
- [EPL](http://faculty.chicagobooth.edu/nicholas.polson/teaching/41000/speigelhalter-EPL.pdf) 
- [Data Cleaning](https://whatsthebigdata.com/2016/05/01/data-scientists-spend-most-of-their-time-cleaning-data/)
- [Airbnb RF](http://nerds.airbnb.com/unboxing-the-random-forest-classifier)
- [Facebook regrsssion](https://research.facebook.com/publications/practical-lessons-from-predicting-clicks-on-ads-at-facebook/) 
- [Youtube DL](https://youtube-eng.googleblog.com/2015/10/improving-youtube-video-thumbnails-with_8.html)
- [Uber Time Series](https://eng.uber.com/telematics/ )
- [EDA](http://www.itl.nist.gov/div898/handbook/eda/eda.htm)
- [Overfitting](http://memosisland.blogspot.de/2017/08/understanding-overfitting-inaccurate.html)
- [2016 Election](https://arxiv.org/abs/1704.01171)


#### Deep Learning
- [Course by Jeremy Howard on coding aspects of deep learning](http://course.fast.ai/)
- [Short introduction into deep learning](https://youtu.be/vq2nnJ4g6N0)
- [Architectures](http://www.asimovinstitute.org/neural-network-zoo/)
- [Keras](https://keras.io/)
- [ConvNetJS](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)
- [Visualization](http://www.denizyuret.com/2015/03/alec-radfords-animations-for.html)
- [Momentum](http://distill.pub/2017/momentum/)
- [Backprop](http://cs231n.stanford.edu/slides/2016/winter1516_lecture4.pdf)


#### Previous instances
- [Spring 2018](old/468-s18.qmd)
