---
title: "SYST/OR 664 CSI 674. Bayesian Inference and Decision Theory"
---

**Spring 2024**\

**Instructor**: [Vadim Sokolov](../index.qmd)\

**Location**: [Planetary Hall](https://maps.app.goo.gl/6f9bE2kFLNvfS1Up6) 120	\
**Time**: Mondays 4:30 pm - 7:10 pm\
**Office hours**: By appointment\
**Zoom Link**: [https://gmu.zoom.us/j/97355319230?pwd=ZXBmcVJWYWFZL0tlNHA2bWFSY0Rzdz09](https://gmu.zoom.us/j/97355319230?pwd=ZXBmcVJWYWFZL0tlNHA2bWFSY0Rzdz09)\
**HW Logistics**: You will submit your HW and projects to BlackBoard\


Course Materials:

- Lecture notes [html](../html/bayes/index.html), [pdf](https://www.dropbox.com/scl/fi/a480anaeeb10ry53il93c/bayes-v1-jan22.pdf?rlkey=fcjs6bqjyf0d1dxo2cd4fn00p&dl=1)
- [Homeworks](../html/ex.html)
- Video Recordings: [YouTube](https://www.youtube.com/playlist?list=PLW7zhaLlN4yApWzUwFjL80QexmXxGWcQ2)

#### Content and goals
Bayesian decision theory provides a unified and intuitively appealing approach to drawing inferences from observations and making rational, informed decisions. Bayesians view statistical inference as a problem in belief dynamics, of using evidence about a phenomenon to revise and update knowledge about it. Bayesian statistics is a scientifically justifiable way to integrate informed expert judgment with empirical data.  For a Bayesian, statistical inference cannot be treated entirely independently of the context of the decisions that will be made on the basis of the inferences.  In recent years, Bayesian methods have become increasingly common in a variety of disciplines that rely heavily on data. This course introduces students to Bayesian theory and methodology, including modern computational methods for Bayesian inference.  Students will learn the commonalities and differences between the Bayesian and frequentist approaches to statistical inference, how to approach a statistics problem from the Bayesian perspective, and how to combine data with informed expert judgment in a sound way to derive useful and policy-relevant conclusions.  Students will learn the necessary theory to develop a firm understanding of when and how to apply Bayesian and frequentist methods, and will also learn practical procedures for developing statistical models for phenomena, drawing inferences, and evaluating evidential support for hypotheses.  The course covers fundamentals of the Bayesian theory of inference, including probability as a representation for degrees of belief, the likelihood principle, the use of Bayes Rule to revise beliefs based on evidence, conjugate prior distributions for common statistical models, Markov Chain Monte Carlo methods for approximating the posterior distribution, Bayesian hierarchical models, and other key topics.  Graphical models are introduced for representing complex probability and decision problems by specifying them in modular components.  Assignments make use of modern computational techniques and focus on applying the methods to practical problems.

#### List of Topics
- Unit 1:  Probability and Bayes Rule
- Unit 2:  Utility and Decision Theory
- Unit 3:  Bayesian Hypothesis Tests
- Unit 4:  Stochastic Processes
- Unit 5:  Reinforcement Learning
- Unit 6:  Bayesian Inference with Conjugate Pairs: Single Parameter Models 
- Unit 7:  Markov Chain Monte Carlo  
- Unit 8:  Hierarchical Bayesian Models 
- Unit 9:  Bayesian Regression 

#### Schedule
- Jan 22: First Class
- Feb 27: We will not meet, I will post a video lecture
- March 4: No class (spring break)
- March 11: Midterm exam
- Apr 29: Last class, project presentations

#### HWs
- HW1: 1,2,3,5,13,17,26,45,50,62


#### Assignments
Homework is due 11:59PM on the assigned due date.  If you have extenuating circumstances, please contact me in advance, and I will consider giving you additional time to complete the assignment for partial credit. Assignments will be posted here and on Blackboard. Please submit your assignments through Blackboard.

Exams are take home and will be posted on Blackboard.

#### Prerequisites
The formal listed prerequisite is OR 542 or STAT 544 or STAT 554 or equivalent.\

The real prerequisites are: 

- Experience with elementary data analysis such as scatterplots, histograms, hypothesis tests, confidence intervals, and simple linear regression. 
- A calculus-based probability course - elementary probability theory, discrete and continuous probability distributions, probability mass and probability density functions, cumulative distribution functions, common parametric models such as the normal, binomial and Poisson distributions.
- Experience with a high-level programming language. We will use R, a programming language for data analysis, and STAN, a language for specifying and performing inference with Bayesian models.
- Comfort with mathematical notation.  We will not do proofs, but you will be expected to be comfortable following and doing mathematical derivations.

#### Computing
We will use R, a powerful (free) statistical graphics and computing language, and STAN, an open-source, cross-platform engine for Bayesian data analysis that can be accessed from within R. Many of the exercises will require programming. RStudio is an integrated development environment for R. Some students prefer Python to R. You may use your preferred software as long as your solution is clear and I can understand what you did, but the solutions and examples will all be in R.

#### Grading
Grade based entirely on participation in class, homework assignments, midterm and final project.\

Midterm 35\% \+ Final project \+ 35\% \+ Homework 30\%.  Scores of each component are normalized to be out of 100. Grades will be posted on [Bb](https://mymasonportal.gmu.edu/). Cut-offs: 97 (A\+), 93 (A), 90 (A\-), 87 (B+), 82 (B), 79 (B\-), 77 (C\+), 73 (C), 70 (C\-), 67 (D\+), 60)

#### Optional Textbooks
I teach from my notes, not from a textbook. The material I cover follows the Hoff text fairly closely, but the Hoff text is not as readable as I would like. Most students like to have a text as a supplement to my notes. The first two listed texts have electronic versions available from the library.

- Primary text (recommended): This book, published in 2009, provides about the right level of coverage and is a reasonably up-to-date treatment.  An electronic edition of this book is available to George Mason University students and faculty from the university library. Computer code is available for most of the examples in the book.\
\
**Hoff**, Peter D., A First Course in Bayesian Statistical Methods. Springer, 2009.

- Secondary text (recommended):  This recently published book was written primarily for social scientists.  It is accessible, well-written, and gives a comprehensive treatment beginning from the very basics through sophisticated hierarchical Bayesian models. An electronic edition of this book is available to George Mason University students and faculty from the university library. Computer code is available at the github site for most of the examples in the book.\
\
**Kruschke**, John, Doing Bayesian Data Analysis: A Tutorial with R, JAGS, and Stan. Academic Press, 2014.

- Reference text (recommended): This comprehensive text has become the standard reference in Bayesian statistical methods. The hyperlink below contains reviews, exercises, data sets and software. \
\
**Gelman**, A., Carlin, J., Stern, H., Dunson, D. B., Vehtari, A. and Rubin, D., Bayesian Data Analysis (3rd edition). CRC Press, 2013.

- Supplemental text (recommended):  This recently published book provides comprehensive coverage of computational Bayesian statistics with a focus on conducting Bayesian analyses of real data sets.  The range of topics covered is much more extensive than the Hoff text, and will serve as a useful supplement for readers interested in Bayesian treatment of topics not covered in this course, such as generalized linear models, capture-recapture experiments, time series and image analysis.   R code and a solution manual are available.\
\
**Marin**, Jean-Michel and Robert, Christian, Bayesian Essentials with R (2nd edition). Springer, 2014.

- Alternate text:  The text by Peter Lee is accessible and may be helpful as an alternative treatment.   Again, the hyperlink contains additional information, including exercises, solutions, errata and software.\
\
**Lee**, Peter, Bayesian Statistics:  An Introduction (4th edition), Wiley, 2012.



#### Mason Honor Code
To promote a stronger sense of mutual responsibility, respect, trust, and
fairness among all members of the George Mason University community and
with the desire for greater academic and personal achievement, we, the
student members of the university community, have set forth this honor code:
Student members of the George Mason University community pledge not to
cheat, plagiarize, steal, or lie in matters related to academic work.
Students are responsible for their own work, and students and faculty must take
on the responsibility of dealing with violations. The tenet must be a foundation
of our university culture.\

All work performed in this course will be subject to Mason's Honor Code.
Students are expected to do their own work in the course. For the group project,
students are expected to collaborate with their assigned group members.
In papers and project reports, students are expected to write in their own words,
 

#### Individuals with Disabilities
The university is committed to providing equal access to employment and
educational opportunities for people with disabilities.\

Mason recognizes that individuals with disabilities may need reasonable
accommodations to have equally effective opportunities to participate in or
benefit from the university educational programs, services, and activities, and
have equal employment opportunities. The university will adhere to all
applicable federal and state laws, regulations, and guidelines with respect to
providing reasonable accommodations as necessary to afford equal
employment opportunity and equal access to programs for qualified people
with disabilities.\

Applicants for admission and students requesting reasonable accommodations
for a disability should call the Office of Disability Services at 703-993-2474.
Employees and applicants for employment should call the Office of Equity and
Diversity Services at 703-993-8730. Questions regarding reasonable
accommodations and discrimination on the basis of disability should be
directed to the Americans with Disabilities Act (ADA) coordinator in the Office
of Equity and Diversity Services.





